### ISSUE TITLE
[Rule] Prefer let-bindings over var-bindings wherever possible

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#10]
Check if a `var` ever changes. If not, `let` should be used.

`key.setter_accessibility` might be useful.

**Comment by segiddins** [comment]
Wouldn't you also need to check if any mutating methods /input functions are called with it?

**Comment by marcelofabri** [comment]
Yeah, this will be a trick one. We can't also predict anything on properties from public API (they might not change inside the file itself, but a consumer may change it).

**Comment by marcelofabri** [comment]
An easier way to do this is trying to replace every (non-public?) `var` with `let` and let the compiler check if it's still ok.

The problems are that this will probably be much slower and that neither `syntax` nor `structure` expose this error (but `swiftc` does).

**Comment by jpsim** [comment]
@mrackwitz is working on a parser for `swiftc -dump-ast` so hopefully that'll make it easier to build different kinds of SwiftLint rules based on that version of the AST.

**Comment by marcelofabri** [comment]
:+1:

I was just about to comment about `swiftc -dump-ast` and how helpful it would be.

**Comment by marcelofabri** [comment]
This is now a compiler warning on Swift 2.0, so maybe it should be closed.

**Comment by jpsim** [comment]
> This is now a compiler warning on Swift 2.0, so maybe it should be closed.

Agreed. Plus, this would have been difficult to do without LLMV IR access.

**Comment by cprovatas** [comment]
Any chance of supporting this for properties?  I noticed the swift compiler doesn't catch this for properties.  Is it too complex to support?

**Comment by jpsim** [comment]
It would be possible to build an analyzer rule to do that.
