### ISSUE TITLE
Enable multi-byte tests on Linux

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1001]
This depends on https://bugs.swift.org/browse/SR-3448 and https://bugs.swift.org/browse/SR-3449 or finding a reliable workaround.

See #997 for more discussion.

**Comment by abl** [comment]
I've created https://github.com/apple/swift-corelibs-foundation/pull/796 in response to this; it should fix SR-3448 and SR-3449.

Also, as a temporary workaround, it is possible to use `options: .regularExpression` to do replacements across multi-byte substrings.

**Comment by marcelofabri** [comment]
Closed by #1563
