### ISSUE TITLE
Line length and [String: SourceKitRepresentable]

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1008]
Our current line length limit is 100, which makes creating functions that receives `[String: SourceKitRepresentable]` as parameter hard, since it's a long (33-char) type.

For example, how should one format this method?

```swift
    fileprivate func dictionaryViolations(in file: File,
                                          dictionary: [String: SourceKitRepresentable])
                                                                                    -> [NSRange] {
```

I find myself using worse choices of name method names or weird formatting because of this limit. I propose we should either (or both 😛):

1. Increase the limit a bit, to 120 for example.
2. Create a `typealias SouceKitDictionary =  [String: SourceKitRepresentable]` to save 11 characters.

Thoughts?

**Comment by jpsim** [comment]
I'd say we could definitely increase of the default even to 120.  A quick GitHub search of SwiftLint configurations appears to show that this is a very common value.  People have been suggesting this for a very long time and I think we better get with the times. See #28

**Comment by mattrubin** [comment]
I agree with the proposal to extend the default line length limit to 120 characters. I've noticed, though, that the lines that most often exceeded the previous limit of 100 and which were the ugliest to try to wrap were lines containing function declarations (as in the example above). Would it be possible to not apply the line length rule on function declaration lines, and trust that `function_parameter_count` and other rules will keep the function declarations to a reasonable length?

**Comment by jpsim** [comment]
That's a good idea, and it's the direction that #975 is going in, so no need to file a new issue.
