### ISSUE TITLE
Configure via command line

### ISSUE THREAD

**Issue by jakecraige** [realm/SwiftLint#101]
It would be nice if there were some way to configure SwiftLint via the command line. This would come in handy for the houndci.com integration rather than us having to write temporary files to configure it.

I'm not sure if it would be valuable for others so it may be a terrible idea. Figured I'd open the issue to discuss.

Related: https://github.com/realm/SwiftLint/pull/99

**Comment by jpsim** [comment]
There's a posix API/command that creates file handles from standard in without having to write that data to disk, which you could use without SwiftLint having to add a custom feature for this... let me see if I can find it.

**Comment by jpsim** [comment]
Named pipes!

```bash
$ mkfifo config_pipe; echo "disabled_rules:\n- todo" > config_pipe; swiftlint --config config_pipe
```

**Comment by jakecraige** [comment]
Nice! I'll give that a shot.

**Comment by jakecraige** [comment]
@jpsim Unfortunately that has the same implications of creating a file. You still have to delete the pipe later and what not. Since I'd have to `rm` that later I get the same result by `echo`ing to a file anyways so I'll just do that for now.

**Comment by jpsim** [comment]
ok, if this ends up being problematic, I'll add in an option to pass a yaml string in a command line parameter directly, but I'd prefer not to, to keep the API simple.
