### ISSUE TITLE
Make `operator_usage_whitespace` Rule Configurable

### ISSUE THREAD

**Issue by aamctustwo** [realm/SwiftLint#1013]
It would be nice to make `operator_usage_whitespace` rule configurable so that you can include or exclude specific operators.

As an example, I prefer to vertically align my assignments and therefore would like to exclude the `=` operator. But I would like to keep all of my arithmetic nicely spaced and continue to be linted.

**Comment by peterprokop** [comment]
We really need this for exactly the same reason (`=` operator)

**Comment by c0diq** [comment]
It also appears that when this rule is turned on, it adds spaces around `/` when swift files are used for scripting and start with `#!/usr/bin/swift` which becomes `#! / usr / bin / swift`

**Comment by jpsim** [comment]
I'd rather just see SwiftLint support vertically aligning operators instead.

**Comment by cennydavidsson** [comment]
I would like to config so it accepts the formatting that can be found in Clean Code by Uncle Bob about precedence of operators.

> Another use for white space is to accentuate the precedence of operators.
```
public class Quadratic {
  private static double determinant(double a, double b, double c) { 
    return b*b - 4*a*c;
  } 
}
```
> Notice how nicely the equations read. The factors have no white space between them because they are high precedence. The terms are separated by white space because addi- tion and subtraction are lower precedence.

**Comment by jpsim** [comment]
@cennydavidsson I agree that case reads more nicely than a single spaces. What about this case can we detect and make an exception for, without also losing some of the valuable violations that the rule would currently catch?

For example, longer variable names would reduce the readability of that code:

```swift
return b*b - 4*a*c
// vs
return variableB*variableB - 4*variableA*variableC
```

**Comment by cennydavidsson** [comment]
@jpsim I'm not sure I understand what you are asking.

I would like to configure the rule to have no whitespace for operators `*` and `/` basically. If we can do this then this rule can be more flexible. I don't see any downside with this feature as it is just additive.

```
operator_usage_whitespace:
  no_white_space: 
    - "*"
    - "/"
```

**Comment by jpsim** [comment]
I was saying that `return variableB*variableB - 4*variableA*variableC` becomes _less_ readable, so I'm asking what heuristics are you suggesting we apply so that avoid cases like these? Or are you saying that it would be up to the user to configure the rule based on their preferences regardless of if it applies well in all cases.
