### ISSUE TITLE
Give file name when using STDIN input

### ISSUE THREAD

**Issue by jakecraige** [realm/SwiftLint#102]
Currently when using the STDIN option you aren't able to give it a filename. In it's current state this doesn't matter but when you are able to exclude files it would be nice to give it a file name so that SwiftLint can decide to ignore it and return no violations.

Without this, anyone using stdin will have to manually read the config to exclude specific files.

I'm pretty sure I could put together a PR to support this if you're for it.

Thoughts?

**Comment by jpsim** [comment]
> I'm pretty sure I could put together a PR to support this if you're for it.
> 
> Thoughts?

Sounds like you need this for hound, so if you make a good PR for this, I'd happily merge it. How do other tools generally deal with this?

**Comment by jakecraige** [comment]
I'm not sure how other tools typically handle this.

I'm actually going to update hound to write to disk and use the `--path` option instead of using STDIN anyways. 

This will probably make it more future proof and make it easy to use more features without having to have the code base filled with branches that make hound work better.

**Comment by moger777** [comment]
ale for vim has the same issue. It uses stdin and causes false errors when using custom rules that only apply to certain paths. Would you still be open to PR which would supply a path? Something along the lines of `--use-stdin-path <PATH>`? I think supporting this allows for real time linting without need to save file.
