### ISSUE TITLE
Use an HTML template file rather than large strings in Swift source

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#1024]
The HTML reporter has this wall of strings in an array:

![image](https://cloud.githubusercontent.com/assets/474794/21402883/73a792ec-c76f-11e6-8838-33e070593d96.png)

Which is unreadable, challenging to maintain, and we need to fight the Swift compiler to avoid type inference fits.

We should just move this template to a file and do string replacement to inject our dynamic content. No need for fancy dependencies like a templating library, our needs are simple enough for straight up string replacement.

**Comment by marcelofabri** [comment]
This is blocked by https://bugs.swift.org/browse/SR-2866.
