### ISSUE TITLE
Add support for storing the reporter output to a file

### ISSUE THREAD

**Issue by JamieEdge** [realm/SwiftLint#1047]
It would be useful if the output from the reporter could be written to a file.

For example:
```
swiftlint --output report.html
```

**Comment by jpsim** [comment]
I'd rather not add this given that basically every shell in existence does this for you. For example, in bash/sh:

```
$ swiftlint > report.html
```

**Comment by jpsim** [comment]
This is why we print reporter output to stdout, but informational logs to stderr.

**Comment by JamieEdge** [comment]
Sure, makes sense.

**Comment by ociata** [comment]
It totally makes sense this way, however it is not **common** sense IMHO. I lost almost two hours trying to figure how to get jUnit report without the _Linting FileXXX..._ texts.

It will be great if it is added inside Readme.md. I could make a PR with only updates to Readme or you could add it later.

**Comment by JamieEdge** [comment]
Agreed - when I first started thinking about how to parse the output, I was thinking that I would have to use `grep`. Adding documentation would be really helpful.

**Comment by marcelofabri** [comment]
Feel free to open a PR improving the docs 👍

**Comment by fabb** [comment]
I use Mint to run a specific version of swiftlint. Now Mint also outputs things to STDOUT, so I cannot just output STDOUT to an xml file. An argument to store swiftlint output to a file would help in this case.

**Comment by fabb** [comment]
I'm aware I can silence Mint output by writing `mint run -s ...`, but having mint output in the CI log would be nice.
