### ISSUE TITLE
Rule request: private is preferred over fileprivate

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1058]
Because of Swift 3 migration, lots of declarations wouldn't need to be `fileprivate`.

**Comment by jpsim** [comment]
Once SwiftLint  has its "compiled" mode we can even do this for `internal`.

**Comment by marcelofabri** [comment]
I'm closing this since #1656 was merged and it finds top level `fileprivate` declarations, but also has a rule to trigger on all `fileprivate ` usage. This second one will be useful when using Swift 4, since basically it'll make possible to convert all the "acceptable" usages of `fileprivate` to `private`.
