### ISSUE TITLE
Rule request: large tuples

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1065]
Tuples should have at most 3(?) members.

**Comment by doozMen** [comment]
In my opinion at least 4

**Comment by jpsim** [comment]
Could do warning at 3, error at 4. Configurable for sure.

Could also make exceptions for tuples defined and only used within the scope of a single function, where making a struct might not be worth it.

**Comment by marcelofabri** [comment]
Probably we should focus on validating function return types first and properties.

**Comment by mcfedr** [comment]
Sure this should be an opt in type of rule..

**Comment by marcelofabri** [comment]
@mcfedr You can always disable a rule if you don't think it applies to your project or in this case tune in the limits.
