### ISSUE TITLE
rule request: consistent number of leading spaces/tabs

### ISSUE THREAD

**Issue by BluMist** [realm/SwiftLint#1076]
actually discovered this with the new `closure_end_indentation` rule; we had a bunch of places where a leading space was accidentally added, so 5/9/13... spaces instead of 4/8/12... etc

**Comment by marcelofabri** [comment]
Duplicated of https://github.com/realm/SwiftLint/issues/227?

**Comment by BluMist** [comment]
yeah, definitely. didn't see that one in my search, will close for now and monitor the other one.
