### ISSUE TITLE
Parallel linting 

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1077]
See this conversation on Twitter: https://twitter.com/merowing_/status/812939171878858752

![10849975_10152591681202799_3947848605304345534_n](https://cloud.githubusercontent.com/assets/833072/21513042/fac65634-cc9a-11e6-9838-df3ab983dead.jpg)

*Picture for illustration purposes only*

**Comment by jpsim** [comment]
The gains would be much higher if we parallelized linting multiple _files_ at once more than parallelizing _rules_.

**Comment by marcelofabri** [comment]
Closed in #1103 🎉
