### ISSUE TITLE
Swift 2.0 Roadmap

### ISSUE THREAD

**Issue by lfaoro** [realm/SwiftLint#108]
Do you have a roadmap of stuff to accomplish before a Swift 2.0 release?

Will there be 2 brew versions of SwiftLint?

**Comment by jpsim** [comment]
I'd like to keep a single release of SwiftLint, and I think it's possible to support older versions of Swift with minor modifications, but I have yet to build that.

**Comment by Tableau-David-Potter** [comment]
I see that Keith has a swift-2.0-update branch.  Will that be merged into this repo at some point, or is that a separate effort altogether?

**Comment by keith** [comment]
That is an unrelated customization branch on our fork.

**Comment by keith** [comment]
Right now swift 2 is on master of homebrew.

**Comment by jpsim** [comment]
Yup, this issue is no longer relevant.
