### ISSUE TITLE
Unable to read license file when installing via CocoaPods

### ISSUE THREAD

**Issue by ZevEisenberg** [realm/SwiftLint#1083]
The SwiftLint Podspec is pointing to the license file in the repository, but maybe something about also using a .zip instead of pointing to the repository itself is confusing CocoaPods. Maybe just specify MIT, without pointing to a file?

Podfile:

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Licensator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

end
```

results of `pod install`:

```
Analyzing dependencies
Downloading dependencies
Using SwiftLint (0.15.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Unable to read the license file `/Users/zev/Desktop/Licensator/Pods/SwiftLint/LICENSE` for the spec `SwiftLint (0.15.0)`

[!] Unable to read the license file `/Users/zev/Desktop/Licensator/Pods/SwiftLint/LICENSE` for the spec `SwiftLint (0.15.0)`
```

CocoaPods version: 1.1.1

**Comment by marcelofabri** [comment]
I think CocoaPods doesn't even clone the repo as there's no mention of it in the Podspec. We should probably just add the license file to the zip.

**Comment by migfabio** [comment]
Sorry to bump up it again, but the problem still persist

> [!] Unable to read the license file `/Users/.../Pods/SwiftLint/LICENSE` for the spec `SwiftLint (0.22.0)`

CocoaPods version 1.3.1

**Comment by jpsim** [comment]
@migfabio could you please file a new issue with exact steps to reproduce (e.g. what commands to run, which versions of tools to have installed, how they're installed, what's in your Podfile, etc). Thanks!

**Comment by edias** [comment]
I'm having this issue just running pod spec lint.

Does anybody found a solution for this one?

**Comment by jpsim** [comment]
@edias could you please file a new issue with exact steps to reproduce (e.g. what commands to run, which versions of tools to have installed, how they're installed, what's in your Podfile, etc). Thanks!

**Comment by khaledannajar** [comment]
I had this warning and it was fixed by commenting all the pods in the Podfile then running pod install then uncomment them back running pod install. I don't know why but it worked fine.
