### ISSUE TITLE
ReadMe should explain how to use with CocoaPods

### ISSUE THREAD

**Issue by ZevEisenberg** [realm/SwiftLint#1084]
There is a podspec, but the script to run SwiftLint assumes that `swiftlint` is in `$PATH`. The Readme should mention that, if you're using CocoaPods, you should use `${PODS_ROOT}/SwiftLint/swiftlint`.

**Comment by marcelofabri** [comment]
I'm closing this as there's already an issue for it https://github.com/realm/SwiftLint/issues/939 😅
