### ISSUE TITLE
Force Cast Violation

### ISSUE THREAD

**Issue by lfaoro** [realm/SwiftLint#109]
e.g.: `let app = NSApp.delegate as! AppDelegate`
Issue: `error: Force Cast Violation (High Severity): Force casts should be avoided`

e.g.: `let app = (NSApp.delegate as? AppDelegate)!`
Issue: none, it passes

Is this the expected behavior?

**Comment by jpsim** [comment]
The force cast rule only checks for `as!`. You're welcome to write a force unwrap rule.

**Comment by jpsim** [comment]
Closing as a duplicate of #55.
