### ISSUE TITLE
Rule request: avoid calling init(arrayLiteral:)

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1096]
`ExpressibleByArrayLiteral` protocol declares `init(arrayLiteral elements: Element...)`, but according to the [documentation](https://developer.apple.com/reference/swift/set/1539368-init) it shouldn't be called directly. 

The types that implement this protocol are:
* Array
* ArraySlice
* ContiguousArray
* IndexPath
* NSArray
* NSCountedSet
* NSMutableArray
* NSMutableOrderedSet
* NSMutableSet
* NSOrderedSet
* NSSet
* SBElementArray
* Set

List obtained from https://developer.apple.com/reference/swift/expressiblebyarrayliteral

**Comment by keith** [comment]
@marcelofabri quick question on this one, I see the info in the `init(arrayLiteral` docs, but not in the [`ExpressibleByIntegerLiteral` protocol](https://developer.apple.com/reference/swift/expressiblebyintegerliteral). Is there info somewhere about not calling this?

**Comment by marcelofabri** [comment]
@keith Not directly, but I think we can generalize it for all protocols in this "family" based on [the proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0115-literal-syntax-protocols.md#alternatives-considered) that renamed them:

```
No, it's exactly the opposite, as I keep saying.  Conformance to this
protocol does *not* mean you can initialize the type with a literal.
```

```swift
  func f<T: IntegerLiteralConvertible>() -> T {
    return T(integerLiteral: 43) // Error
    return T(43)                 // Also an Error
  }

// It means an instance of the type can be *written* as a literal:

  func f<T: IntegerLiteralConvertible>() -> T {
    return 43   // OK
  }
```

**Comment by rob-nash** [comment]
Another example:

```swift
    _ = Calendar.current.dateComponents(Set(arrayLiteral: Calendar.Component.hour, Calendar.Component.minute, Calendar.Component.second, Calendar.Component.nanosecond), from: Date())
```

The above works but is not necessary to call Set(arrayLiteral: ...).


```swift
_ = Calendar.current.dateComponents([Calendar.Component.year, Calendar.Component.month, Calendar.Component.day], from: Date())
```
