### ISSUE TITLE
False positive: empty_count

### ISSUE THREAD

**Issue by alejandro-isaza-hs** [realm/SwiftLint#1113]
I get an empty count violation with this code, even though there is no `isEmpty` in this case: `if let count = collectionView?.numberOfItems(inSection: 0), count > 0 { ... }`

SwiftLint version 0.15.0

**Comment by jpsim** [comment]
We're aware of this false positive category for `empty_count`, which is why it's marked as an "opt-in" rule.

Many others have reported this (known) issue, so I'll be closing this one as a duplicate.

See #827, #884, #848, #719, and #505 for more discussion on this.
