### ISSUE TITLE
Unable to find a specification for `SwiftLint`

### ISSUE THREAD

**Issue by muzamilhassan1987** [realm/SwiftLint#1114]
Unable to find a specification for `SwiftLint`
I am getting this when using cocoapods

**Comment by jpsim** [comment]
could you please run `pod repo update` and try again?

**Comment by CameronAskew** [comment]
I had this same issue, I ran `pod repo update` and all was fine

**Comment by speedoholic** [comment]
I realized that the character casing was not correct in my case. It was 'SwiftLint', but I had written 'Swiftlint'.
