### ISSUE TITLE
Rule request:  if ... != nil over if let _ = ....

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1116]
From [this comment](https://github.com/realm/SwiftLint/pull/1112#discussion_r94672579):

> Please use `if ... != nil` rather than `if let _ = ....` We ought to have a rule for this.

**Comment by BluMist** [comment]
can we have the opposite rule as well? != nil "feels" faster than assignment/unwrapping, we actually prefer the other way.

**Comment by jpsim** [comment]
Sure, I'm always in favor of adapting SwiftLint to reflect the conventions already followed throughout a code base.

Although my feelings on this haven't changed since this twitter convo from nearly 2 years ago: https://twitter.com/danituits/status/594641421925273602
