### ISSUE TITLE
.swiftlint.yml not respected

### ISSUE THREAD

**Issue by formbound** [realm/SwiftLint#112]
Seems my `.swiftlint.yml` is being ignored by swiftlint. Any one else getting this? Might be a good idea to have swiftlint exit if e.g. parsing of `.swiftlint.yml` fails.

**Comment by jpsim** [comment]
Did you build SwiftLint from source? The latest homebrew release came out before we introduced YAML configuration file support.

**Comment by formbound** [comment]
Got it! May want to add a warning or instruction for Make regarding the need for running carthage install.

**Comment by jpsim** [comment]
Done! 00bcfc244942f5e9370b010c7142a3883f4c3294

**Comment by formbound** [comment]
<3

**Comment by efremidze** [comment]
👍

**Comment by esetnik** [comment]
Is there a planned homebrew release update date?

**Comment by jpsim** [comment]
> Is there a planned homebrew release update date?

Once Homebrew starts to accept formulas dependent on Xcode 7, we'll submit an update: https://github.com/Homebrew/homebrew/pull/43684

**Comment by thunderousNinja** [comment]
FYI, It looks like they merged the change in the related issue. Any update on this?

**Comment by jpsim** [comment]
> FYI, It looks like they merged the change in the related issue. Any update on this?

We've made two major releases since the last comment on this thread (0.2.0 and 0.3.0).
