### ISSUE TITLE
Reduce ViolationSeverity to two members: Warning and Error

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#113]
As discussed in #106, 5 severity levels is overkill, especially since Xcode can only (really) display 2: warning and error. So this should simplify things quite a bit.

**Comment by segiddins** [comment]
We could use a third level as `note`, which should show up in the gutter but not cause build failures.

**Comment by jpsim** [comment]
I really don't know when that would be used in practice, I don't think any of SwiftLint's current rules would be appropriate for representation as a "note".

**Comment by jpsim** [comment]
It's trivial to add `.Note` as a case of `ViolationSeverity`, so we can always add it later if we find a use for it.

**Comment by cuddergambino** [comment]
There's a use case I discovered:
Have `approaching_expiry_severity: note` and `expired_severity: warning` to only warn of expired todos and note approaching expiries. 

I originally was going to make a new request for a `none` option, but found this similar issue. Should I make a new request for this?

**Comment by sanguish** [comment]
This would be a great solution for these. Since I don't want to see them as a warning before hand.

It's missing from the documentation how to set approaching_expiry_threshold
