### ISSUE TITLE
Please update the doc: unused_closure_parameter rule is messing up swift 2.3 code

### ISSUE THREAD

**Issue by eMdOS** [realm/SwiftLint#1148]
Swiftlint 0.15.0 is messing up my code in Swift 2.3

`unused_closure_parameter` is messing up function parameter labels, i.e.:

```swift
func set(name name: String) {
    // ..
}
```

Seems like it works fine in Swift 3.*.

Just, I would like to let you know that would be good to add the compatibility version to the `README` file, i.e.:

`swfttlint 0.10.0` -> `swift 2.*`
`swiftlint 0.15.0` -> `swift 3.*`

Thanks for the work you all have been doing, is amazing {^_^}.

**Comment by jpsim** [comment]
Fixed in #1081. Stay tuned for a release soon!
