### ISSUE TITLE
Inappropriate shorthand operator violation

### ISSUE THREAD

**Issue by sunkehappy** [realm/SwiftLint#1156]
`self.flashModeSelectionView.alpha = 1.0 - self.flashModeSelectionView.alpha`.
I can't find an easy conversion for this. I think this should be out of the rule. I mean no check for it because it has a `-` before on the right side of the `=`.
Am I right?

**Comment by marcelofabri** [comment]
You're totally right. I forgot when implementing it that not all operations are commutative 😅
