### ISSUE TITLE
Support for multiple reporter types

### ISSUE THREAD

**Issue by alliannas** [realm/SwiftLint#1162]
Hi.

I'm currently running swiftlint on a CI system and using `junit` reporter there works great.

However by using the `junit` reporter I loose the default `xcode` one so feedback in Xcode isn't immediate. 
Would it be possible to support an array reporters or is there a better way to achieve the desired results, that is on CI getting junit reports and in Xcode getting the inline errors/warnings?

**Comment by marcelofabri** [comment]
While this is a valid enhancement, in your case I don't see why can't you just use `swiftlint lint --reporter junit` on CI and keep using the default one while developing.

**Comment by alliannas** [comment]
Aaah I didn't know I could add the report through the console.

That works for very well for me, thanks :)

**Comment by amlcurran** [comment]
I'd still be interested in this. We have a similar issue, and there are a fews, where I feel multiple reporters is the most useful:

- Have a CI-specific configuration file. The risk of this is that the two configuration files could get out of sync.
- Have multiple reporters. Really happy to add a PR for this.
- Use an environment variable to set which reporter to use, and add this to the build phase. This is do-able but pushes configuration into our CI, whereas I'd prefer our configuration to be in version control

**Comment by marcelofabri** [comment]
@amlcurran There's #1227 to track it.

However, for most use cases, I'd say it's easier to just use `--reporter` instead. You could have two `.sh` in version control (one with each reporter, for example). 

But I agree that in some cases it'd be useful to have multiple reporters.
