### ISSUE TITLE
Excluded broken in 0.16.0?

### ISSUE THREAD

**Issue by jeffmoran** [realm/SwiftLint#1166]
I upgraded to 0.16.0 this morning an it seems like the excluded files aren't being excluded anymore. I'm using Swiftlint through a Build Phase on Xcode.

Below are the contents to my .yml file:

```
disabled_rules:
- todo
- line_length
- type_body_length
- file_length
opt_in_rules:
- force_unwrapping
- private_outlet
- empty_count
- vertical_whitespace
- closure_spacing
- explicit_init
- overridden_super_call
- redundant_nil_coalesing
- closure_spacing
- nimble_operator
- redundant_nil_coalescing
- operator_usage_whitespace
- prohibited_super_call
- closure_end_indentation
- first_where
- object_literal
excluded:
- Bean/Config.swift
- Bean/Localizations.swift
```

Any thoughts?

**Comment by jpsim** [comment]
I think you might be right...

**Comment by jeffmoran** [comment]
I'm surprised no one's opened up an issue about it hah. Any workaround until it gets fixed?

**Comment by jpsim** [comment]
> I'm surprised no one's opened up an issue about it hah

0.16 was just released ~12 hours ago, and isn't even available on Homebrew yet. I can't share a workaround without knowing more about _why_ it's broken. There aren't two ways of excluding files so...

**Comment by jeffmoran** [comment]
Fair enough. Thank you.

**Comment by codytwinton** [comment]
Here's one update: When a file has been marked as excluded, rules that have the warning and error levels modified don't modify for excluded files.

For example, I set:

```
line_length:
  - warning: 170
  - error: 200
```

But, for excluded files, `line_length` still shows a warning at `140` and error at `170`

**Comment by marcelofabri** [comment]
The issue was introduced when we migrated to use `FileManager.enumerator(atPath:)`. As stated in the [documentation](https://developer.apple.com/reference/foundation/filemanager/1408726-enumerator), it won't return itself if the `path` is a file:

> If `path` is a filename, the method returns an enumerator object that enumerates no files—the first call to `nextObject()` will return `nil`.

**Comment by jpsim** [comment]
Oops, my bad. Let's just revert to the old way?

**Comment by marcelofabri** [comment]
I've opened #1171 which fixes the issue without reverting to the old way. I think the new way, even with #1171, is easier to understand.
