### ISSUE TITLE
`--enable-all-rules` option

### ISSUE THREAD

**Issue by norio-nomura** [realm/SwiftLint#1170]
It would be useful for dog fooding or benchmarking SwiftLint, if `--enable-all-rules` enables all rules over `disabled_rules`, `opt_in_rules` and `whitelist_rules` in configuration file.
Currently, I'm using `~/.swiftlint-test.yml` to enable all opt-in rules on testing SwiftLint.
This option will free me from keeping my `~/.swiftlint-test.yml` updated.

**Comment by jpsim** [comment]
👍

**Comment by norio-nomura** [comment]
I hope `OptInRule` would be enabled by `--enable-all-rules` too.

**Comment by jpsim** [comment]
I thought my PR did that. I'll take another look at it later.

**Comment by norio-nomura** [comment]
Implemented in #1172. Thanks! 🙏
