### ISSUE TITLE
Xcode 7.3.1 - 0.16.0 not ignoring excluded files in .swiftlint.yml

### ISSUE THREAD

**Issue by NateFuller** [realm/SwiftLint#1177]
### Install config?
Cocoapods

### Xcode Version
7.3.1

### Summary
Updated to 0.16.0 via Cocoapods `pod update`. Built project with Xcode 7.3.1 and files that were previously being ignored in 0.15.0 are no longer being ignored. No changes have been made to the .swiftlint.yml file I am using.

### Workaround
Went back to 0.15.0 without making any changes to the .swiftlint.yml file and everything is working again.

**Comment by marcelofabri** [comment]
Duplicate of #1166 and fixed in #1171.
