### ISSUE TITLE
[Proposal] Linting multiple paths passed as CLI arg

### ISSUE THREAD

**Issue by benasher44** [realm/SwiftLint#1180]
Hello! I'm working on pre-commit/pre-commit#451 with SwiftLint in mind. I have pre-commit building SwiftPM packages locally, but one of the few things that's preventing me from fully integrating SwiftLint using pre-commit is the lack of ability to specify multiple paths as CLI args. Currently, it appears you can pass `--path <path>`, but SwiftLint will complain about any paths that follow that first `<path>`. To fix this using existing tools, I think using a `Commandant.Argument` makes sense. This would read quite well:

- `swiftlint lint path1.swift path2.swift …`
- `swiftlint autocorrect path1.swift path2.swift …`

I thought I'd ask first since:

1. This'll consume the single positional argument slot available (unless I'm missing something there).
2. It probably makes sense to then deprecate or drop `--path`, since it's just as easy to run `swiftlint lint one_path.swift`.

I'd appreciate your thoughts here. Thanks!

**Comment by aamctustwo** [comment]
Is this a duplicate of #810 `Support list of files as argument`?

**Comment by benasher44** [comment]
Ah yep I think it is. I searched for existing issues using "multiple" instead of "list". Closing
