### ISSUE TITLE
`statement_position` rule customization

### ISSUE THREAD

**Issue by artemnovichkov** [realm/SwiftLint#1181]
I want to change rule only for `else`, moving `else` to next line, for example:
```swift
if true {
    
}
else {
    
}
```
Can I do it with configuration file?

**Comment by aamctustwo** [comment]
@artemnovichkov Try use the `uncuddled_else` configuration option.

So use the following in your `.swiftlint.yml`:

```yml
statement_position:
  statement_mode: uncuddled_else
```

See: https://github.com/realm/SwiftLint/blob/5f442adf5b7725ac2553668f7db925622c821094/Source/SwiftLintFramework/Rules/StatementPositionRule.swift#L45-L72

**Comment by artemnovichkov** [comment]
It works, thanks, @aamctustwo!

**Comment by KyLeggiero** [comment]
> Try use the `uncuddled_else` configuration option

@ghost where is that documented? What other options are there?
