### ISSUE TITLE
Sorted Imports should ignore case (or have it customisable)

### ISSUE THREAD

**Issue by dalemy** [realm/SwiftLint#1185]
I'd expect the following to be valid:

    import AcmeCo
    import ADAL
    import AfterFramework

**Comment by aamctustwo** [comment]
:+1: For adding a customisation option to ignore case. I'd prefer to keeping the case-sensitive sorting as the default however.

**Comment by marcelofabri** [comment]
@dalemy Would you like to try to implement this?

**Comment by dalemy** [comment]
I'd like to implement the various things I've suggested, but getting open source permissions from the company and the time to do it isn't usually possible. And almost never on the time scale that you would expect. For now, assume that I'm unable to take this one.

**Comment by keith** [comment]
I've submitted a non-configurable fix for this: https://github.com/realm/SwiftLint/pull/1218
