### ISSUE TITLE
Suddenly 500 files are being parsed (not in any directory below where I am working)

### ISSUE THREAD

**Issue by Mozahler** [realm/SwiftLint#1187]
Yesterday I went from 2 warnings to nearly 7000 (but don't remember changing anything in the project. I was using 0.15.0, so I upgraded to 0.16.0 but the problem didn't go away.
this showed up this morning:

Showing All Messages
fatal error: Could not read configuration file at path '/User/Alex/Workspace/extraEasyPassLint.yml': File not found.: file /Users/jp/Projects/SwiftLint/Source/SwiftLintFramework/Models/Configuration.swift, line 172

I don't have a user named jp on my machine. 😎

**Comment by Mozahler** [comment]
I corrected the path/command to
swiftlint  lint --config /Users/Alex/Workspace/extraEasyPassLint.yml
and now get: 
Showing All Messages
Done linting! Found 7106 violations, 192 serious in 486 files.
Where I should get 0 -2 non-serious violations only.  These files are not below my working path, so they have nothing to do with my project. I've tried adding back a .swiftlint.yml file in the project directory, removing the --config parameter, etc.  but it still processes these outliers.
I'd be happy to provide more information: just let me know what would be useful.  I'll continue to look.  I have about 15 other projects that are still linting correctly.

**Comment by aamctustwo** [comment]
How do you have SwiftLint installed? Are you using Homebrew, CocoaPods, Carthage, Git Submodules, etc.?

**Comment by Mozahler** [comment]
Was homebrew  could only find 0.16.0 in binary .pkg so now using that. Problem occurred under homebrew version. Happy to try Carthage -- if it makes a difference I'll let you know.

**Comment by Mozahler** [comment]
I ran carthage using: github "realm/swiftlint" ~> 0.16.0
and got a SwiftLintFramework.framework.dSYM  (and SWXMLHash.framework) file which I don't know what to do with.

**Comment by Mozahler** [comment]
Compiling from source:
You can also build from source by cloning this project and running git submodule update --init --recursive; make install (Xcode 8.0 or later).
And got a fatal error:
git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git
what's the step I should have taken before running the recommended
git command?

**Comment by Mozahler** [comment]
This was caused by a glitch in the compiling process.  I found a build directory [which doesn't belong there] in the base folder of the project date Jan 12.  Maybe it had to do with the transition from Xcode 8.2 to 8.2.1?  I deleted the build directory and everything is hunky dory. 👨🏻‍🎤
