### ISSUE TITLE
Rule request: prefer implicit returns when possible

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1194]
From [raywenderlich.com Swift Style Guide](https://github.com/raywenderlich/swift-style-guide#closure-expressions)

----

For single-expression closures where the context is clear, use implicit returns:

```swift
attendeeList.sort { a, b in
    a > b
}
```

**Comment by jpsim** [comment]
related to #70 (only use positional arguments in "simple" closures"

**Comment by marcelofabri** [comment]
While this is related to #70, it's a bit different since we don't need to decide what "simple" means. Implicit returns are only allowed on single-expression closures.

**Comment by jpsim** [comment]
Although it's not always easy to determine if something is a single expression or not. It's not exactly directly determined by number of lines or presence of semicolons.
