### ISSUE TITLE
Print informative errors when configuration YAML contains unused information

### ISSUE THREAD

**Issue by keith** [realm/SwiftLint#120]
Not sure this is worth fixing, but I wanted to bring it up.

If you make a config file like:

```yml
included: Classes
```

Instead of:

```yml
included:
  - Classes
```

SwiftLint will silently ignore the first one. Typically I think this performs the same way in yaml, but regardless it might be nice to add errors for cases where the configuration isn't what we'd expect. The only reason I noticed this is because of the large number of files being linted.

**Comment by jpsim** [comment]
I'd absolutely love to do more error handling wrt yaml files, but haven't yet found an elegant way to do that.

**Comment by sboc** [comment]
Where do I put .swiftlint.yml btw? I cannot get this to work at all. Where do I run swiftlint from?

**Comment by dpassage** [comment]
It looks like `.swiftlint.yml` doesn't work with the latest released version 0.1.2; I got it to work by checking out master and building it myself.

SwiftLint team, would love to get the config file support released! Great tool so far.

**Comment by jpsim** [comment]
> SwiftLint team, would love to get the config file support released! Great tool so far.

Homebrew literally just yesterday started accepting formulas requiring Xcode 7, so we haven't been able to release until now. We'll be releasing shortly.

**Comment by dpassage** [comment]
Hooray! Thanks @jpsim !

**Comment by jpsim** [comment]
Many improvements to YAML error reporting were just merged in #498.
