### ISSUE TITLE
Rules file as argument to support multiple projects

### ISSUE THREAD

**Issue by jacobjennings** [realm/SwiftLint#1207]
It would be nice to specify a rules file as a command line argument, to support having one set of rules for multiple projects.

**Comment by aamctustwo** [comment]
What were you envisioning for this? A commandline argument? A configuration option in the `.swiftlint.yml` file that lists a path to this custom rules document?

**Comment by jacobjennings** [comment]
Either way would be great. I like the configuration option in the .yml idea best

**Comment by jpsim** [comment]
Maybe we could support external file references in `.swiftlint.yml`. Maybe if used in backticks?

```yaml
whitelist_rules: `~/.swiftlint/common_rules.yml`
```

**Comment by marcelofabri** [comment]
I think in general it'd be better to have a `base_configuration` or something like this so this could be solved in a generic way. We'd probably need to implement #676 though.

**Comment by SDGGiesbrecht** [comment]
This isn’t a native solution, but sharing configurations between projects is one of the reasons I started writing [Workspace](https://github.com/SDGGiesbrecht/Workspace).

 If...

1. The only thing you want to configure is to disable rules, and...
2. Your project supports the Swift Package Manager,

...Workspace should already be able to make SwiftLint share its configuration like you want. If your set‐up is more complicated, or if something below does not work properly, raise an [issue](https://github.com/SDGGiesbrecht/Workspace/issues) at the Workspace repository, and I will look into it.

## Steps:

1. Read the summary of [how to use Workspace](https://github.com/SDGGiesbrecht/Workspace/#the-workspace-workflow).

2. [Add Workspace](https://github.com/SDGGiesbrecht/Workspace/#setup) to each project.

3. [Create a configuration file](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Configuring%20Workspace.md) like [this one](https://github.com/SDGGiesbrecht/SDG/blob/c3bda4d0327d840577257e668323052dc3ff069b/.Workspace%20Configuration.txt#L30-L41) in one of the projects, then link to it like [this](https://github.com/SDGGiesbrecht/Workspace/blob/9d769969a247447be8e4d30c749b0e1b4e518fb3/.Workspace%20Configuration.txt#L15) in the other projects.

4. Remove your own `.swiftlint.yml` from each project to pass control of SwiftLint off to Workspace.

5. (Optional) Either put Workspace [in charge of Xcode](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Xcode.md), or add the following [script build phase](http://runscriptbuildphase.com) to your own Xcode project:
```
~/.Workspace/Workspace/.build/release/workspace proofread
```

---

Thanks again to everyone at SwiftLint. Your work is much appreciated.

**Comment by pejalo** [comment]
I would love to reference the config file as a command line argument, or from within `.swiftlint.config` as @aamctustwo suggested. Ideally our organization could have a git repo for our versioned SwiftLint config file. SwiftLint would support loading the file via `git@github.com:...` (to bypass 2FA via https) along with a specific tag, similar to how CocoaPods can be referenced.
