### ISSUE TITLE
emitted errors but did not return a nonzero exit code to indicate failure

### ISSUE THREAD

**Issue by cliren** [realm/SwiftLint#1208]
XCode is not failing the build upon errors but logs errors (XCode 8.2, Swift Lint 0.15.0 installed via brew, the same experience when installed with pod)

`Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure`

**Comment by marcelofabri** [comment]
Can you post you full Build Phase script?

**Comment by marcelofabri** [comment]
Closing due lack of activity.
