### ISSUE TITLE
Why .swiftlint.yml is hidden?

### ISSUE THREAD

**Issue by Den-Ree** [realm/SwiftLint#1219]
Hi! I tried to install Swiftlint. Can you tell me, please, how I should correctly create .swiftlint.yml in my project folder?
I downloaded .swiftlint.yml from github repo, but it's hidden and should I add this file in my project?

**Comment by eneko** [comment]
No need to add the configuration file to your project. You can see it on the terminal by typing `ls -las`.

**Comment by jpsim** [comment]
> Why .swiftlint.yml is hidden?

That's a great question! We simply followed the convention of having application-specific configuration files be hidden, just as `.gitignore`, `.travis.yml` and other commonly used tools. Not all services/tools choose to follow this convention though, such as `circle.yml`, but those seem to be outliers.

**Comment by jpsim** [comment]
Closing assuming we answered your question to your satisfaction. Feel free to reopen if you feel otherwise.
