### ISSUE TITLE
Bug in empty_count rule

### ISSUE THREAD

**Issue by phoney** [realm/SwiftLint#1241]
The empty_count rule seems to key off a variable named 'count' that isn't related to the Container.count method. In the following code there is no reference to a Container but it still generates an Empty Count violation where it shouldn't.

    func emptyCountBug(item: Int?) {
        if let count = item, count > 0 {
            print("Prefer checking isEmpty...")
        }
        if let count1 = item, count1 > 0 {
            print("No Comment")
        }
    }

**Comment by marcelofabri** [comment]
Duplicate of #827.
