### ISSUE TITLE
Extract benchmark to a custom script

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1244]
OSSCheck was added last month (https://github.com/realm/SwiftLint/pull/1056) and runs in CI.

Unfortunately, shared CI providers are not very reliable. It'd be great to be able to run the OSSCheck locally so we can get more accurate results.

**Comment by jpsim** [comment]
The tricky bit here is to do this without mangling the local git environment.

**Comment by marcelofabri** [comment]
We could only run if the git status is clean and only reset after. Does that make sense?

**Comment by jpsim** [comment]
yeah, I think that works, especially since it's just intended to be used by contributors.
