### ISSUE TITLE
Need for firstRegion

### ISSUE THREAD

**Issue by keith** [realm/SwiftLint#125]
I was looking through the region code and noticed the [`firstRegion`](https://github.com/realm/SwiftLint/blob/b932cd2b242ccaecac8476f7600efbd4cb2cdc2d/Source/SwiftLintFramework/File%2BSwiftLint.swift#L21-L26). What's the need for this region with no `disabledRuleIdentifiers`?

**Comment by jpsim** [comment]
[`Linter.styleViolations`](https://github.com/realm/SwiftLint/blob/56fe7b0d3b4db5fe95299b80798a99599967d9fe/Source/SwiftLintFramework/Linter.swift#L22-L27) expects all style violations to be contained in a region.

**Comment by keith** [comment]
Is this true though? This guard will return true if that array is empty?

**Comment by jpsim** [comment]
You're right! Feel free to refactor that in a PR.

**Comment by keith** [comment]
Awesome, incoming.
