### ISSUE TITLE
large_tuple: false positive on tuples with generics having 2 & more type parameters

### ISSUE THREAD

**Issue by nekrich** [realm/SwiftLint#1257]
I have a warning: Large Tuple Violation: Tuples should have at most 2 members. (large_tuple)
on this:
`func getDictionaryAndInt() -> (Dictionary<Int, String>, Int)?`

But there are only 2 members in the tuple.

swiftlint version: 0.16.1

**Comment by marcelofabri** [comment]
I could reproduce it on `master`. Thanks for reporting!

You can workaround the issue for now by using `[Int: String]` instead of `Dictionary<Int, String>`.

**Comment by nekrich** [comment]
Thanks.
