### ISSUE TITLE
TodoRule ignores lowercase todo or fixme

### ISSUE THREAD

**Issue by toshi0383** [realm/SwiftLint#1266]
TodoRule ignores lowercase todo or fixme.
Is this expected behavior ?

**Comment by marcelofabri** [comment]
I think so, because Xcode only recognizes them if they're uppercase.

**Comment by toshi0383** [comment]
@marcelofabri 
Oh that makes sense..
I'm going to create a custom rule like lowercase_todo for myself.
Thank you !

**Comment by marcelofabri** [comment]
I'm going to close this then. Feel free to reopen if you need more help!
