### ISSUE TITLE
How to install SwiftLint on Docker linux image.

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#1272]
If I have a docker image with swift running how can I install SwiftLint so I can run it on my CI. 
https://hub.docker.com/_/swift/

I know it may be a silly question. :)

**Comment by marcelofabri** [comment]
I think you need to build SourceKit by your own first or use https://hub.docker.com/r/norionomura/sourcekit/ instead. Then you can build SwiftLint with `swift build`

**Comment by masters3d** [comment]
How can I tell SPM to build the latest release?

**Comment by marcelofabri** [comment]
Just cloning the latest tag instead? I'm not very familiar with SPM myself, so it might be a better way.

**Comment by aamctustwo** [comment]
Correct, just specify the major/minor version in the `dependencies` array in your `Package.swift` file. Something like:

```swift
dependencies: [
    .Package(url: "https://github.com/realm/SwiftLint.git", majorVersion: 0, minor: 16)
]
```

**Comment by cmillani** [comment]
Was looking for this, found a docker image with an up to date build of swiftlint, maybe it can help someone that end up here as well: 

https://hub.docker.com/r/norionomura/swiftlint :)

**Comment by jpsim** [comment]
Yup, and if anyone wants to see the Dockerfile it's here: https://github.com/norio-nomura/docker-swiftlint/blob/master/swift-4.2.2/Dockerfile
