### ISSUE TITLE
Autocorrectable and disabled rules

### ISSUE THREAD

**Issue by Sealos** [realm/SwiftLint#1273]
I searched for this but didn't find something related, so excuse me if this a duplicate.

Autocorrecting files ignores disabled rules, for example, in my config (Using swiftlint rules):
The rule **unused_closure_parameter** is correctable, but it's not enabled in my config, however, when I run swiftlint autocorrect it does eat un the parameters.

Thanks.

**Comment by marcelofabri** [comment]
I couldn't reproduce it with 0.16.1. Please check your SwiftLint version, attach you configuration file and a sample file that shows the problem when corrected. Thanks!

**Comment by Sealos** [comment]
I updated swiftlint and the problem was fixed. Thanks!
