### ISSUE TITLE
operator_whitespace is conflicting with functions_with_space

### ISSUE THREAD

**Issue by cjheinze** [realm/SwiftLint#1274]
E.g. when conforming to `Equatable` and implementing
```swift
static func == (lhs: Something, rhs: Something) -> Bool
```
swiftlint presents a `functions_with_space` violation but removing the space produces a `operator_whitespace` violation

**Comment by marcelofabri** [comment]
Which version are you using? I couldn't reproduce it with 0.16.1:

```
$ swiftlint lint --path file.swift --enable-all-rules --no-cache
Linting Swift files at path file.swift
Linting 'file.swift' (1/1)
Done linting! Found 0 violations, 0 serious in 1 file.
```

**Comment by cjheinze** [comment]
Strange, I'm on 0.16.1 as well. This snippet produces operator_whitespace:
```swift
class Something: Equatable {
    var text: String?
    
    static func ==(lhs: Something, rhs: Something) -> Bool {
        return lhs.text == rhs.text
    }
}
```
And this produces functions with space:
```swift
class Something: Equatable {
    var text: String?
    
    static func == (lhs: Something, rhs: Something) -> Bool {
        return lhs.text == rhs.text
    }
}
```

**Comment by cjheinze** [comment]
Same behavior regardless of operator: 
```swift
static prefix func ~ (value: Something) {
    print(value.text)
}
```

**Comment by marcelofabri** [comment]
Just to be clear, you're talking about `operator_whitespace` and `operator_usage_whitespace` rules, right?

**Comment by cjheinze** [comment]
Well `operator_whitespace` is working correctly, but correcting it results in a `functions_with_space` violation. 
```
swiftlint lint --path Something.swift --enable-all-rules --no-cache
Loading configuration from '.swiftlint.yml'
Linting Swift files at path Something.swift
Linting 'Something.swift' (1/1)
Something.swift:4:12: warning: Functions with space Violation: Functions shall not have space between function name and parenthesis (functions_with_space)
Done linting! Found 1 violation, 0 serious in 1 file.
```
Using this example:
```swift
class Something: Equatable {
    var text: String?
    
    static func == (lhs: Something, rhs: Something) -> Bool {
        return lhs.text == rhs.text
    }
}
```

**Comment by marcelofabri** [comment]
There's no `functions_with_space` rule 😅 

Maybe it's a custom rule defined on your configuration file?

**Comment by cjheinze** [comment]
... You can close this issue 🤣 
And I need to read through the .yml file more closely next time

**Comment by marcelofabri** [comment]
No worries! Feel free to reopen if you need 👍

**Comment by cjheinze** [comment]
```
  functions_with_space:
    include: "*.swift"
    name: "Functions with space"
    regex: "(func [^ \(]+ \([^\)]*\)[^\{]*\{)"
    message: "Functions shall not have space between function name and parenthesis"
    severity: warning
```
Legacy stuff that's been forgotten about :)

**Comment by yhkaplan** [comment]
Sorry for commenting on a closed issue, but I was wondering if it would be possible to write an exception for operator_whitespace so it ignores the function name below. For now I use comments to make an exception locally, but Swift often encourages using Equatable, so I was wondering what everyone thinks. (Leaving a space after the function name doesn't feel right either here...)

```swift
static func == (lhs: Something, rhs: Something) -> Bool
```
