### ISSUE TITLE
Improve docs on how to start contributing 

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1280]
#1161 has some useful tips.

**Comment by mknabbe** [comment]
I'd like to get more familiar with the SwiftLint code base and try to do my first contribution by improving the documentation. Is this ticket still valid?

**Comment by jpsim** [comment]
Documentation can always be improved! Maybe you could start by reading #1161 and `CONTRIBUTING.md` and see what potentially useful information is missing or could be reworded.

**Comment by mknabbe** [comment]
Thanks. I'll have a look.

**Comment by mknabbe** [comment]
I read through the documentation and executed its steps. There's one thing a stumbled upon and it doesn't seem to be documented. It's mentioned in multiple files to fetch the git submodules and I couldn't find the reason for it. The documentation to make changes to the code base uses Swift Package Manager commands. Swift PM doesn't use git submodules as far as I know.
Could someone please explain why forked projects need to fetch the git submodules? I noticed a Carthage setup too. Why those duplication to manage the dependencies?
Thank you in advance.

**Comment by jpsim** [comment]
The git submodules are used when using the Xcode project & workspace (e.g. `xed SwiftLint.xcworkspace`).

They’re not needed when building using the Swift Package Manager either from the command line or Xcode’s support for it (e.g. `xed .` or `xed Package.swift`).

The Carthage setup is used to handle version control for the git submodules. It was also useful at a point in time for consumers of SwiftLintFramework that wanted to integrate it using Carthage.

I would love to remove the git submodule, Cartfile(s) and Xcode workspace+project and only support Swift Package Manager, but before doing that we should check to see if 1) that breaks Carthage users of SwiftLintFramework and/or 2) if there even are any users of SwiftLintFramework using Carthage to see if it’s worth continuing to support them.
