### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1281]
We should ask for SwiftLint version, Swift version, configuration file, sample example that shows the bug, etc

**Comment by aamctustwo** [comment]
Long-term, it might be worth adding a command that extract all this data nicely for them, like Fastlane does. This command can then be added to the GitHub issue template. See: https://github.com/fastlane/fastlane/blob/master/.github/ISSUE_TEMPLATE.md

To take it one step further, we could then add a bot that checks for this information and reminds the reporter to added it. See: https://github.com/fastlane/issue-bot/blob/ad957e2abf5eda1f4f28fafe21b1a892882d8acd/bot.rb#L210-L222

**Comment by jpsim** [comment]
All great ideas. It'd also be useful to know:

* which Swift toolchain and SourceKit version is being picked up.
* console output with the `SOURCEKIT_LOGGING=3` environment variable set.
* maybe we could have a template like `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`.
