### ISSUE TITLE
Rules should explain their reason for existing

### ISSUE THREAD

**Issue by ileitch** [realm/SwiftLint#1282]
For example, why does the `empty_count` rule exist? Is it purely a stylistic preference? Is the compiler able to better optimize `isEmpty`?

Why do we have `shorthand_operator`? Is there some official Swift guide somewhere that states shortand syntax is more idiomatic?

These are the kinds of things I'd like to know when choosing what rules to disable or opt-in. This could potentially lead to less disabled rules in general.

The simplest thing would be for rules to be able to include a rationale field that can be viewed somehow, likely using the `rules` command.

If we wanted to get a little more fancy, maybe rules could be annotated with attributes such as `stylistic` for rules that are purely subjective, and provide no objective benefit either way. `idiomatic` could be used for rules that are considered idiomatic Swift. `stability` might be applied to rules that avoid stability issues such as `weak_delegate`.

**Comment by allewun** [comment]
I like this idea and had a similar thought -- rules should supply a "rationale" field.

I've had to dig through GitHub issues/PRs to look for the rationale behind some of the rules. This could streamline that process significantly.

**Comment by marcelofabri** [comment]
I agree that more info and categorizing the rules would be helpful, including for https://github.com/realm/SwiftLint/pull/1107.
