### ISSUE TITLE
(key as? String)! ignored by ForceCastRule

### ISSUE THREAD

**Issue by alexpersian** [realm/SwiftLint#129]
After running SwiftLint on my project I found that the ForceCastRule is ignored force cases in the form of `(key as? String)!`.

Looking through the Swift file it looks like the linter is only looking for force casts in the form of `as!`.

**Comment by jpsim** [comment]
`(key as? String)!` isn't a force cast, but rather a force-unwrap, which is a rule we'd like to add and are tracking as #55. So I'm closing this as a duplicate.

**Comment by alexpersian** [comment]
Thanks for the response and clarification.
