### ISSUE TITLE
Option to have CyclomaticComplexityRule ignore case statements?

### ISSUE THREAD

**Issue by mlwelles** [realm/SwiftLint#1298]
I've had a couple of instances where pull requests from my team have include dispatch functions that handle every case in an enum trigger cyclomatic complexity warnings / errors.   We've all looked over the code, and agree we like it.

So that we don't trigger with examples we made some changes to have the rule optionally disregard case statements in scoring.   I've got a PR ready, will submit if there's any interest.

Is there?

**Comment by marcelofabri** [comment]
Implemented in #1299 🎉
