### ISSUE TITLE
Homebrew install "dyld: Library not loaded:" Error

### ISSUE THREAD

**Issue by velocismatt** [realm/SwiftLint#13]
$ brew install swiftlint
==> Downloading https://homebrew.bintray.com/bottles/swiftlint-0.1.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring swiftlint-0.1.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/swiftlint/0.1.0: 161 files, 36M
$ swiftlint
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /usr/local/Cellar/swiftlint/0.1.0/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
  Reason: image not found
Trace/BPT trap: 5
$

**Comment by jpsim** [comment]
Do you have Xcode installed under `/Applications/Xcode.app`? If so, which version of Xcode is there?

**Comment by velocismatt** [comment]
Nope... that would make way too much sense, right? ;)

$ ls -d /Applications/X*
/Applications/Xcode 5.1.1.app		/Applications/Xcode 6.3.1.app		/Applications/Xcode 6.3.app
/Applications/Xcode 6.1.app		/Applications/Xcode 6.3.2 GM.app	/Applications/Xcode-Beta.app
$


Maybe this would be helpful?
$ xcode-select -p
/Applications/Xcode 6.3.app/Contents/Developer
$

**Comment by jpsim** [comment]
If you symlink `/Applications/Xcode 6.3.app` to `/Applications/Xcode.app`, SwiftLintFramework should find `libclang.dylib` and SwiftLint should work.

**Comment by velocismatt** [comment]
good idea, I'll do that for now.

**Comment by phatblat** [comment]
Same issue here. Symlink workaround works great.

Now I need to remember to update the symlink whenever I `xcode-select -s`.

**Comment by jpsim** [comment]
I'm afraid that's the only option for the time being. Until we come up with a way to legally vendor `libclang.dylib`, or if there's a stable place for it.
