### ISSUE TITLE
Ability to customize severity / color of individual rules

### ISSUE THREAD

**Issue by zbeckman** [realm/SwiftLint#130]
I know there are several other tickets regarding customization of rules (e.g., #26) but I don't think this is covered:

It would be ideal to be able to customize not only rule parameters (e.g., the length of a line before the line-length-warning is triggered), but also *color*. Right now we have two colors: Yellow for warnings and red for errors. Severity tends to be in two states ("it's yellow ignore it" and "it's red I have to fix it").

Ideally, I could introduce a pale green (for, say, "FIXME" and "TODO" rules). This makes a clear distinction between to-do items that probably can be ignored, versus warnings that really should *not* be ignored.

**Comment by jpsim** [comment]
The colors rendered in Xcode are actually done *by* Xcode itself. They're built-in diagnostic UI elements. There's also a third one: warning (yellow), error (red) and *note* (gray). We don't have any rules that render notes at the moment, but I could be convinced to update the FIXME/TODO rules to be notes, but I think it's more appropriate to keep them as warnings.

**Comment by zbeckman** [comment]
This would be a perfect configuration item. I personally would make them notes – but I can see how some would prefer to keep them as warnings.
