### ISSUE TITLE
shows up error for libraries in Podfile

### ISSUE THREAD

**Issue by kunalgupta1593** [realm/SwiftLint#1302]
Swiftlint shows up error for the libraries that have been installed using pod. Obviously the developer would not change the code inside the 3rd prty library.

**Comment by jpsim** [comment]
Hi @kunalgupta1593, did you know SwiftLint can ignore certain directories? It's easy, just add the following to your `.swiftlint.yml` file:

```yaml
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
```

You can read more about SwiftLint's configuration options here: https://github.com/realm/SwiftLint#configuration

**Comment by marcelofabri** [comment]
@kunalgupta1593 Feel free to reopen if you have any more questions!
