### ISSUE TITLE
todo rule message is cluttered by whole source line

### ISSUE THREAD

**Issue by reitzig** [realm/SwiftLint#1304]
I get messages like this:

~~~
/my/file.swift:35:46: warning: Todo Violation: TODOs should be avoidedfatalError("Not yet implemente... (todo)
~~~

First, there is not even a space between the message and the line. Secondly, the actual TODO isn't even shown.

The badness propagates, e.g. to AppCode:

![screen shot 2017-02-14 at 11 38 02](https://cloud.githubusercontent.com/assets/4246780/22926400/b121c436-f2ac-11e6-97cd-f6903c921b15.png)

**Comment by jpsim** [comment]
what version of SwiftLint are you using? I feel like something like this was fixed several months ago...

**Comment by reitzig** [comment]
`0.16.1`, the latest brew can get me.
