### ISSUE TITLE
Create an output mode that is more suitable to further processing

### ISSUE THREAD

**Issue by reitzig** [realm/SwiftLint#1305]
The current format works for human CLI use but is not very nice for further processing for at least two reasons.

 1. The human-readable message is obsolete.
 2. There is no common format to details about the offense, and the data is hidden in natural language.

I propose this format:

~~~
file:line:column:rule:details
~~~

where

 * `file` is a path,
 * `line` and `column` are (ranges of?) integers, 
 * `rule` is a rule name (as listed by `swiftline rules`), and
 * `details` (if not empty) has one of these forms:

	~~~
	{expected=..., actual=...}
	"some string"
	~~~

	I have based this on the messages I've seen, which fall into these categories:  

	 * no extra information (e.g. missing_docs);
	 * expected vs actual (e.g. line_length);
	 * offending content (e.g. todo).

Violation types (`error`, `warning`, ...) and human-readable messages can be inferred from (a suitable variant, e.g. CSV, of) the rule list, using the rule name. 
That would also allow tools to *change* the type of rules by using their own lookup file (for instance, AppCode could allow users to configure different rules to be errors, warnings, weak warnings, ... themselves).

**Comment by reitzig** [comment]
Side note: running SwiftLint only for a single rule (given as CLI paramter) may also be useful for tools that want to offer separate settings for separate rules.

**Comment by jpsim** [comment]
Hi @reitzig, are you aware that SwiftLint comes with 7 different reporters, many of which are better suited than the default `xcode` reporter:

* xcode
* json
* csv
* checkstyle
* junit
* html
* emoji

The json and csv ones seem especially well suited for your described use case.

Does that help you or is there something else you'd like to see?

**Comment by reitzig** [comment]
Ah, I didn't think that through properly. I'm coming over from @bealex/SwiftLintAppCode which uses `xcode` so that the `.yml` is compatible with XCode; changing the output format of the `xcode` reporter would only make things worse. I haven't look at the other reporters yet, but I agree that JSON or CSV should be better for post-processing. Thanks!

**Comment by marcelofabri** [comment]
Tou can use the `--reporter` option to avoid changing the configurations file as well.
