### ISSUE TITLE
Don't allow Bundle() or Device() inits as they can be harmful

### ISSUE THREAD

**Issue by Noobish1** [realm/SwiftLint#1306]
We ran into a couple of these recently and we wrote some custom rules to make sure we never have them in our codebase ever again. Not sure if it's worth having a rule for, just figured i'd see what everyone thought.

**Comment by jpsim** [comment]
Seems reasonable to me.

**Comment by ornithocoder** [comment]
@jpsim @marcelofabri issue can be closed :-)
