### ISSUE TITLE
0.16.1: no more `--path` argument?

### ISSUE THREAD

**Issue by cbowns** [realm/SwiftLint#1307]
I'm trying to test a few swiftlint rules on the command-line, and I can't use `--path` anymore:

```
% swiftlint version                                 
0.16.1

cbowns at Warp in ~/Development/crlf/bold/bold-ios
% swiftlint --path BOLD/                            
Unrecognized command: '--path'. See `swiftlint help`.
```

**Comment by marcelofabri** [comment]
I don't think this was officially supported (if it worked at all). You need to use the command `lint` to pass options:
```
$ swiftlint lint --path BOLD/
```

**Comment by cbowns** [comment]
Ah ha. (Yeah, it used to work.) Thanks!

**Comment by jpsim** [comment]
That never worked with any version of SwiftLint, since it's never been available in Commandant, which SwiftLint's always used.
