### ISSUE TITLE
.swiftlint.yml not honored when running "Inspect Code" in AppCode

### ISSUE THREAD

**Issue by adamjmurray** [realm/SwiftLint#1313]
I'm using the SwiftLint AppCode plugin and it mostly works as expected. When I build in AppCode, it shows me the same warnings I get when I run swiftlint on the command line.

AppCode has a feature where you can "Inspect Code" separately from the build process (for example: right click a folder in the project pane and select "Inspect Code..." from the context menu). This is IMO a nicer workflow to review and fix SwiftLint issues along with other inspection results.

Unfortunately it seems using "Inspect Code" causes SwiftLint to run with the default ruleset instead of using my .swiftlint.yml config. That's my guess, because I am getting hundreds of extra warnings. I checked my AppCode preferences for inspections and SwiftLint settings, and don't see a way to address this.

Is this a fixable issue with the AppCode plug-in? Any workarounds?

PS - Thanks for making/maintaining SwiftLint!

**Comment by marcelofabri** [comment]
I'm not sure what we can do here. Seems an issue with either AppCode or AppCode plug-in itself, which is not an official part of the tool and should be reported on it: https://github.com/bealex/SwiftLintAppCode.

Feel free to reopen if there's anything that should be done in SwiftLint itself to fix this.

**Comment by adamjmurray** [comment]
Whoops. I didn't realize the AppCode plug-in is a separate project. Thanks for pointing me in the right direction.
