### ISSUE TITLE
redundant_void_return false positive

### ISSUE THREAD

**Issue by garnett** [realm/SwiftLint#1316]
Is triggered by method with following signature: 
`static func perform(_ model: Model) -> VoidResource`

**Comment by marcelofabri** [comment]
Can you test against master? I believe this was fixed already.

**Comment by garnett** [comment]
What is the easiest workflow to test it? Archive the binary from master?

**Comment by marcelofabri** [comment]
You can clone the project, run `make bootstrap` and `make install`.

I'm closing this since https://github.com/realm/SwiftLint/pull/1251 should fix it. Feel free to reopen if you still have this issue on `master`.
