### ISSUE TITLE
Is .swiftlint.yml ignored by Xcode?

### ISSUE THREAD

**Issue by hiragram** [realm/SwiftLint#132]
I want to exclude Pods directory so I placed .swiftlint.yml on xcode project root.
But still Pods file are linted...

What should I do or Where should I place yml?

**Comment by ZevEisenberg** [comment]
It looks like this may be a duplicate of https://github.com/realm/SwiftLint/issues/112: YAML configuration support was added after the latest Homebrew release.

**Comment by jpsim** [comment]
That's correct. I recommend you build SwiftLint from the `master` branch, which added configuration file support, but cannot be submitted to Homebrew at the moment because they don't allow formulas that depend on Xcode 7.
