### ISSUE TITLE
Tool for linting programmatic errors

### ISSUE THREAD

**Issue by felix91gr** [realm/SwiftLint#1320]
Hi! This issue is probably wholly misdirected, but I can't not ask.

SwiftLint checks for stylistic and convention errors. But is there something to lint for programmatic errors? Like errors that don't let you compile and such.

My guess is that XCode does this already, but I'm on linux and I don't have any macs. Therefore I ask.

Best wishes,
Félix

**Comment by marcelofabri** [comment]
What about using the swift compiler itself?

**Comment by jpsim** [comment]
Yeah, I'd definitely recommend using the Swift compiler for this.
