### ISSUE TITLE
false positive on attributes rule?!

### ISSUE THREAD

**Issue by OliverMahn-flinc** [realm/SwiftLint#1321]
Wether I put `@IBDesigable` on a new line or not, this class definition

`@IBDesignable
public class MoodControl: UIStackView {
`
gives the following warning: 

warning: Attributes Violation: Attributes should be on their own lines in functions and types, but on the same line as variables and imports. (attributes)

So .. what is the correct formatting to suppress the warning?

**Comment by aamctustwo** [comment]
You can configure the `attributes` rule in your `.swiftlint.yml`. It takes two arrays of strings (along with being able to modify the `severity`). You can provide an array of strings for `always_on_same_line` and `always_on_line_above`.

As an example, check out: https://github.com/ustwo/brunel/blob/03468220ab6dfa5a1f4615222f8d1444acc6887d/.swiftlint.yml#L34-L39

**Comment by OliverMahn-flinc** [comment]
Ok, thanks ... but what is the default behaviour? I thought On same line or new line .. one of these two possibilities should have removed the warning? I tried both and always got a warning.

**Comment by aamctustwo** [comment]
Default behaviour is that `@IBAction` and `@NSManaged` are always on the same line. All others default to the line above.

**Comment by OliverMahn-flinc** [comment]
Ok, but that doesn't work ... this code

`@IBDesignablepublic class MoodControl: UIStackView {`

**Comment by aamctustwo** [comment]
Did you try running `swiftlint lint --no-cache` after your modifications to the yml file? There are some caching issues that are currently being worked on.

**Comment by OliverMahn-flinc** [comment]
Ok .... --no-cache worked!

Thanks
