### ISSUE TITLE
Suggestion: Lint errors on new project?

### ISSUE THREAD

**Issue by jasonify** [realm/SwiftLint#1325]
Hi,

Every new project has a few lint errors due to the line length.

Aside from disabling the line count rule / fixing by hand, is there a solution?

Perhaps a command similar to autocorrect but for new projects. 

Nitpick I know but just wanted to throw an idea / suggestion out there. 

Note: Also, originally I had opened this ticket because I kept getting the No litnable path '' found.. it was because it was an objective-c project.

**Comment by marcelofabri** [comment]
I'm not sure how one command could automatically fix the issues. Could you elaborate?

**Comment by jpsim** [comment]
My preferred answer to this problem is to build something like robocop's `--auto-gen-config` as described and tracked in #532. I'll be closing this ticket as a duplicate.
