### ISSUE TITLE
autocorrect reformat indent tab vs space

### ISSUE THREAD

**Issue by rx2130** [realm/SwiftLint#1327]
I'm running ```swiftlint autocorrect --format``` to reformat the Swift files. But the linter was indenting using space while I'm using tab. Reading the source code I found the linter ```useTabs: false``` in the ```AutoCorrectCommand```. But I don't know how to make that ```useTabs: true``` without cloning and recompile the code.

Is there any way user could change the ```useTabs``` in the autocorrect format config? 

Thanks!

**Comment by jpsim** [comment]
SwiftLint doesn't yet expose a way to format with tabs rather than spaces, but you could make a PR to add that option to `AutoCorrectOptions`: https://github.com/realm/SwiftLint/blob/master/Source/swiftlint/Commands/AutoCorrectCommand.swift

I'd be happy to review that.

**Comment by codytwinton** [comment]
@jpsim Would this be added as a stand alone option for `autocorrect`, or would this be a child option of the `--format` option? If so, how can a child option be added to `--format`?

**Comment by marcelofabri** [comment]
Closed by @codytwinton in #1613 🎉
