### ISSUE TITLE
Inconsistent "missing_docs" warnings

### ISSUE THREAD

**Issue by jpipard** [realm/SwiftLint#1330]
Hello all :-)
We get a lot of "missing_docs" warnings in our project. But we don't understand why. We installed SwiftLint via cocoapods `pod 'SwiftLint', '~> 0.16.1'`. 

**1. Here's the **first** example :**
For this example, I don't understand why the comment for `addConstraint` is fine but not the one for `removeContraint`

![image](https://cloud.githubusercontent.com/assets/1567748/23205926/056a6e5e-f8ec-11e6-8217-b130231aed6a.png)

**2. And here's a second example for a struct :**
![image](https://cloud.githubusercontent.com/assets/1567748/23206127/cbf66b7c-f8ec-11e6-88e4-9d6ef2f065a6.png)

Is there something missing in my comments formats ?
Thank you for your help!

**Comment by jpipard** [comment]
seems to be related to https://github.com/realm/SwiftLint/issues/728

**Comment by mgrebenets** [comment]
Same for us, this seems to be an old issue and it wasn't fixed when we moved onto Swift 3.
For now we had to disable `missing_docs`...

**Comment by jpsim** [comment]
That's right, this was tracked as #728 and the rules ultimately disabled for Swift 2.3+.
