### ISSUE TITLE
`unused_closure_parameter` removes all parameter names from closures called immediately.

### ISSUE THREAD

**Issue by ChristopherRogers** [realm/SwiftLint#1332]
Here's a simple example:

```swift
{ (i) in i }(42)
```

...will get turned into

```swift
{ (_) in i }(42)
```

**Comment by marcelofabri** [comment]
This should be fixed on `master`. Could you try that?

**Comment by ChristopherRogers** [comment]
Oh, I had overlooked the bug fix stated in the change log because at the time I thought this issue was due to the parameter name shadowing another name. I'll check it on `master` later when I have time.

**Comment by marcelofabri** [comment]
I'm closing this since I'm pretty sure we already fixed it. Feel free to reopen if that's not the case.
