### ISSUE TITLE
Extend SwiftLint to allow team-wide and project-specific configs together

### ISSUE THREAD

**Issue by gretzki** [realm/SwiftLint#1357]
With SwiftLint it's currently possible to specify such a shared config file via the `--config` option.
Having a project-specific .swiftlint.yml file at the root of the project, a merge of both configurations is already possible. Even if the merge function is not implemented yet, as stated in #676.

But having multiple project specific configurations at different locations inside the project and one global configuration specified, the merge function is not invoked as expected.
The following example should clarify the problem:

$PROJECT_ROOT /
- A.swift
- .swiftlint.yml
- Database/.swiftlint.yml
- Database/B.swift

$HOME /
- corporation-wide-swiftlint.yml

When analysing the project with `swiftlint lint --path $PROJECT_ROOT --config $HOME/corporation-wide-swiftlint.yml` the merge function is invoked as follows:

Merge1) 
$PROJECT_ROOT/.swiftlint.yml (as parameter)
$HOME/corporation-wide-swiftlint.yml (as self)

Merge2)
$PROJECT_ROOT/Database/.swiftlint.yml (as parameter)
$HOME/corporation-wide-swiftlint.yml (as self)

**Expected behavior:**
When linting `B.swift` I would expect the recursive merge to merge as follows:
Expected Merge2a)
$PROJECT_ROOT/Database/.swiftlint.yml (as parameter)
$PROJECT_ROOT/.swiftlint.yml (as self)

Expected Merge2b)
Merged config of merge2a (as parameter)
$HOME/corporation-wide-swiftlint.yml (as self)

**Comment by nigelflack** [comment]
Hi - I got an update on this since I commented on #676 

I think #1357 and #1352 (my issue) are basically the same right? (although I hadn't noticed the --config option!)

**Comment by gretzki** [comment]
Hi @nigelflack,
you're right. Mine issue and yours require the same technical adaptations.
The only difference is, that I propose an automatic merge of the specified config file with the project's config files, instead of (your issue) specifying all config files explicitly.

But yeah, same good ideas ;)

**Comment by gretzki** [comment]
As I debugged SwiftLint I realized, that the project's config file is already being merged with the global one specified via the config option.
Since the merge function is not implemented yet, the global config is simply being replaced by the project's one. So solving #676 will solve my issue too :)

**Comment by gretzki** [comment]
Ok, this was closed a bit early.
There's still some issues when specifying a global configuration via the config file and having multiple configs inside the project. I will update the first comment to include the latest issue.

**Comment by jpsim** [comment]
Sorry I don't understand your last comment @gretzki, notably why merging configurations (#676) isn't sufficient for your needs. Could you please elaborate?

**Comment by gretzki** [comment]
Hi @jpsim . 
As stated above in "expected behavior", I expected a recursive merge of config files up the folder hierarchy. But that's just one possible way to go I guess, so it's also ok as it is.
Nevermind, I'll close this issue for now ;)

**Comment by Aranoledur** [comment]
Hi, @gretzki! Have you debugged this merge call?
Merge1)
$PROJECT_ROOT/.swiftlint.yml (as parameter)
$HOME/corporation-wide-swiftlint.yml (as self)

I set a breakpoint at `Configuration.merge` and it's not hit at this case. Only Merge2 is called. So the logic for `--config`parameter is reset config file at --path or working directory.
