### ISSUE TITLE
Bug/Feature: CI for Linux and/or Linux Documentation

### ISSUE THREAD

**Issue by therealbnut** [realm/SwiftLint#1366]
I'm trying to get a subset of my tests working on AWS using SwiftLint, it seems I'm either doing it wrong or the current release doesn't work.

It would be awesome if:
 * you also ran your **SwiftLint CI on Linux** as well to make sure it keeps working, and/or
 * there was more extensive **documentation for building SwiftLint on Linux**.

I imagine that making this easy would be awesome for the community, it would make it possible to run a wide range of tests on an auto-scaling cloud instance. Currently this is quite hard or expensive to do with MacOS, but relatively easier with Linux.

------

Aside, I have it built, but running `swiftlint` I get an error:
```bash
$ swiftlint
fatal error: Loading libsourcekitdInProc.so failed: <path-to-sourcekitten>/SourceKittenFramework/library_wrapper.swift, line 61
Illegal instruction (core dumped)
```
This file is in the filesystem at `/usr/lib/libsourcekitdInProc.so`.

I realise this problem is probably SourceKitten's fault, but I don't think it has been caught here either.

**Comment by marcelofabri** [comment]
We do run the tests on Linux: https://github.com/realm/SwiftLint/blob/master/.travis.yml#L16

**Comment by therealbnut** [comment]
Okay, thanks for the link @marcelofabri :) I'm going to close this issue and presume this is my fault, if I work out what went wrong I'll put up a PR to clarify the SwiftLint documentation.

**Comment by marcelofabri** [comment]
We definitely can use some help on documentation!
