### ISSUE TITLE
Danger CI task is hanging. 

### ISSUE THREAD

**Issue by aaroncrespo** [realm/SwiftLint#1369]
Looks like the recent Danger release is causing travis' invocation to hang indefinitely. 

https://github.com/danger/danger/releases/tag/v4.3.1

All PR's submitted/updated since the update are failing CI's

**Comment by marcelofabri** [comment]
We lock the Danger version with bundler, so this shouldn't happen. Maybe something else is going on?

**Comment by aaroncrespo** [comment]
Good point I saw the gemfile, but didn't notice the .lock file. 

Not sure what is happening because the only output I get from CI is that Danger took to long to complete. 

this successful build: https://circleci.com/gh/realm/SwiftLint/559 took 18min for the danger task

but recently they have all timed out after 10+

**Comment by marcelofabri** [comment]
Feel free to open a PR printing Danger version so we can be sure.

**Comment by aaroncrespo** [comment]
I don't think its the Danger version anymore, but I'm not sure what is causing it to hang either.

**Comment by marcelofabri** [comment]
I think something might have changed on Circle CI's infrastructure, because it's timing out after the "Building branch" message.

**Comment by marcelofabri** [comment]
It seems it was some instability on Circle CI. I've retriggered the jobs today and they're passing.
