### ISSUE TITLE
** INSTALL FAILED **

### ISSUE THREAD

**Issue by respectTheCode** [realm/SwiftLint#137]
Not sure why a warning is causing the install to fail, but it does.

	==> make prefix_install PREFIX=/usr/local/Cellar/swiftlint/0.1.2 TEMPORARY_FOLDER=/private/tmp/swiftlint20150928-4804-18lrpby/SwiftLint.dst
	Last 15 lines from /Users/kevin/Library/Logs/Homebrew/swiftlint/01.make:
	                                                                ^~~~~~~
	                                                                 
	/tmp/swiftlint20150928-4804-18lrpby/Carthage/Checkouts/Commandant/Carthage/Checkouts/LlamaKit/LlamaKit/Result.swift:135:21: warning: immutable value 'error' was never used; consider replacing with '_' or removing it
	  case .Failure(let error):
	                    ^~~~~
	                    _

	** INSTALL FAILED **

	The following build commands failed:
		CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
		CompileSwift normal x86_64 /tmp/swiftlint20150928-4804-18lrpby/Carthage/Checkouts/Commandant/Carthage/Checkouts/LlamaKit/LlamaKit/Result.swift
	(2 failures)
	make: *** [installables] Error 65

**Comment by jpsim** [comment]
What does `xcode-select -p` print? The version Homebrew is trying to compile requires Xcode 6.4.

**Comment by respectTheCode** [comment]
Well that would be the problem. If SwiftLint doesn't support Xcode 7 / Swift 2.0 there should really be a note in the readme.

**Comment by jpsim** [comment]
SwiftLint on the `master` branch *does* support Xcode 7 and Swift 2.0, but until late last week, Homebrew couldn't accept formulas depending on Xcode 7, so we haven't been able to cut a release.

So if you were looking at the README on the master branch, it's up to date with code that's on that branch.
