### ISSUE TITLE
Specify reporter from the command line

### ISSUE THREAD

**Issue by mrtj** [realm/SwiftLint#1374]
I am using swiftlint two different ways:

1. as an Xcode build phase in a separate target so the developers can lint their code manually
2. as a step in our CI pipeline that rejects merge requests if the linter had some serious warning.

I created the `.swiftlint.yml` file in the project root and almost everything works fine. In the first case it would be very convenient to use the xcode reporter so the devs can see the errors and warnings directly in Xcode, in the second case it made more sense to use the html reporter as these reports will be archived as a build artifacts and it is simple more user friendly to have html reports as an output of the CI pipeline. The problem is that I must specify the reporter in the configuration file and I can not differentiate the reporters from the build phases and the CI script. 

So it would be wonderful to be able to specify the reporter also from the command line.

**Comment by marcelofabri** [comment]
You can do that with `swiftlint lint --reporter xcode` for example.

**Comment by mrtj** [comment]
Sorry I completely overlooked this option

**Comment by marcelofabri** [comment]
No worries! Feel free to reopen or open another issue if you have any other questions 💯
