### ISSUE TITLE
Ability to customize VariableNameRule

### ISSUE THREAD

**Issue by CraigSiemens** [realm/SwiftLint#138]
Right now `VariableNameRule` checks 3 things
- only alphanumeric character
- starts with lowercase character
- length between 3 and 40

It would be nice to be able to individually turn each of those on or off.

My current case is that I want to disable the last one because my models have a property called `id` and I would prefer not to change it to `userId` since it would always be used as `user.userId`. I'd like to keep the first two rules and disable the last one.

**Comment by keith** [comment]
One option for this would be splitting these into multiple rules. In our fork we have disabled some of these as well.

**Comment by jpsim** [comment]
I support splitting VariableNameRule into multiple rules.

**Comment by tom-sparo** [comment]
I also think supporting splitting up VariableNameRule into multiple rules is a good idea

But the original issue is also valid -- maybe there should be the ability to change defaults or add extra customization via the yaml file for certain rules?  VariableNameRule could then be customized for variable length or naming convention.  I've run into the same exact problem as above -- a variable named `id`.

**Comment by roman-dzieciol** [comment]
I'll submit parametrised VariableNameRule once I get some feedback on similar change for TypeNameRule https://github.com/realm/SwiftLint/pull/165

In the long run splitting it into multiple rules is probably the best bet

**Comment by mmorier** [comment]
I also removed min and max length checks of VariableNameRule to create two new parameter rules : VariableNameMaxLengthRule and VariableNameMinLengthRule. See #182.

He may help you for your variable name `id`.

**Comment by jpsim** [comment]
Done in #182.
