### ISSUE TITLE
Crash swiftlint homebrew17 when using custom reports

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#1386]
It seems to be crashing at reporting when there are a lot of violations.

No sure though. The Xcode project shows the same behavior. 
https://travis-ci.org/exercism/xswift/jobs/214475852

**Comment by masters3d** [comment]
```
Testing failed:
	Static method 'generateReport(_:swiftlintVersion:dateString:)' took 175ms to type-check (limit: 150ms)
** TEST FAILED **
```

**Comment by marcelofabri** [comment]
@masters3d I'm not sure how your last comment is related to the issue.

**Comment by masters3d** [comment]
@marcelofabri You are right. 

I guess is the new identifier_name rule. 

```
identifier_name:
    min_length:
        warning: 1
        error: 0
```
