### ISSUE TITLE
do a release with all the added stuff, please!

### ISSUE THREAD

**Issue by roddi** [realm/SwiftLint#139]

**Comment by jpsim** [comment]
Done! https://github.com/realm/SwiftLint/releases/tag/0.2.0

In related news, if anyone would like to help maintain this project, please reach out to me, I could use a hand!

**Comment by jpsim** [comment]
Submitted to Homebrew too: Homebrew/homebrew#44476

**Comment by dpassage** [comment]
Thanks! Looking forward to getting it incorporated in our builds.

**Comment by jpsim** [comment]
And now available via Homebrew.

**Comment by roddi** [comment]
Thank You! Very appreciated. 

You said you could need a helping hand. What did you have in mind?

**Comment by jpsim** [comment]
> You said you could need a helping hand. What did you have in mind?

Anyone who can help respond to "support" tickets that come in via GitHub issues, or tackle [existing feature requests](/realm/SwiftLint/issues) would be great.
