### ISSUE TITLE
Linting with --lenient is still emitting errors

### ISSUE THREAD

**Issue by NachoSoto** [realm/SwiftLint#1391]
See https://github.com/realm/SwiftLint/pull/1364#issuecomment-289083968.

**Comment by aaroncrespo** [comment]
My working theory is that the severity suppression runs after reporters report. 
https://github.com/realm/SwiftLint/blob/master/Source/swiftlint/Commands/LintCommand.swift#L54

**Comment by aaroncrespo** [comment]
https://github.com/realm/SwiftLint/pull/1394

**Comment by jpsim** [comment]
Fixed in bc7fa32.
