### ISSUE TITLE
xcpretty not displaying SwiftLint warnings

### ISSUE THREAD

**Issue by c0diq** [realm/SwiftLint#1392]
When SwiftLint runs as a build phase script but xcodebuild is piped into xcpretty on a jenkins box, warnings don't seem to be displayed like other xcode warnings.

`xcodebuild -project Foo.xcodeproj -scheme Foo -sdk iphoneos -derivedDataPath build -configuration Debug build | xcpretty`

**Comment by marcelofabri** [comment]
Can you share a demo project and a xcodebuild log with a "regular" warning and a SwiftLint violation?

**Comment by thebugcode** [comment]
I experience the very same issue @c0diq is talking about for a few weeks now. Warnings are missing, although they werent missing before that. I'm trying to prepare an xcode project proving this bug.

**Comment by jpsim** [comment]
I look forward to seeing that

**Comment by thebugcode** [comment]
@jpsim Here is my project with a walkthrough. It proves I think beyond doubt that xcpretty is filtering out Swiftlint's warnings.  
https://github.com/thebugcode/SwiftlintWarnings

**Comment by jpsim** [comment]
Thanks for the project! This issue is unrelated to SwiftLint, but rather xcpretty: https://github.com/supermarin/xcpretty/issues/87

See this thread in fastlane about exactly this problem (but without involving SwiftLint): https://github.com/fastlane/fastlane/issues/8026
