### ISSUE TITLE
Bug Fix: Crash when parsing variable names containing unicode only characters

### ISSUE THREAD

**Issue by valdirunars** [realm/SwiftLint#1406]
If variable name is an emoji swiftlint crashes

```line 7:  1225 Illegal instruction: 4  swiftlint```

**Comment by kimdv** [comment]
It can maybe be related to #1336

**Comment by valdirunars** [comment]
Not really error is happening when I do this

```swift
init { 👷 in
    👷.variable = value
}
```

**Comment by marcelofabri** [comment]
Closing as a duplicate of #1006.
