### ISSUE TITLE
Rule request: File name should match first type name

### ISSUE THREAD

**Issue by kainsu** [realm/SwiftLint#1420]
I would like propose a new rule for validating filenames in SwiftLint

**Rule Description**
A violation of this rules occurs when file name doesn't match the first type declared within this file. For example, violation of this rule should be logged in case if file "ClassZ.swift" the firsrt statements declares "ClassX"

**Open questions**
- How to correctly name a files which contains generics? In C# world the name of such files needs to be "Class1{T}.cs" or something like that. However, I'm not sure about whether Swift has such traditions. 
- How to correctly name a files which contains extensions for already defined classes?

**Comment by marcelofabri** [comment]
I don't think first type is quite right. Maybe first non-private type? Or any type at all?

> How to correctly name a files which contains generics? In C# world the name of such files needs to be "Class1{T}.cs" or something like that. However, I'm not sure about whether Swift has such traditions.

This is not usual in Swift. It'd be called just `Class1.swift`.

> How to correctly name a files which contains extensions for already defined classes?

If the extensions are all for the same type, I'd expect it to be called `SomeType+MeaninfulExplanationOrProtocol.swift`. This is inherited from Objective-C days.

**Comment by jpsim** [comment]
In-progress PR here: #1559.
