### ISSUE TITLE
$ apm install SwiftLint ?

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#143]
Alternative to homebrew possible?

**Comment by jpsim** [comment]
> Alternative to homebrew possible?

Sure! Homebrew, pkg and building from source are all supported means of installation! https://github.com/realm/SwiftLint#installation

**Comment by masters3d** [comment]
This is what I was thinking but is not implemented yet in apm https://github.com/atom/apm/issues/355

**Comment by jpsim** [comment]
That's completely unrelated.

**Comment by masters3d** [comment]
Yep ;) I was thinking Atom . oops
