### ISSUE TITLE
Swiftlint crashing

### ISSUE THREAD

**Issue by RishabhTayal** [realm/SwiftLint#1439]
I am running `swiftlint` from command line and it crashes. I have a custom `.swiftlint.yml`.

```
$ swiftlint 
Illegal instruction: 4
```

**Comment by RishabhTayal** [comment]
I was using this line previously

`
return_arrow_whitespace: severity: error
`

now it needs to be like this

```
return_arrow_whitespace: 
     severity: error
```

**Comment by jpsim** [comment]
Yes, the first line isn't valid YAML. Although this will provide a nicer error message once we upgrade Yams to a release that includes https://github.com/jpsim/Yams/pull/37.

**Comment by Coeur** [comment]
Note: duplicate of https://github.com/realm/SwiftLint/issues/1436
Also, there is a StackOverflow answer for it too: https://stackoverflow.com/questions/43405657/illegal-instruction-4-pods-root-swiftlint-swiftlint/43405658#43405658
