### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by SebastianKumor** [realm/SwiftLint#1445]
i was having no problems with swxftlint and then i changed some included and excluded files in the .yml file and now I am getting this error when the script runs 
`/Users/sebastiankumor/Library/Developer/Xcode/DerivedData/TalkingNinja-ewstofrbhurmqpgoxbstuyveuvjv/Build/Intermediates/TalkingNinja.build/Debug-iphoneos/TalkingNinja.build/Script-4B1894391EA6D8F1006A2DE2.sh: line 2: /Users/sebastiankumor/Documents/TvM/talking: No such file or directory`

I tried to change it back even remove the .yml file but still the same error.

I am using cocoapods and I did not change any folder names or anything. Any idea what could cause this issue ?

Thank you

**Comment by marcelofabri** [comment]
Can you provide your build phase script?

**Comment by SebastianKumor** [comment]
I am using this one `${PODS_ROOT}/SwiftLint/swiftlint`

**Comment by marcelofabri** [comment]
Have you run `pod install`?

**Comment by SebastianKumor** [comment]
yes i did

**Comment by SebastianKumor** [comment]
The problem here was that I had a space in folder name where I had the project.
