### ISSUE TITLE
Make redundant_discardable_let and unused_optional_binding opt-in

### ISSUE THREAD

**Issue by klaaspieter** [realm/SwiftLint#1446]
I believe code should be as easy possible to change. I think `redundant_discardable_let` and `unused_optional_binding` make code harder to change. Because of this I would prefer them to be opt-in rules.

They make code harder to change because with `redundant_discardable_let` the `let` has to be prepended again when the requirements change such that the value does have to be captured.

The `unused_optional_binding` is even harder because the code has to change from a trailing `!= nil` to a leading `let name =`. 

These rules are [debated in the community](https://github.com/realm/SwiftLint/issues/1116#issuecomment-270780321) and I think they should therefore be an opt-in rule

**Comment by freak4pc** [comment]
+1 on this. Attaching the original [Unused Optional Binding discussion](https://github.com/realm/SwiftLint/pull/1119#issuecomment-295606484) with @jpsim and @marcelofabri as a followup. 

I am still in favor of perhaps finding a more thorough method of determining if a rule should be implemented as opt-in. I also agree with @marcelofabri that we should aim having most rules as default and be opinionated as other linters, but those opinions should be backed by a community standard or some sort of a majority, and not just by a portion of developers IMO.

**Comment by idrougge** [comment]
I agree that this rule is not established well enough in the Swift community as preferable (many would say that `if let _ =` is more idiomatic Swift) to warrant being enabled by default.
