### ISSUE TITLE
SwiftLint not working within AppCode 2017.1

### ISSUE THREAD

**Issue by gmosx** [realm/SwiftLint#1448]
I installed SwiftLint and the AppCode SwiftLintPlugin.
While SwiftLint works from the command line and within other editors (e.g. Atom) it doesn't seem to work within AppCode, i.e. I don't see any warnings, etc.

The plugin is enabled.

**Comment by marcelofabri** [comment]
I'm not sure what we can do here. Seems an issue with either AppCode or AppCode plug-in itself, which is not an official part of the tool and should be reported on it: https://github.com/bealex/SwiftLintAppCode.

Feel free to reopen if there's anything that should be done in SwiftLint itself to fix this.
