### ISSUE TITLE
How to wrap lines that have a type in them

### ISSUE THREAD

**Issue by Tableau-David-Potter** [realm/SwiftLint#146]
I have some classes and variables with long names that violate the long line rule.  Xcode doesn't give me very many options for wrapping that are also readable - it wants to wrap to the same horizontal position no matter where I choose to wrap.  The best I've come up with is to wrap at the colon.  Here's an example.

````swift
final class MetricOverviewContainerViewController: UIViewController, UIPageViewControllerDataSource {
```

Here's my wrapping solution:

```swift
final class MetricOverviewContainerViewController
: UIViewController, UIPageViewControllerDataSource {
```

However, this violates the colon rule.  I suppose I could disable that rule, but that's getting rather messy.  I have the same problem with properties.  Any ideas on how to solve this problem?

Thanks,
***David***

**Comment by Tableau-David-Potter** [comment]
As a follow-up, the following solutions still produce a colon violation:

```swift
final class MetricOverviewContainerViewController:
    UIViewController, UIPageViewControllerDataSource {

    private var metricOverviewContainerViewControllerFactory:
        MetricOverviewContainerViewControllerFactory!
```

**Comment by jpsim** [comment]
You could disable the rule altogether by adding the following to your `.swliftlint.yml` file:

```yaml
disabled_rules:
  - colon
```

This is discussed in the README: https://github.com/realm/SwiftLint#configuration

You could also disable it just for one file by adding `// swiftlint:disable colon` at the top of the file.

In other words, `swiftlint:disable` commands don't need to be matched with `swiftlint:enable` commands, they can just be one-sided.

**Comment by Tableau-David-Potter** [comment]
Thanks JP.  I actually like the rule, so I don't want to disable it permanently or even for a whole file.  It may be that the best option is to disable it for these lines.  There is a tension between limiting line length and wrapping in a readable way and Xcode doesn't appear to do a very good job of supporting this tension.  I was hoping maybe you'd encountered this issue and had a solution that you could recommend or that was in the works.

Thanks for the response and for your work on this tool.

**Comment by jpsim** [comment]
Something I occasionally do is to have one inheritance/conformance per declaration, which helps organize code into groups of related functionality:

```swift
final class MetricOverviewContainerViewController: UIViewController {
  ...
}

extension MetricOverviewContainerViewController: UIPageViewControllerDataSource {
  ...
}
```

**Comment by Tableau-David-Potter** [comment]
That's a good point, especially for protocols.  Thanks.
