### ISSUE TITLE
Blank lines around var/let

### ISSUE THREAD

**Issue by Uncommon** [realm/SwiftLint#1461]
I like to have blank lines separating groups of var/let statements from other kinds of statements.

I'm taking a stab at implementing this myself, so I'm looking for some feedback on whether I'm on the right track. The angle I'm looking at right now is looping through `file.structure.dictionary.substructure` to collect a list of lines that have var/let statements (SwiftDeclarationKind.var***), and then making sure they're all surrounded by blank lines appropriately. Does that sound like a good approach?

**Comment by marcelofabri** [comment]
Implemented in #1471.
