### ISSUE TITLE
fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed

### ISSUE THREAD

**Issue by PraveenSingh107** [realm/SwiftLint#1466]
I started facing this fatal error while running the lint command. 

fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /tmp/swiftlint-20160824-65136-lo3uim/Carthage/Checkouts/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 59
.git/hooks/pre-commit: line 7: 32011 Illegal instruction: 4  ${SWIFT_LINT} lint --strict --quiet --path ${filename}

Any suggestions why suddenly this fatal error is stopping swiftlint?

**Comment by jpsim** [comment]
Have you installed Xcode? What's the result of `xcode-select -p`?

**Comment by PraveenSingh107** [comment]
Yeah, i've installed xcode. swiftlint was working fine but suddenly it started throwing this error. 
Output of xcode-select -p : /Library/Developer/CommandLineTools

**Comment by jpsim** [comment]
The command line tools located at `/Library/Developer/CommandLineTools` do not contain a Swift toolchain.

Where have you installed Xcode? If it's installed under `/Applications/Xcode.app`, please run:

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

If it's installed elsewhere, please replace the `/Applications/Xcode.app` path in the command above to the location where you've installed Xcode.

**Comment by PraveenSingh107** [comment]
Thanks. Issue got resolved

**Comment by ulkoart** [comment]
> The command line tools located at `/Library/Developer/CommandLineTools` do not contain a Swift toolchain.
> 
> Where have you installed Xcode? If it's installed under `/Applications/Xcode.app`, please run:
> 
> ```
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
> ```
> 
> If it's installed elsewhere, please replace the `/Applications/Xcode.app` path in the command above to the location where you've installed Xcode.

Thank you so much! advice helped me.

**Comment by koushikkarmakar** [comment]
> The command line tools located at `/Library/Developer/CommandLineTools` do not contain a Swift toolchain.
> 
> Where have you installed Xcode? If it's installed under `/Applications/Xcode.app`, please run:
> 
> ```
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
> ```
> 
> If it's installed elsewhere, please replace the `/Applications/Xcode.app` path in the command above to the location where you've installed Xcode.

thanks a lot !! it helped me as well :D

**Comment by ObjectiveCesar** [comment]
> The command line tools located at `/Library/Developer/CommandLineTools` do not contain a Swift toolchain.
> 
> Where have you installed Xcode? If it's installed under `/Applications/Xcode.app`, please run:
> 
> ```
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
> ```
> 
> If it's installed elsewhere, please replace the `/Applications/Xcode.app` path in the command above to the location where you've installed Xcode.

This is not sufficient, if you have a nightly/snapshot swift toolchain installed. See: https://github.com/realm/SwiftLint/issues/5325#issuecomment-1905730385

**Comment by lucaomr** [comment]
Thanks, this help me a lot!

**Comment by metasidd** [comment]
Small nit for non-developers like me who struggled with the command above. If you're running... 

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

and are seeing the error below,
```
xcode-select: error: invalid developer directory '/Applications/Xcode.app/Contents/Developer'
```

You likely have a separate XCode app name. Try running something like this
```
sudo xcode-select -s /Applications/Xcode\ 16.app/Contents/Developer
```

Hope it helps 🙏
