### ISSUE TITLE
dyld errors when trying to run SwiftLint

### ISSUE THREAD

**Issue by tuzonghua** [realm/SwiftLint#147]
When I install SwiftLint from Homebrew and try to run it, I get this error:
```
➜ swiftlint rules                                                                                                                            
dyld: Symbol not found: __TMpSs13OptionSetType
  Referenced from: /usr/local/Cellar/swiftlint/0.2.0/bin/../Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks//Yaml.framework/Versions/A/Yaml
  Expected in: /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftCore.dylib
 in /usr/local/Cellar/swiftlint/0.2.0/bin/../Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks//Yaml.framework/Versions/A/Yaml
[1]    3740 trace trap  swiftlint rules
```

And when I install the .pkg version, this is the error:
```
➜ swiftlint
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Library/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
  Reason: image not found
[1]    3998 trace trap  swiftlint
```

Output of `xcode-select -p` is `/Applications/Xcode.app/Contents/Developer`. Running OS X 10.10.5 and Xcode 7.0.1 (7A1001).

**Comment by tuzonghua** [comment]
Just tried installing from Git. On `make install`, this was the error: https://gist.github.com/tuzonghua/15f374c21a6252005563.

**Comment by jpsim** [comment]
I'm not exactly sure what's causing this. Can you try `rm /usr/local/bin/swiftlint` or `brew uninstall swiftlint` followed by `brew install swiftlint`?

**Comment by tuzonghua** [comment]
Interesting. I had run that combo of commands earlier and on re-install it was still broken. Now it works.
