### ISSUE TITLE
[rule request] enforce the order of `final` along with ACL of classes

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#1472]
optional rule to enforce order of final of classes in a code base

`internal final class MyClass {}`
or
`final public class MyClass {}`

This could probably be done by using a regex to check both possibilities and suggest one or the other depending on preferences. A regex could also catch multiline declarations

```swift
import Foundation

public
final class MyClass{}
```

`<ws*>public|internal<ws*>final<ws*>class<ws*>`
`<ws*>final<ws*>public|internal<ws*>class<ws*>`

This rule doesn't seek to introduce final, only to make the declaration consistent for readability
This is different than  https://github.com/realm/SwiftLint/issues/228

**Comment by marcelofabri** [comment]
Subset of #387?

**Comment by masters3d** [comment]
Yes. Subset. I guess we could also include `weak` but not attributes.
