### ISSUE TITLE
Deprecate/remove implicit configurations

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1475]
Supporting Implicit configurations makes harder to add more options to a rule configurations and I'd bet we already break support for it sometimes when changing a rule configuration.

**Comment by jpsim** [comment]
By "implicit configurations", do you mean like default values for configurations?

Like how [VoidReturnRule](https://github.com/realm/SwiftLint/blob/0.18.1/Source/SwiftLintFramework/Rules/VoidReturnRule.swift#L13) has a default severity configuration of `.warning`? And how [LineLengthRule](https://github.com/realm/SwiftLint/blob/0.18.1/Source/SwiftLintFramework/Rules/LineLengthRule.swift#L13) has a default warning configuration of 120 & error of 200?

It seems like it'd be impractical to have to specify all configuration values for every project in which those rules should be enabled.

Right now, you can run `swiftlint` without a `.swiftlint.yml` file. You couldn't if we removed default configurations.

**Comment by marcelofabri** [comment]
No, I mean supporting arrays like this:

```yml
type_body_length:
  - 300 # warning
  - 400 # error
```

**Comment by jpsim** [comment]
Ah, ok I'm in favor of that I think. Just the array version though, since the `type_body_length: 300` config syntax is pretty nice.
