### ISSUE TITLE
Add excluding_regex to custom_rules

### ISSUE THREAD

**Issue by nvh** [realm/SwiftLint#1479]
It would be nice to have the possibility to add an excluding_regex to custom_rules:

```swift
custom_rules:
  pirates_beat_ninjas: # rule identifier
    name: "Pirates Beat Ninjas" # rule name. optional.
    regex: "([n,N]inja)" # matching pattern
    excluding_regex: "([n,N]inja pirates)" # excluding pattern
```

As far as I can see, what's needed for this is the parsing of this from the config, and the passing of that value into the `excludingPattern` argument of the `match` function in `CustomRules.swift`.

Would a PR for this be interesting?

**Comment by jpsim** [comment]
In order to gauge the usefulness of this it would be helpful if you shared a concrete example of where this would be used.

 I suspect that most combinations of including and excluding regular expressions can be merged into a single regex.

**Comment by nvh** [comment]
I was looking into making a custom adjusted version of the [OpeningBraceRule](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/OpeningBraceRule.swift), but wasn't able to do that because CustomRules didn't support an excludingPattern.
