### ISSUE TITLE
Ignore parts of rules

### ISSUE THREAD

**Issue by gilazo** [realm/SwiftLint#148]
Is there a way to ignore certain parts of rules?  For example, I have an object that has a property name of id.  I chose this name to conform to the key of the json object I get back from the server.

I get a violation because this property name is less than 3 characters.  I would like to ignore this single case of the variable name rule.

Any ideas?

**Comment by keith** [comment]
This is a duplicate of https://github.com/realm/SwiftLint/issues/138

**Comment by gilazo** [comment]
Ha!  It sure is.
