### ISSUE TITLE
Make binary SwiftLint binary  version available via Carthage

### ISSUE THREAD

**Issue by maksymmalyhin** [realm/SwiftLint#1481]
## Goals
I would like to install a specific version of Swiftlint as a dependency to my iOS project using Carthage. Currently, this works perfectly with Cocoapods:
`pod 'SwiftLint', '0.18.1'`
As result, a binary for the specified Swiftlint version is downloaded.

## Expected Results
It is possible to specify a binary in a `Cartfile` e.g.
`binary "https://github.com/realm/SwiftLint/releases/Swiftlint.json" 0.18.1`

## Actual Results
Binary versions of Swiftlint are not available via Carthage. To make them available, there should be a JSON file with enumerations of binary version (see https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification )

Swiftlint version: 0.18.1

**Comment by jpsim** [comment]
We do provide binaries compatible with Carthage of `SwiftLintFramework`, the framework that powers the SwiftLint CLI, but as far as I know, Carthage doesn't support non-frameworks in binary downloads.

@maksymmalyhin could you please clarify this? Also, ideally if you could share an example GitHub repo that provides this, I would greatly appreciate that. Thanks!

**Comment by ikesyo** [comment]
As @jpsim said, Carthage is not for distributing command line tools.

**Comment by maksymmalyhin** [comment]
Excuse me, looks like you are right, currently Carthage does not support it.

@jpsim I've created an example repo https://github.com/maksymmalyhin/SwiftLintBinaryViaCarthage

I am going to create a ticket for Carthage to discuss if it is possible to add  support of binary dependencies other than frameworks.

**Comment by marcelofabri** [comment]
Closing this since it's not actionable.
