### ISSUE TITLE
Rule request: Unneeded parentheses in closure argument

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1483]
```swift
// good
let foo = { (bar: Int) in
    print(bar)
}

// bad
call(arg: { (bar2) in

})
```

We could use a regex (`\{\s*\([^:]+\)\s*in`) to do it and also check for `source.lang.swift.decl.var.parameter` without a `key.typename`.

Stole the idea and regex from @keith

**Comment by marcelofabri** [comment]
Maybe this should have an option to allow the parentheses when the return type is explicit and there are more than one parameter? e.g.

```swift
ruleList.list.flatMap { (identifier, rule) -> [(String, String)] in
   return rule.description.deprecatedAliases.map { ($0, identifier) }
}
```
```

**Comment by Dschee** [comment]
Emphasis on "and", I'd say. See my examples in my request (#1583) to see what I mean what I'd expect to be accepted.
