### ISSUE TITLE
Adding Xcode/Swift compiler warnings to output file

### ISSUE THREAD

**Issue by thorstenstark** [realm/SwiftLint#1487]
It would be nice to have also the complier warnings in the SwiftLint output file, especially for CIs like Jenkins and Travis.

**Comment by marcelofabri** [comment]
SwiftLint doesn't compile your app, so there's no way we could do this (and I think this is outside the scope anyways).

**Comment by SDGGiesbrecht** [comment]
I saw this question earlier and I figured it was outside the scope of SwiftLint too, but I wanted to wait for someone else to confirm it before I directed you elsewhere.

@thorstenstark, have a look at [Workspace](https://github.com/SDGGiesbrecht/Workspace). It hasn’t been stabilized for an “official” release yet, but it can already do what you are asking (depending on your project set‐up).

Specifically, for what you want, look at [configuring](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Configuring%20Workspace.md) [proofreading](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Proofreading.md) (which includes SwiftLint) and [compiler warnings](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Compiler%20Warnings.md). Workspace can even manage your [Travis configuration](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Continuous%20Integration.md) for you if you want.

**Comment by marcelofabri** [comment]
I'm closing this since there's no action to be taken here.
