### ISSUE TITLE
Configuring rules in the yml file

### ISSUE THREAD

**Issue by Tableau-David-Potter** [realm/SwiftLint#149]
Thanks for your changes to support configurable rules.  This is a good step forward for this feature.  What I'd really like to see is a way to configure rules in the yml file.  That way we wouldn't have to modify the source code to adjust things like line length.  Have you guys given any thought to how that might be implemented?

**Comment by jpsim** [comment]
This was done in #106 and improved upon in #144. Although we have yet to adequately document this in the README, those PRs should demonstrate how to use this functionality.

**Comment by Tableau-David-Potter** [comment]
D'oh!  Thanks.  Exactly what I was looking for.
