### ISSUE TITLE
Caching doesn't seem to be working (perhaps from unit test targets?)

### ISSUE THREAD

**Issue by samskiter** [realm/SwiftLint#1490]
As I understand, Swiftlint should now cache results and not run again on files if they haven't changed.

Unfortunately, we aren't seeing this in our project - whenever I build I still see Swiftlint output `Linting 'XXX.swift' (1232/1275)` for every file in the project. As far as I know we have the setup recommended in your README. We use portable Swiftlint to keep all devs on the same version and call that from our main target build phases and we are up to date with version 0.18.1 and using XCode 8.3.2.

**Comment by jpsim** [comment]
Caching was disabled in #1384 due to several issues, so it's expected that SwiftLint doesn't cache anything at the moment. I apologize for the inconvenience, and thank you for your patience as we work on re-enabling the cache.

**Comment by samskiter** [comment]
Ah ok. Thanks for the swift reply :)

**Comment by samskiter** [comment]
Hey again @jpsim - do you know what the timeline/priority for getting caching back up is? any workaround for now? (e.g. if none of the files have changed)

**Comment by jpsim** [comment]
There's no workaround needed to get SwiftLint working, it works fine today, it just doesn't have caching enabled, which is an optimization that shouldn't affect behavior other than performance.

You can either help fix issues with our caching implementation, build caching on top of SwiftLint (e.g. don't call SwiftLint on files that _you_ detect haven't changed since last lint), or wait for this to happen by SwiftLint contributors.

**Comment by samskiter** [comment]
@jpsim Sorry, what I meant is that even if none of my files change it still lints every file, I was wondering if there was a way to avoid a re-lint in this one case (rather than the 'full' caching solution).

I can certainly try and help out. Where should I start reading? Any bug number where this is all discussed?

**Comment by jpsim** [comment]
> I was wondering if there was a way to avoid a re-lint in this one case (rather than the 'full' caching solution).

This appears to be identical to the full caching solution.

**Comment by samskiter** [comment]
@jpsim Looks like there is a change our for review to fix some of these issues https://github.com/realm/SwiftLint/pull/1311
