### ISSUE TITLE
Extraneous `file.zip` in CocoaPods release

### ISSUE THREAD

**Issue by heshamsalman** [realm/SwiftLint#1507]
Looking through the source in the CocoaPods releases, there's an extraneous `file.zip` that takes up 4.4MB and contains _a duplicate copy of the SwiftLint framework and binary_.

**Comment by marcelofabri** [comment]
I think this is a side effect of https://github.com/realm/SwiftLint/blob/master/SwiftLint.podspec#L9. We could change the regex to not match `file.zip` and try it.

**Comment by jpsim** [comment]
Fixed in 536c24c39dd95bdb91286def32e51c5500243363.
