### ISSUE TITLE
False positive on `syntactic_sugar` rule

### ISSUE THREAD

**Issue by JohnEstropia** [realm/SwiftLint#1508]
I have a nested type named `<SomeClass>.Optional` and swiftlint thinks this is `Swift.Optional` so I am getting the following warning:
<img width="998" alt="screen shot 2017-05-12 at 18 42 27" src="https://cloud.githubusercontent.com/assets/3029684/25992849/d933156c-3742-11e7-9760-9dea2d8ab8a0.png">

**Comment by marcelofabri** [comment]
This shouldn't be too hard to fix: basically we should not trigger if there's a `.` before the type. We should  trigger on `Swift.Optional<Int>` though. Do you wanna take a look at it?
