### ISSUE TITLE
Use environment variables in .swiftlint.yml file

### ISSUE THREAD

**Issue by auryn31** [realm/SwiftLint#1512]
Is it possible to use global vars from project in the .swiftlint.yml file?
I want to create a template for all projects and have a subfolder in these, that I want to exclude like this:

```
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - $(PROJECT_NAME)/Extensions
```

is this possible? because this does not work :-( 
thanks for help

**Comment by bestlem** [comment]
In this case just use
    excluded: # paths to ignore during linting. Takes precedence over `included`.
      - Extensions

As paths are relative to the current directory

**Comment by auryn31** [comment]
But if i only exclude Extensions he does not exclude the Folder
Directory/Extension
so the problem does exists further :-(
