### ISSUE TITLE
0.18.1 does not compile with swift build

### ISSUE THREAD

**Issue by soutaro** [realm/SwiftLint#1528]
0.18.1 does not compile with `swift build`. It says:

```
/Users/soutaro/src/SwiftLint/Source/SwiftLintFramework/Rules/MissingDocsRule.swift:47:12: error: use of unresolved identifier 'parseDocumentationCommentBody'
        if parseDocumentationCommentBody(dictionary, syntaxMap: syntaxMap) != nil {
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SourceKittenFramework.File:5:17: note: did you mean 'getDocumentationCommentBody'?
    public func getDocumentationCommentBody(_ dictionary: [String : SourceKitRepresentable], syntaxMap: SourceKittenFramework.SyntaxMap) -> String?
                ^
```

This is because SourceKitten 0.17.3 removed `parseDocumentationCommentBody`, and specifying dependency as `..<Version(0,17,3)` in `Package.swift` solves.

* https://github.com/soutaro/SwiftLint/commit/6a456c01aaa7bcebcd9e5137285de457c021667d

I would like to propose releasing another version, maybe 0.18.2?, which compiles with `swift` command. What do you think?

**Comment by marcelofabri** [comment]
This rule was actually removed on `master`, so the next release will already fix it.

**Comment by soutaro** [comment]
Ok, I will use my patched version for a while and wait for next release.

Thanks.

**Comment by soutaro** [comment]
I found `swift package pin` helps.

```
$ swift package pin SourceKitten --version 0.17.2
```
