### ISSUE TITLE
Add configuration for line_length to ignore comments

### ISSUE THREAD

**Issue by amarcadet** [realm/SwiftLint#1541]
What do you think about that?

**Comment by marcelofabri** [comment]
Isn't this supported by https://github.com/realm/SwiftLint/pull/1264?

**Comment by amarcadet** [comment]
My bad, it should be documented in `swintlint rules`.

**Comment by marcelofabri** [comment]
It is actually documented there, but not with the exact keys: https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/RuleConfigurations/LineLengthConfiguration.swift#L35-L38

Feel free to send a PR 💯
