### ISSUE TITLE
Will I be able to download a version that supports swift 2.3 from Brew?

### ISSUE THREAD

**Issue by brennantaylor** [realm/SwiftLint#1544]
With swift 2 support removed in the upcoming release can I still download a version that supports swift 2.3 from Brew?

Would you be willing to upload a different package to keep 0.18.1 around for a while?

**Comment by marcelofabri** [comment]
Homebrew doesn't support pinning a version, so I'd recommend either installing with CocoaPods or directly from the binary: https://github.com/realm/SwiftLint/releases/tag/0.18.1

**Comment by brennantaylor** [comment]
Ok that should be doable and I can cache it in our CI to keep it fast. Thanks.
