### ISSUE TITLE
[Rule Request] Swift Radar Bug Status Checker

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#1547]
I've noticed that many codebases include the SR-xxx bug as a comment. 
https://github.com/realm/SwiftLint/search?utf8=%E2%9C%93&q=%22SR%22&type=
It would be really cool if the linter could check the status of the bug and give a warning when the bug is resolved.
Probably it would be better to check whenever the full Swift Radar is included in a comment.
`//https://bugs.swift.org/browse/SR-3449`
or 
`//https://bugs.swift.org/browse/SR-1234`
or
`//Workaround SR-1234`

This could be expanded to Apple Radar if Apple ever opens this up. This could also be a framework but I don't think people would use a framework for this.

**Comment by marcelofabri** [comment]
I don't this should be in SwiftLint since it'd make it slow and not predictable, since it'd need to make network calls 😬 

I can see this as a separate tool that could use `SwiftLintFramework` or `SourceKit` directly though.

**Comment by masters3d** [comment]
This would be optional so speed should not be an issue. It would be awesome to have a native plug in system https://github.com/realm/SwiftLint/pull/711 that could be like Custom Rules but perhaps they could be packages that could be imported. Perhaps all optional rules should work this way.

**Comment by marcelofabri** [comment]
I'm closing this because I think this is outside SwiftLint's scope. If/when we implement a plug-in system, this could be implemented using it, but until then I'd recommend making this another tool.

**Comment by masters3d** [comment]
Good call. This is not not needed with #warning() coming. https://github.com/apple/swift-evolution/blob/master/proposals/0196-diagnostic-directives.md
