### ISSUE TITLE
Declaration on multiple lines problem

### ISSUE THREAD

**Issue by jeremygrosjean** [realm/SwiftLint#1548]
Hello,
I have a warning because my method is too long (I know that I can up the number of lines that is allowed).
But my method is too long because of declaration like that : 
![screen shot 2017-05-23 at 10 06 39](https://cloud.githubusercontent.com/assets/26868457/26344336/9399524a-3f9f-11e7-90d0-410a0035d7e8.png)

Should not it count like one line ?

**Comment by marcelofabri** [comment]
> Should not it count like one line ?

I don't think so. Although it's just method call, it's still split in several lines.
