### ISSUE TITLE
function_parameter_count rule should not apply to overridden methods / protocol implementations

### ISSUE THREAD

**Issue by frenetisch-applaudierend** [realm/SwiftLint#1562]
When overriding a method, or implementing one from a protocol, I don't have any control over the number of parameters. Therefore I feel this rule should not report in those cases. Instead it should (and presumably does) report at the base class / protocol definition.

**Comment by marcelofabri** [comment]
Checking if it's an overridden method should be easy, but we can't check if a method is implemented from a protocol without major changes on how SwiftLint works (see https://github.com/realm/SwiftLint/issues/836#issuecomment-262671902).

**Comment by marcelofabri** [comment]
Do you want to try making a PR to check if it's an overridden method? 💯

**Comment by frenetisch-applaudierend** [comment]
Love to! I'll take a stab at it over the weekend 👍
