### ISSUE TITLE
Improve Linux performance

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#1577]
86% of the time spent linting the SwiftLint repo on Linux is in [CFStringFindCharacterFromSet](https://github.com/apple/swift-corelibs-foundation/blob/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-05-24-a/CoreFoundation/String.subproj/CFString.c#L4125).

![image](https://cloud.githubusercontent.com/assets/474794/26519923/c9796c52-427d-11e7-82a6-a63bca87f334.png)

Interactive version (open in a web browser): [flamegraph.svg.zip](https://github.com/realm/SwiftLint/files/1033421/flamegraph.svg.zip)

**Comment by norio-nomura** [comment]
We need to disable caching in `NSString` on Linux.
https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/String%2BSourceKitten.swift#L184

**Comment by jpsim** [comment]
Actually, _enabling_ caching on Linux has a great impact:

![image](https://cloud.githubusercontent.com/assets/474794/26520308/99de5622-4284-11e7-91a1-fd08e9630418.png)

[flamegraph.svg.zip](https://github.com/realm/SwiftLint/files/1033440/flamegraph.svg.zip)

Just a naive implementation:

```diff
diff --git a/Source/SourceKittenFramework/String+SourceKitten.swift b/Source/SourceKittenFramework/String+SourceKitten.swift
index c40cffe..14163a1 100644
--- a/Source/SourceKittenFramework/String+SourceKitten.swift
+++ b/Source/SourceKittenFramework/String+SourceKitten.swift
@@ -35,6 +35,10 @@ private let commentLinePrefixCharacterSet: CharacterSet = {
 private var keyCacheContainer = 0
 
 extension NSString {
+
+    static private var stringCache = [NSString: CacheContainer]()
+    static private var stringCacheLock = NSLock()
+
     /**
     CacheContainer caches:
 
@@ -181,7 +185,14 @@ extension NSString {
     */
     private var cacheContainer: CacheContainer {
         #if os(Linux)
-        return CacheContainer(self)
+        NSString.stringCacheLock.lock()
+        defer { NSString.stringCacheLock.unlock() }
+        if let cache = NSString.stringCache[self] {
+            return cache
+        }
+        let cache = CacheContainer(self)
+        NSString.stringCache[self] = cache
+        return cache
         #else
         if let cache = objc_getAssociatedObject(self, &keyCacheContainer) as? CacheContainer {
             return cache
```

**Comment by jpsim** [comment]
With the caching above, linting this repo takes 15.04s rather than the previous 3m23s.

**Comment by norio-nomura** [comment]
Yup,. The disadvantage of that implementation is that "`CacheContainer` and `String` are never freed".

**Comment by jpsim** [comment]
True, but we already make that trade off on macOS. Linting this repo in debug mode with a dictionary cache above takes the same amount of memory as with ObjC associated objects (46MB).

**Comment by norio-nomura** [comment]
Certainly `File` will persist until the end of the SwiftLint process, so neither` String` nor `CacheContainer` will be freed until the end. 🤔 
I don't know about another consumer of SourceKitten. Are memory leaks due to intentional circular references an issue for other SourceKittenFramework users?

**Comment by jpsim** [comment]
It probably is an issue, but not at the expense of performance.  I'd say we should implement the dictionary based caching approach for now and eventually move that to File.

**Comment by norio-nomura** [comment]
> I'd say we should implement the dictionary based caching approach for now and eventually move that to File.

I fully agree. 👍
