### ISSUE TITLE
Rule to enforce ordering of access modifies and override keyword

### ISSUE THREAD

**Issue by mgrebenets** [realm/SwiftLint#1585]
Feature request: add a rule that can enforce the ordering of access modifiers and `override` keyword.

E.g. the "override first" rule could be introduced, to ensure that `override` keyword is always put before access modifiers:

```swift
// Override first
override public internal(set) var property: Bool

// Access modifies first
public override var property: Bool
```

**Comment by marcelofabri** [comment]
Subset of #387

**Comment by masters3d** [comment]
This does seem to be the most popular arrangement. I did a draft rule https://github.com/realm/SwiftLint/pull/1501. I am wondering if we should make it so the default is 
`let beforeACL = ["override"]` 
If somebody wants to have another list they would have to add a list to their config file `["override", "final"]`

**Comment by masters3d** [comment]
I updated this [rule](https://github.com/realm/SwiftLint/pull/1501). It can be configured as so:
```
opt_in_rules:
  - modifiers_order

modifiers_order:
  before_acl: ["override"]
  after_acl: ["class"]

```

**Comment by SD10** [comment]
This would be an awesome addition 😃 The inconsistent ordering in my code-base is driving me crazy.

**Comment by jpsim** [comment]
Done in #1501.

**Comment by superarts** [comment]
> This does seem to be the most popular arrangement.
> I did a draft rule #1501. I am wondering if we should make it so the default is
> 
> ```swift
> let beforeACL = ["override"]
> ```
> 
> If somebody wants to have another list they would have to add a list to their config file like so:
> `["override", "final"]`

Any reference of this please? I search in https://github.com/apple/swift and found:

- less than 43 [override public](https://github.com/apple/swift/search?q=%22override+public%22&unscoped_q=%22override+public%22)
- 72+ [public override](https://github.com/apple/swift/search?q=%22public+override%22&unscoped_q=%22public+override%22)

**Comment by gobetti** [comment]
+1 to @superarts question - not really questioning the decision, for some reason I like `override` first but it's not Xcode's default so often this brings up team discussions.

I've just repeated the search suggested above and I got 24 `override public` vs. 75 `public override`
Also 3 `override open` vs. 27 `open override`
