### ISSUE TITLE
WARN: The rule 'SwiftLint:identifier_name' does not exist.

### ISSUE THREAD

**Issue by auryn31** [realm/SwiftLint#1588]
When I run the run-sonar-swift.sh script with custom swiftlint rules
tailor says, the following error:
WARN: The rule 'SwiftLint:identifier_name' does not exist.
how did I get the warnings into sonarqube? :-)
sorry if its a bad question.
Thanks for Help

**Comment by jpsim** [comment]
Looks like you CI machine is running an older version of SwiftLint. Can you please update it to 0.19.0? Thanks!

**Comment by auryn31** [comment]
Thanks
But I am at the version 0.19 with my CI and have the same error
I got the following error:

Done linting! Found 2881 violations, 46 serious in 176 files.
Running Tailor....................................Running Lizard....Running SonarQube using SonarQube RunnerWARN: SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
.WARN: The rule 'SwiftLint:identifier_name' does not exist.
WARN: The rule 'SwiftLint:identifier_name' does not exist.
WARN: The rule 'SwiftLint:curly_brackets' does not exist.

My SonarQube shows only 1.3k Warnings
Thanks for help

**Comment by marcelofabri** [comment]
This looks like an issue with SonarQube and/or your integration. If running `swiftlint lint` works, there's not much we can do.

**Comment by marcelofabri** [comment]
Closing this since there's nothing much to do on our side.
