### ISSUE TITLE
Suggestion - Add custom rules from file

### ISSUE THREAD

**Issue by diogoguimaraes** [realm/SwiftLint#159]
I was trying to introduce new rules (that only matter to me) and the only way I found possible was to fork the repo change the already existing structs.
Is there any plan on your roadmap to import custom rules from a file (JSON, XML, ..) ? 

Thanks for your great work :)

**Comment by jpsim** [comment]
We're tracking an issue to provide custom rules via regex matchers defined in the configuration file as #123, so I'll close this one as a duplicate. Very much something we'd love to have, but it hasn't been built yet.
