### ISSUE TITLE
Analyse only project source code files

### ISSUE THREAD

**Issue by vidhyasri2106** [realm/SwiftLint#1590]
Hi,
I integrated Swiftlint for my xcode project. When i run it, it is analysing all swift files even the ones inside frameworks that i installed using carthage. Is there a way to avoid this so that it analyses only the swift files created by the developer in the project leaving behind the frameworks installed using carthage?

**Comment by marcelofabri** [comment]
You should use the `excluded` key in your configuration file, as shown [in the README](https://github.com/realm/SwiftLint#configuration).
