### ISSUE TITLE
Can we generate report of warnings and errors using swiftlint

### ISSUE THREAD

**Issue by vidhyasri2106** [realm/SwiftLint#1595]
Is it possible to get the warnings and errors that we get using swiftlint using some API like number of warnings, errors etc.? We have a dashboard built, where we display all the Xcode generated errors, warnings etc. We are thinking of displaying all the warnings and errors that we get using swifitlint also in that dashboard. Is there any way to achieve this?

**Comment by marcelofabri** [comment]
You should use the `reporter` key in your configuration file or pass `--reporter` with the reporter that suits you the most (in this case, probably `json`), as shown in the [README](https://github.com/realm/SwiftLint#configuration).
