### ISSUE TITLE
Override Rules

### ISSUE THREAD

**Issue by auryn31** [realm/SwiftLint#1596]
Hey There,
is it possible to override rules without creating a custom rule?
For example I have another regex for curly brackets
if I want to use the standard rule with my custom regex, is this possible in any way?
Its not possible to exclude the rule and write this with the same name as custom
and its also not possible to write it only as custom rule
Thanks for Help

**Comment by marcelofabri** [comment]
I'm closing this because I don't think we should ever support expose a regex as configuration. If needed, each rule should expose its own configuration to change behavior.
