### ISSUE TITLE
Why the cocoapods last version is 0.16.1 when the last stable release in the repo is 0.19.0?

### ISSUE THREAD

**Issue by acecilia** [realm/SwiftLint#1607]
Thanks :)

**Comment by marcelofabri** [comment]
The latest version on CocoaPods [is updated](https://github.com/CocoaPods/Specs/blob/master/Specs/4/0/1/SwiftLint/0.19.0/SwiftLint.podspec.json). You probably just need to run `pod repo update`.

**Comment by acecilia** [comment]
My bad. Thanks @marcelofabri
