### ISSUE TITLE
Variable name violation should be ignored if the entire name is in capitals

### ISSUE THREAD

**Issue by yoavschwartz** [realm/SwiftLint#161]
A lot of times there are variable names where the name is an acronym, even in apple code such as RSSI from CoreBluetooth which stands for Relative Signal Strength Indication. of course you could call it relativeSignalStrengthIndication but it seems impractically long. I think people agree that when acronyms are used, the entire name is in capitals. 
I think writing the entire variable name in capitals is unlikely something done by mistake and usually has a meaning.

**Comment by jpsim** [comment]
Sure. This should be easy to do.
