### ISSUE TITLE
Add documentation in the README for #111

### ISSUE THREAD

**Issue by tom-sparo** [realm/SwiftLint#162]
The other day I was trying to disable a warning that I thought was not applicable to my use case (`id` name less than 3) but didn't see any documentation for a way to disable via comments in code.

But I browsed some of the closed pull requests/issues and found [#111](https://github.com/realm/SwiftLint/pull/111)!  I think documentation of this should be added to the README.

Happy to give a PR for it if it's not already in the works.

**Comment by keith** [comment]
It would be awesome if you could PR this! I've been meaning to do this for a while but haven't had a chance.
