### ISSUE TITLE
EmptyCountRule catches words that include "count"

### ISSUE THREAD

**Issue by bdrelling** [realm/SwiftLint#1622]
[EmptyCountRule.swift:34](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/EmptyCountRule.swift#L34)

`let pattern = "count\\s*(==|!=|<|<=|>|>=)\\s*0"`

This should change so that it doesn't match words that _end_ in `count`, only the word `count` itself.

ie. `discount == 0`

**Comment by marcelofabri** [comment]
Duplicate of #827

**Comment by marcelofabri** [comment]
Actually, not a duplicate.
