### ISSUE TITLE
Implicitly Unwrapped Optionals with some protocols

### ISSUE THREAD

**Issue by MetalheadSanya** [realm/SwiftLint#1628]
If we have Implicitly Unwrapped Optional property with more than one protocol swiftLint determinate this as force_unwrapping error

```
var router: (Module1RouterInput & Module2RouterInput)!
```

**Comment by marcelofabri** [comment]
What version of SwiftLint are you using? I couldn't reproduce it with 0.20.0.

**Comment by MetalheadSanya** [comment]
Sorry. In latest version doesn't respoduce
