### ISSUE TITLE
Rules documentation & usage

### ISSUE THREAD

**Issue by pak-amsiq** [realm/SwiftLint#1638]
Hello everyone! 

Can I find documentation & examples of all SwiftLint rules? 

I found 32/75 rules on this link: 
http://kevindelord.io/2016/04/06/integrate-swiftlint/ 

Thank you!

**Comment by pak-amsiq** [comment]
Thank you!

**Comment by marcelofabri** [comment]
This is something that we want to improve though: check #1107 and #1288 for some ideas. I'm closing this for now.
