### ISSUE TITLE
Weak Delegate should not trigger for `let`

### ISSUE THREAD

**Issue by Uncommon** [realm/SwiftLint#1639]
I have a particular property whose name happens to end in "delegate", but it's declared with `let` so it doesn't quite make sense to recommend making it weak. That seems like an easy enough case for the rule to recognize and skip.

(If that naming seems weird, it's because the object is used as a delegate for something else, not for the object that has this property)

**Comment by marcelofabri** [comment]
I'm not sure if this is valid, because this could be a case where the delegate is just immutable (it should be mutable and `weak` to avoid retain cycles).

**Comment by Uncommon** [comment]
I guess that's possible if the delegate were passed in through `init`, though the more normal practice is to have a settable property.

**Comment by marcelofabri** [comment]
> more normal practice is to have a settable property

I agree, but I wouldn't rely on that. Unfortunately, I don't have any other suggestions.

**Comment by Uncommon** [comment]
OK, I guess it's not as clear cut as I thought.
