### ISSUE TITLE
SwiftLint finished with errors (exit code: 2)

### ISSUE THREAD

**Issue by Thomas-Pelfrene** [realm/SwiftLint#1640]
Hi!
I looked for google but couldn't find any answer..
I’m trying to use Swiftlint with Fastlane, it seems to work but at the end I have an issue : 
« SwiftLint finished with errors (exit code: 2) » 
Swiftlint version -> 0.20.0

<img width="593" alt="result_error" src="https://user-images.githubusercontent.com/9356101/27445072-d9f63924-5778-11e7-9b54-f4a10d4c0a8e.png">

Do I do something wrong ?
Thanks in advance :)

**Comment by marcelofabri** [comment]
SwiftLint is returning an error code because there're violations in your code.

**Comment by Thomas-Pelfrene** [comment]
Thank you !

**Comment by marcelofabri** [comment]
I'm closing this issue, feel free to reopen or open a new issue if you have more questions!

**Comment by kalafun** [comment]
Where can I see the violations? I enabled a `warning_threshold` rule in my swiftlint file and it clearly breaks the build but I can't see the `warning_threshold` being referenced anywhere. I know which swiftlint rule is breaking the build, but none of my colleagues will.
