### ISSUE TITLE
Rule request: bring back missing_docs

### ISSUE THREAD

**Issue by jdmarshall90** [realm/SwiftLint#1652]
Any chance this could be revived?

**Comment by masters3d** [comment]
@marcelofabri What was the rational in removing missing docs?
https://github.com/realm/SwiftLint/pull/1455/files

**Comment by marcelofabri** [comment]
It didn't work with Swift 3. There was an issue with more history (I'm on my phone right now, otherwise I'd link it here)

**Comment by jpsim** [comment]
See #728 and [SR-2487](https://bugs.swift.org/browse/SR-2487) for details.

**Comment by marcelofabri** [comment]
There's also some discussion in https://github.com/apple/swift/pull/9868.

**Comment by marcelofabri** [comment]
Closed by mistake, sorry 😅

**Comment by acecilia** [comment]
Would be awesome to have this back. Is the fix from https://github.com/apple/swift/pull/11264 already in Swift4? (how can we know in which version a PR was included?) Thanks!

**Comment by marcelofabri** [comment]
@acecilia it's not. Luckily it'll be part of Swift 4.1 early next year.

**Comment by Nef10** [comment]
@marcelofabri any update on this as Swift 4.1 is release now? Do you have checked if it is possible again?

**Comment by marcelofabri** [comment]
It should be possible, feel free to send a PR 😊

**Comment by Nef10** [comment]
@marcelofabri see #2172

**Comment by marcelofabri** [comment]
Merged in #2318 🎉
