### ISSUE TITLE
Use multiple exit status codes

### ISSUE THREAD

**Issue by jakecraige** [realm/SwiftLint#166]
Currently SwiftLint exits with a 1 error code when it dies because something is invalid(path, config, etc) OR if there are serious violations. What do you think about exiting with a different code on failing because of violations vs. invalid params?

This would be useful when running SwiftLint within another script and making decisions based on the response. Currently I have no way to tell if it's failing because of violations or invalid data.

**Comment by kylef** [comment]
This will also be helpful for any vim syntastic plugin since you'd want to show swiftlint errors different to linting responses.

**Comment by jpsim** [comment]
Agreed! Perhaps errors should exit with code `2` and warnings (in strict mode) could return `3`?

**Comment by picaso** [comment]
Hi! Any timeframe on this enhancement? Thanks.

**Comment by marcelofabri** [comment]
Fixed in #584
