### ISSUE TITLE
Consider renaming rules_docs command

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#1660]
Underscores in POSIX commands aren't common. Maybe `generate-docs` or `rules-docs`?

For example, Carthage uses [`copy-frameworks`](https://github.com/Carthage/Carthage/blob/0.24.0/Source/carthage/CopyFrameworks.swift#L9) rather than `copy_frameworks` as a command.

**Comment by marcelofabri** [comment]
I'm okay with either options, especially since this shouldn't be used by users in general.

**Comment by jpsim** [comment]
How about just `docs`?

**Comment by marcelofabri** [comment]
I prefer the other options. Just `docs` can be misleading IMO

**Comment by jpsim** [comment]
Addressed in #1662
