### ISSUE TITLE
Documentation: Missing information about versions

### ISSUE THREAD

**Issue by eMdOS** [realm/SwiftLint#1663]
Would be good if having a list/table of `Swift` versions vs `SwiftLint` version. There is no clear info about what SwiftLint version I should install when using `x` version of `Swift`.

**Comment by jpsim** [comment]
Maybe we could add this table to the README?

| Swift version | Last supported SwiftLint release |
| ------------- | -------------------------------- |
| Swift 1.x     | SwiftLint 0.1.2                  |
| Swift 2.x     | SwiftLint 0.18.1                 |
| Swift 3.x     | SwiftLint 0.20.1 (latest)        |
| Swift 4.x     | SwiftLint 0.20.1 (latest)        |

**Comment by eMdOS** [comment]
Yep, it would be really useful.

Thanks for clarifying.

**Comment by jpsim** [comment]
See 629b053
