### ISSUE TITLE
Swiftlint not working in AppCode

### ISSUE THREAD

**Issue by ohadnav** [realm/SwiftLint#1666]
I get the following error:

> Can't find swiftlint utility here:
> /usr/local/bin/swiftlint
> Please check the path in settings.

**Comment by jpsim** [comment]
Looks like you're telling AppCode to find SwiftLint in a place where it isn't. Why is this a SwiftLint issue?

**Comment by ornithocoder** [comment]
@ohadnav is `/usr/local/bin/swiftlint` the path to the swiftlint binary or to the directory where the binary is? Try `/usr/local/bin/` instead.

**Comment by ohadnav** [comment]
how can I alter the path to a plugin in AppCode? :O

**Comment by ornithocoder** [comment]
@ohadnav that's a good question :-) I stopped using AppCode a month ago, when my license expired and I didn't renew. I was just assuming it was looking on the wrong path and that the path was somehow configurable.

Can you try this on the terminal?

```
which swiftlint
```

It will show where your swiftlint is installed.

**Comment by jpsim** [comment]
SwiftLint doesn't provide an AppCode plugin. Are you perhaps using this plugin?
 https://plugins.jetbrains.com/plugin/9175-swiftlint

If so, perhaps you could file an issue on its GitHub repo? https://github.com/bealex/SwiftLintAppCode

**Comment by marcelofabri** [comment]
Closing this since it looks like there's nothing we can do here.
