### ISSUE TITLE
Run autocorrect on oss-check

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1680]
This would be useful to check performance of `swiftlint autocorrect` (e.g. for #1679).

**Comment by jpsim** [comment]
We could also have Swift build commands to confirm that if the build succeeded before correcting, that it still succeeds after correcting.

**Comment by marcelofabri** [comment]
This would be really awesome, but maybe it could be hard because we'd have to deal with each project configuration.

**Comment by jpsim** [comment]
Definitely doesn't need to be done for all of them to provide value.

**Comment by marcelofabri** [comment]
You could even leverage https://github.com/apple/swift-source-compat-suite 🤔
