### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by mrchenhao** [realm/SwiftLint#169]
I use the pkg 0.2.0
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Library/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
  Reason: image not found
[2]    57620 trace trap  swxftlint

Xcode Version 7.1 on /Applications/Xcode.app

if i use brew  i will failed at

*\* INSTALL FAILED **

The following build commands failed:
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    CompileSwift normal x86_64 /tmp/swiftlint20151026-57687-4g3k1r/Carthage/Checkouts/SwiftXPC/SwiftXPC/XPCType.swift
(2 failures)
make: **\* [installables] Error 65

**Comment by otusweb** [comment]
Same issue with Xcode 7.1, OS X 10.11

**Comment by zippy1978** [comment]
Same here with Xcode 7.0.1

**Comment by nvzqz** [comment]
Same as @otusweb

**Comment by mrchenhao** [comment]
I have installed the swiftlint successfully 

step1:install carthage by pkg
step2: install swiftlint by brew

**Comment by jpsim** [comment]
@mrchenhao @otusweb @zippy1978 @nvzqz installing SwiftLint with `brew install swiftlint` requires Xcode 7.0.1 (for now) installed under `/Applications/Xcode.app`.

If following those exact steps causes issues for you, please post steps that I can follow that would reproduce the issue you're seeing so I can help.

**Comment by ivanbruel** [comment]
Having the same issue when installing swiftlint by .pkg.
Seems to be working as a brew but I want to exclude a folder and therefor I would prefer to use v0.3 instead.
My Xcode is installed in `/Applications/Xcode.app`

**Comment by jpsim** [comment]
The pkg install is incompatible with the homebrew install. You'll have to uninstall one to install the other properly.

**Comment by ivanbruel** [comment]
I had uninstalled the brew version even before installing the .pkg one.

**Comment by jpsim** [comment]
`brew uninstall swiftlint`, and if you've ever installed SourceKitten directly as well: `brew uninstall sourcekitten`.

**Comment by hugocore** [comment]
+1 same error here. @ivanbruel command fixed the problem!!

**Comment by NilStack** [comment]
+1 @ivanbruel 's solution works. Thanks!

**Comment by Igor-Palaguta** [comment]
+1 for @ivanbruel fix. Thanks!

**Comment by AaronBratcher** [comment]
I just installed the latest .pkg version and get an error when trying to use it in my run script.
Library not loaded: @rpath/libclang.dylib
Using Xcode 7.1.1 under /Applications/Xcode.app

So should I be using the .pkg or the brew to get this installed properly?

**Comment by allen-zeng** [comment]
I installed using pkg 0.5.2 and still got that error. Tried @ivanbruel's command and received an error saying it already has a `LC_RPATH`, but it points to Xcode at `/Applications/Xcode.app`, so I ended up creating a symlink there pointing to `~/Applications/Xcode.app` and everything worked.

I'm not sure whether the existence of `LC_RPATH` was because I installed swiftlint via homebrew first.

**Comment by norio-nomura** [comment]
@allen-zeng `LC_RPATH` does not support `~` expansion as I tested.
#244 depends on hardcoded `/Applications/Xcode.app` and the path of `Xcode.app` that building by user such as `Xcode-beta.app`.
If you want to use `~/Applications/Xcode.app` without `/Applications/Xcode.app`,  it needs `make install` by your self or `sudo install_name_tool -add_rpath ~/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /Library/Frameworks/SwiftLintFramework.framework/SwiftLintFramework` (the `~` will be expanded by shell without `"`)

**Comment by allen-zeng** [comment]
It probably doesn't, but `ln -s` does :)

I created a symlink to it so `/Applications/Xcode.app` will resolve.

**Comment by norio-nomura** [comment]
Yes, symlink works on `LC_RPATH`.

**Comment by norio-nomura** [comment]
Existing `Xcode.app` at non-standard path can't be resolved on Homebrew's bottling process.
That should be resolved on `swiftlint.rb` formula of Homebrew.

**Comment by norio-nomura** [comment]
> Existing Xcode.app at non-standard path can't be resolved on Homebrew's bottling process.
That should be resolved on swiftlint.rb formula of Homebrew.

I can't find methods for doing that on Homebrew's bottle install process. :disappointed: 
But found that would be resolved also by following:
```
brew install swiftlint --build-from-source
```

**Comment by jpsim** [comment]
Since there have been no reports of this for over a year, I think this can be closed.
