### ISSUE TITLE
How to write custom rules to check if super is written in viewDidLoad

### ISSUE THREAD

**Issue by Rahul15963214** [realm/SwiftLint#1696]

**Comment by marcelofabri** [comment]
Do you mean if `super.viewDidLoad()` is called?

**Comment by Rahul15963214** [comment]
Yes

**Comment by marcelofabri** [comment]
Check [`overridden_super_call`] (https://github.com/realm/SwiftLint/blob/master/Rules.md#overridden-methods-call-super) rule. It already has this validation.
