### ISSUE TITLE
Move examples to separated files

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1704]
Maybe we should move nonTriggering/triggering/corrections examples to their own files:

**Pros**:
* It'd be easier to make sure they are correctly formatted. Today, since they are `String`s in Swift, it's hard to properly format them. With multiline literals in Swift 4, this will get better, but probably it won't be good enough. This is important for documentation.
* We could run `sourcekitten` and see if the file is parsed correctly (i.e. is valid Swift code).
* We'd avoid cluttering source code with data.

**Cons**:
* It may be more work to maintain.
* It might not be obvious for new contributors.
* How would we deal with custom configurations?
* How would we deal with corrections?
* Would this make tests slower? If so, how much?
* How would we deal with `swiftlint rules a_rule_identifier`? We can't bundle resources with SPM.

**Comment by jpsim** [comment]
I don't think there's significant value in the Pro's section to warrant doing this. 🤷‍♂️

**Comment by marcelofabri** [comment]
I think we definitely should adopt multiline strings first and see how it turns out. Having the examples poorly formatted is pretty bad IMO.

**Comment by jpsim** [comment]
Yeah, but isn't the whole solution there to just visually inspect the (lovely) [Rules.md](https://github.com/realm/SwiftLint/blob/master/Rules.md) file now?

**Comment by marcelofabri** [comment]
I'm not sure I follow, but the issue is that we use those examples to generate the Rules.md file, so some snippets there have really weird formatting.

**Comment by jpsim** [comment]
Sorry, I wasn't clear. I mean that since the examples _do exist_ in a format where we can visually confirm that they're properly formatted (i.e. the `Rules.md` file), that this should be enough to identify which samples are incorrectly formatted and adjust them?

**Comment by marcelofabri** [comment]
Yes, hopefully we can fix that in the near future 🙏

**Comment by jpsim** [comment]
Addressed in #3016.
