### ISSUE TITLE
Compiling from source: no such module 'SourceKittenFramework'

### ISSUE THREAD

**Issue by Coeur** [realm/SwiftLint#1715]
Based on current Master, I followed the instructions from readme
>git submodule update --init --recursive; make install

But I got:
> /Users/coeur/Documents/Today 2017 07/Project 0.21/Pods/SwiftLint/Source/SwiftLintFramework/Rules/LegacyCGGeometryFunctionsRule.swift:10:8: error: no such module 'SourceKittenFramework'
import SourceKittenFramework
       ^

>** INSTALL FAILED **

>The following build commands failed:
	CompileSwift normal x86_64 /Users/coeur/Documents/Today 2017 07/Project 0.21/Pods/SwiftLint/Source/SwiftLintFramework/Rules/LegacyCGGeometryFunctionsRule.swift
	CompileSwift normal x86_64 /Users/coeur/Documents/Today 2017 07/Project 0.21/Pods/SwiftLint/Source/SwiftLintFramework/Extensions/SyntaxMap+SwiftLint.swift
	CompileSwift normal x86_64 /Users/coeur/Documents/Today 2017 07/Project 0.21/Pods/SwiftLint/Source/SwiftLintFramework/Rules/ExtensionAccessModifierRule.swift
	CompileSwift normal x86_64 /Users/coeur/Documents/Today 2017 07/Project 0.21/Pods/SwiftLint/Source/SwiftLintFramework/Rules/TrailingNewlineRule.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)
make: *** [installables] Error 65

I have:
>$ xcodebuild -version
Xcode 8.3.3
Build version 8E3004b

And:
>$ sourcekitten version
0.18.0

**Comment by marcelofabri** [comment]
Why are you running it inside `Pods`? How have you downloaded the project, with CocoaPods or cloning it?

**Comment by Coeur** [comment]
If I do `pod 'SwiftLint', '~> 0.20'`, I get a pre built `swiftlint` without issue.
But if I do `pod 'SwiftLint', :git => 'https://github.com/realm/SwiftLint'` to get the latest from master, then apparently the `Pods\SwiftLint` folder only has source file and requires manual compilation.

**Comment by marcelofabri** [comment]
That's not really supported, because the Podspec was created to work with a pre-built binary (see https://github.com/realm/SwiftLint/pull/936#issuecomment-265348307).

If you want to build from source, please clone the repo separately. Feel free to reopen if you have more questions 💯
