### ISSUE TITLE
Generate Rules.md automatically

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1734]
It would be great if we could automate the generation of `Rules.md` even more, so we wouldn't even need to run its scheme. Maybe somehow running it together with unit tests?

Another option would be generating whenever something is merged in master.

**Comment by jpsim** [comment]
Running it as part of the unit tests sounds good. It's what we do for SourceKitten's library wrappers: https://github.com/jpsim/SourceKitten/blob/0.18.0/Tests/SourceKittenFrameworkTests/SourceKitTests.swift#L163-L182
