### ISSUE TITLE
Executable does not run on CircleCI

### ISSUE THREAD

**Issue by jschmid** [realm/SwiftLint#174]
This is most likely related to an issue in SwiftGen: AliSoftware/SwiftGen#35

The machines on CircleCI have Xcode installed at a path different than the regular one.

When running, the executable does not find some libs an fails. You can see an output [here](https://circleci.com/gh/jschmid/test-swiftgen-circleci/14). I don't know exactly what did @AliSoftware to fix it, but I guess the same fix will apply here.

**Comment by AliSoftware** [comment]
What I did to fix it is that I simply copied the Swift runtime dylibs alongside my binary, using `xcrun install-stdlib-tool`, then removed Xcode.app from my executable `@rpath` and add the relative path to the Swift runtime dylibs I copied as `@rpath` instead.

See https://github.com/AliSoftware/SwiftGen/blob/master/Rakefile#L97-L101 + https://github.com/AliSoftware/SwiftGen/blob/master/Rakefile#L85

**Comment by jpsim** [comment]
Looks like the CircleCI VMs don't have write permissions in `/usr/local/bin`, so use `brew install --prefix {writeable location}`
