### ISSUE TITLE
SonarQube integration

### ISSUE THREAD

**Issue by zippy1978** [realm/SwiftLint#175]
Hi,

I'm currently working on a open source SonarQube Swift plugin using SwiftLint.
However I need to match a violation with it matching rule and I cannot do it because:
 - *swiftlint rules* command does not output rule ids.
 - *swiftlint lint* command only prints violations without any reference to the related rule.

I was thinking about adding a rule:Rule property (or at least the rule identifier) to StyleViolation.

Is it the right way to do ? 
Is there any other way ?

**Comment by rompic** [comment]
no idea, but +1

**Comment by zippy1978** [comment]
Hi,

I issued a PR to do it : https://github.com/realm/SwiftLint/pull/176.

I Hope it will be  accepted !

**Comment by rompic** [comment]
looking forward to https://github.com/Backelite/sonar-swift

**Comment by zippy1978** [comment]
Yes :)
I still need to do some work on it, but I should issue a 0.1 release in the weeks to come

**Comment by jpsim** [comment]
@zippy1978 looks great! let me know if there's anything I can do, and please keep us posted on this ticket when you make a release!

**Comment by rompic** [comment]
+1

**Comment by zippy1978** [comment]
Hi, 

I just released a first version of the Swift SonarQube plugin here : https://github.com/Backelite/sonar-swift

**Comment by jpsim** [comment]
Cool! I'll be closing this issue then. Feel free to file new issues if you need anything else on the SwiftLint side!
