### ISSUE TITLE
private_over_fileprivate should flag fileprivate declarations that are not used outside their context

### ISSUE THREAD

**Issue by FXLV4PGE** [realm/SwiftLint#1771]
SwiftLint v0.21.0:

@objc fileprivate isn't flagged in preference for private.

<img width="548" alt="sample" src="https://user-images.githubusercontent.com/26314830/29326435-506f056c-81a0-11e7-831e-1d655118be6d.png">

**Comment by marcelofabri** [comment]
Can you give a full triggering example? Which rule are you referring to? `private_over_fileprivate`?

**Comment by FXLV4PGE** [comment]
Attached is a png of a sample.

The code was originally having BOTH @objc fileprivate functions.
I changed one to ‘@objc private’ which SwiftLint didn’t notice.

Either ‘private’ or ‘fileprivate’ is correct.
But SwiftLint doesn’t make the distinction for @objc calls.

Ric.

**Comment by marcelofabri** [comment]
GitHub doesn’t show attachments from emails apparently. Please upload through the web interface or use a code snippet.

**Comment by FXLV4PGE** [comment]
I've uploaded a screen snippet showing two (2) @objc calls: private & fileprivate.   SwiftLink doesn't distinguish the two.   For SwiftLink, both are okay.   Here's the image again:

<img width="548" alt="sample" src="https://user-images.githubusercontent.com/26314830/29326492-932fbeb4-81a0-11e7-990a-b3befb0efe60.png">

**Comment by marcelofabri** [comment]
That's expected, because SwiftLint currently doesn't know if `didTapCurrentLocationButton` is used outside of the scope of its declaration.
