### ISSUE TITLE
unused_enumerated bug

### ISSUE THREAD

**Issue by PavleFromToptal** [realm/SwiftLint#1787]
`for (section, (event, _)) in data.enumerated()`

Data is an array of tuples, and this line of code reports that the item is not used, even though "event" is being used.

**Comment by marcelofabri** [comment]
Please provide a complete snippet.

**Comment by PavleFromToptal** [comment]
```
let data:[(String, String) = []
for (section, (event, _)) in data.enumerated() { }
```
