### ISSUE TITLE
Lines with only whitespace throw the trailing whitespace warning.

### ISSUE THREAD

**Issue by RussVanBert** [realm/SwiftLint#18]
Is that intentional? 

Xcode seems to put them in. I have a fix if it isn't:
https://github.com/RussVanBert/SwiftLint/commit/5f02cdfc93840d979d5fb4ad65f20d7cfc90e30d

**Comment by RussVanBert** [comment]
Oh, I see it's explicitly discouraged. Maybe it needs a rule of its own.

"Don’t leave trailing whitespace.
Not even leading indentation on blank lines."

**Comment by PorterHoskins** [comment]
Is there a way to get Xcode to play nice with this?

**Comment by segiddins** [comment]
Settings -> Text Editing -> While editing

**Comment by jpsim** [comment]
This is intentional.

**Comment by flexaddicted** [comment]
Hello guys! I have the above issue. It seems that Xcode (the option that @segiddins suggested) does not work.

![sample](https://cloud.githubusercontent.com/assets/1482350/19357738/2e6c226a-9173-11e6-8ec9-0376f85ebc0b.png)

Every time I create a new line, I need to remove the white spaces contained within the red box. Any clue?

**Comment by RussVanBert** [comment]
@flexaddicted The `Including whitespace-only lines` preference works (in Xcode 8.0) for new lines. Whitespace in existing lines will need to be manually deleted.

**Comment by scottrhoyt** [comment]
You should be able to quickly do the manual part with `swiftlint autocorrect`.

**Comment by flexaddicted** [comment]
@RussVanBert @scottrhoyt Thanks for the reply. This is my configuration but it does not work. Trailing spaces are added automatically. I have Xcode 8. Am I missing something?

![sample](https://cloud.githubusercontent.com/assets/1482350/19378705/6dd3e3cc-91ee-11e6-9792-be1c6274ff5a.png)

**Comment by flexaddicted** [comment]
@scottrhoyt @RussVanBert Thanks for the reply. I also found additional info here [Trim trailing spaces in Xcode](http://stackoverflow.com/questions/1390329/trim-trailing-spaces-in-xcode)

**Comment by RussVanBert** [comment]
That's an annoying bug. It's only for the line you're currently editing. I guess you'll need to move the cursor away from newly created lines before you navigate away from the file or save. I've logged [a bug with Apple](https://bugreport.apple.com). You should too. I'm sure they will get marked as a dupe, but someone will look at it. It has been there a long time.

Steps to Reproduce:
1. Open any Xcode project or create a new one.
2. Verify the two Text Editing preferences are selected. "Automatically trim trailing whitespace" and "Including whitespace-only lines". 
3. Choose a .swift, .h or .m file.
4. Hit the 'return' key one or more times (but don't move the cursor) to add empty lines.
5. Take note of which line the cursor is on.
6. Use the project navigator to navigate away from the file (this will cause the edited file to save).
7. Navigate back to the file you edited.
8. The line where the cursor was will contain whitespace.

**Comment by flexaddicted** [comment]
@RussVanBert Thanks for confirming this 👍

**Comment by nicolas-miari** [comment]
I have a "Run Script" build phase after compiling, as recommended. 

Perhaps I should add another Run Script phase _before_ compiling, with `swiftlint autocorrect`. What do you guys think about this idea?

**Comment by geoffreywiseman** [comment]
I have to admit, I wish this were two different rules so I could disable the whitespace-only variant, particularly if the whitespace is inline with the rest of the text indentation. I kinda like being able to arrow-down through my code and have the cursor stay with the code indent level, but I definitely don't want random whitespace at the end of the line.

**Comment by RussVanBert** [comment]
I created a separate rule way back in May 2015 (with tests). You'd need the three commits. https://github.com/RussVanBert/SwiftLint/commits/master

**Comment by Vyazovoy** [comment]
I think it should be separated to two different rules: trailing whitespaces and empty line indentation whitespaces. Maybe last one should be opt out. Xcode ability to indent imply lines is a perfect ability and many developers relay on it. There is should be ability to use it with swiftlint.

**Comment by jpsim** [comment]
@geoffreywiseman @Vyazovoy you can do what you're asking by configuring the `trailing_whitespace` rule to ignore whitespace-only lines (`ignores_empty_lines`) or ignore comments (`ignores_comments`). See https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/RuleConfigurations/TrailingWhitespaceConfiguration.swift

**Comment by Vyazovoy** [comment]
Thank you, @jpsim ! I've already found this customization. Really useful.

**Comment by richimf** [comment]
Is it possible to highlight the spaces (blank) with some color?

**Comment by geoffreywiseman** [comment]
@richimf Swiftlint lints text files which ... don't really contain color information, so your question is puzzling me. Ae you asking on a SwiftLint bug for Xcode configuration tips?

**Comment by richimf** [comment]
@geoffreywiseman I mean with the native Xcode preferences. Because I always left blank spaces when coding. :/
