### ISSUE TITLE
Need to disable autocorrect but still warn

### ISSUE THREAD

**Issue by robertocordon** [realm/SwiftLint#1813]
Currently, the rule `unused_closure_parameter` (and possibly others) will autocorrect any violation. This is sometimes not desired, and a warning is preferred. This is especially the case during development, where SwiftLint runs automatically from Xcode and deletes a variable that is still not being used, but will be. If the rule is disabled, then there may be cases where this error is left there. 
A mechanism for disabling auto correct and enabling a warning instead, for a specific rule, would be great.

**Comment by marcelofabri** [comment]
As described in #1667, you can use different configurations for this.
