### ISSUE TITLE
Exclusion paths are not evaluated when using script input files

### ISSUE THREAD

**Issue by Johennes** [realm/SwiftLint#1823]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

Consider the following example

```bash
$ ls -hal
total 24
drwxr-xr-x   5 jmarbach  SKYDIVE\Domain Users   170B Sep  7 09:49 .
drwxr-xr-x  40 jmarbach  SKYDIVE\Domain Users   1.3K Sep  7 09:43 ..
-rw-r--r--@  1 jmarbach  SKYDIVE\Domain Users    51B Sep  7 09:46 .swiftlint.yml
-rw-r--r--@  1 jmarbach  SKYDIVE\Domain Users    15B Sep  7 09:44 File.swift
-rwxr-xr-x@  1 jmarbach  SKYDIVE\Domain Users   118B Sep  7 09:47 lint.sh
```

```bash
$ cat .swiftlint.yml 
whitelist_rules:
  - colon
excluded:
  - File.swift
```

```bash
$ cat File.swift 
let a : Int = 0
```

```bash
$ cat lint.sh 
#!/bin/bash
export SCRIPT_INPUT_FILE_COUNT=1
export SCRIPT_INPUT_FILE_0=File.swift
swiftlint --use-script-input-files
```

When running swiftlint in the folder, `File.swift` is excluded.

```bash
$ swiftlint lint
Loading configuration from '.swiftlint.yml'
Linting Swift files in current working directory
No lintable files found at path ''
```

However, when running `lint.sh` which triggers swiftlint with `File.swift` as a script input file, the file is *not* excluded.

```bash
./lint.sh 
Loading configuration from '.swiftlint.yml'
Linting 'File.swift' (1/1)
/Users/jmarbach/ios/test/File.swift:1:5: warning: Colon Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
Done linting! Found 1 violation, 0 serious in 1 file.
```

This is problematic when swiftlint is run on staged files as part of a git commit hook.

### Environment

* SwiftLint version: 0.22.0
* Installation method used: Homebrew

**Comment by jpsim** [comment]
Could you please explain how this request is distinct from #591? If what you're requesting is covered in #591, let's close this one as a duplicate.

**Comment by Johennes** [comment]
@jpsim Yepp, that's a dupe. Sorry, I don't know why that didn't show up in my issue search earlier.

**Comment by jpsim** [comment]
No problem.
