### ISSUE TITLE
Rule Request: Update function_body_length to account for nested functions

### ISSUE THREAD

**Issue by pranjalsatija** [realm/SwiftLint#1826]
### Rule Request
In its current state, the `function_body_length` rule does not account for nested functions, which, in my opinion, downplays the usefulness of them.

Would it make sense to update `function_body_length` to be aware of nested functions? What I mean by this is that the `function_body_length` rule shouldn't count the implementations of nested functions when measuring the length of a function's body.

I'm aware that this was mentioned before in issue #385 but that issue is now old and I haven't seen any activity on it so I thought it may be beneficial to mention this again.

**Comment by marcelofabri** [comment]
As you've said, this is already tracked, so I'm closing it as a duplicate. Feel free to share your thoughts on the original issue or (even better) submit a PR.
