### ISSUE TITLE
for_where, false positive for optional binding

### ISSUE THREAD

**Issue by jaylindelycke** [realm/SwiftLint#1838]
This for in loop with optional binding violates the rule "for_where":
for node in json {
    if var data = node.value as? [String: String] {
        //do stuff with data
    }
}

But the rules preferred code doesn't compile:
for node in json where var data = node.value as? [String: String] {
    //do stuff with data
}
Maybe I don't know how to write the correct code.
Or the rule is throwing a false positive.

### Environment
SwiftLint 0.22.0 over CocoaPods
and Swift3 in Xcode 8.3.3

**Comment by marcelofabri** [comment]
Are you sure this example triggers? I wasn't able to reproduce it. 

Also, if you check [the examples](https://github.com/realm/SwiftLint/blob/master/Rules.md#examples-30) you can see that it shouldn't trigger indeed.

**Comment by jaylindelycke** [comment]
You are right, this example actually doesn't trigger. I was trying to explain the false positive with an standard "if let" optional binding. Sorry about that.
My real code is an "if var" and that does trigger a false positive.

**Comment by marcelofabri** [comment]
Thanks for the update, @jaylindelycke! I've submitted https://github.com/realm/SwiftLint/pull/1840 to fix the issue.
