### ISSUE TITLE
Skip warnings in strict mode

### ISSUE THREAD

**Issue by Sega-Zero** [realm/SwiftLint#1851]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Enhancement Request

I need todo warnings to be ignored when running in strict mode, is there a way to have a warning in a normal mode and no error in strict mode except having another yml config?

**Comment by marcelofabri** [comment]
This is a perfect use case for having two configuration files IMO.

**Comment by marcelofabri** [comment]
Feel free to reopen if you have more questions!
