### ISSUE TITLE
Always report any issue as non-error

### ISSUE THREAD

**Issue by weyert** [realm/SwiftLint#1899]
I am trying to clean up my code base but I don't want to stop the project from compiling but just give me notes that the code is a bit so I can step-by-step can fix it. Show would be possible to report any error's to be warnings? 

I am unable to find it to set the default severity for any rule. Looks like I would need to least every rule and say it should be a warning, is this correct?

**Comment by marcelofabri** [comment]
You can use `swiftlint lint --lenient`

**Comment by weyert** [comment]
Great, thank you!

**Comment by marcelofabri** [comment]
Feel free to reopen if you have more questions!
