### ISSUE TITLE
Add "allowed" configuration to NoExtensionAccessModifierRule

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#1900]
NoExtensionAccessModifierRule Rule currently bans all modifiers. 
It would be great to have the option to allow certain modifiers like `private` or `internal` but still not allow `public` modifiers for example. 

This can also help enforce only `private extension` or `fileprivate extension` since these are effectively the same. A code base should choose one or the other but not use both. 

Inspired from this  evolution thread.
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171002/040086.html

**Comment by Igor-Palaguta** [comment]
Agree, `public extension` can be dangerous, and good to have way to disallow just it
