### ISSUE TITLE
Static variables treated as local variables by `variable_name`

### ISSUE THREAD

**Issue by zwaldowski** [realm/SwiftLint#192]
In Swift 2.1, it seems like SwiftLint is not following the exception stated [here](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/VariableNameRule.swift).

The following code:

```swift
struct NetworkProviderNotifications {
    static let ReachabilityChanged = "ReachabilityChanged"
}
```

Gets the following:

```
Name Format Violation: Variable name should start with a lowercase character: 'ReachabilityChanged' (variable_name)
```

**Comment by jpsim** [comment]
Are you sure you're running from SwiftLint's `master` branch? That rule behavior was added in #110, which landed after the last official release of SwiftLint.

**Comment by zwaldowski** [comment]
Whoops. Sorry. :heart:

**Comment by jpsim** [comment]
No worries
