### ISSUE TITLE
Making .gitignore matter to SwiftLint

### ISSUE THREAD

**Issue by pbrewczynski** [realm/SwiftLint#1953]
Doesn't it make a sense to ignore stuff that defined in .gitignore automatically as if the user created .gitignore, he is saying "I don't care about those files in source control" and my reasoning is why would he care about them in terms of Swift lint rules? 

I'm not sure how should it be implemented, but I think .gitignore should matter to SwiftLint in the default setup.

**Comment by marcelofabri** [comment]
I don't think a linter should know anything about which versioning system is being used.

Besides that, linting an ignored file might be useful. One example would be code generated by tools like SwiftGen or Sourcery.
