### ISSUE TITLE
--config not working when used with swiftlint from cocoapod

### ISSUE THREAD

**Issue by gkmrakesh** [realm/SwiftLint#1955]
### Environment

Version : 0.15.0
Installation type: cocoapod 
Script:
#!/bin/bash

set -e

swiftlint="$SRCROOT/Pods/SwiftLint/swiftlint"

if [ -f "$swiftlint" ]; then
  "$swiftlint" --config $SRCROOT/Configurations/.swiftlint.yml
else
  echo 'warning: Cannot find SwiftLint in the expected location. If you are developing ReSwift please install it via `pod install`. If you are building ReSwift as a dependency of your project feel free to ignore this.'
fi

### Xcode error:
Unrecognized command: '--config'. See `/Users/rmembaram/Desktop/MERCIMDP/merci-mdp-ios/MeRCIapp/Pods/SwiftLint/swiftlint help`.
Command /bin/sh failed with exit code 1

**Comment by ornithocoder** [comment]
Hi @gkmrakesh did you try it with the latest SwiftLint version? I have 0.24.0 here and it worked for me when I changed the build phase to pick the configuration from another place.
 
<img width="1068" alt="screen shot 2017-11-24 at 9 49 36 am" src="https://user-images.githubusercontent.com/19753339/33202463-ee4d220e-d0fc-11e7-9485-1e9bbe2d928d.png">

**Comment by gkmrakesh** [comment]
Hello ornithocoder,

Thank you so much. it is working with the newer version.


Rakesh.
