### ISSUE TITLE
how to refer swiftlint latest version from podfile using :git or :http

### ISSUE THREAD

**Issue by gkmrakesh** [realm/SwiftLint#1956]
#### Installation method:
CocoaPods

#### Description:
My pod spec repo is old, so I am trying to refer latest swiftlint like below from my podfile

pod 'SwiftLint', :http => 'https://github.com/realm/SwiftLint/releases/download/0.24.0/portable_swiftlint.zip'

#### Issue:
Pre-downloading: `SwiftLint` from `https://github.com/realm/SwiftLint/releases/download/0.24.0/portable_swiftlint.zip`
[!] Unable to find a specification for 'SwiftLint'.

**Comment by ornithocoder** [comment]
You can ignore the pod version on the Podfile by not adding one. For SwiftLint the entry on the Podfile would be:

```ruby
pod 'SwiftLint'
```

Then run `pod update SwiftLint` to update SwiftLint. You can find more about upgrading pods [here](https://guides.cocoapods.org/using/pod-install-vs-update.html)

**Comment by gkmrakesh** [comment]
thanks for the reply,

i have to fix version because i want all my team to work on one version.

also, i want to point to specific URL so that even if spec repo is old in some developer machine they can work without any problem.

**Comment by ornithocoder** [comment]
So you can specify the version.

```
pod 'SwiftLint', '0.24.0'
```

Then `pod update SwiftLint`.

**Comment by gkmrakesh** [comment]
Is there anyway i can specify URL

For example: pod 'SwiftLint', :git => 'https://www.swiftlintsource.com', :tag => '0.24.0'

So that i can skip pod update SwiftLint everytime new version released.

**Comment by ornithocoder** [comment]
When you not specify the version, you get the latest version. You can find [this](https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions) and more on the CocoaPods documentation.

**Comment by marcelofabri** [comment]
@gkmrakesh that's currently not supported because we don't keep the releases in the repo, they're binaries available via HTTP(s).

I suggest you to lock the version either on your `Podfile` or by commiting `Podfile.lock`.

**Comment by gkmrakesh** [comment]
Thanks for your clarifications
