### ISSUE TITLE
Point SPM to versions of deps and not branches

### ISSUE THREAD

**Issue by kdawgwilk** [realm/SwiftLint#1962]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

So I am trying to work on a SPM project using the SwiftLintFramework library and when I add SwiftLint as a dependency e.g.
```swift
        .package(url: "https://github.com/realm/SwiftLint.git", .upToNextMajor(from: "0.24.0")),
```
SPM complains with this error:
```
error: the package https://github.com/realm/SwiftLint.git @ 0.24.0 contains revisioned dependencies:
    https://github.com/Carthage/Commandant.git @ master
    https://github.com/jpsim/SwiftyTextTable.git @ characters
```

This can be resolved temporarily by pointing my Package.swift to SwiftLint master branch or the issue can be resolved by not pointed SwiftLint's Package.swift to dependencies using a branch.  It would prob be a good idea to not point to branches anyways

**Comment by SDGGiesbrecht** [comment]
Good catch, @kdawgwilk.

From Swift [proposal 150](https://github.com/apple/swift-evolution/blob/master/proposals/0150-package-manager-branch-support.md#specifying-branches-or-revisions-in-the-manifest), which brought us this branch functionality:

> While [pointing at branches] is useful during development, a package's dependencies should be updated to point at versions instead of branches before that package is tagged for release. This is because a released package should provide a stable specification of its dependencies, and not break when a branch changes over time. To enforce this, it is an error if a package referenced by a version-based dependency specifies a branch in any of its dependencies.

Pointing your package at SwiftLint’s `master` will only break your package in turn. I recommend pointing at `0.23.1` until a fix is released.

**Comment by kdawgwilk** [comment]
Since my package is a Vapor web app it will be okay for me to point at master

**Comment by jpsim** [comment]
Since those changes were made to Package.swift, SwiftyTextTable has cut a release. However, there's still no tagged release of Commandant that supports Swift 4.x, so that still has to point to a branch for now.
