### ISSUE TITLE
Fatal error: Illegal instruction: 4

### ISSUE THREAD

**Issue by chonex143** [realm/SwiftLint#1969]
Loading configuration from '.swiftlint.yml'
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /tmp/swiftlint-20171110-35989-ue11z3/Carthage/Checkouts/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 61
Illegal instruction: 4

OS: High Sierra
swiftlint-version: 0.24.0

**Comment by chonex143** [comment]
![screen shot 2017-12-06 at 1 56 59 pm](https://user-images.githubusercontent.com/25475522/33646967-60a51796-da8d-11e7-8388-dc743058bcce.png)

**Comment by chonex143** [comment]
fix by running `sudo xcode-select -s /Applications/Xcode\ 9.0.app/Contents/Developer`

**Comment by chonex143** [comment]
#1446

**Comment by christopherstock** [comment]
> fix by running `sudo xcode-select -s /Applications/Xcode\ 9.0.app/Contents/Developer`

Thank you so much! :D That did the trick for me .. mandatory if you got several Versions of XCode installed in custom paths :D <3
