### ISSUE TITLE
Unknown rule in `.swiftlint.yml` makes SwiftLint ignore the file and run

### ISSUE THREAD

**Issue by dpassage** [realm/SwiftLint#197]
If you have an unknown rule in the `disabled` section of your `.swiftlint.yml` file, swiftlint prints a nice message - and then proceeds to run with an empty configuration.

Found this because I'd added lines to ignore new rules in version 0.3.0 but our CI server had 0.2.0 installed. Many hundreds of lines of output resulted as SwiftLint descended into all our dependencies...

Happy to work on a PR. @jpsim what do you think the right behavior is - bail out entirely, or just ignore the unknown rule?

**Comment by jpsim** [comment]
> ignore the unknown rule?

I'd say this would be the right move. Thanks for offering to make a PR for this!

**Comment by jpsim** [comment]
Fixed in #198.
