### ISSUE TITLE
swiftlint.yml not found

### ISSUE THREAD

**Issue by Shahbaz-Akram** [realm/SwiftLint#1986]
I install swiftlint through  `cocoapods` by adding `pod 'SwiftLint'` in existing project. But pod  `swiftlint.yml` file not found in project to add some rules etc. Please help me.

**Comment by ornithocoder** [comment]
Hi @Shahbaz-Akram, you'll have to create a file called `.swiftlint.yml` on you project's root directory.

```
$ ls -la
drwxr-xr-x  16    544B Dec 31 23:38 .
drwxr-xr-x  12    408B Dec 10 16:37 ..
-rw-r--r--   1    950B Dec 30 20:37 .swiftlint.yml                # <---- this one
drwxr-xr-x   8    272B Jan  2 01:29 Project.xcodeproj
-rw-r--r--   1    514B Dec 31 00:35 Package.swift
drwxr-xr-x   3    102B Jun 12  2017 Sources
drwxr-xr-x   4    136B Jun 12  2017 Tests
$ 
```

**Comment by Shahbaz-Akram** [comment]
I found this video helpful: https://www.youtube.com/watch?v=cEA9BDVbjfI

**Comment by Toby-O-Connell** [comment]
Not so helpful when the video is private...
