### ISSUE TITLE
How to execute swiftlint lint in jenkins

### ISSUE THREAD

**Issue by AlphaJian** [realm/SwiftLint#1993]
It's fine for me to use swift lint to check code style in my macbook. But now, I want swiftlint to check my code when I commit the code to github. I have a Jenkins, but I don't know how and where to config the task to run "swiftlint lint"

**Comment by marcelofabri** [comment]
Just add a shell script phase that runs `swiftlint lint`. I'm closing this because this is not a SwiftLint issue, it's a Jenkins usage question and there are better places to look for help.
