### ISSUE TITLE
Rule Request: UIApplication should always be run on the main thread

### ISSUE THREAD

**Issue by RamblinWreck77** [realm/SwiftLint#2054]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Rule Request

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this. 

Hello! After a lot of frustration I finally tracked down a seemingly "random" crash. Turns out:

UIApplication.shared.DoSomeThing can cause a crash if not called on the main thread. This problem is also not likely to appear in testing and only show up once you've rolled out to 10,000 daily users or so. Often crash reporters like Fabric will not provide useful data on the crash making it hard to figure out what's happening. This is *especially* true if you do something like 

``
UIApplication.shared.registerForRemoteNotifications() 
``

In code that might get executed in the background. The solution to this is fairly simple and I think a new rule might save people a lot of headache in production.

2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

Would trigger:
``
UIApplication.shared.registerForRemoteNotifications()
``
``
UIApplication.shared.open(url, options: [:], completionHandler: nil)
``

Would not trigger:
``
DispatchQueue.main.async {
                UIApplication.shared.open(url, options: [:], completionHandler: nil)
}
``
``
DispatchQueue.main.async {
                if let window = UIApplication.shared.keyWindow {
                      print("Make root window")
                } else {
                      print("No Window")
                }
            }
``

3. Should the rule be configurable, if so what parameters should be configurable? 

I'm not sure, it's really all about making sure that said code will *always* run on the main thread, I'm not sure what options would be relevant. 

4. Should the rule be opt-in or enabled by default? Why?
   
In my opinion the rule should be enabled by default, as the amount of frustration this can cause is very severe. In my case it was crash reports on "random" functions all around App initialization. The fix is also fairly straightforward and as far as I can see shouldn't require breaking refactors or changes.

**Comment by marcelofabri** [comment]
I don't think this would be a very useful rule. We would only be able to catch the fairly obvious cases.

Instead, you probably should use [Main Thread Checker](https://developer.apple.com/documentation/code_diagnostics/main_thread_checker) inside Xcode.
