### ISSUE TITLE
How to use `excluded` with an environment variable?

### ISSUE THREAD

**Issue by heidiproske** [realm/SwiftLint#2072]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Question

I was looking at https://github.com/realm/SwiftLint/pull/1703 which says that support was added to specify the `excluded` section in your `.swiftlint.yml` via an environment variable but i can't seem to get mine to work. 

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? `0.25.0`
* Installation method used (Homebrew, CocoaPods, building from source, etc)? `CocoaPods`
* I've got an Xcode Build Phase **run script** that runs a script: ```${SRCROOT}/runLinter.sh```

where the `fastlane/.env` contains a line like this:
```
# Custom path to ignore during linting.
FL_LINT_CUSTOMIGNORE="Pods"
```
and the shell script referenced by the Xcode run script looks like:
```
# Extract the custom ignore path if it's set in our fastlane environment variables.
export FL_LINT_CUSTOMIGNORE=$(grep FL_LINT_CUSTOMIGNORE fastlane/.env | xargs)

echo "Before"
echo $FL_LINT_CUSTOMIGNORE

SWIFTLINT=${PODS_ROOT}/SwiftLint/swiftlint
$SWIFTLINT autocorrect
$SWIFTLINT

echo "After"
echo $FL_LINT_CUSTOMIGNORE
```

and the exclude section in `.swiftlint.yml` looks like:
```
excluded:
 - ${FL_LINT_CUSTOMIGNORE}
 ```

However, no matter what I do, SwiftLint appears to completely ignore this custom excluded section. Is there any more documentation or does anyone have an example of where this works? (Note that my `Before` and `After` print statements do show with the correct custom environment variable value in the Build log under the Xcode navigator.

Any guidance on using this environment variable / what the limitations are would be much appreciated 😄 

PS: What I'd *really* like is that the environment variable should be allowed to specify a list of exclusions so that my framework users have total control e.g.
`FL_LINT_CUSTOMIGNORE=['Pods', 'Some/Rather/ObscurePath','AndJustForFun/OneSpecificFile.swift']`

**Comment by marcelofabri** [comment]
I've tried just specifying it on the command line and it worked 🤔 

````
$ FL_LINT_CUSTOMIGNORE="Pods" swiftlint
```

I'd try to simplify the script until you find out what's wrong. Some ideas:

* Removing fastlane
* Running the script from terminal instead of a build phase

**Comment by heidiproske** [comment]
Aah weird, guess I’ll take a look again tomorrow- thanks @marcelofabri 😊

**Comment by heidiproske** [comment]
Doh, figured it out :) It was my poor bash script! 

Changed it as below.
-export FL_LINT_CUSTOMIGNORE=$(grep FL_LINT_CUSTOMIGNORE fastlane/.env | xargs)
+export $(grep FL_LINT_CUSTOMIGNORE fastlane/.env | xargs)

Thanks again :)

**Comment by marcelofabri** [comment]
@heidiproske glad that you figured it out! 💯
