### ISSUE TITLE
Idea: usage hints

### ISSUE THREAD

**Issue by thecodewarrior** [realm/SwiftLint#2082]
I think it'd be useful to have a set of "hint" driven rules in SwiftLint. The basic idea is that you would add hint comments (`// swiftlint:hint hint_name`) like annotations to functions, variables, classes, etc. which could provide additional linting. 

Examples of rules that could use this:

- `never_instantiate` - Essentially mimics abstract classes from other languages. It makes directly instantiating the hinted class an error. 
- `always_override` - Essentially mimics abstract methods/properties from other languages. It makes subclassing without overriding the hinted method/property or hinting the subclass with `never_instantiate` an error. Using this in a class not marked with `never_instantiate` is an error in and of itself. 
- `factory_method` - Add this to a static method in a class marked with `never_instantiate` and it will allow the method to instantiate its own class without an error occurring.
- `init_let` - Add this to a `var` to throw an error if its value is modified anywhere outside of that class's constructor or a method in that class marked with `factory_method`. Useful for properties that should be immutable but need to be set in one of several constructors or a factory method for one reason or another. (e.g. a UIViewController subclass where the value can't be properly initialized in the `init(coder:)` constructor)

I understand if this seems beyond the scope of this project, I just thought I'd throw it out there. Also I'm certain there are rules besides these that could make use of this system, they're just what I could think of in the last few minutes.

**Comment by thecodewarrior** [comment]
Has anyone looked at this? If one of the admins could label it so it shows up when people are looking for enhancements that would be helpful, as otherwise it's easy for it to be lost to the last page of issues. There's no time pressure, just want to make sure it wasn't missed/forgotten.

**Comment by SDGGiesbrecht** [comment]
@thecodewarrior, I have seen it, but I’m not the one who decides these things.

For clarification. Are you asking for permission to implement it, or are you hoping someone else will? If the former, you will probably catch attention faster if you say so.

**Comment by thecodewarrior** [comment]
I can't do the implementation at the moment, so mostly hoping someone else will. Eventually™ I may be able to spend time to implement it, but I have no idea when that will be.
