### ISSUE TITLE
redundant_nil_coalescing is not working with ExpressibleByNilLiteral

### ISSUE THREAD

**Issue by swordray** [realm/SwiftLint#2085]
```swift
var variable: Class?
print(type(of: variable))        // Optional<Class>
print(type(of: variable ?? nil)) // Class
```
`variable` is different from `variable ?? nil` when class implements `ExpressibleByNilLiteral`.

### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --path class.swift --no-cache
Loading configuration from '.swiftlint.yml'
Linting Swift files at path class.swift
Linting 'class.swift' (1/1)
/Users/swordray/Sites/swiftlint-demo/class.swift:7:24: warning: Redundant Nil Coalescing Violation: nil coalescing operator is only evaluated if the lhs is nil, coalescing operator with nil as rhs is redundant (redundant_nil_coalescing)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?

0.25.0

* Installation method used (Homebrew, CocoaPods, building from source, etc)?

CocoaPods

* Paste your configuration file:

```yml
opt_in_rules:
  - redundant_nil_coalescing
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.

No.

* Which Xcode version are you using (check `xcode-select -p`)?

Version 9.2 (9C40b)

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
class Class: ExpressibleByNilLiteral {
    required init(nilLiteral: ()) {}
}

var variable: Class?
print(type(of: variable))        // Optional<Class>
print(type(of: variable ?? nil)) // Class
```

**Comment by marcelofabri** [comment]
Currently, this would only be possible for types defined on the same file as the violation, as SwiftLint only knows about the current file while linting.

**Comment by swordray** [comment]
Sorry to hear that. My case is crossing multiple files.

**Comment by marcelofabri** [comment]
It's a current limitation of SwiftLint. I recommend you to just disable that rule locally for now.

**Comment by swordray** [comment]
Thank you for answering.

**Comment by SDGGiesbrecht** [comment]
@swordray,

Have you read the [documentation for `ExpressibleByNilLiteral`](https://developer.apple.com/documentation/swift/expressiblebynilliteral)?

> `nil` has a specific meaning in Swift—the absence of a value. Only the `Optional` type conforms to `ExpressibleByNilLiteral`. `ExpressibleByNilLiteral` conformance for types that use `nil` for other purposes is discouraged.

Are you sure you want to be disregarding that?

If you *are* sure about what you are doing and you *do* want to maintain a distinction between `nil` and `nil`, then my recommendation is the same as Fabri’s—disable the rule locally.

**Comment by swordray** [comment]
@SDGGiesbrecht 

This is a very good opinion. `ExpressibleByNilLiteral` should not be used at all. 

The use case is, I want absent model objects become empty objects like `[:]` instead of `Optional<>`. It looks like `Optional` but already unwrapping with default values. I can just use `variable ?? .init()` replacing `variable ?? nil`.
