### ISSUE TITLE
Install SwiftLint with gem

### ISSUE THREAD

**Issue by jhandguy** [realm/SwiftLint#2093]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

I think a lot of people here are using **Fastlane** and most probably with the Bundle (_bundle exec fastlane_).
Currently, SwiftLint can not be installed using the **Gemfile**, I think that would be nice to be able to do so.
Could it be possible to have SwiftLint as a **Gem**?

##### Complete output when running SwiftLint, including the stack trace and command used

_In the Gemfile:_
**gem "swiftlint"**

_In the command line:_
```bash
$ bundle update
```

**Comment by marcelofabri** [comment]
SwiftLint is not written in Ruby, so it doesn't make sense to be distributed through RubyGems.
