### ISSUE TITLE
legacy_cggeometry_functions autocorrect doesn't correct when functions are used

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#2103]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

#2098, but for `legacy_cggeometry_functions`

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint --path file.swift 
Loading configuration from '.swiftlint.yml'
Linting Swift files at path file.swift
Linting 'file.swift' (1/1)
file.swift:1:1: warning: Legacy CGGeometry Functions Violation: Struct extension properties and methods are preferred over legacy functions (legacy_cggeometry_functions)
Done linting! Found 1 violation, 0 serious in 1 file.

$ swiftlint autocorrect --path file.swift
Loading configuration from '.swiftlint.yml'
Correcting Swift files at path file.swift
Correcting 'file.swift' (1/1)
Done correcting 1 files!
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.25.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? CP
* Paste your configuration file: 

No configuration file needed

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.

No

* Which Xcode version are you using (check `xcode-select -p`)? 9.2
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// this triggers a violation but doesn't autocorrect
CGRectIsNull(foo())
```

**Comment by jszumski** [comment]
This may be more systemic... I'm seeing autocorrect failing on many but not all rules (e.g., `redundant_void_return` works).  Each of these examples triggers a linter warning but doesn't autocorrect:

`joined_default_parameter`

```swift
["1", "2"].joined(separator: "")
```

 `empty_enum_arguments`:
```
enum Foo {
    case bar(String)
}

func f(foo: Foo) {
    switch foo {
    case .bar(_):
        break
    }
}
```

`empty_parentheses_with_trailing_closure`:
```
func f() {
    [1, 2].map( ) { $0 + 1 }
}
```

**Comment by marcelofabri** [comment]
@jszumski I know that this is a lot to ask, but can you please open one issue per rule you're seeing this (with examples)?

I've tried the examples you've provided and it really seems they're not being autocorrected.

**Comment by marcelofabri** [comment]
Actually, `joined_default_parameter` works for me.
