### ISSUE TITLE
Cannot get nested configuration to work

### ISSUE THREAD

**Issue by svdo** [realm/SwiftLint#2110]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --no-cache
Loading configuration from '.swiftlint.yml'
Linting Swift files in current working directory
Linting 'Data+IndexOfAfterSpec.swift' (1/80)
Linting 'String+LengthEncodedDataSpec.swift' (2/80)
Linting 'SequenceNumberSpec.swift' (3/80)
Linting 'UInt8+BalanceSpec.swift' (4/80)
Linting 'ClasséReducerSpec.swift' (5/80)
Linting 'ClasséStateSpec.swift' (6/80)
Linting 'CommandSenderSpec.swift' (7/80)
Linting 'DevReducerSpec.swift' (8/80)
Linting 'StorePersisterSpec.swift' (9/80)
Linting 'ConfigurationsPacketSpec.swift' (10/80)
Linting 'FrequencyPacketSpec.swift' (11/80)
Linting 'GeneralInfoPacketSpec.swift' (12/80)
Linting 'L23PacketSpec.swift' (13/80)
Linting 'L25PacketSpec.swift' (14/80)
Linting 'L47PacketSpec.swift' (15/80)
Linting 'Sources1PacketSpec.swift' (16/80)
Linting 'Sources2PacketSpec.swift' (17/80)
Linting 'OutgoingReducerSpec.swift' (18/80)
Linting 'RecordingStore.swift' (19/80)
Linting 'CommandSpec.swift' (20/80)
Linting 'UserReducerSpec.swift' (21/80)
Linting 'UserStateSpec.swift' (22/80)
Linting 'AppDelegate.swift' (23/80)
Linting 'ConfigurationsViewController.swift' (24/80)
Linting 'MuteControl.swift' (25/80)
/Users/stefan/Documents/Projects/CP800/CP800ControlTests/Global store/StorePersisterSpec.swift:9:14: warning: Function Body Length Violation: Function body should span 40 lines or less excluding comments and whitespace: currently spans 46 lines (function_body_length)
Linting 'PowerControl.swift' (26/80)
Linting 'VolumeControl.swift' (27/80)
/Users/stefan/Documents/Projects/CP800/CP800ControlTests/ClasséState/ClasséReducerSpec.swift:9:14: error: Function Body Length Violation: Function body should span 40 lines or less excluding comments and whitespace: currently spans 127 lines (function_body_length)
Linting 'DevViewController.swift' (28/80)
Linting 'HomeViewController.swift' (29/80)
/Users/stefan/Documents/Projects/CP800/CP800ControlTests/User/UserReducerSpec.swift:8:14: warning: Function Body Length Violation: Function body should span 40 lines or less excluding comments and whitespace: currently spans 66 lines (function_body_length)
Linting 'LCDViewController.swift' (30/80)
Linting 'PacketDetailsViewController.swift' (31/80)
Linting 'PresetDetailsViewController.swift' (32/80)
/Users/stefan/Documents/Projects/CP800/CP800ControlTests/Packets/Outgoing/OutgoingReducerSpec.swift:8:14: warning: Function Body Length Violation: Function body should span 40 lines or less excluding comments and whitespace: currently spans 100 lines (function_body_length)
/Users/stefan/Documents/Projects/CP800/CP800ControlTests/CommandSender/CommandSenderSpec.swift:37:14: error: Function Body Length Violation: Function body should span 40 lines or less excluding comments and whitespace: currently spans 161 lines (function_body_length)
Linting 'PresetsViewController.swift' (33/80)
Linting 'SourcesViewController.swift' (34/80)
Linting 'StatusViewController.swift' (35/80)
Linting 'Data+ASCII.swift' (36/80)
Linting 'Data+Hex.swift' (37/80)
Linting 'Data+IndexOfAfter.swift' (38/80)
Linting 'SequenceNumber.swift' (39/80)
Linting 'String+CamelCased.swift' (40/80)
Linting 'String+LengthEncodedData.swift' (41/80)
Linting 'UIColor+Hex.swift' (42/80)
Linting 'UInt8+Balance.swift' (43/80)
Linting 'UInt8+Volume.swift' (44/80)
Linting 'ClasséActions.swift' (45/80)
Linting 'ClasséReducer.swift' (46/80)
Linting 'ClasséState.swift' (47/80)
Linting 'CommandSender.swift' (48/80)
Linting 'DevActions.swift' (49/80)
Linting 'DevReducer.swift' (50/80)
Linting 'DevState.swift' (51/80)
Linting 'Discovery.swift' (52/80)
Linting 'AppReducer.swift' (53/80)
Linting 'AppState.swift' (54/80)
Linting 'AppStore.swift' (55/80)
Linting 'StorePersister.swift' (56/80)
Linting 'MulticastListener.swift' (57/80)
Linting 'ConfigurationsPacket.swift' (58/80)
Linting 'FrequencyPacket.swift' (59/80)
Linting 'GeneralInfoPacket.swift' (60/80)
Linting 'InterpretedPacket.swift' (61/80)
Linting 'L200Packet.swift' (62/80)
Linting 'L23Packet.swift' (63/80)
Linting 'L25Packet.swift' (64/80)
Linting 'L47Packet.swift' (65/80)
Linting 'Packet.swift' (66/80)
Linting 'PacketActions.swift' (67/80)
Linting 'PacketsReducer.swift' (68/80)
Linting 'PacketsState.swift' (69/80)
Linting 'SourcesPacket.swift' (70/80)
Linting 'ClasséCommand.swift' (71/80)
Linting 'OutgoingActions.swift' (72/80)
Linting 'OutgoingReducer.swift' (73/80)
Linting 'OutgoingState.swift' (74/80)
Linting 'Command.swift' (75/80)
Linting 'Preset.swift' (76/80)
Linting 'UserActions.swift' (77/80)
Linting 'UserReducer.swift' (78/80)
Linting 'UserState.swift' (79/80)
Linting 'TodayViewController.swift' (80/80)
Done linting! Found 5 violations, 2 serious in 80 files.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure): **0.25.0 (also tried with self-compiled version of commit `c87b2c7091fb8e2b893f6a2b3d503c0c3406977b`)**
* Installation method used (Homebrew, CocoaPods, building from source, etc): **homebrew**

I am using **nested configuration**:

`.swiftlint.yml`:
```yml
excluded:
  - Carthage
  - Pods
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - quick_discouraged_focused_test
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
```

`CP800ControlTests/.swiftlint.yml`:
```yml
function_body_length: 200
disabled_rules:
  - force_unwrapping
```

* Which Xcode version are you using (check `xcode-select -p`): **Version 9.2 (9C40b)**

### Issue/Problem Description
As you can see from the output above, the nested configuration file in `CP800ControlTests` is not used: the `function_body_length` violations are incorrect, as the maximum length is overridden in the nested config to be 200. 

When running the command in the `CP800ControlTests` subfolder, I get the expected output: no linter violations. This means that the `.swiftlint.yml` file is correct.

I'm having this problem with multiple projects. Am I missing something / misunderstanding? Or is this really a bug? This problem was introduced for me with SwiftLint release 0.22.0; when using 0.21.0 I don't have this issue. Thanks for your feedback!

**Comment by svdo** [comment]
Anybody have any ideas how to solve this? Thanks!

**Comment by SDGGiesbrecht** [comment]
> ```
> disabled_rules:
>  - force_unwrapping
> ```

Does this part work?

The granularity of the merge operation is limited. Enabling and disabling of entire rules should work, but I do not think changes to rule parameters (such as `function_body_length: 200`) are considered during the merge operation (yet).

If you want to try your hand at a pull request, the related code is all in [Source/SwiftLintFramework/Extensions/Configuration+Merging.swift](https://github.com/realm/SwiftLint/blob/cf59e0c771b7f50611ef2c4ee0c8386a92098cd8/Source/SwiftLintFramework/Extensions/Configuration%2BMerging.swift).

**Comment by svdo** [comment]
Ahhhh that explains it. Indeed, disabling `force_unwrapping` in the subfolder does work. Maybe I should make a pull request on `README.md` first, to make this more explicit :)

Actually solving this issue is also tempting. I'll ponder on it a bit. I'm afraid I don't have the bandwidth at the moment to learn the internals of SwiftLint, starting with "how do you create a unit test for this"?

**Comment by svdo** [comment]
Ok, I gave it a quick look and testing it may actually be easier than I initially thought. @SDGGiesbrecht Would a pull request for only merging `function_body_length` correctly be acceptable, or would I have to implement all rule parameter merging everywhere?

**Comment by SDGGiesbrecht** [comment]
> Would a pull request for only merging function_body_length correctly be acceptable, or would I have to implement all rule parameter merging everywhere?

That decision is not up to me, but a quick look makes me suspect that it would be just as easy to get all parameters at once.

- The rules get merged in [Configuration.mergingRules(with:)](https://github.com/realm/SwiftLint/blob/cf59e0c771b7f50611ef2c4ee0c8386a92098cd8/Source/SwiftLintFramework/Extensions/Configuration%2BMerging.swift#L84-L117).
- Any rule with parameters has them stored in [`ConfigurationProviderRule.configuration`](https://github.com/realm/SwiftLint/blob/4539e21b3aa4c4a58cddfdf5803bc806b694340f/Source/SwiftLintFramework/Protocols/Rule.swift#L37).

So just make sure to apply the parameters from the nested instance to the rule. If you also want to specially handle the `SeverityLevelsConfiguration` used by `function_body_length` and merge its property combination (error and warning thresholds), I doubt anyone would object.

If it turns out to be more complicated than that, feel free to ask more questions.
