### ISSUE TITLE
Rule Request: Opposite of SwitchCaseAlignmentRule

### ISSUE THREAD

**Issue by Noobish1** [realm/SwiftLint#2119]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Rule Request

1. Why should this rule be added? 

In my codebase (and others i've worked on) I like switch cases to be indented one level extra than the switch itself (i've known others to do the same also), e.g:

```swift
switch enumThing {
    case firstCase:
        // do stuff
    default:
        // do stuff
}
```

This could be implemented as a separate opt-in rule or as a configuration option on the existing `SwitchCaseAlignmentRule`.

**Comment by freak4pc** [comment]
Have been looking for a similar rule as well, might take a crack at it

**Comment by freak4pc** [comment]
@Noobish1 Added a quick PR mentioned here. Check it out and let me know what you think.
