### ISSUE TITLE
Custom "advanced" rule locally question

### ISSUE THREAD

**Issue by Abeansits** [realm/SwiftLint#2137]
After reading the README up and down there is one thing that I can't wrap my head around, how do I create a custom rule that is not a simple regex rule and only is included in my project?

I'm trying to write a rule that implements some style guide rules of my team, more specifically we have a collection of `MARKs` that we want to show up in a particular order. To my understanding the simpler format of a regex rules specified in the config file is not enough to deal with this. But the rule is also specific enough that the community wouldn't benefit from me creating a PR.

**Comment by marcelofabri** [comment]
Currently SwiftLint doesn't support custom rules that require code. That's something that would be a welcome addition, but it's also not straightforward to implement/support, as we'd need to create a plugin system.

**Comment by Abeansits** [comment]
I see @marcelofabri. Thanks for explaining.

**Comment by Johennes** [comment]
Would it actually be possible to create a plugin system while Swift does not have ABI stability or would that be a blocker?

**Comment by jpsim** [comment]
ABI stability isn't necessarily a blocker for a SwiftLint plugin system. Plugins could interact with SwiftLint via XPC or JSON and wouldn't necessarily need to even be written in Swift.

This is a green field project that could be designed in a hundred different ways, so the first step would be to come up with a comprehensive proposal pitching how such a system should be designed.

**Comment by vickyrocky** [comment]
Hi,

Is there a way to modify this tool itself for implementing a new rule. I was not able to find any documentation regarding this information. It would be great if we can get to know the process to add the rule so in this case there is no need to create a plugin system.

**Comment by jpsim** [comment]
There are instructions for contributing new rules in CONTRIBUTING.md. There are also over 150 rules defined in SwiftLint that you can use as examples for how to implement a wide variety of rules.

**Comment by marcelofabri** [comment]
Closing this in favor of #2529.
