### ISSUE TITLE
Question: [type_name] wildcard `excluded` property

### ISSUE THREAD

**Issue by RishabhTayal** [realm/SwiftLint#2156]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

Is there a way to specify a wildcard in the `excluded` property of the rule `type_name`. For e.g: my class names are named as `ClassName_v2`. How can I disable the rule for this name? I tried using the following and it doesn't work

```
type_name:
  excluded: _v2
```

**Comment by marcelofabri** [comment]
There's no way to specify a wildcard. You can use `allowed_symbols` to allow `_`.

**Comment by Blackjacx** [comment]
Wow could you add this to the README examples? Many ppl search there first and in my case I was just lucky to discover this here in the ~300 issues.

**Comment by marcelofabri** [comment]
@Blackjacx feel free to submit a PR!

**Comment by arnauddorgans** [comment]
Is there still no way to do it?
