### ISSUE TITLE
What rules does swiftlint autocorrect follow?

### ISSUE THREAD

**Issue by AlphaJian** [realm/SwiftLint#2157]
When I use autocorrect, I find lint can autocorrect the rules such as "colon", "comma", whatever I add this rules into "opt_in_rules". So my question is how many rules and what are they, that lint autocorrect follows?

**Comment by SDGGiesbrecht** [comment]
@AlphaJian

```shell
$ swiftlint rules
```
... column 3. 😉

**Comment by marcelofabri** [comment]
Or check [Rules.md](https://github.com/realm/SwiftLint/blob/master/Rules.md).
