### ISSUE TITLE
Replace strings representing declaration attributes to SwiftDeclarationAttributeKind

### ISSUE THREAD

**Issue by dirtydanee** [realm/SwiftLint#2162]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Description

With the release of `SourceKitten` 0.20.0, [`SwiftDeclarationAttributeKind`](https://github.com/jpsim/SourceKitten/pull/507/commits/e63040b536ffbd1d56dff7a985d44b0c37f73e9b) was added to represent declaration attributes in Swift. 

The SwiftLint code base has 19+ occurrences, if one runs a search for `source.decl.attribute`. I would be opening a PR to replace the string types for the enum, if you guys think it makes sense.

**Comment by dirtydanee** [comment]
Great, i was not aware of the PR. Thanks fot the change!

**Comment by marcelofabri** [comment]
Thank you for jpsim/SourceKitten/pull/507 💯
