### ISSUE TITLE
How to make serious as warning

### ISSUE THREAD

**Issue by AlphaJian** [realm/SwiftLint#2178]
I integrate swiftlint in gitlab. But if the project has serious lint issues will make the job failed. So my question is, is there a way to make serious as warning?

**Comment by kimdv** [comment]
Hi @AlphaJian 
It is possible to change rules from only showing warning to show error.

You can see an example in: [https://github.com/realm/SwiftLint/blob/master/README.md#configuration](README)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcelofabri** [comment]
You can also use `--lenient` when running `swiftlint lint`.

**Comment by marcelofabri** [comment]
@AlphaJian I'm closing this for now. Feel free to reopen if needed.
