### ISSUE TITLE
0.4.0 not available with brew

### ISSUE THREAD

**Issue by mmorier** [realm/SwiftLint#220]
Thanks for the Wrinkle release! I am trying to deploy it on all my CI slaves but not yet available with brew. Forgetting of send it to brew?

**Comment by ehamberg** [comment]
It will probably be in homebrew soon: https://github.com/Homebrew/homebrew/pull/46104

**Comment by jpsim** [comment]
Please see https://github.com/Homebrew/homebrew/pull/46104 for updates on when it will be merged. It's out of our hands.

**Comment by jpsim** [comment]
They just merged it.
