### ISSUE TITLE
Selectively turn off autocorrect for specific rules

### ISSUE THREAD

**Issue by teameh** [realm/SwiftLint#2207]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Feature Request

I've been able to set up formatting on save in XCode with [`npm-watch`](https://www.npmjs.com/package/npm-watch) 😄. The autocorrect feature works great. 

However, although I want to get warnings for all rules when I build the project in XCode I don't want all the rules corrected upon each save (for example `unused_closure_parameter`). It would be great if you could selectively turn off autocorrect for each rule in the config so that the autocorrect mainly fixes formatting but leaves some code-smell things untouched.

**Comment by marcelofabri** [comment]
@teameh you could have two different configuration files to accomplish this

**Comment by teameh** [comment]
Nice idea. But how can I specify a different config file? Something like `--config=....` would be nice. Swiftlint will currently take nested configs right, so putting different config files in different folders won't work.

**Comment by jpsim** [comment]
Hopefully @marcelofabri's last comment resolved your issue.

**Comment by teameh** [comment]
> Hopefully @marcelofabri's last comment resolved your issue.

Yes it did. Sorry for the late response. Thanks @marcelofabri 😄
