### ISSUE TITLE
line_length configuration setting ignores_interpolated_strings causes invalid configuration

### ISSUE THREAD

**Issue by likeaj6** [realm/SwiftLint#2237]
### New Issue Checklist

- [X ] Updated SwiftLint to the latest version
- [X ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
Loading configuration from '.swiftlint.yml'
Invalid configuration for 'line_length'. Falling back to default.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.25.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Homebrew, same issue with CocoaPods
* Paste your configuration file:
```yml
line_length:
  warning: 250
  error: 400
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ### works up until this config rule
  ignores_interpolated_strings: true
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
no
* Which Xcode version are you using (check `xcode-select -p`)?
9.3.1
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.
N/A

**Comment by marcelofabri** [comment]
That feature is only available on `master`, it's not included on 0.25.1.
