### ISSUE TITLE
Split RulesTests into several test cases

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#2263]
Xcode 10 introduced parallel testing. It works by giving out different `XCTestCase`s to different runners.

However, `RulesTests` contains a lot of tests that could be easily parallelizable. We need to split it into several test cases in order to take full advantage of parallel testing.

**Comment by jpsim** [comment]
One thing we could do is to leverage Sourcery to automatically generate RulesTests tests. Might need to add a dummy protocol to track which rules should opt-in to these automatically generated tests.
