### ISSUE TITLE
Emitted warnings/errors should include a column number

### ISSUE THREAD

**Issue by kballard** [realm/SwiftLint#2267]
### New Issue Checklist

- [ ] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

The output of SwiftLint is of the form

    /path/to/file:15: warning: message goes here

Unfortunately, this doesn't play well with `xcpretty`, as `xcpretty` appears to require a column number for warnings (filed as https://github.com/supermarin/xcpretty/issues/321). It would be great if SwiftLint could start including column numbers so the output would be

    /path/to/file:15:23: warning: message goes here

### Environment

* SwiftLint version 0.25.1

**Comment by kballard** [comment]
Looks like the `xcpretty` issue is more than just column, it also wants the "cursor" output that compilers include. I'll file a separate issue about that.

**Comment by jpsim** [comment]
I wonder if there would be any negative ramifications of using a fallback column of `1` if there's none provided. This would be very easy to do.

**Comment by kballard** [comment]
Probably very minimal. You could also use a column of `0` to signify that there is no column information (similar to how Swift backtraces use a line number of `0` for generated code that has no associated source line).

**Comment by jpsim** [comment]
Went with a fallback column value of `1` like we do for line numbers. At least this way the location is a valid location in the file. Seems safer. https://github.com/realm/SwiftLint/pull/2488

**Comment by jpsim** [comment]
Addressed in #2488.
