### ISSUE TITLE
force-exclude doesn't work

### ISSUE THREAD

**Issue by cooksimo** [realm/SwiftLint#2275]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

Running swiftlint with a `path` specified and an exclusion in the config that would exclude that file still lints that file even when `force-exclude` is specified.

```bash
$ swiftlint lint --path path/to/SomeFile.swift --force-exclude
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.26.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Cocoapods

**Comment by marcelofabri** [comment]
Can you provide more info or even better a sample example?

**Comment by cooksimo** [comment]
Sure, see attached.

[swiftlint-example.zip](https://github.com/realm/SwiftLint/files/2157613/swiftlint-example.zip)

Running `swiftlint --path exclude/ExcludeMe.swift --force-exclude` will still lint the file `exclude/ExcludeMe.swift`
