### ISSUE TITLE
[Rule Request Modification] - PrivateUnitTestRule.swift Unit tests marked 'private' warning incorrect

### ISSUE THREAD

**Issue by thefredelement** [realm/SwiftLint#2282]
### New Issue Checklist

- [X ] Updated SwiftLint to the latest version
- [X ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Rule Request Modification

On an XCTestCase if a method is marked private the following warning triggers: 
Private Unit Test Violation: Unit test marked "private" will not be run by XCTest. (private_unit_test)

However, if the @objc keyword is used it will run.

**Comment by marcelofabri** [comment]
This seems reasonable and a great starter task! @thefredelement would you like to take a shot at it?

**Comment by thefredelement** [comment]
@marcelofabri sure :).
