### ISSUE TITLE
Rule Request: Use AnyObject instead of class for class-only protocols

### ISSUE THREAD

**Issue by Noobish1** [realm/SwiftLint#2283]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Rule Request

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this.

Apple recommends it, as of Swift 4: https://docs.swift.org/swift-book/LanguageGuide/Protocols.html. And `class` is just a typealias to `AnyObject` as is stated [here](https://github.com/apple/swift-evolution/blob/e3f387d08307ce0af7a0f80979151714c41988bb/proposals/0156-subclass-existentials.md#class-and-anyobject)

2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

triggering: `protocol <protocol-name>: class`
non-triggering: `protocol <protocol-name>: AnyObject`

3. Should the rule be configurable, if so what parameters should be configurable?

Nope, we should we using AnyObject in all cases I believe.

4. Should the rule be opt-in or enabled by default? Why?
   See [README.md](../README.md#opt-in-rules) for guidelines on when to mark a
   rule as opt-in.

Nope, we should we using AnyObject in all cases I believe.

**Comment by ornithocoder** [comment]
@Noobish1, are you planning to work on it? Otherwise I will :-)

**Comment by Noobish1** [comment]
I’m not, no. Go ahead and thanks!

Blair.

**Comment by ornithocoder** [comment]
@Noobish1 👍 Thanks!

**Comment by marcelofabri** [comment]
Implemented by @ornithocoder on #2285 🎉

**Comment by ornithocoder** [comment]
@Noobish1, implemented w/ autocorrect.

**Comment by Noobish1** [comment]
Awesome, nice work @ornithocoder.
