### ISSUE TITLE
"ignores_interpolated_strings" does not work in line_length rule

### ISSUE THREAD

**Issue by VivoEx** [realm/SwiftLint#2284]
When I define the rule in order to ignore violations for interpolated strings such as below, it does not work where it does bring warnings even for the lines that goes beyond length of just 120, whereas if I just ignore the "ignores_interpolated_strings" from the below, then it works as expected(that is shows warning only when line length is beyond 200)
"
line_length:
  warning: 200
  error: 250
  ignores_interpolated_strings: true
"

Tried another prop "ignores_comments" instead of "ignores_interpolated_strings" in the above segment  which works ok.

**Comment by marcelofabri** [comment]
Please update the issue to follow the template to make it easier to help you.

**Comment by karthikAdaptavant** [comment]
still the issue is happening with long interpolated regex strings in swift.
