### ISSUE TITLE
Properly document Code in SwiftLint for new Contributors

### ISSUE THREAD

**Issue by Jeehut** [realm/SwiftLint#2290]
Hi guys, I just started implementing new rules for SwiftLint and while I found the CONTRIBUTING.md very useful, it leaves much to the code to explain itself. While I like this idea, this can only work if the core types in SwiftLint are properly documented – which is not the case. As far as I could see until now, forget _properly_ here, the core types aren't documented at all!

What I mean by core types, until now:
- [Rule](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Protocols/Rule.swift)
- [ASTRule](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Protocols/ASTRule.swift)
- [RuleDescription](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Models/RuleDescription.swift)
- [RuleKind](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Models/RuleKind.swift)
- [StyleViolation](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Models/StyleViolation.swift)

While sometimes I can guess from the name, what things are or do, sometimes it's not possible. For example I just started implementing the first requirement for my first rule and I already don't know what to specify for the `kind` parameter since the `RuleKind` type isn't documented. What's the case `idiomatic` supposed to mean? How is it different from `style`? What's the case `lint` in a lint tool?

Some documentation would be awesome.

**Comment by marcelofabri** [comment]
I agree, but I believe that a high-level explanation on CONTRIBUTING.md or a new file would be even better so contributors could know what types to look for.

**Comment by marcelofabri** [comment]
Related: #2234

**Comment by Dschee** [comment]
While adding high-level explanation to `CONTRIBUTING.md` sounds good to me, I still think it's something different to have properly documented code since you might have already read the "high-level" descrription but want to just lookup something real quick by command-clicking in Xcode. And if we already have some description somewhere, why not copy & paste it to the classes in code?

**Comment by marcelofabri** [comment]
I agree that both are useful

**Comment by donald-m-ritter** [comment]
@Dschee I finally had time to update my rule tutorial PR.  It has some of this information in it but please take a look and let me know if there is anything else in there you would like explained further.
