### ISSUE TITLE
Add ability to Lint subregions of a file

### ISSUE THREAD

**Issue by aarondaub** [realm/SwiftLint#23]
A Linter should be able to create a sub-Linter when we enter a region of code that has comment modifiers applied to it (e.g. // swift-lint:enable-rule).

Suggested implementation hints: Linter takes a File as an initializer, we can create a File with a contents String. If a Linter does a pass over that string to find each sub-region it can map those sub-regions into a [Linter] and then flatMap styleViolations over the resultant [Linter].

**Comment by jpsim** [comment]
Closing as a duplicate of #4.
