### ISSUE TITLE
redundant_type_annotation autocorrect is really buggy

### ISSUE THREAD

**Issue by Dschee** [realm/SwiftLint#2314]
I recently turned on `redundant_type_annotation` which seems to work fine when it comes to showing warnigns. But when running `swiftlint autocorrect` I get many changes that break my code. Here are a few examples of the changes made by this rule:

**BEFORE**
```swift
 enum EventType {
     case amazingMonitor(isPresenting: Bool)
     case amazingHistory(isPresenting: Bool)
     case startNFCScan
     case scanAmazingQRCode
 }

```

**AFTER** (the fist two cases mixed up)
```swift
 enum EventType {
     case amazingMonitor(isPresentingcase amazingHistory(isPresenting: Bool)
     case startNFCScan
     case scanAmazingQRCode
 }
```

**BEFORE**
```swift
 import Foundation
 import MapKit
 
 // swiftlint:disable:next type_body_length
 final class AmazingTracking: NSObject {
     // MARK: - Stored Type Properties
     static let shared = AmazingTracking()

```

**AFTER** (the swiftlint disabling broken)
```swift
 import Foundation
 import MapKit
 
 // swiftlintlength
 final class AmazingTracking: NSObject {
     // MARK: - Stored Type Properties
     static let shared = AmazingTracking()
```

**BEFORE**
```swift
 protocol AmazingManagerDelegate: class {
     func manager(_ manager: AmazingManager, didChange region: MKCoordinateRegion)
```

**AFTER** (the `: class` is gone)
```swift
 protocol AmazingManagerDelegate {
     func manager(_ manager: AmazingManager, didChange region: MKCoordinateRegion)
```

There's a lot more if you need more examples, but I thinks this is a start.

**Comment by marcelofabri** [comment]
@Dschee I wasn't able to reproduce the problem with the examples you've provided. Can you double check that those reduced snippets trigger the issue?

**Comment by Dschee** [comment]
I just checked both the reduced snippets and also the project itself and the issue didn't happen anymore. Can't explain why, but maybe it was fixed as a side effect of something else (I just tried with the latest master) or I had done something wrong when forking SwiftLint (I had the issue with the master branch in my fork). In any case, I can't reproduce it either, so I'm closing. Sorry for the inconvenience!

**Comment by Dschee** [comment]
Okay, I could reduce the issue to the following examples, where this happens:

```swift
class ViewController: UIViewController {
    func someMethod() {
        let myVar: Int = Int(5)
    }
}
```

When autocorrecting this example, instead of removing the redundant `: Int` it removes the `: UIViewController`.

**Comment by Dschee** [comment]
@marcelofabri Thank you for fixing this so quickly!
