### ISSUE TITLE
Exclude `Pods` and `Carthage` directories by default

### ISSUE THREAD

**Issue by robmaceachern** [realm/SwiftLint#2319]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Enhancement Request

I think that the `Pods` and `Carthage` directories should be excluded from SwiftLint by default.

Flagging linter warnings/errors on dependencies isn't a very useful or commonly needed feature. Most sample `.swiftlint.yml` files that I've seen manually exclude these directories (examples: [0](https://github.com/realm/SwiftLint#configuration), [1](https://github.com/xmartlabs/Swift-Project-Template/blob/master/Project-iOS/XLProjectName/.swiftlint.yml#L26), [2](https://medium.com/developermind/using-swiftlint-and-danger-for-swift-best-practices-48432e4e268a)). This should be a built-in default which can be overridden with `included` if needed for some reason.

At least with Cocoapods, excluding the Pods directory by default would simplify the initial integration of SwiftLint into the project. Currently, the initial setup goes something like:

* Add `pod 'SwiftLint'`
* Add the `"${PODS_ROOT}/SwiftLint/swiftlint"` to a build phase
* Build project, which fails due to third party linter violations
* Google "swiftlint config sample"
* Add `.swiftlint.yml` and `excluded: - Pods`

It also makes running an initial or one-off autocorrect more cumbersome than it needs to be.

Related to https://github.com/realm/SwiftLint/issues/1637. This was mentioned also in #6 but the issue was closed with the addition of the exclusion options to `.swiftlint.yml`.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.26.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Cocoapods

**Comment by fabb** [comment]
Maybe rather create a `swiftlint init` command (similar to `pod init`) that creates a default `.swiftlint.yml` configuration file that already includes `excluded: - Pods`?

**Comment by sindresorhus** [comment]
@fabb It's easy enough to add it manually. The point here is to reduce boilerplate and optimize for the common case.

**Comment by robmaceachern** [comment]
@fabb I think some kind of command that generates a `.swiftlint.yml` could be useful, particularly if there was some way it could make discovering opt-in rules better. I still think the Pods exclusion should be a SwiftLint default though :)

**Comment by fabb** [comment]
I‘m not against it, just wanted to point out a possible alternative.
