### ISSUE TITLE
`operator_usage_whitespace` rule disable for the visual code paddings.

### ISSUE THREAD

**Issue by soberman** [realm/SwiftLint#2330]
Right now I have problems with the `operator_usage_whitespace` rule - it always being triggered for this block of code which I write to visually read it better:
```
private typealias AccessibleFromOutside     = SomeClass
private typealias Private_Configs           = SomeClass
private typealias Private_SizeClass_Related = SomeClass
```

Is it possible to add this knowledge to SwiftLint somehow so that I wouldn't have to annotate all the places where I have similar typealiases?

**Comment by marcelofabri** [comment]
Duplicate of #1013.
