### ISSUE TITLE
Can't update to the latest version via brew.

### ISSUE THREAD

**Issue by jonasecandersson** [realm/SwiftLint#2331]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report
I cannot install latest version of swiftlint via Homebrew. It just says:

Warning: swiftlint 0.26.0 is already installed and up-to-date

I want the latest 0.27.0

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.26.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew

**Comment by ornithocoder** [comment]
It's not merged yet, @jonasecandersson https://github.com/Homebrew/homebrew-core/pull/30651

**Comment by marcelofabri** [comment]
Closing this for now.
