### ISSUE TITLE
Support SonarQube issue format

### ISSUE THREAD

**Issue by junkpiano** [realm/SwiftLint#2350]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Proposal

This is a new feature proposal.

Looking at #175 , SwiftLint was integrated by SonarQube plugin.
Now SonarQube 7.2 provides the way to import issues from the 3rd party analyzers.

- https://www.sonarqube.org/sonarqube-7-2/
- https://docs.sonarqube.org/display/SONAR/Generic+Issue+Data

So I added another reporter for SonarQube.
I conducted tests on my personal applications, and found [my patch](https://github.com/junkpiano/SwiftLint/commit/eaff52c38884c729693378292ea68a8ea6f6b87f) works fine and sents collect data.

 It looks like this.

![imageedit_2_9847954649](https://user-images.githubusercontent.com/25413198/43886138-d4055802-9bf5-11e8-865b-687f2b381991.png)

The difference is that the issue has `SwiftLint` tag besides the issue description.
We can continuously check our code violations on SonarQube.

On the other hand, there is a limitation. We cannot use `character` in the JSON we send.
I took a look at SonarQube code, where I got a java exception error.

https://github.com/SonarSource/sonarqube/blob/4bccde70aab57079a0c7b6055528f776fac315fe/sonar-scanner-engine/src/main/java/org/sonar/scanner/externalissue/ExternalIssueImporter.java#L120

If startColumn(= `character` in SwiftLint) is specified, it throws null pointer exception, since SwiftLint `StyleViolation` doesn't have endColumn, and endLine. So I skipped `startColumn` intentionally to avoid the exception.

That said, it's appreciated if you consider adding this feature to SwiftLint.

My code is https://github.com/junkpiano/SwiftLint/commit/eaff52c38884c729693378292ea68a8ea6f6b87f.
If you are OK with it, I can send PR.

**Comment by marcelofabri** [comment]
A PR would be welcome!

**Comment by marcelofabri** [comment]
Implemented on #2352.
