### ISSUE TITLE
`--force-exclude` vs. `included`

### ISSUE THREAD

**Issue by fabb** [realm/SwiftLint#2351]
### Bug Report

`--force-exclude` seems not work together with `included` setting, even if the specified `--path` is inside the included folders.

##### Complete output when running SwiftLint, including the stack trace and command used

My configuration contains:
```
included:
  - path/to
```

```bash
$ swiftlint lint --force-exclude --path path/to/swift/file.swift
Loading configuration from '.swiftlint.yml'
Linting Swift files at paths path/to/swift/file.swift
No lintable files found at paths: 'path/to/swift/file.swift'
```

vs.

```bash
$ swiftlint lint --force-exclude --path path/to/swift/file.swift
Loading configuration from '.swiftlint.yml'
Linting Swift files at paths path/to/swift/file.swift
Linting 'file.swift' (1/1)
[..]
Done linting! Found 30 violations, 0 serious in 1 file.
```

### Environment

* SwiftLint version 0.27.0

**Comment by fabb** [comment]
Not sure if this is related to #2275

**Comment by ikesyo** [comment]
https://github.com/realm/SwiftLint/blob/0c36874ec1b11e35adea835db0a135d3ff63755a/Source/SwiftLintFramework/Extensions/Configuration%2BLintableFiles.swift#L11-L15

This should be

```diff
- let pathsForPath = included.isEmpty ? fileManager.filesToLint(inPath: path, rootDirectory: nil) : []
+ let pathsForPath = included.isEmpty ? fileManager.filesToLint(inPath: path, rootDirectory: nil) : path.isFile ? [path] : []
