### ISSUE TITLE
Autocorrect Cosmetic Rules

### ISSUE THREAD

**Issue by fabb** [realm/SwiftLint#2353]
Autocorrect is awesome (even more so when using File Watchers in AppCode and autocorrect a file on every save). There are some cosmetic (whitespace etc.) rules that would be cool if they got autocorrected as well:

```
closure_parameter_position
control_statement
implicit_getter
let_var_whitespace
modifier_order
multiline_function_chains
multiline_parameters
operator_whitespace
```

**Comment by zkrige** [comment]
Is it possible to make `operator_whitespace` autocorrect?

**Comment by marcelofabri** [comment]
@zkrige feel free to send a PR!

**Comment by zkrige** [comment]
I would gladly but I have no idea what I'm doing in swiftlint
