### ISSUE TITLE
Upgrade Homebrew formula

### ISSUE THREAD

**Issue by vytis** [realm/SwiftLint#236]
At the moment SwiftLint 0.2.0 is the newest available through Homebrew. Would be very nice to be able to use all new rules without manually installing from .pkg. Are there any outstanding issues left that prevents pushing an update?

**Comment by ikesyo** [comment]
0.4.0 is already in homebrew. You should run `brew update` at first.

**Comment by vytis** [comment]
Ooops, my bad. Thanks for a quick reply!
