### ISSUE TITLE
Where to find compiler log path for analyzing?

### ISSUE THREAD

**Issue by niilohlin** [realm/SwiftLint#2398]
When using `swiftlint analyze`, what is the filetype and expected location of the `--compiler-log-path`? I have tried some files in `DerivedData` but I can't get it to work.

**Comment by marcelofabri** [comment]
You can see an example on #2386

```
$ # Ensure derived data for SwiftLint is clean
$ xcodebuild -workspace SwiftLint.xcworkspace -scheme swiftlint > xcodebuild.log
$ echo "included:
  - Source
analyzer_rules:
  - unused_private_declaration" > .swiftlint.yml
$ swift run -c release swiftlint analyze --compiler-log-path xcodebuild.log
```

**Comment by kimdv** [comment]
I also looked for this today. Maybe we could add an example in the readme ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
