### ISSUE TITLE
swiftlint analyze wrongly removes import

### ISSUE THREAD

**Issue by Torsph** [realm/SwiftLint#2408]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When running `swiftlint analyze --autocorrect` it will wrongly remove imports in some cases.

Current issue is in a file called `Spacing.swift`:
```
import UIKit
extension CGFloat {
    public static var normalSpacing: CGFloat = 8
    public static func normalSpacing(multiplier: CGFloat) -> CGFloat {
        return normalSpacing * multiplier
    }
}
```
It will remove the `import UIKit` and we will end up with a project that don't compile.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ xcodebuild clean build -scheme swiftlint-analyze-bug -sdk iphonesimulator12.0 > xcodebuild.log
$ swiftlint analyze --autocorrect --compiler-log-path xcodebuild.log
Loading configuration from '.swiftlint.yml'
Correcting Swift files at paths
Correcting 'ViewController.swift' (1/3)
Correcting 'Spacing.swift' (2/3)
Correcting 'AppDelegate.swift' (3/3)
./swiftlint-analyze-bug/swiftlint-analyze-bug/Spacing.swift:1:1 Corrected Unused Import
Done correcting 3 files!
```

### Environment
macOS Mojave 10.14 (18A389)
Xcode 10.0 Build version 10A255

### Example project
https://github.com/Torsph/swiftlint-analyze-bug

**Comment by esteluk** [comment]
The reason it's being removed is that `import CoreGraphics` is a more appropriate import, but yeah it would be nice if that replacement was handled by the autocomplete.

**Comment by jpsim** [comment]
@esteluk is right. The unused imports rule doesn’t detect imports that are only used for their transitive dependencies.

**Comment by Torsph** [comment]
Thanks for the info guys! Closing since it sort of solved :)

**Comment by biboran** [comment]
How about adding an option to the rule to insert missing imports? So in the example above the correction would remove `import UIKit` and insert `import CoreGraphics`.

**Comment by jpsim** [comment]
> How about adding an option to the rule to insert missing imports? So in the example above the correction would remove `import UIKit` and insert `import CoreGraphics`.

Yup, that would be great. Ideally we'd only add missing imports for files in which we remove unused imports, so that we do the minimum necessary changes to keep the project compiling, without adding a ton of transitive imports to unaffected files.
