### ISSUE TITLE
Generate a report with only errors

### ISSUE THREAD

**Issue by asmabee7** [realm/SwiftLint#2412]
I'm new to swiftlint and the current version I'm using is 0.27.0

I wanted to generate the report which shows only the errors and these errors should be grouped together based on the rule. Is there any way where to do it? 

Currently, the report shows all the warnings and errors based on the file name but I need the grouping based on rule.

**Comment by marcelofabri** [comment]
You could use the json reporter and do some post-processing with another script.

**Comment by jpsim** [comment]
Agreed.
