### ISSUE TITLE
"swiftlint start" to paste '//swiftlint:disable:next ...' before all raising lines

### ISSUE THREAD

**Issue by MortyMerr** [realm/SwiftLint#2414]
Actually, it's not a rule, so i will delete basic template. Sorry for that (
There a lot of situations in my practice where team decides to add swiftlint in project. But there is a very annoying thing - they should comment (`//swiftlint:disable:next ...`) all lines with legacy code, which raise warnings. I'm sure that this can be done automatically to reduce amount of work.
Actually, this can even raise swiftlint popularity, because many developers are not using swiftlint just because huge legacy codebase with a lot of errors, which can't be fixed with `swiftlint autocorrect`.

So, shortly run `swiftlint start` to disable old warnings with auto-pasted comments, but leave all rules working in all files.

P.S Maybe there is a way to do it automatically? Then please show it to me and i will close the issue

**Comment by marcelofabri** [comment]
I don't think this is the best approach to take when integrating SwiftLint to a project: it'll cause a lot of modifications just to please SwiftLint.

It'd be better IMO to use one of these strategies (or both):
1. only lint new/modified files
2. adopt rule by rule 

[This presentation](https://academy.realm.io/posts/slug-jp-simard-swiftlint/) goes into more details on some other approaches as well.
