### ISSUE TITLE
Use max_length with custom rules

### ISSUE THREAD

**Issue by ggirotto** [realm/SwiftLint#2429]
I'm trying to create a custom rule where the number of characters from an error description must be less than 200. I've made a regex to capture all characters between `"` in the error description. Now a just need to limit the number to be less than 200, is it possible? I'm looking for something like this

```
custom_rules:
  error_description_length:
    regex: '(?<=Error\(description: \")(.*)(?=\"\))'
    message: "Error Description length limit is 200 characters"
    max_length:
      error: 200
```

**Comment by marcelofabri** [comment]
This is not supported out of the box, but you could try to incorporate that on the regex instead.

**Comment by ggirotto** [comment]
For those looking for this solution, you can count characters with Regex as described here https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s09.html

**Comment by marcelofabri** [comment]
@ggirotto can we close this?

**Comment by ggirotto** [comment]
Yes, sure.
