### ISSUE TITLE
Multiple rules applied to the same line of code

### ISSUE THREAD

**Issue by morgan-legal** [realm/SwiftLint#2432]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Multiple rules won't apply to the same line of code. 

### Environment

* SwiftLint version: **0.27.0**
* Installation method used: **Homebrew**
* No configuration file, I use the default one.
* Xcode version 10
* This run script is : 
```
if which swiftlint >/dev/null; then
  swiftlint autocorrect
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

### Issue description with example:

Let's say I have a variable like this:
`var test: (()->())?`

What I want is to achieve this style `var test: (() -> Void)?` when building the project. But the issue is that we will apply the first rule that we find to this line and not the second one. Building the project a second time will format the line as wanted.

Result after first build: `var test: (()->Void)?`
Result after second build: `var test: (() -> Void)?`

Is there a way to fix this ? Something that I've missed ?

**Comment by marcelofabri** [comment]
@morgan-legal I wasn't able to reproduce it: the file was autocorrected to `var test: (() -> Void)?` with a single `swiftlint autocorrect` run.

Feel free to reopen if needed.
