### ISSUE TITLE
Add how many rules violations are ignored to finished output

### ISSUE THREAD

**Issue by kimdv** [realm/SwiftLint#2461]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

It would be cool if we somehow could add how my rule violations are ignored. 
This can be used to some statistics in big projects to avoid people just use `//swiftlint:disable` to avoid fixing warnings.

**Comment by marcelofabri** [comment]
While I agree that this could be useful, I'm not sure if just printing at the end would be enough to get people's attention.

**Comment by kimdv** [comment]
I agree on that just a print will not get peoples attention. But I think it could be added to CI so builds are failing if more are added.

**Comment by jpsim** [comment]
This is a situation where SwiftLint's existing machine-parseable reporters can be processed and transformed to do anything you want with that data.

e.g. `swiftlint lint --reporter json | swiftlint-output-formatter.sh`

**Comment by kimdv** [comment]
So it is already possible? 😅👏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jpsim** [comment]
In the sense that SwiftLint provides the information you need to do this externally, yes.
