### ISSUE TITLE
Unused Import rule should allow Foundation imports if @objc is used

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#2464]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Usage of `@objc` requires importing Foundation, unless `-disable-objc-attr-requires-foundation-module` is specified to the Swift frontend. SwiftLint currently treats `import Foundation` as unused even if the file uses `@objc`.

**Comment by marcelofabri** [comment]
@jpsim I think this was fixed by https://github.com/realm/SwiftLint/pull/2492?

**Comment by jpsim** [comment]
Yes!
