### ISSUE TITLE
Line length rule includes comments

### ISSUE THREAD

**Issue by mpurland** [realm/SwiftLint#248]
Is this intended? 
![screen shot 2015-12-03 at 3 23 00 pm](https://cloud.githubusercontent.com/assets/113033/11577352/f365343e-99d1-11e5-9f90-e494f5f7bab7.png)

**Comment by segiddins** [comment]
Yes, this is the intended behavior

**Comment by mpurland** [comment]
Okay, another example of SwiftLint failure on Xcode template projects. :+1:
