### ISSUE TITLE
Error: SwiftLint takes too long to process file

### ISSUE THREAD

**Issue by jgarciatt** [realm/SwiftLint#2483]
I'm using AppCode and the SwiftLint plugin, and since a couple of weeks ago I started to get _**Error: SwiftLint takes too long to process file**_ every time I edit a file. I had to disable the plugin in order to be able to work, because it reached a point where the cursor was delayed to show the error in the event log. This happens with every class, no matter the size, even a file of 20 lines of code cause the error. Any idea how to solve it?

This is my AppCode and plugin version:

AppCode 2018.2.5
Build #OC-182.5107.23, built on November 13, 2018
JRE: 1.8.0_152-release-1248-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
SwiftLint version 1.10.3

Thanks.

**Comment by jpsim** [comment]
To help you, we'll need more information. Can you share steps to reproduce the performance problem you're seeing? You also didn't post the SwiftLint version you're using. SwiftLint never released a version with the number 1.10.3. The last release is 0.28.2: https://github.com/realm/SwiftLint/releases/tag/0.28.2

To give you a sense of expected SwiftLint performance, a large project with over 100 nested `.swiftlint.yml` files, 91 enabled rules, 41 custom regex rules, 5,000 Swift files and 275,000 lines of Swift code (according to the `cloc` utility) takes 25s for a clean lint and 2.3s for subsequent lints on my laptop.

Linting SwiftLint itself (355 Swift files) takes 2.8s for a clean lint and 130ms for subsequent lints.

**Comment by jgarciatt** [comment]
I refer to the SwiftLint plugin for AppCode, that has a version 1.10.3. I do have the version 0.28.2 version installed.

The problem is not easy to reproduce I guess, if you are familiar with AppCode or JetBrains IDE's, they have an event log in the bottom right part of the window, and there I keep getting this error every time I'm typing or just navigating through the file. And this happens with every file, even if it is short. 

When SwiftLint runs at build time, I get the Linting messages and get warnings with no problems, it looks like it is a problem with the AppCode plugin that runs in the background analyzing the files in real time.

**Comment by jgarciatt** [comment]
I just found the actual repository for the plugin, I guess I will post my issue there. Closing.

Thanks for your help.
