### ISSUE TITLE
Auto generate configuration

### ISSUE THREAD

**Issue by kimdv** [realm/SwiftLint#2498]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

Just like we generate the `Rules.md` it would be awesome if we could do the same with all configurations. as there come more and more configurations to rules.

**Comment by marcelofabri** [comment]
Duplicate of https://github.com/realm/SwiftLint/issues/1653?

**Comment by kimdv** [comment]
Yes, will close!
