### ISSUE TITLE
swiftlint failing on CircleCI

### ISSUE THREAD

**Issue by espeneric** [realm/SwiftLint#2510]
I am pretty new to this tool, though I highly appreciate its value and I would like to say thank you to the community,
This is what I get on my local machine : 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/23578783/49964297-6eec1b80-ff1a-11e8-9eeb-2cc8d284d2c0.png">
I am using CircleCI for CI;
Here is the output :
<img width="816" alt="image" src="https://user-images.githubusercontent.com/23578783/49964336-87f4cc80-ff1a-11e8-855d-7ee3ec19fdab.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/23578783/49964621-4153a200-ff1b-11e8-8a55-18d9956e2597.png">

**Comment by espeneric** [comment]
looks like the CI is checking "more" files. But the configuration file works just fine on local machine. Any ideas why it doesn't on CI?

**Comment by marcelofabri** [comment]
Can you share the commands that are used to run SwiftLint? Are they run from the same working directory?

**Comment by espeneric** [comment]
There are no additional configurations on the CI.
On my local repo on my machine I just run swiftlint (installed via homebrew)

**Comment by espeneric** [comment]
These are some of the files which are "linted" on the CI but not on the local machine?
Any idea "where they come from"?
Thank you,
<img width="776" alt="image" src="https://user-images.githubusercontent.com/23578783/50008168-a22eb900-ffb3-11e8-9c15-8ea202aefecb.png">

**Comment by espeneric** [comment]
any ideas what can be wrong here?

**Comment by espeneric** [comment]
fixed the issue by declaring to run swiftlint only on one folder, the main folder with the sourcecode.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/23578783/50099742-1e790480-021f-11e9-8486-b5e197c42388.png">
