### ISSUE TITLE
Automatic Xcode Compiler Target Deduction

### ISSUE THREAD

**Issue by zx2c4** [realm/SwiftLint#2511]
My project has two targets. Target T1 uses source code from directory D1 and D3. Target T2 uses sources code from directory D2 and D3. I want to `swiftlint` my code on build and have it throw nasty warnings when I write nasty code.

Currently @EricKuck, @roop, and I are doing this with the suggested instructions from README.md: adding a build step that just calls `swiftlint` with the nice `which` wrapper to print a nice error if it's not installed. The problem is that this winds up linting _all_ files of the project, not just the files specific to that project. I realize there's the `--use-script-input-files` option, but this requires listing all the files for that target in two places: once in the list of actual files that need to be compiled, and once in the file list file. Yuck.

It would be much nicer to, instead, pass an option called `--xcode-compiled-files` that uses environment variables to determine the path to the xcproj and the current target, parses the former in terms of the latter, and then only lints those files. Alternatively, perhaps this could work as a wrapper around `swiftc` itself, so that it's just called individually for each file _as it's being compiled_; this would probably be quicker in the case of incremental compilation.

Are these modes you'd consider adding? Or do you have a different suggested approach to handle what I suspect is probably a fairly common use case?

**Comment by marcelofabri** [comment]
@zx2c4 are the targets in different folders? If so you could either have multiple calls to `swiftlint` using `--path` or have multiple configuration files that only lint one target or another (using `--config`).

Does that solve the issue?

Generally speaking, I don't think SwiftLint should know about targets (or Xcode) to avoid adding too much complexity on the tool for a specific use case.

**Comment by zx2c4** [comment]
Yes, but they also share a common folder together, so not quite.

**Comment by zx2c4** [comment]
@marcelofabri Shouldn't this be tagged with "enhancement" instead of "question"?

**Comment by marcelofabri** [comment]
I think there's a discussion on whether we ever want to support this use case.

In my personal opinion, parsing a `xcodeproj` and dealing with targets is not something that SwiftLint should do.
