### ISSUE TITLE
--path directive causes swiftlint to ignore --strict directive.

### ISSUE THREAD

**Issue by joshareogun** [realm/SwiftLint#2516]
- Swiftlint version 0.29.1 (portable swiftlint)
- Checked open issues.

I'm currently integrating swiftlint into a repo, using the gradual adoption approach, in which we only lint  modified/untracked files.

However, I noticed that specifying the --path causes '--strict' to be ignored. What's more, --lenient works just fine.  Here's a snippet from my build phase script.

`${SWIFT_LINT} lint --strict --path "${filename}" | sed 's/warning:/error:/g'` 

When I build my project using the above, swiftlint successfully lints the file, but doesn't fail as '--strict' is supposed to.  I get the following message instead: 

> Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

Using this: `${SWIFT_LINT} lint --lenient --path "${filename}"`  however, successfully downgrades all errors to warnings.

**Comment by NiallBegley** [comment]
I'm seeing this same behavior - are there any workarounds?
