### ISSUE TITLE
Invalid cast when compiling on archilinux. 

### ISSUE THREAD

**Issue by diasbruno** [realm/SwiftLint#2535]
Hi, 

I tried to install `swiftlint` on archlinux (using a arch's package manager and compiling) and I got an error related to an `invalid cast` on [Commandant/Option.swift:214:9](https://github.com/Carthage/Commandant/blob/master/Sources/Commandant/Option.swift#L214) - probably related to its usage.

* Install from the package manager: `swiftlint 0.27.0` 
* Compiling branch: `master`

All the information is in this [gist](https://gist.github.com/diasbruno/60aee1b5eff24f81fbf2fe9df7a664da).

Thanks.

**Comment by diasbruno** [comment]
Apparently, it seems to be a bug somewhere else (swift compiler?).  
It doesn't compile when building a release.

`swift build --c release`

**Comment by marcelofabri** [comment]
This looks like an issue in the compiler when building Commandant on archilinux. I'd suggest opening an issue on https://bugs.swift.org with as many instructions as possible (e.g. a docker image that can be used).

It also seems that archlinux is not an officially supported platform, so you might want to use Ubuntu if possible.

**Comment by diasbruno** [comment]
Good that there are already some issues reported related to this bug on swift's issue tracker.
The project compiles on debug mode and all the tests are passing, so nothing to worry about.

Thanks, @marcelofabri.
