### ISSUE TITLE
enabled_rules option in .swiftlint.yml?

### ISSUE THREAD

**Issue by daniel-beard** [realm/SwiftLint#256]
- It would be helpful to have an `enabled_rules` option in the `.swiftlint.yml` config file that works as a whitelist. 
- I'm using swiftlint as part of a CI process, so by using the `disabled_rules` option, each time I upgrade the swift lint binary, and there have been new rules added, I have to disable more rules (otherwise swiftlint will generate warnings / errors for rules I don't necessarily want).

**Comment by jpsim** [comment]
Thanks for the suggestion!

I think we should add both an `enabled_rules` and a `rules`

* `enabled_rules` would opt into rules that are disabled by default
* `rules` would be a final list of all rules to be used, and specifying a value for this would ignore `enabled_rules` and `disabled_rules`

**Comment by scottrhoyt** [comment]
@jpsim I think it starts to get complicated if we allow blacks lists, black lists with opt in, and white lists. Why not just got with the "either black list or white list" approach, similar to `included` and `excluded`?

**Comment by jpsim** [comment]
You're right @scottrhoyt. Re-reading my comment I don't recall why I though that would be a good idea.

**Comment by jpsim** [comment]
done in #436.
