### ISSUE TITLE
FunctionBodyLengthRule should not count comment lines

### ISSUE THREAD

**Issue by proth** [realm/SwiftLint#258]
lines that start with a "//" after removing all leading whitespaces should not be treated as line inside a function. Otherwise the obvious way to fix violations of that rule would be to write less comments.

**Comment by aamctustwo** [comment]
+1.

It should also ignore headerdoc documentation comments.

**Comment by jpsim** [comment]
I like this idea.

> lines that start with a "//" after removing all leading whitespaces should not be treated as line inside a function. Otherwise the obvious way to fix violations of that rule would be to write less comments.

SwiftLint can actually detect all kinds of comments (`//`, `/* */`, `///`, `/** */`), so really we could just not count lines that only have comment-like tokens.

**Comment by kevindelord** [comment]
+1 

Looks even better with all kind of comments: `//`, `/* */`, `///`, `/** */`

**Comment by scottrhoyt** [comment]
+1 here. I've already adapted some of my commenting style to avoid this.
