### ISSUE TITLE
Rule Request: Enforce bundle parameter to NSLocalizedString

### ISSUE THREAD

**Issue by lilyball** [realm/SwiftLint#2595]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

When writing frameworks that have localized strings, it's really easy to forget the `bundle:` parameter to `NSLocalizedString`. Unfortunately this isn't something that can be solved in code; adding my own override of `NSLocalizedString` for the bundle-less case trips up `genstrings`, and adding a custom function with a different name isn't compatible with `xcodebuild -exportLocalizations`.

The goal of the rule here is to catch all calls to `NSLocalizedString` and enforce that the `bundle:` parameter is present. It doesn't matter what the value is, it should just be specified.

This would be opt-in. I don't think there's any configuration for it.

**Comment by marcelofabri** [comment]
This seems a great candidate for a first contribution! 💯
