### ISSUE TITLE
If $PODS_ROOT (folder project name contain space) ${PODS_ROOT}/SwiftLint/swiftlint lint command failed with path not found error

### ISSUE THREAD

**Issue by agolovatuk** [realm/SwiftLint#2618]
We have SwiftLint 0.29.1
We are using swiftlint installed with pods
Xcode version 10.1

Till I have file project folder with name fluix-ios everything was fine.
But if rename folder project to 'fluix ios' 
command in script section:
${PODS_ROOT}/SwiftLint/swiftlint lint --strict

Steps to reproduce: 
- rename project folder to name which contain space
- build it from xcode

 Build failed with error:
Script-7C245E4821BFC25D00DBEA5A.sh: line 2: /Users/anngolovatuk/code/fluix: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by agolovatuk** [comment]
Ok, It seems this is not real swiftlint issue, but this is issue of the way you guys provide a command with is not working for pod path with space.

Here is a command fo script phase which is works:
POD_ROOT_ESCAPED=$(printf %q "$PODS_ROOT")
eval ${POD_ROOT_ESCAPED}/SwiftLint/swiftlint lint --strict

**Comment by WayneEld** [comment]
If it helps anyone in the documentation it states "Alternatively, if you've installed SwiftLint via CocoaPods the script should look like this:"
`"${PODS_ROOT}/SwiftLint/swiftlint"`

The quotation marks helped me in this case.
