### ISSUE TITLE
Exit with Code 0 in Case No Files Left to Lint because of Excluded Config

### ISSUE THREAD

**Issue by fabb** [realm/SwiftLint#2619]
When I provide `--use-script-input-files` and `--force-exclude`, and all of my input files are filtered away by my `excluded` config, then swiftlint exits with error code 1:
```
No lintable files found at paths: ''
```
It would be helpful if swiftlint would exit with error code 0 in that case, since we always run swiftlint on modified files in our pre-commit hook, and a nonzero exit code prevents commits.

**Comment by jpsim** [comment]
Can you chime in on #2608 as well, which is related.

**Comment by fabb** [comment]
As said in #2608, I would be happy if there just was a separate exit code for the „no files“ case. Then I can treat this as success in my pre-commit script, without silencing other errors that might lesd to exit code 1.

**Comment by lilyball** [comment]
I just hit this issue. It looks like an opt-in config parameter `allow_zero_lintable_files` was added in #2732, which solves my problem, but I'm really surprised this is opt-in.
