### ISSUE TITLE
Add more configuration options to OpeningBraceRule 

### ISSUE THREAD

**Issue by VojtaStavik** [realm/SwiftLint#2635]
`OpeningBraceRule` currently excludes the cases where `if` `guard` and `while` statements are spread over multiple lines. Example:

```swift
if let x = someX { // This is OK
}

if let x = someX 
{ // This violates the rule
}

if 
   let x = someX,
   let y = someY
{ // This is also OK because multiline `if` is excluded
}
```
**I think it would be worth it to make the excluded keywords configurable.**

In my case, for example, I'd like to exclude multiline `func` from this rule, too, and there's currently no way to do that, without modifying the source code.

 The default configuration will be the same as the current hardcoded one, so the behavior of the rule won't change.

I'm OK with implementing this change myself. I just want to test the waters and see whether the community would be OK with this change.

**Comment by marcelofabri** [comment]
This has been requested a few times in different ways, so I'm sure it'd be a welcome contribution!
