### ISSUE TITLE
swiftlint_version is always enforced

### ISSUE THREAD

**Issue by c0diq** [realm/SwiftLint#2649]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New feature request

Today, if one specifies the `swiflint_version` in a config file, swiftlint will error with an exit code if the version found is below that minimum version. However in some instances, it would be better to just skip linting and fail with (0). A lot of third party dependencies are using swiftlint in a build phase. If for some reasons, a user has an outdated version, this could cause false positives during linting and fail to build the 3rd party altogether. Forcing consumers of given 3rd party to update their swiftlint version may not be possible if incompatible with other 3rd party libraries.

The solution would be to allow passing an option to swiftlint command line to wether enforce or not the swiftlint_version check like `--skip-lint-version-mismatch` similar to the `--strict` option. This option would be used by 3rd party library owner in their CI environment using an environment variable maybe or other means. The default should be to skip linting if the option is not passed and the version is outdated.

Thoughts?

**Comment by jpsim** [comment]
> However in some instances, it would be better to just skip linting and fail with (0). A lot of third party dependencies are using swiftlint in a build phase

Regardless of whether or not more version control flexibility ends up being built into SwiftLint itself, you can do this fairly easily by checking SwiftLint's version in your build phase and taking the appropriate action based on the semantics you want.

**Comment by c0diq** [comment]
I understand I could totally do that but in this case why add `swiflint_version` at all to swiftlint.
