### ISSUE TITLE
[Rule Request] Prefer reduce(into:_:) over reduce(_:_:)

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#2658]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this.

[The docs](https://developer.apple.com/documentation/swift/array/3126956-reduce) say:

> This method is preferred over reduce(_:_:) for efficiency when the result is a copy-on-write type, for example an Array or a Dictionary.

2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

See https://github.com/realm/SwiftLint/pull/2657 for some examples.

3. Should the rule be configurable, if so what parameters should be configurable?

Just severity

4. Should the rule be opt-in or enabled by default? Why?
   See [README.md](../README.md#opt-in-rules) for guidelines on when to mark a rule as opt-in.

Enabled by default if we can avoid false positives

**Comment by jpsim** [comment]
> Enabled by default if we can avoid false positives

I’d love to see a rule like this but I don’t know if I’d enable it by default. If the code isn’t performance critical, there are times when the legibility of the other reduce function makes it worth using it.
