### ISSUE TITLE
Should ignore rule for parameters descriptions 

### ISSUE THREAD

**Issue by techmehra** [realm/SwiftLint#2668]
On Lastest Version:- 
[](url)
<img width="1377" alt="screenshot 2019-03-06 at 10 16 32 am" src="https://user-images.githubusercontent.com/18284379/53856723-3b8cca80-3ff9-11e9-816e-e86302ebfe47.png">

**Comment by marcelofabri** [comment]
You can use the `ignores_comments` configuration on `line_length` rule to achieve this.

**Comment by jpsim** [comment]
@marcelofabri is right, there's a configuration option for exactly this.
