### ISSUE TITLE
It's unknown if "fallthrough" can be used for its intended purpose

### ISSUE THREAD

**Issue by CTMacUser** [realm/SwiftLint#2674]
Looking at the [rules](https://github.com/realm/SwiftLint/blob/master/Rules.md), specifically the (non-)triggering examples for `fallthrough`, it's not clear if:

    switch myInt {
    case 2:
        myResult += 1
        fallthrough
    case 1:
        myResult += 1
    default:
        return 0
    }

is a non-triggering case or not.  (It shouldn't be.  And I need to file a new issue if it is, unless issue [#2194](https://github.com/realm/SwiftLint/pull/2194) already covered it.)

**Comment by marcelofabri** [comment]
`fallthrough` is now optional and completely forbids `fallthrough`. You may want to look at `fallthrough_only` which validates the behavior you want.

**Comment by CTMacUser** [comment]
> fallthrough is now optional and completely forbids fallthrough. You may want to look at fallthrough_only which validates the behavior you want.

I was about to respond that I read more of the file and saw the "No Fallthrough Only" rule.  Sorry.
