### ISSUE TITLE
Project doesn't work with Xcode 10.2 for contributors

### ISSUE THREAD

**Issue by Dschee** [realm/SwiftLint#2693]
I just tried to rebase my PR https://github.com/realm/SwiftLint/pull/2296 onto the current master, but couldn't run the tests in order to update the Rules.md after rebasing using Xcode 10.2.

So I guessed that it's due to the dependencies not yet being Swift 5 compatible and ran ` carthage update --platform macos --cache-builds` but that failed to build SourceKitten, which has a `swift-5.0` branch soon to be merged, but seems not yet ready to be merged.

We should update the project to work with Xcode 10.2 shortly to allow contributors to use Xcode 10.2 and Swift 5. As a next step we could evalutate what new features of Swift 5 could be useful for SwiftLint (e.g. I suppose making use of [SE-200](https://github.com/apple/swift-evolution/blob/master/proposals/0200-raw-string-escaping.md) would make sense).

**Comment by marcelofabri** [comment]
>  As a next step we could evalutate what new features of Swift 5 could be useful for SwiftLint

We usually support building with the previous version of Swift for a while.

**Comment by Dschee** [comment]
Makes sense. Does "while" mean something like "3 months" or more like "a year"? :)

In any case, we could still start elaborating what both the code simplification and performance improvements could be using Swift 5. I might look into this sometime later this month unless someone else has time earlier.

**Comment by marcelofabri** [comment]
> Makes sense. Does "while" mean something like "3 months" or more like "a year"? :)

I think it depends on how hard would it be to support both and what we'd be missing. Historically, I think it's closer to "a year" than "3 months", but also because it's been ok-ish to support the previous Swift version with `#if`s and friends.

**Comment by jpsim** [comment]
For reference, we supported Swift 4.0/4.1 for just over two months after [4.2 was released](https://swift.org/blog/swift-4-2-released/) and the [first SwiftLint release requiring 4.2 to build](https://github.com/realm/SwiftLint/releases/tag/0.29.0). However, that was probably the fastest we did that in SwiftLint's history.

Also note that we've historically had proper support for new Swift versions within 1-2 weeks of the language's official release date (closer to 3 I think this time around). AND that we still supporting _running_ SwiftLint on codebases as far back as Swift 3.0 even today (although it seems pretty safe to drop Swift 3 now if we want).

As you mentioned, there are PRs in flight for properly supporting Swift 5 for all our dependencies

* Yams (released): https://github.com/jpsim/Yams/releases/tag/2.0.0
* CryptoSwift (released): https://github.com/krzyzanowskim/CryptoSwift/releases/tag/1.0.0
* SwiftyTextTable (released): https://github.com/scottrhoyt/SwiftyTextTable/releases/tag/0.9.0
* SourceKitten (PR): https://github.com/jpsim/SourceKitten/pull/581
* Commandant (PR): https://github.com/Carthage/Commandant/pull/148

I suspect the SourceKitten and Commandant releases will come in the next 2-4 days.

**Comment by marcelofabri** [comment]
This should be fixed.
