### ISSUE TITLE
Xcode file saving inserts trailing whitespaces everywhere

### ISSUE THREAD

**Issue by ivanbruel** [realm/SwiftLint#271]
Xcode seems to be going crazy and inserts whitespaces everywhere just after saving any file.
Auto indent seems to fix it, but right after saving, all the whispaces come back.
Any idea on how to work around this?
Really wish I didn't have to add `trailing_whitespace` to the ignore list of the `.swiftlint.yml` file.

![Image](http://i.imgur.com/B6hbFEu.png)

**Comment by neilpa** [comment]
<img width="753" alt="screen shot 2015-12-16 at 10 34 44 am" src="https://cloud.githubusercontent.com/assets/42419/11850228/e187fc42-a3e0-11e5-85fe-b9533518c851.png">

**Comment by ivanbruel** [comment]
I already had it on, wonder if something is acting up. I didn't have this problem before today.

![screen shot 2015-12-16 at 18 43 53](https://cloud.githubusercontent.com/assets/4968178/11850408/00a97d28-a425-11e5-85e6-ef26b1532bbd.png)

**Comment by pqnet** [comment]
Auto indent (ctrl + i) introduces trailing whitespaces in lines, and "automatically trim trailing whitespaces" do not trigger on auto indent. You have to select all content in your file, cut and paste it again before saving to trigger an "edit"
