### ISSUE TITLE
Error while adding SwiftLint as a Swift Package in Xcode 11 beta.

### ISSUE THREAD

**Issue by PhilippeRiegert** [realm/SwiftLint#2781]
### Description 

When adding SwiftLint to an Xcode project as a Swift Package with the url,
this error occur: `The package dependency graph can not be resolved`

### Screenshot

<img width="730" alt="Screen Shot 2019-06-05 at 3 15 20 PM" src="https://user-images.githubusercontent.com/1270537/58994315-ecdfff80-87a4-11e9-9353-9f36e41a730a.png">

### Environment

Xcode 11.0 beta (11M336w)

**Comment by norio-nomura** [comment]
It can not be reproduced on my Mac.

**Comment by PhilippeRiegert** [comment]
@norio-nomura are you able to add SwiftLint ?

**Comment by norio-nomura** [comment]
Yes, I can add SwiftLint as Swift Package Manager Dependency.
<img width="1114" alt="スクリーンショット 2019-06-07 9 56 19" src="https://user-images.githubusercontent.com/33430/59075258-a3a9c000-890a-11e9-97b7-c59dbbac4974.png">

Could you please check if other packages depend on the package SwiftLint depends on and if the conditions are different from SwiftLint?

**Comment by PhilippeRiegert** [comment]
It's now working ! Thanks !

**Comment by AdityaJha94** [comment]
How to exclude Swift package manager from linting?
