### ISSUE TITLE
Xcode 11 build time optimization: Emit dependency file during run script phase 

### ISSUE THREAD

**Issue by rounak** [realm/SwiftLint#2783]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New enhancement request

I was looking through [Xcode 11's release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_release_notes), and came across this under the build section:

> Run script phases and custom build rules may declare and emit a dependencies file, in the Makefile-style .d format output used by some compilers and build tools. The build system checks the files listed for changes during subsequent builds when determining if the rule or phase should be executed. (49226986)

Xcode + SwiftLint integration is done through a run script phase, and it seems like this integration could benefit from this optimization opportunity. I think SwiftLint already does some caching under the hood, so in the ideal case, it emits a representation of that cache in a ".d" output to avoid running SwiftLint again for an unchanged project.

Caveat: I'm not intimately familiar with the inner workings of SwiftLint, so I apologize if this integration is not practical. Thanks to all the contributors for their hard work on making SwiftLint such a useful tool!

**Comment by jpsim** [comment]
Yeah we should be able to make use of this. Do you know how to actually emit this dependencies file? It's just a blank text field

![image](https://user-images.githubusercontent.com/474794/59870309-22aae980-934a-11e9-9074-e66d05af8b99.png)
