### ISSUE TITLE
running 'swiftlint rules' overruns the terminal width

### ISSUE THREAD

**Issue by Fudge0952** [realm/SwiftLint#2787]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When running `swiftlint rules`, I expect it to use the width of the terminal correctly. What is happening is that it appears to be thinking the terminal is 11 characters wider (in iTerm at least). I've attached a screenshot showing the output before any resizing.

![image](https://user-images.githubusercontent.com/3098078/60068585-c0d7ee80-9752-11e9-851a-28abe1f5504b.png)

Tested and got the same output from Apple Terminal as well.

##### Complete output when running SwiftLint, including the stack trace and command used

n/a

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? **0.33.0**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **brew**
* Paste your configuration file:

```yml
opt_in_rules: # some rules are only opt-in
  - conditional_returns_on_newline
  - empty_count
  - force_unwrapping
  - missing_docs
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline

disabled_rules: # rule identifiers to exclude from running
  - multiple_closures_with_trailing_closure
  - statement_position
  - trailing_whitespace
  - unused_closure_parameter

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage

file_length:
  warning: 750
  error: 1000
  ignore_comment_only_lines: true
force_cast:
  severity: warning
force_try:
  severity: warning
force_unwrapping: error
function_body_length:
  warning: 80
  error: 150
line_length: 150
missing_docs:
  warning: open
nesting:
  type_level:
    warning: 2
trailing_comma:
  mandatory_comma: true
weak_delegate: error

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? **no**
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)? `/Applications/Xcode.app/Contents/Developer` - **Version 10.2.1 (10E1001)**

**Comment by idrougge** [comment]
In my case, the output is 54 columns wider (134 columns) than my terminal (80x24).

**Comment by idrougge** [comment]
On a related note, the `configuration` column is nevertheless truncated.
