### ISSUE TITLE
Codecov not updating

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#2800]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

We've used to have test coverage data in Codecov: https://codecov.io/github/realm/SwiftLint?branch=master (it's still linked in README).

However, it stopped working ~7 months ago. Do we believe there's value in it? If so, we should look into reviving it. Alternatively, we should just remove it from the README.

**Comment by jpsim** [comment]
Meh, I'm not sold on its value beyond reminding contributors that tests matter, but I don't know why it suddenly stopped working and I'd be fine if we just reenabled it too.
