### ISSUE TITLE
syntactic_sugar: Don't trigger on calls to initializers

### ISSUE THREAD

**Issue by lilyball** [realm/SwiftLint#2804]
### New Issue Checklist

- [ ] Updated SwiftLint to the latest version (I'm one release behind but the changelog doesn't list anything relevant)
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The `syntactic_sugar` rule tells me to use e.g. `[Int]` instead of `Array<Int>`. I want a way to turn this off for calls to initializers. `[Int]()` looks really weird to my eyes and I refuse to write code like that.

I'd argue that this should never trigger on initializers, but I know some people will feel differently, so this at least should have a config flag.

**Comment by marcelofabri** [comment]
A PR adding this as an option is welcome!

**Comment by jpsim** [comment]
This could very well be the default behavior 👌
