### ISSUE TITLE
file_types_order: Correct order of type feels kind of unnatural

### ISSUE THREAD

**Issue by olvrlrnz** [realm/SwiftLint#2813]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When I declare the types as shown in the triggering example below the linter complains about the type order. Fixing it is easy, but forces me to declare conformance to a protocol before declaring the actual protocol which compiles, but doesn't seem like it's the answer to what the rules tries to achieve.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
swiftlint lint --enable-all-rules --no-cache --path CustomViewController.swift
Linting Swift files at paths CustomViewController.swift
Linting 'CustomViewController.swift' (1/1)
/tmp/CustomViewController.swift:8:8: warning: File Types Order Violation: A 'main_type' should not be placed amongst the file type(s) 'supporting_type'. (file_types_order)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint version: 0.33.1
* Installation method used: Homebrew
* Paste your configuration file: none
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
* Which Xcode version are you using? Xcode 11.0 Build version 11M337n
* Do you have a sample that shows the issue?

### Triggering Example
```swift
// swiftlint:disable missing_docs required_deinit

import Foundation

public protocol CustomViewControllerDelegate: AnyObject {
}

public protocol CustomViewController { // L8
    var delegate: CustomViewControllerDelegate? { get set }
}

public class MyCustomViewController: CustomViewController {
    public weak var delegate: CustomViewControllerDelegate?
}
```

### Non Triggering Example
```swift
// swiftlint:disable missing_docs required_deinit

import Foundation

public protocol CustomViewControllerDelegate: AnyObject {
}

public class MyCustomViewController: CustomViewController {
    public weak var delegate: CustomViewControllerDelegate?
}

public protocol CustomViewController {
    var delegate: CustomViewControllerDelegate? { get set }
}
```

**Comment by Jeehut** [comment]
@olvrlrnz Your file is named `CustomViewController.swift` so this rules is treating the type `CustomViewController` (which is a protocol) as the main type within this file, which makes sense. I think the correct solution is not to change the order of the types, instead you should change the name of your file to match your main type: `MyCustomViewController.swift`. Then, the rule should work as expected.

Also mentioning the likers @nderkach & @idrougge for getting informed.

I hope, this helps.
