### ISSUE TITLE
Disabled opt-in rule warning violates json contract

### ISSUE THREAD

**Issue by rounak** [realm/SwiftLint#2817]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Using the json reporter when linting prints output that's not json.

command: `./Pods/SwiftLint/swiftlint lint --reporter json --quiet`

output:
```
Found a configuration for 'modifier_order' rule, but it is disabled on 'disabled_rules'.
[
    {
````

The warning introduced with #1350 breaks the output from following the standard json schema.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ ./Pods/SwiftLint/swiftlint lint --reporter json --quiet
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.33.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Cocoapods
* Which Xcode version are you using (check `xcode-select -p`)? 10.1.0

**Comment by marcelofabri** [comment]
That message should be printed to `stderr`, while the json should be printed to `stdout`.

**Comment by rounak** [comment]
Thank you!
