### ISSUE TITLE
`dyld: Library not loaded: @rpath/libswiftCore.dylib` Error

### ISSUE THREAD

**Issue by eggnima** [realm/SwiftLint#2837]
### New Issue Checklist

- [Yes] Updated SwiftLint to the latest version
- [Yes] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? <- 0.34.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? <- Portable
* Paste your configuration file: N/A

```yml
N/A
```

### Describe the bug

Hi all, I'm currently trying to use Swiftlint in a Swift 5 project, compiled with Xcode 10.2. Due to security constraints, I'm limited to using the portable version of SwiftLint downloaded directly from GitHub, and subsequently transferred securely to my development environment.

However, after adding in the run script phase in my Xcode project, project builds error out with a message `Command PhaseScriptExecution failed with a nonzero exit code`.

Attempting to manually run `swiftlint` from the command line results in a similar error message received when building in Xcode:

```bash
$ ./swiftlint lint
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: <project dir>/ ./swiftlint
  Reason: image not found
Abort trap: 6
```

**Comment by nhatkhang169** [comment]
I'm facing the same issue. 
0.32.0 works fine:
`./Pods/SwiftLint/swiftlint version
0.32.0
`
but 0.33.0, or 0.34.0
`./Pods/SwiftLint/swiftlint version
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/azun/Documents/0iOS/release/sardine/./Pods/SwiftLint/swiftlint
  Reason: image not found
Abort trap: 6
`

**Comment by nhatkhang169** [comment]
This issue is a `selective` issue. My other co-workers are NOT facing it with 0.34.0

**Comment by marcelofabri** [comment]
The solution is on README: https://github.com/realm/SwiftLint#known-installation-issues-on-macos-before-10144

**Comment by ciorceri** [comment]
I confirm that for MacOS 10.14.3 the marcelofabri solution worked ! Thanks.
