### ISSUE TITLE
redundant_type_annotation conflicts with valid_ibinspectable

### ISSUE THREAD

**Issue by weakfl** [realm/SwiftLint#2842]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Triggers rule `valid_ibinspectable`:

```swift
@IBInspectable var fooColor = UIColor.white
```

Adding the type triggers `redundant_type_annotation `:

```swift
@IBInspectable var fooColor: UIColor = UIColor.white
```

### Environment

* SwiftLint version: `0.34.0`
* Installation method used: Homebrew

**Comment by marcelofabri** [comment]
You can workaround this by using:

```swift
@IBInspectable var fooColor: UIColor = .white
```
