### ISSUE TITLE
Custom rule only matches once

### ISSUE THREAD

**Issue by danmartyn** [realm/SwiftLint#2863]
### New Issue Checklist

- [✓] Updated SwiftLint to the latest version -> Running version 0.35.0
- [✓] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I've created a custom rule looking for any occurrences of UIColor initializers to treat as an error. I want developers to use colors from our design system instead. However, when I run SwiftLint, it will only find the first match in a file.

<img width="829" alt="Screen Shot 2019-09-04 at 3 02 02 PM" src="https://user-images.githubusercontent.com/1069611/64283230-03713080-cf25-11e9-9e59-f4c7a0873931.png">

### Environment

* SwiftLint version 0.35.0
* Installation method used Homebrew
* Paste your configuration file:

```yml
#
# This is a configuration file for Swiftlint. See documentation here: https://github.com/realm/SwiftLint#configuration
#


excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Tests

line_length: # A rule for the max number of characters on a line.
    warning: 180
    error: 200

type_body_length: # A rule for the max number of lines in a class body.
    warning: 500
    error: 600

file_length: # A rule for the max number of lines in a file.
    warning: 800
    error: 1200

type_name: # A rule for the max / min number of characters in a type name.
    max_length:
        warning: 60
        error: 80

function_parameter_count: # A rule for the max number of parameters in a function.
    warning: 6
    error: 12

identifier_name:
    excluded: # We don't want warnings/errors for identifiers with the following names.
        - id
        - URL
        - x
        - y

custom_rules:
    no_ui_colors:
        excluded: ".*Colors.swift" # Ignore this rule in the Colors.swift file
        name: "Don't use Standard UIColors"
        regex: '[.]\b(systemBlue|systemGreen|systemIndigo|systemOrange|systemPink|systemPurple|systemRed|systemTeal|systemYellow|systemGray|systemGray2|systemGray3|systemGray4|systemGray5|systemGray6|clear|black|blue|brown|cyan|darkGray|gray|green|lightGray|magenta|orange|purple|red|white|yellow)\b'
        message: "Only use the colors from the Design System"
        severity: error

    no_color_initializers:
        excluded: ".*Colors.swift"
        name: "Don't use color initializers"
        regex: '\sUIColor\(.*\)'
        message: "Only use the colors from the Design System"
        severity: error
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? NO
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)? Xcode 11 beta 7

```swift
let col1 = UIColor(named: "") // This triggers a violation
let col2 = UIColor(red: 1, green: 1, blue: 1) // This should trigger a violation but doesn't.
```

**Comment by acecilia** [comment]
Based on my experience, I think `.*` is matching all the text on the file after the `UIColor(`. I am not sure why, but seems to me `.` matches any character *including new lines*.

So what you see here is that `\sUIColor\(` matches `UIColor(`, and `.*\)` is matching
```
named: "") // This triggers a violation
let col2 = UIColor(red: 1, green: 1, blue: 1) // This should trigger a violation but doesn't.
...
// It will match all code until the last closing parenthesis  of the file
```

And because the rule only shows on the first line, then you only get one violation.

Can somebody "officially" explain what is going on when using `.` in the regex of custom rules?

Meanwhile, you can use the following regex: `UIColor\(.*?\)`
Or better: `UIColor\(`

**Comment by danmartyn** [comment]
Awesome, thanks for the help @acecilia! That new regex did indeed work.
