### ISSUE TITLE
What is the behaviour of a period character when inside a regex of a custom rule?

### ISSUE THREAD

**Issue by acecilia** [realm/SwiftLint#2864]
Hello:

Based on https://github.com/realm/SwiftLint/issues/2863#issuecomment-528266958, I opened this issue in order to try to understand what is going on in swiftlint when using a period inside a regex of a custom rule.

Lets take for example the following regex:
```
.+
```

Such regex applied to the following text results in 5 matches, one per line of text (see: https://regexr.com/4keuq)
```
struct SomeStruct {
    let property1: String

    let property2: String
    let property3: String
}
```

In swiftlint, when placing that regex on a custom rule:
```
  a_rule:
    regex: '.+'
    message: "Violation"
```

It only raises one violation in the first line of the file.

So hence the question, can somebody shine some light upon the behaviour of the period character when inside a regex of a custom rule?

Thanks!

**Comment by iressler** [comment]
I am looking at how custom rules implement regex and it looks like they eventually end up creating a NSRegularExpression using the regex function in [SwiftLintFile+Regex.swift](https://github.com/realm/SwiftLint/blob/075312af6e8b2ac527a02a725a51e55f65816a0f/Source/SwiftLintFramework/Extensions/SwiftLintFile%2BRegex.swift#L9) without any options. This means the default options are used, including the `.dotMatchesLineSeparators` option which I think explains the behavior you are seeing.

**Comment by iressler** [comment]
Also for anyone who is curious if you want to change the behavior you can actually use the flags specified by the [NSRegularExpression docs](https://developer.apple.com/documentation/foundation/nsregularexpression) (search for "Flag settings") in your regex.

For example to make the regex in https://github.com/realm/SwiftLint/issues/2863# work it could be changed from `'\sUIColor\(.*\)'` to `'(?-s)\sUIColor\(.*\)'` or `'(?-s:\sUIColor\(.*\))'` (not that I'm suggesting it's a good solution in this case).

**Comment by acecilia** [comment]
Thanks @iressler, good to know :)
