### ISSUE TITLE
Detect triple slashes (`///`) in `mark` rule

### ISSUE THREAD

**Issue by nvanfleet** [realm/SwiftLint#2866]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Using `/// MARK:` doesn't integrate with Xcode by creating a section in the code. You have to use `// MARK:` with `//` instead of `///`. 

I propose there be a lint to make sure all comment marks follow that format.

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this.

This is otherwise a silent issue where the mark is not used to create a sections in the file.

2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

What would trigger a violation: anytime you have `/// MARK:`

3. Should the rule be configurable, if so what parameters should be configurable?

Not really. 

4. Should the rule be opt-in or enabled by default? Why?
   See [README.md](../README.md#opt-in-rules) for guidelines on when to mark a rule as opt-in.

enabled by default
I expect that engineers expect it to work when they do `/// MARK` but don't check to see if it did. I don't see a use case where their guidelines could be to use `///`

**Comment by jpsim** [comment]
Fixed in #2868.
