### ISSUE TITLE
Xcode 11 install via SPM won't compile because of SourceKitten

### ISSUE THREAD

**Issue by RamblinWreck77** [realm/SwiftLint#2867]
Installing SwiftLint via SPM installs dependencies that prevent the project from compiling. 

SourceKitten doesn't seem to consider this their problem:

https://github.com/jpsim/SourceKitten/issues/612

Any proposed solution?

Also, since I'm trying to move from Cocoapods > SPM, I'm running into another issue:

In cocoapods you could do:

```
pod 'SwiftLint', :configurations => ['Debug']
```

And SwiftLint wouldn't get included in your release builds. Is this possible with SPM?

**Comment by crsantos** [comment]
But does bumping to jpsim/SourceKitten#612 's `0.26` fixes this?

**Comment by MaxHaertwig** [comment]
No, still two issues:
<img width="269" alt="Screen Shot 2019-10-08 at 14 19 15" src="https://user-images.githubusercontent.com/9899051/66395037-c80bcb00-e9d6-11e9-9001-8944f66d7600.png">

**Comment by marcelofabri** [comment]
> No, still two issues:
> <img alt="Screen Shot 2019-10-08 at 14 19 15" width="269" src="https://user-images.githubusercontent.com/9899051/66395037-c80bcb00-e9d6-11e9-9001-8944f66d7600.png">

You can't use SwiftLint via SPM on an iOS project like that - see the comment on https://github.com/jpsim/SourceKitten/issues/612#issuecomment-529001750

**Comment by crsantos** [comment]
**Question**: (if someone knows)

Swiftlint used via SPM wasn't even compiling for macOS, but right now, in [`master`](https://github.com/realm/SwiftLint/commit/495407b452e964486027157ca96d7026ec99b733) it compiles perfectly when you add `swiftlint` as an SPM dependency

But we don't have a tag 😬 

When should be the next release?

**Comment by fruitcoder** [comment]
@crsantos after 2h of searching I finally found this issue. It seems that the newest release (0.38.2) still doesn‘t work with SPM. After using `master` Swiftlint finally builds 🎉 thanks for pointing me into the right direction

**Comment by crsantos** [comment]
@fruitcoder Previous tags were working fine, guess it was fine on `0.35.0`+

but if `master` is working and `0.38.2` isn't, was fixed after that tag was created. Same problem as before.

**Comment by szuniverse** [comment]
I tried with the latest master and I got the same errors as here: https://github.com/realm/SwiftLint/issues/2867#issuecomment-539486303
any update? Will it work with the next release?

**Comment by 22Round** [comment]
On version 0.40.0 I am getting same error, any workaround?

**Comment by kongzii** [comment]
Same here, is it working for someone?

**Comment by jpsim** [comment]
Again, SwiftLint can't compile against iOS SDKs. If you're building SwiftLint from source, please target macOS or Linux.

**Comment by MarioCode** [comment]
XCode 12.0, same error, master branch... hoped to switch completely to SPM
Haven't solved this problem in a year? return to cocoapods?

**Comment by jpsim** [comment]
Please open a new issue with clear and complete steps to reproduce. SwiftLint can only be built on macOS or Linux.
