### ISSUE TITLE
Document match_kinds syntax kind list

### ISSUE THREAD

**Issue by jalone87** [realm/SwiftLint#2869]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

_I would like to request a better description/documentation of the possible values associated with the `match_kinds ` field of custom rules._ 
As of now it is quite hard to understand what some of these values match with and in which way. 

For example i could not find a value that could match object literals (eg: `#imageLiteral(...)`, `#colorLiteral(...)`, etc) , ending up having to rely solely on the regex field (which, i guess, is not as performant as a filter).
In some other cases there were more than one value matching with the desired case, but i could not understand which one was better/more restrictive.

To be sure we are on the same page these are the values i am talking about:

```
argument
attribute.builtin
attribute.id
buildconfig.id
buildconfig.keyword
comment
comment.mark
comment.url
doccomment
doccomment.field
identifier
keyword
number
objectliteral
parameter
placeholder
string
string_interpolation_anchor
typeidentifier
```
Thank you for your time and attention.

**Comment by marcelofabri** [comment]
You can use [SourceKitten](https://github.com/jpsim/SourceKitten) to explore. For example:

```
$ sourcekitten syntax --file file.swift
[
  {
    "length" : 3,
    "offset" : 0,
    "type" : "source.lang.swift.syntaxtype.keyword"
  },
  {
    "length" : 3,
    "offset" : 4,
    "type" : "source.lang.swift.syntaxtype.identifier"
  },
  {
    "length" : 3,
    "offset" : 10,
    "type" : "source.lang.swift.syntaxtype.identifier"
  },
  {
    "length" : 3,
    "offset" : 14,
    "type" : "source.lang.swift.syntaxtype.identifier"
  },
  {
    "length" : 2,
    "offset" : 20,
    "type" : "source.lang.swift.syntaxtype.identifier"
  },
  {
    "length" : 5,
    "offset" : 23,
    "type" : "source.lang.swift.syntaxtype.identifier"
  },
  {
    "length" : 6,
    "offset" : 31,
    "type" : "source.lang.swift.syntaxtype.identifier"
  }
]
```

**Comment by jalone87** [comment]
Ahh cool thanks!
