### ISSUE TITLE
empty_count: include check for `count < 1`

### ISSUE THREAD

**Issue by gobetti** [realm/SwiftLint#2872]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Modified rule request

Right now the existent `empty_count` rule includes several checks with comparisons to zero (the rule description is `Prefer checking isEmpty over comparing count to zero`) but I found that a less usual `count < 1` has the same meaning as `isEmpty` assuming `count` can't be negative.

**Comment by marcelofabri** [comment]
This is a good issue for a first-time contributor 🚀
