### ISSUE TITLE
run autocorrect with each build

### ISSUE THREAD

**Issue by embassem** [realm/SwiftLint#2886]
I have faced issues with autocorrect -- format  when adding it as a phase script  with Xcode 10, 11  beacuse of the new Build System and Parallel tasks, it some times get intersect with the Compile task and Xcode throws an error `file was modifie during build `
is there a way to run  ` swiftlint autocorrect --format` with each build before the build and no paralleled  with other tasks?

**Comment by vani2** [comment]
What is the order of your build phases, @embassem? Check and try to move swiftlint before compiling sources phase.

**Comment by christiankm** [comment]
@embassem Yes, you should most often place your SwiftLint run phase directly before 'Compile Source Files' step.
Then your build phase could run the command `swiftlint autocorrect && swiftlint`
Otherwise warnings won't show up in the project afterwards.

**Comment by embassem** [comment]
@christiankm 
the issue is that because of the parallel build for some times I got a build error file was modified during the build.

**Comment by jpsim** [comment]
@christiankm and I just pushed some changes to the instructions for integrating SwiftLint into Xcode build phases in 67165f7c, along with some tradeoffs when adding the phase before or after the 'Compile Sources' phase.
