### ISSUE TITLE
`identical_operands` falsely triggered

### ISSUE THREAD

**Issue by 00FA9A** [realm/SwiftLint#2890]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
`identical_operands` is unexpectedly triggered by  `let isLowerCase = name == name.lowercased()`

It's present in https://github.com/realm/SwiftLint/pull/2889

### Environment

* SwiftLint version: **0.29.1**
* Installation method used: **Homebrew**

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? **No**

* Which Xcode version are you using? **10.3**
* Do you have a sample that shows the issue? **See above**

**Comment by PaulTaykalo** [comment]
Please, check, this seems to be fixed in #2918
