### ISSUE TITLE
Ability to mark something as okay?

### ISSUE THREAD

**Issue by soffes** [realm/SwiftLint#29]
In [X](https://github.com/soffes/X), I have the following code:

```swift
extension NSImage {
		public var CGImage: CGImageRef! {
			return CGImageForProposedRect(nil, context: nil, hints: nil)?.takeUnretainedValue()
		}
}
```

This now produces an error because the name starts with a capital letter. I definitely want this to be capital here so it matches iOS (that's the point of this extension). Is there a way to mark this as okay?

**Comment by aarondaub** [comment]
There's an open issue for this #4

**Comment by soffes** [comment]
Cool. Closing dupe.
