### ISSUE TITLE
Unable to excluded sub folder in `excluded: `

### ISSUE THREAD

**Issue by alfredcc** [realm/SwiftLint#290]
I configure the .swiftlint.yml see this below :-1: 

```
included: # paths to include during linting. `--path` is ignored if present.
  - Source
excluded: # paths to ignore during linting.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/EcludedFile.swift
```

But the ` - Source/ExcludedFolder`  and ` - Source/EcludedFile.swift` are still been included
is this a bug or did i miss some steps?

the only approach i can do is :
```
included: # paths to include during linting. `--path` is ignored if present.
  - Source/IncludedFolder1
  - Source/IncludedFolder2
  - Source/IncludedFolder3
excluded: # paths to ignore during linting.
  - Carthage
  - Pods
```

**Comment by scottrhoyt** [comment]
In the current implementation, you either explicitly include files and folders with `included` (implicitly excluding everything else) or you explicitly exclude with `excluded` (implicitly including everything else). Basically you either have a white list or a black list.

In your example, you could accomplish the same task with:

    excluded: # paths to ignore during linting.
      - ExcludedFolder
      - EcludedFile.swift

and either running `swiftlint` from the `Source` directory or running `swiftlint --path Source` from the same directory as before.

Can you give a use case where you would want to both explicitly include and explicitly exclude?

**Comment by alfredcc** [comment]
@scottrhoyt 
My use case is:
First time I `included ` a `IncludedFolder ` (there are many sub folders under it), then I want to `excluded ` one sub folder which under the `IncludedFolder ` , so I put the sub folder in the black list
```
excluded: # paths to ignore during linting.
  - subFolder
``` 
but I find that this sub folder is still be included

**Comment by scottrhoyt** [comment]
I see what you are trying to accomplish. Is it possible for you to run `swiftlint` from the `IncludedFolder` so that you only need an `excluded` parameter in your *.yml? If you are running from the command line you can run directly from the `IncludedFolder` directory. If you are running from Xcode using a shell script, you can add the `--path` option to the script.

**Comment by alfredcc** [comment]
Thans for such quick answer, you are right and I solved it. But some how it means the white list has a higher priority, the`Configuration ` is ambiguous

**Comment by scottrhoyt** [comment]
I'm glad that's working for you @alfredcc , but I've looked into this a bit more, and I was quite wrong. It appears the intention is to honor both `excluded` and `included` by subtracting `excluded` from `included`. Can you share a project that duplicates your problem, and I can work on a fix?

**Comment by alfredcc** [comment]
@scottrhoyt Hi, I've looked into this a bit more too. Finally It's my fault. I got wrong folder hierarchy. Everything works fine now. 
**The conclusion is：We can have both `included` (a white list) and `excluded ` (a black list).**
Thanks for your help :+1:

**Comment by scottrhoyt** [comment]
No problem, and sorry for leading you astray at first.

@jpsim we can close this issue.

**Comment by jpsim** [comment]
Thanks for figuring this out! I've clarified this in the README: de6c9ad

**Comment by AdityaJha94** [comment]
How to exclude Swift package manager from linting?

**Comment by rogerluan** [comment]
@AdityaJha94 add `.build` to the list of excluded directories
