### ISSUE TITLE
Package.resolved should include CryptoSwift

### ISSUE THREAD

**Issue by Fryie** [realm/SwiftLint#2905]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

A build of SwiftLint on Linux with Swift 5.0 was failing because a newer version of `CryptoSwift` is broken. It would IMHO be better to pin the `CryptoSwift` dependency to avoid such issues in the future. This probably doesn't happen because `SwiftLint` developers use a mac and the Package.swift only includes `CryptoSwift` on Linux. I'm not sure if there's a way to do this or if this is a problem with the package manager; maybe it would be enough to simply temporarily set `addCryptoSwift` to `true` in the Package.swift, running `swift package resolve` and committing the changed `Package.resolved`... however, I don't know how this affects platforms that don't require `CryptoSwift`.

**Comment by PaulTaykalo** [comment]
I think it is fixed in #2902

**Comment by marcelofabri** [comment]
We don't want to add it to `Package.resolved` to avoid Mac users having to clone/build `CryptoSwift`. (Unless I'm missing a way to do it without penalizing Mac users)

I think the lesson here is that we should be more strict with dependencies versions.

**Comment by Fryie** [comment]
It's at least been discouraged to use this approach by [SwiftNIO developers](https://forums.swift.org/t/dependency-only-for-linux/28515/3). That said, pinning the specific version at least for CryptoSwift (because it's not in Package.resolved) would probably be fine too.
