### ISSUE TITLE
Todo rule does not match variations in to do grammar

### ISSUE THREAD

**Issue by iliaskarim** [realm/SwiftLint#2909]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

If you enter a to do item as `// todo` or `//to do:` then Swiftlint does not count it because the prefix is lowercase or separated into two words.

**Comment by marcelofabri** [comment]
This is by design as Xcode only recognizes `// TODO: x`

<img width="311" alt="Screen Shot 2019-10-16 at 9 59 00 AM" src="https://user-images.githubusercontent.com/833072/66941372-9ceb3200-effb-11e9-8e89-390f9718bd4f.png">
