### ISSUE TITLE
Rules.md is rendered as raw instead of markdown in Github

### ISSUE THREAD

**Issue by sarunw** [realm/SwiftLint#2930]
https://github.com/realm/SwiftLint/blob/master/Rules.md is rendered as raw instead of markdown in Github.

This make it hard to read and browse through all the rules. Not sure why it isn't rendered as markdown.

**Comment by Drarok** [comment]
I presume there's a size limit on rendered files – at over 26k lines, Rules.md is bound to exceed _some_ limits! 😅

**Comment by CraigSiemens** [comment]
Maybe it would make sense to split it up into multiple files. Have one top level one with name and summary for each rule with a link to another file that contains the details and examples.

**Comment by jpsim** [comment]
Ah this must have exceeded the limit recently. Thanks for bringing this to our attention. We should definitely split this up.

**Comment by jessesquires** [comment]
@jpsim Can we close this issue in favor of #2933? 

There's a discussion at #2933 for how to address this -- with proper GH Pages docs, or something similar.

**Comment by jpsim** [comment]
Sure, let's close in favor of #2933.
