### ISSUE TITLE
Generates markdown documentation only for enabled rules.

### ISSUE THREAD

**Issue by 417-72KI** [realm/SwiftLint#2961]
Current `generate-docs` command makes `Rules.md` for all rules, but the generated file is too large and bothersome to find specific rule.

There are `-e` or `-d` options in `rules` command, which makes enabled to display only enabled / disabled rules on terminal.

I want similar options for `generate-docs` command.

Best regards.

**Comment by marcelofabri** [comment]
Can you elaborate why you're running this command? 

The `generate-docs` command was added mainly for contributors to run - and it's now pretty much redundant as we have a unit test that generates the file instead. I was actually thinking about removing the command completely.

**Comment by 417-72KI** [comment]
@marcelofabri 
I often want to see an overview or an example of a particular SwiftLint rule (especially when setting up a rule), and ideally a Markdown-preview.
When there were few rules, [Rules.md](https://github.com/realm/SwiftLint/blob/master/Rules.md) was useful because it was previewed.
However, it is no longer previewed on GitHub because the file is too heavy now.
Therefore, I thought that if only valid rules could be output to Rules.md, it would be possible to preview them again on GitHub.

Also, since rules settings are different for each OSS, Rules.md is managed for each repository, and if it is visualized, I think that development efficiency will increase.

**Comment by marcelofabri** [comment]
> However, it is no longer previewed on GitHub because the file is too heavy now.
> Therefore, I thought that if only valid rules could be output to Rules.md, it would be possible to preview them again on GitHub.

We're fixing this separately, see https://github.com/realm/SwiftLint/pull/3016

**Comment by 417-72KI** [comment]
That's what I wanted and should be able to solve this problem.

I close this when it will be merged, thank you!

**Comment by jpsim** [comment]
Addressed in #3016.
