### ISSUE TITLE
Compilation errors when running a build

### ISSUE THREAD

**Issue by kkiermasz** [realm/SwiftLint#2972]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I'm getting below errors when running a build
```
../SourceKittenFramework/JSONOutput.swift:28:41: 'sortedKeys' is only available in iOS 11.0 or newer
../SourceKittenFramework/Exec.swift:67:23: Use of unresolved identifier 'Process'
```

##### Complete output when running SwiftLint, including the stack trace and command used

Not needed

### Environment

* SwiftLint version: 0.37.0
* Installation method: Swift Package Manger
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using (check `xcode-select -p`)? version 2370
* Do you have a sample that shows the issue? I have lint installed inside project only

**Comment by marcelofabri** [comment]
You can't compile SwiftLint in an iOS target: https://github.com/realm/SwiftLint/issues/2923#issuecomment-552207442
