### ISSUE TITLE
How to Fix warning about Medium and large style before ios 13.0

### ISSUE THREAD

**Issue by hungwei0331** [realm/SwiftLint#2973]
I have set some activity Indicator view through storyboard,

the xcode appear the warning "Medium/Large style before ios 13.0",

but the style from interface builder just have Medium and large options,

others already deprecated, 

i would like to ask how to fix and made warning disappear,

thanks in advance for comment.

**Comment by marcelofabri** [comment]
This is not a SwiftLint warning, closing it.
