### ISSUE TITLE
Xcode build for profiling is misconfigured

### ISSUE THREAD

**Issue by kastiglione** [realm/SwiftLint#2978]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

1. Open `SwiftLint.xcworkspace`
2. Run Product > Build For > Profiling

The build fails in `Clang+SourceKitten.swift`, on `import SWXMLHash`. The error message is:

> No such module 'SWXMLHash'

### Environment

* SwiftLint version: master (as of cc57ed3d69b99c23126176f4f241d9de3dcaa877)
* Installation method used: building from source
* Paste your configuration file: N/A
* Which Xcode version are you using (check `xcode-select -p`)?

```
% xcodebuild -version
Xcode 11.2.1
Build version 11B500
```

**Comment by jpsim** [comment]
This is an artifact of how dependencies are set up in the SourceKitten Xcode project.

To work around this, you can use Xcode 11's SwiftPM support.

1. Open `Package.swift` with Xcode 11+
2. Run Product > Build For > Profiling

**Comment by fresh-Blood** [comment]
Same problem here
