### ISSUE TITLE
`unused_declaration` rule does not appear to work

### ISSUE THREAD

**Issue by Drarok** [realm/SwiftLint#2986]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version (0.38.0)
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The `unused_declaration` rule doesn't appear to work at all. In my example below, I would expect the class or at least to doSomething method to be flagged as unused.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ touch empty  # Create an empty config file
$ echo "/// My awesome class\npublic class MyGreatClass {\n    deinit {}\n    private func doSomething() {}\n}" | swiftlint lint --config empty --no-cache --enable-all-rules --use-stdin
Loading configuration from 'empty'
Done linting! Found 0 violations, 0 serious in 1 file.
```

### Environment

* SwiftLint version: 0.38.0
* Installation method used: Homebrew
* Paste your configuration file: N/A (I supply an empty one for testing)

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using? `Xcode 11.2.1, Build version 11B500`
* Do you have a sample that shows the issue? As above

I've also created a sample "project", attached. You can confirm by running:
```bash
mkdir example
# put my example.tar.gz file in here
tar zxvf example.tar.gz
swiftlint --enable-all-rules
```

[example.tar.gz](https://github.com/realm/SwiftLint/files/3936494/example.tar.gz)

**Comment by marcelofabri** [comment]
That is an analyzer rule, you need to follow the [instructions in the README.md](https://github.com/realm/SwiftLint#analyze-experimental)

**Comment by Drarok** [comment]
Hmm, that isn't clear in the docs. From `Rules.md`:

```
Identifier | Enabled by default | Supports autocorrection | Kind | Analyzer | Minimum Swift Compiler Version
--- | --- | --- | --- | --- | ---
`unused_declaration` | Disabled | No | lint | Yes | 3.0.0 
```

So it looks to be like its kind is "lint", incorrectly? It does state analyzer Yes, but are those not mutually exclusive?

**Comment by marcelofabri** [comment]
No, `lint` is just a "category" used for documentation/organization purposes. I agree that the name can cause confusion.
