### ISSUE TITLE
Separate config for tests (or any sub directory)

### ISSUE THREAD

**Issue by scottrhoyt** [realm/SwiftLint#299]
There are some cases where I would like to disable certain rules for a sub directory without disabling them for the entire project or excluding that directory. For example, in general I would like to disable force casting and force try's, but I would like to leave these as valid for test code where the exceptions they cause can be considered test failures.

One approach to this might be to allow a `.swiftlint.yml` to be placed in a subdirectory where it will override the global `.swiftlint.yml` (or potentially augment it).

What do you think?

**Comment by jpsim** [comment]
That's a fine idea! Is this something that you're interested in contributing?

**Comment by scottrhoyt** [comment]
Sure! I was just starting to dig into the code to ramp up on how `Configuration`s work. Where can I find where the recursive directory search is handled?

I suppose the first question to answer is how we should support the merging of `Configuration`s. I think the plan of attack will be to first implement merging by overriding the parent `Configuration` with the child. This is the easiest approach, but it will require fully forming each *.yml and the associated coordination effort if you need to change a global value.

If we like the results, we can then implement a Union/Override operation for `Configuration` that will take the union of the two configurations and resolve conflicts by overriding the parent value with the child value. That will provide the best usability by only requiring *.yml diffs to maintained in the child directories.

What do you think about this plan?

**Comment by scottrhoyt** [comment]
Obviously additional care will be needed to handle the include and exclude values. I think I'll tackle that by at first only honoring those values at the root level, and we may just want to enforce that as a rule.

If we think it's necessary, later we can decide to allow this at the child levels and manage the inclusion/exclusion trees.

**Comment by scottrhoyt** [comment]
Sorted out how the recursive directory search works.

**Comment by jpsim** [comment]
The steps as I see them are:

1. Recursively find all the configuration files.
2. When creating the linter ([currently done here](https://github.com/realm/SwiftLint/blob/0.5.3/Source/swiftlint/Extensions/Configuration%2BCommandLine.swift#L83)), use the furthest-level down configuration instead of always the same configuration.

That's the minimum needed to get started, although if you wanted to cumulatively apply configurations in the path to the file being linted, you could also do that.

**Comment by scottrhoyt** [comment]
This can now be accomplished with Recursive Configs in #307.
