### ISSUE TITLE
False Positive on class_delegate_protocol when restricting to NSObject Class type

### ISSUE THREAD

**Issue by AnthonyMillerSF** [realm/SwiftLint#2994]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When using a protocol with a conformance restriction to a type that is an NSObject, I get a warning for the `class_delegate_protocol` linter rule. Even though the conforming objects **must** be classes due to the restriction on the type.

![image](https://user-images.githubusercontent.com/49412465/71127761-83539b80-21a0-11ea-8118-b76aa4e3a53d.png)

**Comment by kmaschke85** [comment]
Any news on this one?

**Comment by josecostamartins** [comment]
There is also the case for using `where Self:` which implies a class. 

even the compiler complains about redundancy with something like 
`protocol MyProtocol: AnyObject where Self: SomeClassType { }`
