### ISSUE TITLE
Please update 'IPHONEOS_DEPLOYMENT_TARGET'

### ISSUE THREAD

**Issue by SatishBirajdar2019** [realm/SwiftLint#3019]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Can someone please update the Deployment target. I am getting following warning on my jenkins logs `The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'SwiftLint' from project 'SwiftLint'`

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? -> 0.37.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? -> cocoapods
* Paste your configuration file:

```yml
pod 'SwiftLint'
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? -> No
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? -> XCode 11.3

**Comment by jpsim** [comment]
SwiftLint can't run on iOS. Not sure how you're getting that error.

**Comment by SatishBirajdar2019** [comment]
It is integrated via cocoapods

**Comment by jpsim** [comment]
This seems to be a configuration issue with your project, not something wrong with SwiftLint's podspec.

**Comment by LowAmmo** [comment]
I'm guessing it is due to a lack of specifying the iOS deployment target in the podspec... Maybe Cocoapods defaults to 4.3 if nothing is specified?

Maybe just update the podspec to call out a version?

https://github.com/CocoaPods/Specs/blob/master/Specs/4/0/1/SwiftLint/0.39.2/SwiftLint.podspec.json#L18

**Comment by JanC** [comment]
hey, is there any workaround for this warning?

**Comment by jpsim** [comment]
SwiftLint doesn't support building on the iOS platform. Please build on macOS or Linux.

**Comment by klsetzer** [comment]
These errors arise from Xcode / SwiftLint integration via Cocoapods. There are numerous guides available that suggest this over using Homebrew to install SwiftLint. It's certainly a superior solution vs using Homebrew in CI pipelines.

What would be the downside to updated the Podspec to eliminate this warning?
