### ISSUE TITLE
Detect nesting of "if" statements in nesting rule

### ISSUE THREAD

**Issue by steve21124** [realm/SwiftLint#304]

**Comment by jpsim** [comment]
The nesting rule's threshold is currently set to 5 levels for the non-type case: https://github.com/realm/SwiftLint/blob/0.5.3/Source/SwiftLintFramework/Rules/NestingRule.swift#L46-L50.

There's no way to parameterize that rule at the moment.

**Comment by steve21124** [comment]
thanks for the pointer, I can hardcoded to 3 there...

**Comment by steve21124** [comment]
I did change to 3. it did catch for class but it did not catch the "nesting if statement". how to change the code to support it, "if then"

**Comment by jpsim** [comment]
It appears that's not currently supported. We'd have to update the rule to make that work. Figuring out how to do that is the first step!

**Comment by AviSergey** [comment]
Guys. Please add the feature to configure "nested" rule in config.yaml. We are looking forward to get any news about that question.

**Comment by jpsim** [comment]
> Guys. Please add the feature to configure "nested" rule in "swiftlint.yaml". We are looking forward to get any news about that question.

Only news I can give here is that I'm unaware of anyone having started work on this. @AviSergey since this feature is important to you, would you be interested in contributing a first version of it to the project?
