### ISSUE TITLE
opening_brace Conditional on func length

### ISSUE THREAD

**Issue by gwsounddsg** [realm/SwiftLint#3043]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Currently the `opening_brace` rule works for methods to enforce the following condition:
```
func foo() {
    // some code
}
```

But in the case where the method name and/or parameters exceeds you column limit, some folks will have this automatically/manually wrap to the next line. This is quite common when using Cocoa types as they have very descriptive and long names (eg: `NSAccessibility.ParameterizedAttribute.layoutPointForScreenPoint`)
```
func aReallyLongMethod(named: String, with: Int, many: String
    vars: ACrazyLongLongReallyLongProtocolNameDelegate) {
    // some code
}
```

In the above instance I find to improve [local reasoning](http://iosbrain.com/blog/2018/03/28/protocol-oriented-programming-in-swift-is-it-better-than-object-oriented-programming/) that having the curly brace on the next line makes it much easier to read:
```
func aReallyLongMethod(named: String, with: Int, many: String
    vars: ACrazyLongLongReallyLongProtocolNameDelegate) 
{
    // some code
}
```

Granted, I could just disable this rule for this instance. But I have to add the following comments:
```
// swiftlint:disable opening_brace
func aReallyLongMethod(named: String, with: Int, many: String
    vars: ACrazyLongLongReallyLongProtocolNameDelegate) 
{
// swiftlint:enable opening_brace
    // some code
}
```

Obviously I could clean that up, but it just eats up vertical space and makes it even harder to read. I have no clue how to write this custom rule, but it would be great to have this as a parameter in the `opening_brace` rule that the user can enable. I imagine this would be an opt-in parameter.

I'm open to thoughts and discussion about this proposal, and I'm happy to put the work in on the programming side to help make it happen.

Thanks,
GW

**Comment by lordzsolt** [comment]
There is already an open issue, pretty much same as yours: #1921

**Comment by gwsounddsg** [comment]
@lordzsolt wow, that issue is almost 2 years old but is defiantly what I'm talking about. Any chance it will get implemented?

**Comment by lordzsolt** [comment]
I opened a PR on it yesterday #3068, so hopefully it won't be that long 😄
