### ISSUE TITLE
Reporter json for Sonarqube

### ISSUE THREAD

**Issue by wolfAle** [realm/SwiftLint#3049]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I'm trying to import the generated swiftlint reports into Sonarqube.
The problem is that the json contains absolute paths for the files, that SonarQube can't then find.

This is the configuration:
In Xcode run phase:
**${PODS_ROOT}/SwiftLint/swiftlint --reporter json > ${PROJECT_DIR}/report/swiftlint.json**
The file gets correctly generated.
**Note:** this is the first issue. If I used `--reporter sonarqube` my instance of sonarqube (v 8.1) wouldn't like the output, the only viable option seems to be `json`....

The problem is that the generated file contains something like:
> [{
    "character" : null,
    "file" : "\/Users\/user\/Development\/iOS\/projectFolder\/folder\/Constants.swift",
    "line" : 121,
    "reason" : "Line should be 120 characters or less: currently 121 characters",
    "rule_id" : "line_length",
    "severity" : "Warning",
    "type" : "Line Length"
}]

the `file` row contains an absolute path.
I then import it on sonarqube **executed on my instance of gitlab**. In that case the path are completely different because it's not installed on the machine I'm working on. Gitlab runs sonarqube on a docker, therefore the environment doesn't match.

The path in the json should be relative to the project folder, or to the main .swiftlint.yml, or something along that line. 

### Environment

* SwiftLint version: 0.30.1
* Installation method used: CocoaPods

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using (check `xcodebuild -version`)? 11.3.1

Thanks for your help,
Alessandro

**Comment by wolfAle** [comment]
Hi guys,

any help on this matter? :-)

Thanks,
Alessandro

**Comment by marcelofabri** [comment]
PRs are welcome 😉

**Comment by wolfAle** [comment]
😄 
No idea where to start from in this case but I'll give it a go.
Any hint to address me in the right direction?

Thanks,
Alessandro

**Comment by marcelofabri** [comment]
Looks like it's supposed to use relative paths already: https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Reporters/SonarQubeReporter.swift#L27
