### ISSUE TITLE
Rule Request: Cyrillic spell checking

### ISSUE THREAD

**Issue by SpectralDragon** [realm/SwiftLint#3056]
## New Issue Checklist

- [x]  Updated SwiftLint to the latest version
- [x] I searched for existing GitHub issues

## New rule request

Good day, if you are don't use the Russian keyboard!

### 1. Why should this rule be added?

This is a long story about a man, who created a Russian keyboard in 1880! In the keyboard English character `C` was placed with the Russian character `С` and after that, our life was changed. All Russian developers sometimes make mistakes, when switch language from Russian to English and collision looks like `сurrentContext` where first `с` is Cyrillic. Problem with Cyrillic `C` is not alone, because I found code with Cyrillic `у` instead of English `y`.

![Screenshot 2020-01-27 at 14 51 17](https://user-images.githubusercontent.com/6003467/73172903-26d78a80-4115-11ea-984e-01fb27d83d6b.png)

How Russian Keyboard looks like:
![IMG_5636](https://user-images.githubusercontent.com/6003467/73173896-7dde5f00-4117-11ea-8e99-23413a173f02.jpg)

I don't have a link to the public discussion about that, only Slack discussion.

###  2. Provide several examples.

Problem with Russian `C` on production app:

<img width="1331" alt="Screenshot 2020-01-27 at 15 00 37" src="https://user-images.githubusercontent.com/6003467/73173542-a6b22480-4116-11ea-9cc7-3726a53a400c.png">

And another one:

![image (5) (5)](https://user-images.githubusercontent.com/6003467/73174263-5d62d480-4118-11ea-94ee-a102dde17555.png)

Like an experiment, just search on Github the next query `сurrent language:Swift` and you should understand what I talking about. 

For checking Russians characters in code, you can use the next tool: https://www.textmagic.com/free-tools/unicode-detector

### 3. Should the rule be configurable, if so what parameters should be configurable?

I think, that this rule shouldn't be configurable, because Russian symbols will not change in the future (I hope, so).

### 4. Should the rule be opt-in or enabled by default? Why?

I think, that this rule should be enabled by default because this is the most painful problem. But I'll not sad if this rule will be turned off by default.

Thanks for reading, and sorry for my bad English.

**Comment by vades79** [comment]
Oh, thank you bro

**Comment by SpectralDragon** [comment]
I really hope, that this issue will be resolved

**Comment by mikestalker** [comment]
You can try to add this rule to your .swiftlint.yml

custom_rules:
  restrict_cyrillic: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    excluded: ".*Test\\.swift" # regex that defines paths to exclude during linting. optional
    name: "Restrict Cyrillic Characters" # rule name. optional.
    regex: "([ЁёА-я])" # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    match_kinds: # SyntaxKinds to match. optional.
      - comment
      - identifier
    message: "Cyrillic characters prohibited." # violation message. optional.
    severity: error # violation severity. optional.
  no_hiding_in_strings:
    regex: "([ЁёА-я])"
    match_kinds: string
