### ISSUE TITLE
Show warning for `{return}`

### ISSUE THREAD

**Issue by nmtitov** [realm/SwiftLint#3059]
I wonder if there is a rule to show a warning for
```
{return}
```
and require it to be
```
else {
    return
}
```
instead?

The following rules do nothing in this situation
```
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
```

**Comment by lordzsolt** [comment]
`opening_brace` will warn you to write it as `{ return }`

**Comment by nmtitov** [comment]
I see that `opening_brace` does something different: it checks if there is a space **before** the brace

**Comment by lordzsolt** [comment]
@nmtitov Ah yes. Then use `closure_spacing`.
