### ISSUE TITLE
Homebrew version is outdated

### ISSUE THREAD

**Issue by jshuaf** [realm/SwiftLint#306]
When installing swiftlint from homebrew, the maximum version is *0.3.0.*

When installing from GitHub (the .pkg file) autocorrect works, along with configuring with a .yml file.

Does the brew version need to be updated?

**Comment by keith** [comment]
Looks like the homebrew formula on master is `0.5.3` right now https://github.com/Homebrew/homebrew/blob/master/Library/Formula/swiftlint.rb#L4

Maybe you need to run `brew update`?

**Comment by jshuaf** [comment]
@keith yep, you're right. facepalm.
