### ISSUE TITLE
Error installing SwiftLint

### ISSUE THREAD

**Issue by TangChanged** [realm/SwiftLint#3111]
[!] Error installing SwiftLint
[!] /usr/bin/curl -f -L -o /var/folders/m3/62y3tb1n01v7ct6fhgdc7st40000gn/T/d20200213-1048-141v0zq/file.zip https://github.com/realm/SwiftLint/releases/download/0.38.2/portable_swiftlint.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   612  100   612    0     0    392      0  0:00:01  0:00:01 --:--:--   392
  0     0    0     0    0     0      0      0 --:--:--  0:01:23 --:--:--     0
curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Operation timed out

**Comment by CGseng** [comment]
Hello,Are you fix the problem? Now, I have the same problem

**Comment by Pehon1** [comment]
I'm having the problem now as well

**Comment by Pehon1** [comment]
It turned out to be a network problem, specific to the CDN hosting SwiftLint

**Comment by marcelofabri** [comment]
Yeah, this comes from GitHub, so any outages or issues on their side could cause this.
