### ISSUE TITLE
require_explicit_imports: true nukes all import headers

### ISSUE THREAD

**Issue by AdrianBinDC** [realm/SwiftLint#3136]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Typed the following in iTerm:

`swiftlint analyze --compiler-log-path ./xcodebuild.log --autocorrect --reporter json > swiftlint.json`

I expected unnecessary headers to be removed, leaving only headers that are needed to be kept. In the class in question, there are declarations which use `Foundation`, so I would expect those to stay.

##### Complete output when running SwiftLint, including the stack trace and command used

Not finished yet. Looking at changes in Tower as it's going.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? Build from repo on local machine with latest [PR](https://github.com/realm/SwiftLint/pull/3123)
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Built from source.
* Paste your configuration file:

```yml
analyzer_rules:
  - unused_import

opt_in_rules:
  - unused_import:
      require_explicit_imports: true
```

* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 11.3.1

**Comment by jpsim** [comment]
I’m sorry you’re seeing this, I haven’t experienced this on the project where I’ve enabled this configuration. Can you please share a sample project that reproduces the issue so I can look into it?

**Comment by AdrianBinDC** [comment]
@jpsim Unfortunately, I'm not able to do so. I downloaded the repo locally and I will fiddle around with it as time allows. If I'm able to find the issue, I'll get clearance from Clarence to up a PR.

**Comment by AdrianBinDC** [comment]
What's the best way to debug something like this on actual code? Just do print statements or is there a way to link this up to `lldb` as you would w/ a iOS project?

**Comment by jpsim** [comment]
Sorry for never answering your last question, but I've documented how I run and debug SwiftLint locally using Xcode here: https://github.com/realm/SwiftLint/blob/master/CONTRIBUTING.md#using-xcode
