### ISSUE TITLE
dos file endings? Illegal Instruction: 4

### ISSUE THREAD

**Issue by fireflyexperience** [realm/SwiftLint#315]
As far as I can tell, this is the issue ... 

I have a file which seems to have DOS file endings, running swiftlint causes "Illegal Instruction: 4".
If I run the file through dos2unix, swiftlint works

git seems to make a mess of line endings at times, so would be good if swiftlint was more forgiving (or at least didn't give an unhelpful error message).

**Comment by lfarah** [comment]
+1

**Comment by norio-nomura** [comment]
:+1:

**Comment by norio-nomura** [comment]
Oops, sorry I failed comment.
I did not yet review that.
