### ISSUE TITLE
Valid IBInspectable Violation: @IBInspectable should be applied to variables only

### ISSUE THREAD

**Issue by ahmedsafadii** [realm/SwiftLint#3161]
### New Issue Checklist

- [1] Updated SwiftLint to the latest version
- [1] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

Valid IBInspectable Violation: @IBInspectable should be applied to variables only, have its type explicit and be of a supported type (valid_ibinspectable)

<img width="1773" alt="Screen Shot 2020-03-30 at 12 51 00 PM" src="https://user-images.githubusercontent.com/6974081/77899287-2bd7c800-7285-11ea-8d78-89a7b3d262a3.png">

**Comment by jpsim** [comment]
Fixed by #3155, assuming this is happening with Swift 5.2

**Comment by scott-lydon** [comment]
<img width="783" alt="Screen Shot 2021-06-13 at 1 27 05 PM" src="https://user-images.githubusercontent.com/4231144/121821031-0c8b4780-cc4b-11eb-8cbe-62e279e0ea51.png">
