### ISSUE TITLE
Reflection API compatibility with syntactic_sugar autocomplete 

### ISSUE THREAD

**Issue by jacobsapps** [realm/SwiftLint#3162]
### New Issue Checklist

- [✅] Updated SwiftLint to the latest version
- [✅] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
When using the Mirror API to iterate through the properties of an object, checking for any being nil, I needed to test for nil using `if case let Optional<Any>.none = $0`. After compile-time, this is autocorrected by the syntactic_sugar rule to `Any?`, which breaks the code.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
/my-file-system/.../MyClass+Extensions.swift:49:25: warning: Syntactic Sugar Violation: Shorthand syntactic sugar should be used, i.e. Int? instead of Optional<Int>. (syntactic_sugar)
```

### Environment

* SwiftLint version 0.39.1
* Installation method - Cocoapods 
* Paste your configuration file:
```yml
excluded:
- Pods
- R.generated.swift

disabled_rules:
- line_length
- unused_optional_binding
- nesting
trailing_whitespace:
  ignores_empty_lines: true
vertical_whitespace:
  max_empty_lines: 2
large_tuple:
  warning: 3
  error: 4
identifier_name:
  max_length:
   warning: 60
  min_length:
    warning: 1
    error: 1
  allowed_symbols: ["_"]
type_name:
  allowed_symbols: ["_"]
  
```
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents. No.
* Which Xcode version are you using (check `xcodebuild -version`)? 11.4

### Sample Code

```swift
// This triggers a violation:
    func validateAllFieldsHaveValues() -> Bool {
        Mirror(reflecting: self).children
            .map { $0.value }
            .allSatisfy {
            // swiftlint:disable:next syntactic_sugar 
           // This rule needs to be disabled because `Any?` can't have it's `.none` case inspected. Autocomplete modifies `Optional<Any>` to `Any?`.
                if case Optional<Any>.none = $0 {
                    return true
                } else {
                    return false
                }
        }
    }
```

**Comment by astroboy0803** [comment]
I have same issue in version 0.39.2

**Comment by mac-cain13** [comment]
A somewhat similar case I ran into is that  `Foo<Array<Void>.SubSequence>()` is autocorrected to `Foo<[Void].SubSequence>()` which doesn't compile:
- ❌ Adjacent operators are in non-associative precedence group 'ComparisonPrecedence'
- ❌ Generic parameter 'T' could not be inferred

*Environment:*
- Swiftlint 0.46.1
- Installation method: Mint
- Empty configuration file
- Xcode 12.0 Beta 6
