### ISSUE TITLE
Unclear “Xcode scheme”/“Run script phase” Readme Instructions

### ISSUE THREAD

**Issue by capnslipp** [realm/SwiftLint#3169]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The current [README.md](https://github.com/realm/SwiftLint/blob/master/README.md)'s setup instructions instruct the user to _”Integrate SwiftLint into an Xcode scheme to get warnings and errors displayed in the IDE. Just add a new "Run Script Phase" with:”_.  I'm not sure what I'm supposed to do here.

The **Scheme** editor in Xcode doesn't have an option for Run Script Phase, only **New Run Script Action**.  Also, the instruction don't specify whether this should be a Pre-action or a Post-action.

<img width="896" alt="Screen Shot 2020-04-03 at 8 10 57 PM" src="https://user-images.githubusercontent.com/74679/78415433-485a6400-75e7-11ea-8194-f77eb93bb377.png">
 

Alternatively, the instructions may have meant  _“Integrate SwiftLint into an Xcode **target**”_, in which case the instructions should be updated to reflect that.  (Targets and Schemes are distinctly different concepts in Xcode.)

<img width="1064" alt="Screen Shot 2020-04-03 at 8 03 55 PM" src="https://user-images.githubusercontent.com/74679/78415345-ccf8b280-75e6-11ea-81ca-1620c7256a57.png">

I'm going to assume the latter for now and hope it works, simply based on the fact that Target scripts tend to be a more commonplace solution than Phase scripts.  However, I'd like some term-fixing for the sake of clarity in the readme— it should be either:

1. _”Integrate SwiftLint into an Xcode **target** to get warnings and errors displayed in the IDE. Just add a new "Run Script Phase" with:”_, or
2. _”Integrate SwiftLint into an Xcode scheme to get warnings and errors displayed in the IDE. Just add a new **Build Pre-action "Run Script Action"** with:”_

##### Complete output when running SwiftLint, including the stack trace and command used

Not relevant— this is an issue about the Markdown-formatted documentation.

### Environment

Not relevant— this is an issue about the Markdown-formatted documentation.  Environment is the website at https://github.com/realm/SwiftLint/ (technically, https://github.com/realm/SwiftLint/blob/master/README.md).

**Comment by christiankm** [comment]
Good catch. Could certainly be improved.
I'll create a pull request now to correct this.

**Comment by capnslipp** [comment]
@christiankm Awesome, thanks!

May I also suggest specifying where in the build phase list the SwiftLint phase should go (e.g. before Compile Source, after Compile Source but before Link Binary, etc.).  There have been a number of common Xcode build errors that have cropped up in the past when Apple drops a new Xcode version that are usually solved by having build phases in a sensical order.  I imagine you know what order is “most correct” better than I do.

**Comment by marcelofabri** [comment]
A PR improving the instructions would be lovely!

**Comment by capnslipp** [comment]
#3290 looks good to me; can we merge this?

**Comment by jpsim** [comment]
I'll make some small edits to that PR and merge.

**Comment by christiankm** [comment]
> I'll make some small edits to that PR and merge.

Sounds wonderful, thank you!

**Comment by jpsim** [comment]
67165f7c
