### ISSUE TITLE
Couldn't "pod install/update" to 0.39.2 version

### ISSUE THREAD

**Issue by MaximSkorynin** [realm/SwiftLint#3172]
Hi! I cant install/update version 0.39.2 from terminal. I am just waiting long time

**Comment by shtnkgm** [comment]
In order to solve the problem, you need to describe the problem in more detail.
Try outputting a lot of logs using the verbose option, for example:

```bash
$ pod install --verbose
```

**Comment by jormungand2006** [comment]
I don't know why, but in my case, clearing pods cache solve it.

```
# for backup
$ mv ~/.cocoapods ~/cocoapods
$ mv ~/Library/Caches/CocoaPods ~/CocoaPodsCaches

$ pod setup
$ pod install
```

**Comment by marcelofabri** [comment]
Closing this because it seems to be a (temporary?) CocoaPods issue.
