### ISSUE TITLE
setting empty_count severity implicitly not working anymore 

### ISSUE THREAD

**Issue by catach** [realm/SwiftLint#3181]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Since upgrading SwiftLint to the latest version (0.39.2), all `empty_count` warnings became errors. I used an implicitly severity configuration like:

```yml
empty_count: warning
```

but this does not work anymore. I had to change to

```yml
empty_count:
    severity: warning
```

to make it work. I saw some changes in the severity configuration for this rule, so I think that could be a side effect.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
Loading configuration from '.swiftlint.yml'
Invalid configuration for 'empty_count'. Falling back to default.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.39.2
* Installation method used (Homebrew, CocoaPods, building from source, etc)? CocoaPods

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 11.4
Build version 11E146

**Comment by LearnMoreAndBetter** [comment]
I encountered the same issue，add I found ‘empty_count’ is disable by default

**Comment by BalestraPatrick** [comment]
Seeing the same issue. I think this is a regression since a configuration that was valid in 0.35.0 for us is now invalid in 0.39.2.

**Comment by jpsim** [comment]
Yes, this is a regression introduced in https://github.com/realm/SwiftLint/pull/3052

Enough time has elapsed that I don't think it's as important to fix now though.
