### ISSUE TITLE
Dynamic Linking Error

### ISSUE THREAD

**Issue by donald-pinckney** [realm/SwiftLint#32]
Installing fresh using Homebrew, the .pkg download and compiling from source all leads to the same linking error message:
```
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Library/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
  Reason: image not found
[1]    49802 trace trap  swiftlint
```

Tell me if there is anything I can do to help.

**Comment by segiddins** [comment]
Do you have Xcode installed at `/Applications/Xcode.app`?

**Comment by donald-pinckney** [comment]
Had only beta installed, my bad ;)
