### ISSUE TITLE
https://github.com/github/swift-style-guide

### ISSUE THREAD

**Issue by seenZone** [realm/SwiftLint#3200]
**Problem:** https://github.com/github/swift-style-guide has been archived and not active anymore.

**Question:** What swift style guide reference does SwiftLint do?

**Comment by seenZone** [comment]
Hi I would like to suggest this guide: https://google.github.io/swift/

Hoping for your feedback, thanks!

**Comment by christiankm** [comment]
I don't know if the project authors have any preference, but I can say that the standard SwiftLint rules also follow the Ray Wenderlich guide closely.
https://github.com/raywenderlich/swift-style-guide

**Comment by seenZone** [comment]
@christiankm thanks for the reply, that would be great.
