### ISSUE TITLE
How to use Swiftlint when creating a Swiftpackage

### ISSUE THREAD

**Issue by satan87** [realm/SwiftLint#3201]
Hello,

I'm using SwiftLint with my Xcode project ith no issue.
now I'm trying to create a Swift package.

How can I use SwiftLint in Xcode?

thanks,
Nicolas

**Comment by Atimca** [comment]
Looks like SPM and SwiftLint relationship is a big issue itself

**Comment by fishercraigj** [comment]
+1

**Comment by christiankm** [comment]
What I do is to wrap the Swift Package in a generated project. Then you can add the build phase as normal.

**Comment by flopshot** [comment]
> What I do is to wrap the Swift Package in a generated project.

I'd greatly appreciate it if anyone expand on how to do this.

I'm talking over a Vapor project and would like to add SwiftLint to it. Having the cli is great for CI but I'd like myself and my developers to be able to add SwiftLint Xcode integration to make it as easy as possible to fix linting issues.
