### ISSUE TITLE
Swiftlint overriding project settings

### ISSUE THREAD

**Issue by kwakueshun** [realm/SwiftLint#3213]
https://stackoverflow.com/questions/59830330/swiftlint-overriding-project-settings-related-to-spm

Link above does not have an answer but I am facing the same issue now and I am unable to find any thing related to this. Would appreciate some help regarding this if it is a known issue.

Thanks for the great work!

**Comment by marcelofabri** [comment]
SwiftLint doesn't touch your project at all. This could be an issue with Xcode, SPM or both.
