### ISSUE TITLE
Lint output is incomplete at times

### ISSUE THREAD

**Issue by franciscodua** [realm/SwiftLint#3214]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When running the swiftlint CLI (lint option), the output is not complete. The behavior is not consistent, sometimes it ends and outputs `Done linting! Found 7 violations, 5 serious in 2 files.`, other times it ends mid-issue.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --reporter json -- closing_brace2.swift dynamic_inline2.swift
Loading configuration from '.swiftlint.yml'
Linting Swift files at paths closing_brace2.swift, dynamic_inline2.swift
Linting 'closing_brace2.swift' (1/2)
Linting 'dynamic_inline2.swift' (2/2)
[
  {
    "character" : 14,
    "file" : "\/src\/closing_brace2.swift",
    "line" : 6,
    "reason" : "Closing brace with closing parenthesis should not have any whitespaces in the middle.",
    "rule_id" : "closing_brace",
    "severity" : "Warning",
    "type" : "Closing Brace Spacing"
  },
  {
    "character" : 14,
    "file" : "\/src\/closing_brace2.swift",
    "line" : 8,
    "reason" : "Closing brace with closing parenthesis should not have any whitespaces in the middle.",
    "rule_id" : "closing_brace",
    "severity" : "Warning",
    "type" : "Closing Brace Spacing"
  },
  {
    "character" : 31,
    "file" : "\/src\/dynamic_inline2.swift",
    "line" : 10,
    "reason" : "Avoid using 'dynamic' and '@inline(__always)' together.",
    "rule_id" : "dynamic_inline",
    "severity" : "Error",
    "type" : "Dynamic Inline"
  },
  {
    "character" : 38,
    "file" : "\/src\/dynamic_inline2.swift",
    "line" : 14,
    "reason" : "Avoid using 'dynamic' and '@inline(__always)' together.",
    "rule_id" : "
```

The files used in this analysis are:
dynamic_inline.swift:
```swift
//#Patterns: dynamic_inline

//#Issue: {"severity": "Info", "line": 10, "patternId": "dynamic_inline"}
//#Issue: {"severity": "Info", "line": 14, "patternId": "dynamic_inline"}
//#Issue: {"severity": "Info", "line": 18, "patternId": "dynamic_inline"}
//#Issue: {"severity": "Info", "line": 23, "patternId": "dynamic_inline"}
//#Issue: {"severity": "Info", "line": 29, "patternId": "dynamic_inline"}

    class C {
    @inline(__always) dynamic func f() {}
    }

    class C {
    @inline(__always) public dynamic func f() {}
    }

    class C {
    @inline(__always) dynamic internal func f() {}
    }

    class C {
    @inline(__always)
    dynamic func f() {}
    }

    class C {
    @inline(__always)
    dynamic
    func f() {}
    }
```
And closing_brace.swift:
```swift
//#Patterns: closing_brace

//#Issue: {"severity": "Info", "line": 6, "patternId": "closing_brace"}
//#Issue: {"severity": "Info", "line": 8, "patternId": "closing_brace"}

    [].map({ } )

    [].map({ }	)
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.39.2
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Running analysis in Docker image `norionomura/swiftlint:0.39.2_swift-5.2.4`
* Paste your configuration file:

```yml
whitelist_rules:
  - closing_brace
  - dynamic_inline
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  No
* Which Xcode version are you using (check `xcodebuild -version`)?
 Docker container doesn't have xcodebuild
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.
 The issue happens for the files I shared above if I run the analysis a few times. I would say 1 out of 5.

**Note:**
I don't know that much about swift yet. But I was thinking if this problem could be related to the async nature of the [print](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Extensions/QueuedPrint.swift#L27)? Is it possible that the print is not completing when the tool finishes executing?

Thanks for reading this long issue.

**Comment by franciscodua** [comment]
Hi
Any news on this issue? Do you need more information?

**Comment by marcelofabri** [comment]
This is probably because we don't use `atexit_b` on Linux: https://github.com/realm/SwiftLint/commit/8c171458f8d5c01f20263c3a89fb56d5d10ad6a6
