### ISSUE TITLE
`unused_import` usage

### ISSUE THREAD

**Issue by AdrianBinDC** [realm/SwiftLint#3221]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I'm having trouble finding directions how to use `unused_import`. Are there instructions laying around re: what goes where in the .yml file w/ `unused_import`, configuring autocorrect, etc.?

**Comment by marcelofabri** [comment]
`usused_import` is an "analyzer" rule, so you can find the instructions on README: https://github.com/realm/SwiftLint#analyze-experimental

**Comment by chaseklingelzen** [comment]
I know this issue is closed, but wanted to get some clarification here. Does SwiftLint provide a way to see warnings when an import is unused?

**Comment by jpsim** [comment]
See an example configuration for [Yams](https://github.com/jpsim/Yams):

* `unused_import` configured in `.swiftlint.yml`: https://github.com/jpsim/Yams/blob/e736a48df02330c38aabac4e9963e761922ab057/.swiftlint.yml#L7
* CI steps to generate the Xcode build log and invoke SwiftLint: https://github.com/jpsim/Yams/blob/e736a48df02330c38aabac4e9963e761922ab057/.github/workflows/swiftlint_analyze.yml#L28-L35

At which point if I add an unused import (e.g. `import Combine` in Emitter.swift):

```console
$ xcodebuild -sdk macosx -scheme Yams -project Yams.xcodeproj clean build-for-testing > xcodebuild.log
$ swiftlint analyze --compiler-log-path xcodebuild.log
Analyzing Swift files in current working directory
Collecting 'Mark.swift' (1/28)
...
Collecting 'NodeTests.swift' (28/28)
Analyzing 'Mark.swift' (1/28)
...
Analyzing 'Emitter.swift' (13/28)
/Users/jsimard/src/Yams/Sources/Yams/Emitter.swift:12:1: warning: Unused Import Violation: All imported modules should be required to make the file compile. (unused_import)
Analyzing 'Node.swift' (14/28)
...
Analyzing 'NodeTests.swift' (28/28)
Done analyzing! Found 1 violation, 0 serious in 28 files.
```

**Comment by chaseklingelzen** [comment]
Thanks for the quick response @jpsim. So, we must use the analyzer in order to see warnings related to unused imports essentially?

**Comment by jpsim** [comment]
Yes, unused imports is an analyzer rule.

**Comment by chaseklingelzen** [comment]
Great, thanks @jpsim !

**Comment by chaseklingelzen** [comment]
@jpsim is it ever likely that this will just be a compile time warning shown in xcode? I'm sure there are good reasons it currently isn't. Thank you guys for creating such an amazing tool.

**Comment by jpsim** [comment]
That's very tricky and would require some significant investments.

**Comment by chaseklingelzen** [comment]
I figured there was a good reason for not implementing 😄. No problem, appreciate the info.
