### ISSUE TITLE
Rule for whitespace in function declaration

### ISSUE THREAD

**Issue by tumata** [realm/SwiftLint#3229]
I would like to know if there is a rule for when white-spaces are added around the function name such as below:
`func     bind    (something: A, somethingElse: B) {`

These do not trigger any violation at the moment.
Thanks

**Comment by tumata** [comment]
Up!

**Comment by tumata** [comment]
Last up!

**Comment by SimplyDanny** [comment]
Such a rule only exists for operators where it enforced whitespace around the operator symbol.

Whitespace handling is the expertise of [SwiftFormat](https://github.com/nicklockwood/SwiftFormat).

**Comment by SimplyDanny** [comment]
Feel free to reopen the issue if there are more related questions.
