### ISSUE TITLE
Ignore rule based on regex

### ISSUE THREAD

**Issue by NikKovIos** [realm/SwiftLint#3234]
What about make settings to rule to ignore some situations based on regex? It rely on closed https://github.com/realm/SwiftLint/issues/589

For example: I need to have https://realm.github.io/SwiftLint/conditional_returns_on_newline.html rule. But not include `guard let self = self else { return }` statement.

**Comment by marcelofabri** [comment]
This is really hard to do in a general level. Your best shot is to add a configuration to specific rules.
