### ISSUE TITLE
Curl Error 400 with pod install 

### ISSUE THREAD

**Issue by Danisnowman** [realm/SwiftLint#3245]
### New Issue Checklist

- [x ] Updated SwiftLint to the latest version
- [ x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When I run ```pod install``` it returns an error.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ pod install
```

```
[!] Error installing SwiftLint
[!] /usr/bin/curl -f -L -o /var/folders/_4/znvdcyy17739_cbcdwxwdgnh0000gn/T/d20200617-2878-14yk8aa/file.zip https://github.com/realm/SwiftLint/releases/download/0.39.2/portable_swiftlint.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633    0   633    0     0   1582      0 --:--:-- --:--:-- --:--:--  1582
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 400 Bad Request
```

### Environment

* I'm trying to install it through cocoapods

**Comment by marcelofabri** [comment]
This is a request error on GitHub side, there's not much we can do.
