### ISSUE TITLE
Custom 'Example.configuration' not read for triggeringExamples / nonTriggeringExamples

### ISSUE THREAD

**Issue by keith** [realm/SwiftLint#3255]
When adding new test cases to a rule that rely on custom configuration for that rule, you can provide `configuration` for corrections, but not for triggeringExamples / nonTriggeringExamples.

This is because this is handled here for corrections:

https://github.com/realm/SwiftLint/blob/075312af6e8b2ac527a02a725a51e55f65816a0f/Tests/SwiftLintFrameworkTests/TestHelpers.swift#L246-L252

But not for those other assertions.

**Comment by keith** [comment]
Still relevant

**Comment by SimplyDanny** [comment]
Fixed in #3431.
