### ISSUE TITLE
Please create a new release version

### ISSUE THREAD

**Issue by jqsilver** [realm/SwiftLint#3264]
While using the latest release, version 0.39.2, I encountered the issues fixed in https://github.com/realm/SwiftLint/pull/3198

Concretely, in a file that only referenced `DispatchQueue`, the `unused_import` rule would remove `import Foundation` but not replace it with `import Dispatch`. 

I can update my repository to use a build from master, but it would be great to use a release version instead.

**Comment by noahsark769** [comment]
I also think it would be really useful to put out another release now, since the last one was in April. @jpsim or @marcelofabri perhaps you could help? I'd be happy to contribute some time if there's some way for me to help as well

**Comment by marcelofabri** [comment]
I've been merging a few PRs today and I'm planning to cut a new release later this week 🔜

**Comment by noahsark769** [comment]
Awesome, thank you!

**Comment by marcelofabri** [comment]
https://github.com/realm/SwiftLint/releases/tag/0.40.0 is now out 🚀

**Comment by matrejek** [comment]
Thank you @marcelofabri 👍 Good job!
