### ISSUE TITLE
Why I added .swiftlint.yml, and xcode said no such file or directory

### ISSUE THREAD

**Issue by crablife** [realm/SwiftLint#3265]
I use Swiftlint with CocoaPods, and I also added .swiftlint.yml in root projection path.

```
So my structure is
-- .swiftlint.yml
-- Pods
    |--SwiftLint

```
My script like this

```
SWIFT_LINT="${PODS_ROOT}/SwiftLint/swiftlint"
SWIFT_LINT_CONFIG="${SRCROOT}/.swiftlint.yml"
"${SWIFT_LINT} --config ${SWIFT_LINT_CONFIG}
```

And then I start to build, and Xcode told me that "**No such file or directory.**"
Anybody know what's going on?

**Comment by daltonclaybrook** [comment]
Not exactly sure about your specific issue, but looking at the [Using CocoaPods](https://github.com/realm/SwiftLint#using-cocoapods) section of the README, you shouldn't have to specify the config path at all. Just add a run script phase with the single line:
```
${PODS_ROOT}/SwiftLint/swiftlint
```
