### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 619455272** [realm/SwiftLint#3266]
After I have configured successfully, Enter Swiftlint Autocorrect on the terminal     

<img width="645" alt="WechatIMG127" src="https://user-images.githubusercontent.com/24289298/88993134-ae49c480-d317-11ea-8c08-5c271fb5d337.png">

**Comment by marcelofabri** [comment]
You’re using a very old version of SwiftLint. Please update it.

**Comment by 619455272** [comment]
![1596175427173](https://user-images.githubusercontent.com/24289298/89005309-b06f4b80-d336-11ea-834f-c167bae0d495.jpg)

Updated to the latest version, execute the command, or report an error

**Comment by marcelofabri** [comment]
You’re running a swiftlint that was installed globally, not the one from CocoaPods

**Comment by 619455272** [comment]
There is only one SWIftlint on my computer, and the global SWIftlint is not configured. May I ask what should I do next
![1596191108826](https://user-images.githubusercontent.com/24289298/89026435-4a48ef80-d35b-11ea-94d6-377a56dfc190.jpg)

**Comment by marcelofabri** [comment]
You can try using `which swiftlint` or `whereis swiftlint`. The binary from CocoaPods won’t be in your PATH, so you should use `Pods/SwiftLint/swiftlint`

**Comment by 619455272** [comment]
Thank you. The problem has been solved
