### ISSUE TITLE
[Question] How to files regardless its folder

### ISSUE THREAD

**Issue by amadeu01** [realm/SwiftLint#3285]
I have a project that is organized like this: 

```
Pipe
├── Components
│   ├── AssigneeAvatars
│   │   ├── AssigneeAvatars.swift
│   │   ├── AssigneeAvatarsTest.swift
```

I was trying to exclude the `force_unwraping` rule for test files like 

```
force_unwrapping:
  excluded:
    - "**/*.Test\\.swift"
```

But it didn't work. Do you know how can I do it?

**Comment by amadeu01** [comment]
I also tried to put the entire path of the file inside the `excluded`. But it didn't work either.

**Comment by marcelofabri** [comment]
- We don't support recursive globs (using `**`)
`force_unwrapping` doesn't provide a `excluded` configuration

The way that people usually solve this is to have tests in their own folder, so they can use [nested configurations](https://github.com/realm/SwiftLint#nested-configurations) to disable rules in tests.

Another alternative is to use `swiftlint:disable` in the file.

**Comment by amadeu01** [comment]
thank @marcelofabri
