### ISSUE TITLE
Excluding takes too long

### ISSUE THREAD

**Issue by JohnReeze** [realm/SwiftLint#3304]
I use Swiftlint for one very big project for only changed files by specyifing `--use-script-input-files --force-exclude` and after some checks and measurements with Time Profiler I found out that excluding paths takes more then 3-4 seconds on my machine.

I investigated that problem and found next: while excluding it finds ALL lintable files in all excluded paths from config. And then the result set of excluded swift files is subtracted from the input paths set.

I find it quiet strange algorithm, because why do we need to collect all lintable files for example in excluded Pods directory. 

So, I tryed to changed it to the next exclusion algorithm:

```swift
let allPaths = paths.flatMap { $0 }
let excludedPaths = excluded.flatMap(Glob.resolveGlob).map { $0.absolutePathStandardized() }
return allPaths.filter { path in
    !excludedPaths.contains { path.hasPrefix($0) }
}
```

And it still excludes files, lints and works for those 3-4 seconds faster 

Are there any special reasons for current exclusion algorithm? or it can be changed to something like I used?

**Comment by jpsim** [comment]
If you can improve the algorithm I'm all for it, although it seems like your latest attempt in https://github.com/realm/SwiftLint/pull/3345 is actually changing the behavior, not sure if you're expecting that to happen or not.

**Comment by jpsim** [comment]
Try the `--use-alternative-excluding` flag
