### ISSUE TITLE
Line Length Violation: Line should be 120 characters or less: currently 145 characters (line_length)

### ISSUE THREAD

**Issue by ramakrishna013** [realm/SwiftLint#3308]
Hi, I've recently installed the Swiftlint using pods for swift. It installed successfully and I've created my `.swiftlint.yml` file. And  in that `.yml` file I've set the `line_length: 200`. But when I build my app it does not update and still showing the `Line Length Violation: Line should be 120 characters or less: currently 145 characters (line_length)` error. How can I fix this?

**Comment by jpsim** [comment]
Sounds like the `.swiftlint.yml` config file isn't being picked up. Are you passing it explicitly via `--config`? Or are you running `swiftlint` in the same directory as the config file?
