### ISSUE TITLE
Can we make fixable custom warnings/errors that have a red dot next to it?

### ISSUE THREAD

**Issue by akun1** [realm/SwiftLint#3315]
Hello! 

We all know and love those errors in Xcode that pop up with a fix button so we can just click it and solve our issue, right?

Is this possible to make with a custom rule?

Thanks!

Example:

![Screen Shot 2020-08-21 at 10 22 54 PM](https://user-images.githubusercontent.com/23622603/90949448-e4510480-e3fc-11ea-80a0-256d51b837cb.png)

**Comment by marcelofabri** [comment]
Xcode doesn't provide an easy way of implementing this. See #27 for more discussion.

**Comment by jpsim** [comment]
@akun1 if you'd like to see Xcode support this, please file feedback with Apple and let us know, I'll be happy to duplicate the feedback.
