### ISSUE TITLE
Private Tests for Custom Rules

### ISSUE THREAD

**Issue by akun1** [realm/SwiftLint#3322]
My org is using SwiftLint, I made some custom rules for our codebase, I'm loving it!

I was wondering if we can make some unit tests for each custom rule using SwiftLineFramework?

I just couldn't figure out how to do it outside of the SwiftLint repo.

Simply importing wasn't working either!

Thanks!

**Comment by PaulTaykalo** [comment]
@akun1 I would suggest having a Package that will be dependent on the SwiftFramework package, so by this you'll be able to add any tests you want by using the framework itself by using CustomuRule in tests
