### ISSUE TITLE
Line Length Violation: Line should be "250" characters or less: currently "207" characters (line_length)

### ISSUE THREAD

**Issue by emreakcan** [realm/SwiftLint#3333]
### New Issue Checklist

- [YES] Updated SwiftLint to the latest version
- [YES] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Line should be 250 characters or less: currently 207 characters, but 250 is bigger than 207.
I changed the line rule to 250 from 200

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
Line Length Violation: Line should be 250 characters or less: currently 207 characters (line_length)
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.40.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
CocaPods
* Paste your configuration file:

```yml
line_length: 
    warning: 250
    ignores_comments: true

disabled_rules:
    trailing_whitespace
```

**Comment by jpsim** [comment]
Fix in #3406.
