### ISSUE TITLE
[Feature request] Make autocorrect take an optional list of files

### ISSUE THREAD

**Issue by NachoSoto** [realm/SwiftLint#334]
*Writing from my phone, so apologies if this is actually already possible and I didn't see it*.

I was thinking of adding a build phase that calls `swiftlint autocorrect` before actually linting, but I wouldn't want it to modify any file, only those that I've touched (to avoid too many changes but also to speed it up). This could by done by passing the list of "dirty" files on the `git`  checkout.

Other tools like `clang-tidy` can do this on a line-by-line basis too, which would be harder but definitely great!

**Comment by jpsim** [comment]
We don't mention it in the README, but `lint` and `autocorrect` have a `--use-script-input-files` flag that will only lint/correct files passed via SCRIPT_INPUT_FILE* environment variables. This was introduced in #193, the PR has some of the motivations behind the design.

I know clang-format has [git integration](https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format), it'd be useful to have something similar for SwiftLint.

**Comment by NachoSoto** [comment]
Oooh `clang-format` is what I actually meant. Awesome! Of course @norio-nomura already did this :smile:.

I'll make a PR to add this to the README when I'm back in my computer. Thanks @jpsim!
