### ISSUE TITLE
// swiftlint:disable all doesn't disable custom rules

### ISSUE THREAD

**Issue by rcritz** [realm/SwiftLint#3364]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`// swiftlint:disable all` doesn't disable custom rules

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 12

**Comment by jpsim** [comment]
Can you please share an example that can demonstrate the issue? This should work.

**Comment by rcritz** [comment]
As soon as I enter the bug report, after fighting with it for an hour, it works. I have no idea. So, never mind for now.
