### ISSUE TITLE
Function Parenthesis removed because followed by braces

### ISSUE THREAD

**Issue by mime29** [realm/SwiftLint#3382]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When we write the following code:

```swift
private func handleError(error: MyError) {
        switch dispatch(error: error) {
        case .retryMode:
            if startTime + args.retryDuration < .now() {
                completion(Result(error: .other))
            } else {
                oneMoreTime()
            }
        case .failed(let anotherError):
            completion(Result(error: anotherError))
        }
    }
```

It outputs the following:

```swift
private func handleError(error: MyError) {
        switch dispatch(error: error) {
        case .retryMode:
            if startTime + args.retryDuration < .now {
                completion(Result(error: .other))
            } else {
                oneMoreTime()
            }
        case .failed(let anotherError):
            completion(Result(error: anotherError))
        }
    }
```

Which triggers a compilation error

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

Can't do this due to company rules

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?

0.40.3

* Installation method used (Homebrew, CocoaPods, building from source, etc)?

homebrew

* Paste your configuration file:

Can't do this due to company rules

```yml
# insert yaml contents here
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?

11.7

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
let foo = try! bar()
```

**Comment by PaulTaykalo** [comment]
@mime29 It doesn't clear what is the issue here.
Can you clarify?

**Comment by PaulTaykalo** [comment]
@lordzsolt Are you trying to perform autocorrection?
If so, what is your config?
linting itself shouldn't do any harm

**Comment by PaulTaykalo** [comment]
Okay, got it.
