### ISSUE TITLE
`ConditionalBindingCascadeRule` hangs up on linting KeychainAccess

### ISSUE THREAD

**Issue by norio-nomura** [realm/SwiftLint#340]
It can be reproduced by
`curl https://raw.githubusercontent.com/kishikawakatsumi/KeychainAccess/master/Examples/Playground-iOS.playground/section-1.swift |swiftlint lint --use-stdin`

**Comment by norio-nomura** [comment]
SwiftLint hangs up in `matchesInString(_:options:range:)`.
Maybe it needs to change `ConditionalBindingCascadeRule` from `Rule` to `ASTRule` for supporting the triggering test case:
```swift
"if let a = b, c = d.indexOf({$0 == e}), let f = g {",
```
and avoiding infinite loop in `matchesInString`.

**Comment by jpsim** [comment]
Yes, this is a major problem. I'm looking into it now.

**Comment by norio-nomura** [comment]
@jpsim On re-writing, It also needs to consider #347
