### ISSUE TITLE
Implement Apple Naming conventions

### ISSUE THREAD

**Issue by luinily** [realm/SwiftLint#341]
I don't think that the github swift style guide has any rule for the naming of variables/functions/types but Apple does.
Would it be possible for SwiftLing to implement those rules?

Apple naming conventions :
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/CodingGuidelines.html#//apple_ref/doc/uid/10000146-SW1

**Comment by scottrhoyt** [comment]
I'm unsure this is a good idea. Just a quick glance at the referenced guide indicates most of these recommendations apply to Objective-C Cocoa-like interfaces, which Apple has been moving away from with Swift.

**Comment by luinily** [comment]
As I'm new to Swift (and do not have any experience in Objective-C) I don't really know wich rules should be applied if Apple's own are outdated. 

If Apple write new ones for Swift I'd go for those ones.
Unless there is another naming guidelines set that are shared by the community, for now I'd go with Apple's one (start variables and function names with a small letter, types with a capital letter etc..).

Which guidelines are people here following ?

**Comment by scottrhoyt** [comment]
I'm not sure if there is comprehensive agreement Swift style yet, but here are some great resources, including one from the horse's mouth (Swift.org).

https://swift.org/blog/swift-3-api-design/
https://github.com/raywenderlich/swift-style-guide
https://github.com/github/swift-style-guide
