### ISSUE TITLE
Rule Request: Discourage comparing Bool value with `true` or `false`

### ISSUE THREAD

**Issue by agarmash** [realm/SwiftLint#3420]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

The usage of `==` or `!=` operators for checking if the Bool value is `true` or `false` should be discouraged in favour of using the Bool value itself or the one with negating operator.

#### 1. Why should this rule be added? Share links to existing discussion about what the community thinks about this.

Since Bool can only have 2 values, there's no need to compare it with constant values, like:
```swift
var isEnabled = true
if isEnabled == true { /* do stuff */ } 
```

The only exception is checking an optional Bool value, although this case is already covered in [Discouraged Optional Boolean](https://realm.github.io/SwiftLint/discouraged_optional_boolean.html):
```swift
var hasPermission: Bool? = true
if hasPermission == true { /* do stuff */ } 
```

Another point is that regarding [Swift code style](https://github.com/raywenderlich/swift-style-guide#naming), "boolean types should read like assertions".
Let's compare 2 examples:
* `if switch.isActive { updateAppearance() }` is naturally perceived as "If the switch is active, update the appearance";
* `if switch.isActive == true { updateAppearance() }` is a bit more cluttered and makes it harder to quickly grasp the intension of the code.

Also, [a recent forum thread shows](https://forums.swift.org/t/boolean-comparison-causes-extremely-slow-compilation/41609) that Bool comparison is quite slower than using the value itself during compilation.

#### 2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

**Triggering examples:**

```swift
var isEnabled = true
if ↓isEnabled == true { /* do stuff */ } 
```

Don't forget the [Yoda notation](https://en.wikipedia.org/wiki/Yoda_conditions):
```swift
var isEnabled = true
if ↓true == isEnabled { /* do stuff */ } 
```

**Non-triggering examples:**

```swift
var hasPermission: Bool? = true
if hasPermission == true { /* do stuff */ } 
```

```swift
var isEnabled = true
if isEnabled { /* do stuff */ } 
```

#### 3. Should the rule be configurable, if so what parameters should be configurable?

I don't think so, there's basically nothing to configure.

#### 4. Should the rule be opt-in or enabled by default? Why?

Due to perceivable performance drop, it worth enabling this rule by default

**Comment by agarmash** [comment]
Let me know what you think, I'd like to hear any possible concerns and implement the rule myself in the next few days

**Comment by incoming-mailintellectua** [comment]
@agarmash https://ernest-joomla5.github.io/10HBwOEyh26cg75io49m0ODzpIa10VD/
