### ISSUE TITLE
Codeclimate report format for Gitlab MR Widget

### ISSUE THREAD

**Issue by jkroepke** [realm/SwiftLint#3424]
Gitlab make the Code Quality MR Widget available to the free edition.

https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html

At this time, gitlab only support the codeclimate format as source for the Code Quality MR Widget.

https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool

It's possible to provide such a report format? I guess, it could be done by copy the json reporter and adjust the fields.

**Comment by jpsim** [comment]
> I guess, it could be done by copy the json reporter and adjust the fields.

That sounds like the right way forward to me. Let us know if you need any help.

**Comment by jkroepke** [comment]
Thanks I opened https://github.com/realm/SwiftLint/issues/3424
