### ISSUE TITLE
SwiftLint excluded Pods , also be compiled

### ISSUE THREAD

**Issue by kyleYang** [realm/SwiftLint#3446]
### New Issue Checklist
swiftlint version 0.41.0

my swiftlint.yml file
disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - force_cast
  - switch_case_alignment
  - trailing_whitespace
  - cyclomatic_complexity
  - unused_closure_parameter
  - multiple_closures_with_trailing_closure
# opt_in_rules: # some rules are only opt-in
#   - empty_count
#   # Find all the available rules by running:
#   # swiftlint rules

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

included: # paths to include during linting. `--path` is ignored if present.
  - CYFinance
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Pods/RxSwift
  - CYFinanceTests
  - CYFinanceUITests
  - CYFinance/CYCommon/Vendor
  - CYFinance/CYCommon/Core/Model
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# function both length
function_body_length:
  warning: 200
  error: 300
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  allowed_symbols: "_"
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  allowed_symbols: "_"
  min_length: 1 # only min_length
  max_length:
    warning: 40
    error: 50 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)

I have exclued the Pods file ,but some pods file still be compiled.
For Example ,the Rxswift file .

![image](https://user-images.githubusercontent.com/3926757/99949987-dbcee800-2db6-11eb-9ebb-0df8f5276469.png)
what's wrong with my switlint

**Comment by kyleYang** [comment]
Why the excluded files ,also be compiled

**Comment by Nonuld** [comment]
Is your `.swiftlint.yml` file at the root of your project ? 
Paths are resolved using the position of your configuration file.

On another note, you should have included the content of your configuration file using code block, it would have been more readable.
