### ISSUE TITLE
swiftlint crashes immediately

### ISSUE THREAD

**Issue by WhyNotHugo** [realm/SwiftLint#3447]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
  - Both via brew and the `Pkg` provided in GitHub releases.
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

```con
$ swiftlint
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file SourceKittenFramework/library_wrapper.swift, line 39
zsh: illegal hardware instruction  swiftlint
```

##### Complete output when running SwiftLint, including the stack trace and command used

```con
$ swiftlint lint
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file SourceKittenFramework/library_wrapper.swift, line 39
Illegal instruction: 4
```

### Environment

```con
$ swiftlint version
0.41.0
$ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

I'm not very knowledgeable when it comes to macOS, but I'm happy to help debug this further.

**Comment by jpsim** [comment]
How'd you install SwiftLint? What version(s) of Xcode do you have installed and where are they on your system? What version of macOS are you running? Do other commands like `swiftlint version` or `swiftlint help` work?

**Comment by jpsim** [comment]
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Ah, it seems like this might be the issue. You might need to install Xcode: https://developer.apple.com/xcode/

**Comment by WhyNotHugo** [comment]
Xcode is installed and running (I've built a "hello world" for iOS and ran that in the simulator).

```con
bash-3.2$ which swiftlint
/usr/local/bin/swiftlint
bash-3.2$ which xcodebuild
/usr/bin/xcodebuild
```
> How'd you install SwiftLint?

I tried installing with `brew` and then [after uninstalling via brew] downloading from GitHub release.

> What version(s) of Xcode
> where are they on your system?

Xcode 12.2, installed via the App Store.

> What version of macOS are you running?

Big Sur 11.0

**Comment by jpsim** [comment]
And `xcodebuild -version`?

**Comment by WhyNotHugo** [comment]
```console
$ xcodebuild --version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Found some help online that I needed to run `xcode-select -s /Applications/Xcode.app/Contents/Developer/` to fix this (I've no idea how this broke).

After reinstalling with brew it now works. Thanks for the help!

**Comment by WhyNotHugo** [comment]
Closing since it seems the issue was on my end -- though, again, I've no idea how things broke; this installation is about 2 days old :sweat_smile:

**Comment by cameronsstone** [comment]
Thank you for documenting, @WhyNotHugo. I had the same problem, and your fix worked for me, too.
