### ISSUE TITLE
Except make install, is there other way to build the swiftlint excutable file?

### ISSUE THREAD

**Issue by sfasdas** [realm/SwiftLint#3448]
I want to develop swiftlint and test it, after I modify project I hava to use "make install" command to get my new product, and then test it. This is so tedious. 
Is there other way to build the swiftlint excutable file? And what did command "make install" exactly do?

I also notice these is a Extract CLI Tool phase in swiftlint target, I try to use the swiftlint excutable file mentioned in this phase that is "$(BUILT_PRODUCTS_DIR)/$(EXECUTABLE_NAME)". This swiftlint file is only about 3M, compare to the almost 13M file got from "make install"

And I finally got a "dylb: Library not loaded: @rpath/Commandant.framework/Commandant" error. What about this "$(BUILT_PRODUCTS_DIR)/$(EXECUTABLE_NAME)" file is use to? and compare "make install" file, what is missing from it?

Any reply will be appreciated!!!

**Comment by jpsim** [comment]
To develop and test SwiftLint locally, I recommend following the steps outlined in the CONTRIBUTING.md doc: https://github.com/realm/SwiftLint/blob/master/CONTRIBUTING.md#building-and-running-locally

Let me know once you've had a chance to try that to see if that workflow works for you.
