### ISSUE TITLE
Integrated Linting has stopped working in Xcode 12.2

### ISSUE THREAD

**Issue by uryyakir** [realm/SwiftLint#3449]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
Hi,
I'm very new to using SwiftLint & been loving the tool so far.
However, yesterday I updated my Xcode IDE to the newest version (12.2).
Since the update, integrated Linting within Xcode has **stopped working**.
As suggested in the README, I'm using CocoaPods to install SwiftLint, and using a script within my target's build phases to enable linting.
This is my script:
```
"${PODS_ROOT}/SwiftLint/swiftlint"
```
I've placed that script right before the "Compile Sources" phase.

Running SwiftLint from the command line (_/path/to/project/Pods/SwiftLint/swiftlint_) works perfectly.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? **0.41.0**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **CocoaPods**
* Paste your configuration file:
```.swiftlint.yml
# insert yaml contents here
line_length:
- 500  # warning

disabled_rules:
- identifier_name
- implicit_getter
- statement_position
- large_tuple

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents. **no**
* Which Xcode version are you using (check `xcodebuild -version`)? **12.2**
* Do you have a sample that shows the issue?

**Comment by uryyakir** [comment]
damn, aliasing swiftlint solved my issue:
```
alias swiftlint='/path/to/project/Pods/SwiftLint/swiftlint'
```

**Comment by casperson** [comment]
Where did you put this alias?

**Comment by casperson** [comment]
> damn, aliasing swiftlint from my project's root directory solved my issue:
> 
> ```
> alias swiftlint='/path/to/project/Pods/SwiftLint/swiftlint'
> ```

Where did you put this alias?

**Comment by uryyakir** [comment]
@casperson What do you mean? This is a terminal command. You just need to run the command and you should have that alias ready for use.

**Comment by casperson** [comment]
I mean, running it there, would that persist the alias with my project? Like if I were to run swiftlint in CI?

**Comment by uryyakir** [comment]
I don't think so. This command only applies the alias to your private terminal/computer.
