### ISSUE TITLE
Handle Package.resolved changes

### ISSUE THREAD

**Issue by fredpi** [realm/SwiftLint#3463]
When SwiftLint is developed by opening the `Package.swift` file, it seems like Xcode is automatically upgrading (or sometimes even downgrading ?!) the dependencies and, as a result, also updating the `Package.resolved` file. In some recent commits (82e5870a16da77c4724c296937b9529e7889ad78, 01b1001a8169081da9c26c27d8487ced979ee92a) that change was committed to git. When you work on SwiftLint and don't want to commit the automatic change of the `Package.resolved` file to git, that's always a hassle.

I wonder if there is anything we can do about this. I guess just gitignoring the `Package.resolved` file is considered bad style and also a bit "dangerous" in that the notion of the currently used dependency version might diverge among different checkouts of the repository.

But maybe there is also an option to prevent Xcode from always updating dependencies if it isn't explicitly asked to do so.

**Comment by fredpi** [comment]
As an example, these are the changes to the `Package.resolved` file that "happen" when I open SwiftLint's `Package.swift` with Xcode 12.2. (Using the current `master`, f8bc10aaaa6e5bd36e9e184f67b6b254fee7bafe):

<img width="400" alt="Package resolved_changes" src="https://user-images.githubusercontent.com/19194800/101920738-73f90980-3bcc-11eb-8a54-ce3947c1ceb6.png">

**Comment by jpsim** [comment]
Worth filing feedback with Apple about this.

**Comment by fredpi** [comment]
@jpsim Which Xcode version did you use for the commits I referenced in the initial issue?

**Comment by jpsim** [comment]
Xcode 12.2 RC I believe.
