### ISSUE TITLE
no tooltips in Editor if project name contains apostrophe

### ISSUE THREAD

**Issue by godbout** [realm/SwiftLint#3480]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

might be related to https://github.com/realm/SwiftLint/issues/1612

### Describe the bug

it's the first time i try SwiftLint. my main project is called `macO'Vim`. the linting gives correct feedback in the `Issue Navigator` but nothing shows up in the `Editors`. 

i've made several tests. projects called `macOVim`, `test`, `testAgain` all work. projects called `macO'Vim`, `tes't`, `testAg'ain` all don't work.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.42.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? homebrew
* Xcode 12.3

i didn't bother (yet, at least) with the yml file as the issue happens before. let me know if you need more info. thanks!

**Comment by godbout** [comment]
`swift-format` from Apple has the same issue. so i guess it's an Xcode thing rather than SwiftLint. probably time to rename my project, then.

**Comment by jpsim** [comment]
This might be an Xcode limitation, have you tried filing a Radar with Apple? In any case, I don't see how this is actionable on our side right now without a way to do this in Xcode.
