### ISSUE TITLE
Illegal Hardware Instruction

### ISSUE THREAD

**Issue by lawgimenez** [realm/SwiftLint#3483]
### New Issue Checklist

- [x ] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When I run `swiftlint analyze` it will generate an error
```
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file SourceKittenFramework/library_wrapper.swift, line 39
zsh: illegal hardware instruction  swiftlint analyze
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
swiftlint lint
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file SourceKittenFramework/library_wrapper.swift, line 39
zsh: illegal hardware instruction  swiftlint lint
lawrencegimenez@Lawrences-MacBook-Pro OnlineJobsPH % 
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.42.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
# insert yaml contents here
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
let foo = try! bar()
```

**Comment by stefanozanella** [comment]
I'm also experiencing this from a clean environment installation.

**Comment by jpsim** [comment]
What's the result of `xcode-select -p` and `xcodebuild -version`?

**Comment by stefanozanella** [comment]
```

**Comment by stefanozanella** [comment]
Ok, changing the active developer directory with `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` seems to have fixed the problem for me.

**Comment by jpsim** [comment]
Yup, SwiftLint needs xcode-select to be pointed to a valid Xcode installation.

**Comment by bgoncal** [comment]
I am having this issue with Xcode 26 Beta 6 and 7 but not Xcode beta 5 for some reason, any ideas? xcode-select does not fixes the issue for me in this case.
