### ISSUE TITLE
`SwiftLint` binary size duplicated when installed via `cocoapods`

### ISSUE THREAD

**Issue by mathaeus** [realm/SwiftLint#3497]
Hi, more of a question than a bug report, but I noticed that the `SwiftLint` binary (when installed via `cocoapods`) basically duplicated in size (I updated from `0.40.0` to `0.42.0`).

I was just wondering if this is known and what's the cause for that? Thanks.

<img width="599" alt="Screenshot 2021-01-21 at 12 56 25" src="https://user-images.githubusercontent.com/5389635/105354345-574aeb00-5be8-11eb-9a85-d3ccf3340140.png">

### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

**Comment by jpsim** [comment]
We now build a universal binary for both Intel and Apple Silicon 😄 

See 88d77a3211bf2a3831910fa8714061fc88fbf21c

**Comment by mathaeus** [comment]
I see, thanks for the clarification @jpsim
