### ISSUE TITLE
[CI] Fix OSSCheck Reports

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#3533]
I don't know how long this has been the case, but they're incredibly noisy, presumably because they're not comparing the right git revisions.

For example: https://github.com/realm/SwiftLint/pull/3532#issuecomment-784550902

![image](https://user-images.githubusercontent.com/474794/108917593-d450f200-75e4-11eb-9adc-b44162cd2fcc.png)

OSSCheck is supposed to handle this by using `git merge-base origin/master`, but clearly it's not working. https://github.com/realm/SwiftLint/blob/0.43.0-rc.3/script/oss-check#L265

**Comment by fredpi** [comment]
I also experienced the issue in the following PR: https://github.com/realm/SwiftLint/pull/3491. To better understand it, I created a test PR (https://github.com/realm/SwiftLint/pull/3493) with just variable name changes, and got far less warnings (only the `inclusive_language` warning that appears in almost every PR).

Maybe this example helps with fixing the underlaying issue.

**Comment by jpsim** [comment]
Attempting to fix in https://github.com/realm/SwiftLint/pull/3550

> only the `inclusive_language` warning that appears in almost every PR

I think this is because the rule's output was non-deterministic if a declaration had more than one violation. I'm also fixing that in my PR above.

**Comment by jpsim** [comment]
Hopefully fixed in #3550. Time will tell.
