### ISSUE TITLE
[XCode12.4] Compile time error when installed through SPM

### ISSUE THREAD

**Issue by monica18p** [realm/SwiftLint#3556]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Got following compile time error:

- `/Users/XXX/Xcode/DerivedData/<Project>/SourcePackages/checkouts/SourceKitten/Source/SourceKittenFramework/Exec.swift:60:23: Cannot find 'Process' in scope`

- `/Users/XXX/Xcode/DerivedData/<Project>/SourcePackages/checkouts/SourceKitten/Source/SourceKittenFramework/JSONOutput.swift:20:41: 'sortedKeys' is only available in iOS 11.0 or newer`

### System Config

`swift --version`

> Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
> Target: x86_64-apple-darwin20.1.0

`xcode version`
> 12.4

Kindly assist to resolve the issue. I created a new project and added SwiftLint using SPM through Xcode

**Comment by jpsim** [comment]
Looks like you’re trying to build SwiftLint for iOS. SwiftLint can only be compiled to run on macOS and Linux.

**Comment by monica18p** [comment]
> Looks like you’re trying to build SwiftLint for iOS. SwiftLint can only be compiled to run on macOS and Linux.

Oh... My mistake.. I was looking for swift lint for my iOS projects.
Thanks for the prompt help. I will close this ticket.
