### ISSUE TITLE
File Length Rule has the wrong name

### ISSUE THREAD

**Issue by onato** [realm/SwiftLint#3560]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The name of the File Length rule is **"File Line Length"** when it should be **"File Length"**. Line length is confusing as it seems to refer to the length of lines rater than the number of them. An alternative might be “File Line Count”.

https://github.com/realm/SwiftLint/blob/058869f4465618fa259c06f9f4bceeb840287a50/Source/SwiftLintFramework/Rules/Metrics/FileLengthRule.swift#L10

<img width="627" alt="Screen Shot 2021-03-08 at 12 08 29 PM" src="https://user-images.githubusercontent.com/107999/110258345-057aea80-8007-11eb-89d3-a3b14a69f2e9.png">

**Comment by marcelofabri** [comment]
Closed in #3561
