### ISSUE TITLE
SwiftLint installed via Homebrew cannot be run from Xcode by documented script

### ISSUE THREAD

**Issue by AlesMMichalek** [realm/SwiftLint#3576]
### New Issue Checklist

- [x ] Updated SwiftLint to the latest version
- [x ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Newly Homebrew uses different prefix `/opt/homebrew`, what means all links are located in `/opt/homebrew/bin`. From Command-line `SwiftLint` works fine, because this folder is correctly added into `PATH`, but Xcode has own `PATH` definition. It means the build step based on documented script does not work.

Please, update documentation for Xcode how to run `SwiftLint` from build step.

### Environment

* macOS 11.2.3 Big Sur on Apple Silicon
* Homebrew version 3.0.5
* SwiftLint version (run `swiftlint version` to be sure)? 0.43.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 12.4 (12D4e)

**Comment by asolovev** [comment]
Looks like it will be fixed in #3527

**Comment by SimplyDanny** [comment]
Thank you for bringing this up! The README has meanwhile been updated with #3903. If you feel the current description is still not sufficient, please reopen this issue.
