### ISSUE TITLE
XCODE 12.4 Warning dissappear

### ISSUE THREAD

**Issue by jesusmateos1234** [realm/SwiftLint#3580]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When use from buildPhase swiftlint warnings dissappear after build the app. Same with --restrict method

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

**Comment by sethfri** [comment]
Hi @jesusmateos1234, I am able to see SwiftLint warnings fine in Xcode 12.4 and 12.5. It would really help us to be able to help you if you could attach an Xcode project that reproduces the issue you're describing.

Also, I'm not quite sure what you're describing here:

> When use from buildPhase swiftlint warnings dissappear after build the app

Do you mean you build the app once, the warnings appear, and then when you build the app again they disappear? Or do you mean they never appear in the first place?

Thank you!

**Comment by Tridie2000** [comment]
Hi @sethfri 

I think I'm running into the same issue where SwiftLint warnings disappear after the app has been built. The warnings appear briefly while building the app, but as soon as the "successful build"-toast appears, the SwiftLint, and only the SwiftLint warnings disappear. 

I've narrowed it down to a specific Run Script Phase. In one of my projects I use a script to sort the files and folders in the Xcode project alphabetically. It doesn't matter if you run this script before SwiftLint or after SwiftLint, when you run it, all SwiftLint warnings disappear after the app has been built.

I've attached a small sample project with only SwiftLint and the sort-script installed.

[SwiftLint No Error Test.zip](https://github.com/realm/SwiftLint/files/7774017/SwiftLint.No.Error.Test.zip)

**Comment by Tridie2000** [comment]
This doesn't appear to be a SwiftLint specific issue since all warnings disappear.

**Comment by sethfri** [comment]
@Tridie2000 I agree with you that this doesn't seem like a SwiftLint issue.

However, just as a friendly tip: That doesn't feel like something I'd want to do in a run script build phase anyway. I wouldn't want the project to change out from under me while I'm trying to build it (which is probably why Xcode bails on showing you warnings).

You might want to consider a [pre-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) instead. Good luck!
