### ISSUE TITLE
After applying explicit_acl, Xcode complains to remove it   

### ISSUE THREAD

**Issue by alok-dks** [realm/SwiftLint#3582]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

how to make xcode stop complaining when start using explicit_acl and putting internal in from of functions.
`internal' modifier is redundant for property declared in an internal ext`

**Comment by marcelofabri** [comment]
Can you provide an example?
