### ISSUE TITLE
Docs on `type_name` includes wrong "Non Triggering Examples"

### ISSUE THREAD

**Issue by tobihagemann** [realm/SwiftLint#3593]
Not sure if I'm right about this one since I'm just starting out with SwiftLint but I noticed some "non triggering examples" on the `type_name` documentation that should be in "triggering examples". https://realm.github.io/SwiftLint/type_name.html

Basically all "non triggering examples" that have an underscore (`_`) should be listed under "triggering examples" instead because:

> Type name should only contain alphanumeric characters [...]

Or did I miss something?

**Comment by SimplyDanny** [comment]
You are right. Some of the examples are not clear. The rule allows private types to start with an underscore. This is now mentioned in the description. Also, the number of examples has been reduced hiding some confusing examples only relevant for thorough testing.
