### ISSUE TITLE
`weak_delegate`: @NSApplicationDelegateAdaptor should be excepted

### ISSUE THREAD

**Issue by tillhainbach** [realm/SwiftLint#3598]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

This is a complement to #3456:

The weak delegate rule fires on the following declaration, which is not appropriate:

@NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

I will create a PR follow up PR, complementing the exception for these SwiftUI specified wrappers.

**Comment by circAssimilate** [comment]
I noticed that #3599 is approved but not merged. In case it wasn't clear to anyone the kinda difficult to arrive at workaround is this.

```
struct TimeTravelApp: App {
  // swiftlint:disable:next weak_delegate
  @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
```
