### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by eimantas** [realm/SwiftLint#36]
I cloned this repo and, seeing Cartfile, ran `carthage update`. This is what I saw in workspace navigator once the command completed:

![screen shot 2015-05-26 at 10 41 54](https://cloud.githubusercontent.com/assets/551543/7807389/dae150c0-0393-11e5-8836-86dff77edbca.png)

Needless to say, the build failed. Is there some other command I need to run in terminal?

**Comment by beltex** [comment]
Hi @eimantas!

`make install` should take care of everything.

**Comment by eimantas** [comment]
Thanks! That did the trick. Is there any fast way to check the rules I develop? Running `make install` each time seems counterproductive.

**Comment by jpsim** [comment]
Once the submodules are available locally, all the standard Xcode operations should be supported (build, analyze, test, run, etc.).
