### ISSUE TITLE
Default Config throws 999+ warnings and 800 errors in a little project

### ISSUE THREAD

**Issue by timmkent** [realm/SwiftLint#3600]
When installing SwiftLint it seams not to be coming with a good default configuration. Even in a little project it throws me above mentioned amount of problems.
That's not helpful guys.
We want tool like this to optimise our code and save us time. If I need to set-up a complicated config file for myself and spend hours in reducing little errors the tool is more of a burden than a help.

So please, provide a good default config that will not overwhelm you with errors.

**Comment by marcelofabri** [comment]
Sorry you don't think that a project that several people have contributed hundreds (if not thousands) of hours for free is not useful. 

SwiftLint is meant to be opinionated but flexible - if the default behavior is not what you want, there are several ways to tweak it with custom configurations, disabling rules, etc.
