### ISSUE TITLE
Couldn't disable `redundant_nil_coalescing` in code.

### ISSUE THREAD

**Issue by iWECon** [realm/SwiftLint#3608]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

couldn't disable redundant_nil_coalescing in code:
```
// swiftlint:disable:next redundant_nil_coalescing

@Routable(["pastCpId", "pastCoupleId"]) var pastCoupleId: String? = nil

@Routable(["cpId", "coupleId"]) var coupleId: String? = nil

// swiftlint:disable:previous redundant_nil_coalescing
```

the `swiftlint autocorrect` always be fixing that.

**Comment by marcelofabri** [comment]
`// swiftlint:disable:next` disables violations on the next line only. Same for previous, disabling violations for the previous line.

In your case, either you want to remove `:next` and `:previous` so they act as a "begin"/"end" or remove the empty lines between the comments and the code.
