### ISSUE TITLE
Support for `import` `match_kinds` in custom rules

### ISSUE THREAD

**Issue by danyf90** [realm/SwiftLint#3609]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

For some custom rules it might be helpful to check that some target is not imported in any source file.
Do you think it would be possible to add `import` among the available `match_kinds`?

**Comment by marcelofabri** [comment]
This is not how `match_kinds` work. It's for syntactic information - so an `import` would be a `keyword`.

I recommend you to install [SourceKitten](https://github.com/jpsim/SourceKitten) and then run `sourcekitten syntax --file file.swift` to see what's available for you.
