### ISSUE TITLE
Adhering to untyped_error_in_catch for type `Error` causes Xcode warning "'as' test is always true"

### ISSUE THREAD

**Issue by cuddergambino** [realm/SwiftLint#3614]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

SwifLint rule untyped_error_in_catch requires declaring the error type, however declaring the error type `Error` causes the Xcode warning "'as' test is always true".
In order to work with the xcode warning, SwiftLint should not require a type for the error type `Error`.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```
Output:
```
warning: Untyped Error in Catch Violation: warning (untyped_error_in_catch)
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? Yes
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
opt_in_rules:
  - untyped_error_in_catch
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 12.4, Build version 12D4e
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
do {
    let data = try result.get()
    print(data)
} catch let error { // This triggers a SwiftLint violation
                              // Untyped Error in Catch Violation: warning (untyped_error_in_catch)
    print(error)
}
```

```swift
do {
    let data = try result.get()
    print(data)
} catch let error as Error { // This triggers an Xcode violation
                                            // 'as' test is always true
    print(error)
}
```

**Comment by marcelofabri** [comment]
The idea of this rule is that `error` is the default name anyway, so you can just use:

```swift
do {
  // ...
} catch {
  print(error)
}
```

**Comment by SimplyDanny** [comment]
If you always want to rename the error, you may not enable the rule at all. If this is only at some places, a `// swiftlint:disable:this untyped_error_in_catch` can be used. I don't think there is a need for a fix or another option here.

Feel free to reopen the issue if you do not agree with me.
