### ISSUE TITLE
README presentation _Watch Your Language!_ media missing.

### ISSUE THREAD

**Issue by jasonzurita** [realm/SwiftLint#3619]
### New Issue Checklist

- [n/a] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Looks like the linked to [presentation in the README](https://github.com/realm/SwiftLint#presentation) is missing the actual video. Not sure if this is the right place to flag this, but given that it is one of the first things in the README I figured I would try here.

**Comment by SimplyDanny** [comment]
Link updated in #4360.
