### ISSUE TITLE
Found multiple rules violation in Xcode 12.5 (almost 200 errors) but not in Xcode 12.4

### ISSUE THREAD

**Issue by tapan-nathvani** [realm/SwiftLint#3623]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version - YES
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues) - YES

### Describe the bug

I Have installed SwiftLint through Brew in MacBook Air M1. I am using Xcode 12.5 and found that in my existing project which works fine in Xcode 12.4 with intel processor but in the current machine that M1 have 200+ errors regarding rules violation. Even found issues in Alamofire (i.e 3rd Party Framework). So what should be the best way to resolve this issue? We did not add any custom rules or no any yml file. We are using default rules that is provided by SwiftLint.

* SwiftLint version (run `swiftlint version` to be sure)? -> 0.43.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? -> Homebrew

**Comment by marcelofabri** [comment]
Can you list the rules that are triggering violations? I assume it's a subset of the rules mentioned in https://github.com/realm/SwiftLint/pull/3618, but it'd be good to confirm

**Comment by tapan-nathvani** [comment]
1. Line Length Violation: Line should be 200 characters or less: currently 285 characters (line_length)
2. Identifier Name Violation: Variable name should be between 3 and 40 characters long: 'i' (identifier_name)

All the errors are related to above rules violation.

**Comment by marcelofabri** [comment]
Are you sure SwiftLint is actually being run on the first machine? I'd be really surprised if line length (and even identifier name) rule broke on Xcode 12.5.

Can you run SwiftLint manually from the terminal in both machines to confirm?

**Comment by tapan-nathvani** [comment]
Ok. Can you please tell me how to run SwiftLint from terminal? I'll check with both the machines.

**Comment by marcelofabri** [comment]
If SwiftLint was installed with Homebrew, just running `swiftlint` inside the project folder should be enough.

**Comment by tapan-nathvani** [comment]
I have checked with older machine.. It works fine there.. there is no any serious issue in that machine. I have uninstall home-brew & SwiftLint and install it again but facing the same issues.

**Comment by marcelofabri** [comment]
Can you please:

1. Isolate one file that demos the issue and post it here
2. Run `swiftlint lint --path file.swift`
3. Paste the whole output here

**Comment by tapan-nathvani** [comment]
Hi @marcelofabri , Issue is fixed now. Actually they didn't push the yml file (Which has custom rules) thats why I was facing the error. Thanks for the support.
