### ISSUE TITLE
Add Buildkite config to repo

### ISSUE THREAD

**Issue by sethfri** [realm/SwiftLint#3637]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

It was difficult to troubleshoot why Buildkite wasn't working in #3583 because I couldn't find the relevant configuration. I looked in the `Dangerfile` and `azure-pipelines.yml`, but I still couldn't figure out how the Buildkite check was getting triggered. It turns out it's because the CI job was removed from Azure Pipelines in https://github.com/realm/SwiftLint/pull/2941.

It would be great to check in the Buildkite configuration to make it easy for contributors to inspect how the code in their PRs is getting run, and even allow for PRs on the configuration itself so that contributors might make improvements.

Thanks, as always, for all you do @jpsim!

**Comment by SimplyDanny** [comment]
Done in #3893.
