### ISSUE TITLE
SourceKitten dependency is broken when compiling swiftlint with SPM in XCode 13 beta 2

### ISSUE THREAD

**Issue by didix21** [realm/SwiftLint#3674]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

SourceKitten dependency is broken when compiling swiftlint with SPM in XCode 13 beta 2

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
swift run -c release --package-path BuildTools swiftlint lint --strict .
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization

[0/13] Compiling Swift Module 'Files' (1 sources)warning: failed to load the cached build description: fatalError
/Users/didaccollpujals/repos/localfilter/BuildTools/.build/checkouts/SourceKitten/Source/SourceKittenFramework/Request.swift:243:58: error: cannot convert value of type 'Int' to expected dictionary value type 'Int64'
                    "key.editor.format.usetabs": useTabs ? 1 : 0
                                                         ^
error: fatalError
```

### Environment

* SwiftLint version: `.package(url: "https://github.com/realm/SwiftLint.git", .exact("0.43.1"))`
* Installation method used: Swift package management
* Which Xcode version are you using:
```bash
Xcode 13.0 beta 2
Build version 13A5155e
```

**Comment by robmontesinos** [comment]
same issue here: Xcode 13.0 beta 2

**Comment by eduls7** [comment]
Same issue here
Xcode 12.5. 
iOS Target 14.5
Swift 5

**Comment by jpsim** [comment]
Closing assuming fixed.
