### ISSUE TITLE
SourceKitten dependency is broken when installing with SPM

### ISSUE THREAD

**Issue by dbeleza** [realm/SwiftLint#3681]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

After installing SwiftLint using SPM, Xcode (version 12.5.1) is retrieving me this errors:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/4144018/126360024-1c14f68a-0476-46ec-8182-0affb1eef2a2.png">

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? **0.43.1**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **SPM**

Am I doing something wrong?

Thanks for your help

**Comment by dmytriigolovanov** [comment]
I had the same issue in project

**Comment by OlegEremenko991** [comment]
I have the same issue in the project. Xcode 13.2, project iOS deployment target: 11.4

**Comment by anish190** [comment]
Try unchecking SwiftLintFrameworks and swiftlint to your targets.

https://github.com/realm/SwiftLint/issues/3073#issuecomment-934301131

**Comment by jpsim** [comment]
SwiftLint can only be compiled against the macOS or Linux platform. SwiftLint can't run on iOS because it depends on SourceKit, which is only available on macOS & Linux.
