### ISSUE TITLE
`implicit_return` rule autocorrect output changes depending on swift version used

### ISSUE THREAD

**Issue by fabfelici** [realm/SwiftLint#3685]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

By using this file as input:
```swift
final class Test {
  var foo: Bool {
    return true
  }

  func test() -> Bool {
    return true
  }

  func testClosure() -> Void -> Bool {
    return { return true }
  }
}
```
And this SwiftLint config:
```yaml
opt_in_rules:
 - implicit_return

implicit_return:
    included:
        - closure
        - getter
```
The output of `swiftlint autocorrect` for closures changes depending on the swift version being used.
Using XCode 12.4:
```
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.4.0
```
The file gets correctly corrected to:
```swift
final class Test {
  var foo: Bool {
    true
  }

  func test() -> Bool {
    return true
  }

  func testClosure() -> Void -> Bool {
    return { true }
  }
}
```
Using XCode 12.5:
```
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.4.0
```
The file gets corrected to:
```swift
final class Test {
  var foo: Bool {
    true
  }

  func test() -> Bool {
    return true
  }

  func testClosure() -> Void -> Bool {
    return { return true }
  }
}

```
So as you can see the closure `return` is still there.

##### Complete output when running SwiftLint, including the stack trace and command used

Using XCode 12.4 build system
```bash
$ swiftlint autocorrect 
Loading configuration from '.swiftlint.yml'
Correcting Swift files at paths 
Correcting 'Test.swift' (1/1)
/Path/SwiftLintTest/Test.swift:11:14 Corrected Implicit Return
/Path/SwiftLintTest/Test.swift:3:5 Corrected Implicit Return
Done correcting 1 file!
```

Using XCode 12.5 build system
```bash
$ swiftlint autocorrect 
Loading configuration from '.swiftlint.yml'
Correcting Swift files at paths 
Correcting 'Test.swift' (1/1)
/Path/SwiftLintTest/Test.swift:3:5 Corrected Implicit Return
Done correcting 1 file!
```
### Environment

* SwiftLint version: 0.40.0 (I tested latest version 0.43 using `--fix` and I got the same issue)
* Installation method used: CocoaPods

**Comment by marcelofabri** [comment]
Fixed in #3618

**Comment by fabfelici** [comment]
Tested using 0.43.1 and this issue is still there

**Comment by marcelofabri** [comment]
This is currently only on `master`.
