### ISSUE TITLE
Homebrew install in app using SPM results in error "Currently running SwiftLint 0.43.1 but configuration specified version 0.39.2."

### ISSUE THREAD

**Issue by AttilaTheFun** [realm/SwiftLint#3707]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I'm trying to add SwiftLint to my project. I have an xcworkspace with with two application targets and many embedded swift package manager packages which each have many static libraries. I installed SwiftLint via homebrew and `swiftlint version gives `0.43.1`.

I added a run script phase after 'Compile Sources' with the following:

```
if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
Currently running SwiftLint 0.43.1 but configuration specified version 0.39.2.
```

I don't have a configuration file, so I'm not sure which configuration it is specifying. Do I have to create a configuration file? Are there instructions available for doing so? Thanks!

**Comment by akhilccrb** [comment]
Same for me.

**Comment by jpsim** [comment]
I suspect that in somewhere in your Xcode project you're pulling in a dependency that has a SwiftLint configuration file that specifies that the exact version of SwiftLint should be used, and that either its build script or yours is linting the files from that dependency.

Take a look at your dependencies and see which one has a `.swiftlint.yml` file that has `swiftlint_version: "0.39.2"` specified.

If that's indeed what's happening, then I suggest you create a SwiftLint configuration file (`.swiftlint.yml`) that specifies the paths to lint. For example:

```yaml
include:
  - Sources
  - Tests
```

**Comment by AttilaTheFun** [comment]
Thanks @jpsim! That helped. The issue was that the default checkout location for swift package manager sources is PackageName/.build/... and because some of the packages I'm using used SwiftLint, it was finding their config files. I added an exclude rule to just ignore everything under it -- "**/.build/**". I'd maybe recommend updating the SPM instructions to tell people to exclude those files because otherwise SwiftLint will find their SPM caches and it could cause problems.
