### ISSUE TITLE
redundant_optional_initialization removes opening bracket before property observer 

### ISSUE THREAD

**Issue by maikasshoff** [realm/SwiftLint#3718]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The redundant_optional_initialization rule removes the opening bracket before a property observer which causes a syntax issue. For example 

```swift
var foo: String? = nil {
  didSet {
    print("foo")
  }
}
```

is changed to 

```swift
var foo: String?
  didSet {
    print("foo")
  }
}
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint       

Linting Swift files in current working directory
Linting 'Foo.swift' (1/1)
/Foo.swift:3:21: warning: Redundant Optional Initialization Violation: Initializing an optional variable with nil is redundant. (redundant_optional_initialization)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

 ```bash
$ swiftlint version
swiftlint version
0.44.0
```

@iressler

**Comment by naru-jpn** [comment]
Hi, I found same problem and created PR to fix this issue 👍  #3717

**Comment by morluna** [comment]
This is breaking our workflow since our development team uses the Homebrew installation of `swiftlint` for analysis 😔 Our workaround is to disable the rule for now, but a fix would be appreciated. Thanks @naru-jpn for the fix.

**Comment by BrunoVillanova-SaudeID** [comment]
Awaiting PR merge and release.

**Comment by maartenbusstra** [comment]
We ran into this issue as well. For good measure, we're turning off automatically fixing issues in CI, as the underlying project shouldn't change when publishing builds.

**Comment by jonas-simkus-mw** [comment]
This is not fixed, still an issue so many years later.

**Comment by SimplyDanny** [comment]
> This is not fixed, still an issue so many years later.

Luckily, you're now here to change that!🙏
