### ISSUE TITLE
What should be the path of SwiftLint when installed with Swift Package Dependency

### ISSUE THREAD

**Issue by fuxlud** [realm/SwiftLint#3734]
I have installed SwiftLint with Swift Package Dependancy. I have added the following Run script in Build Phases as described in the manual:

```
if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

When running my project, I receive the warning message:

> warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint

So I guess thy system can't find the swiftlint executable. Where is it located if installed with Swift Package Dependency?

**Comment by martinmose** [comment]
Not that it solves your concrete issue I would suggest to install SwiftLint with Homebrew (`brew install swiftlint`) or Mint (`mint install realm/SwiftLint`) take a look at:
https://stackoverflow.com/a/58036391/1528427
I would prefer to install it with Mint.

Then in your Build Phase add the following:
```
if test -d "/opt/homebrew/bin/"; then
  PATH="/opt/homebrew/bin/:${PATH}"
fi

export PATH

if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, run setup.sh (or download from https://github.com/realm/SwiftLint)"
fi
```

I would agree with you it would be nice with a updated documentation for SwiftLint when using SPM or even better a recommendation like what I have tried to do here :).

**Comment by alandeguz** [comment]
@fuxlud @martinmose I was able to get the most recent version (0.45.1) to work natively with Swift Package Manger (without Homebrew nor any other external installation) with the following steps. 

1. Add SwiftLint via SPM normally, but leave both **SwiftLintFramework** (Library) and **swiftlint** (Executable) unchecked [choose image](https://user-images.githubusercontent.com/4161830/146976597-a6d40e51-1e49-41bf-a9ae-90d7394ee342.png).

2. Add the following **Run Script** to **Build Phases**. 

```
# Don't run this during index builds
if [ $ACTION = "indexbuild" ]; then exit 0; fi

# Go to the build root and search up the chain to find the Derived Data Path where the source packages are checked out.
DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"

while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
  if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
    echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
    exit 1
  fi

  DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
done

# Grab a reference to the directory where scripts are checked out
SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/SwiftLint"

if [ -z "${SCRIPT_PATH}" ]; then
    echo >&2 "error: Couldn't find the SwiftLint script in your checked out SPM packages; make sure to add the framework to your project."
    exit 1
fi

CURRENT_DIR=`pwd`

cd "${SCRIPT_PATH}"/Source

/usr/bin/xcrun --sdk macosx swift run swiftlint "${CURRENT_DIR}"
```

**Comment by OlegEremenko991** [comment]
> 

Hey, your script results in fatal error, how can I solve it?

`invalid access to /Users/*/Library/Developer/Xcode/DerivedData/*/SourcePackages/checkouts/swiftlint/Package.resolved`

**Comment by jpsim** [comment]
Thanks for sharing some various ways to install SwiftLint and where the resulting CLI binary path ends up being located @martinmose @alandeguz. Feel free to enhance the documentation with any improvements you like.
