### ISSUE TITLE
Valid docs rule not covering all closure parameter cases.

### ISSUE THREAD

**Issue by diogoguimaraes** [realm/SwiftLint#375]
I've noticed that some cases are not being covered by the `validDocsRule` and SwiftLint generates wrong warnings, for instance:
* `func foobar (closure1: () -> Foo, closure2: (foobar: Bar) -> Foo, closure3: (foobar: Bar) -> Foo) {`
* `func footer (closure1: (Foo) -> Void, onError closure2: ((NSError) -> Void)? = nil) {`

I'll add a pull request with a fix for this ASAP.

**Comment by jpsim** [comment]
> I'll add a pull request with a fix for this ASAP.

Thanks!
