### ISSUE TITLE
Compilation errors after following new rule prefer_self_in_static_references

### ISSUE THREAD

**Issue by christiankm** [realm/SwiftLint#3768]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

After implementing the new rule in SwiftLint 0.45.1 `prefer_self_in_static_references` and running `swiftlint --fix` our code no longer compiles. This rule is not ignoring some cases where it should not be followed. Please see screenshots:

![Skærmbillede 2021-11-30 kl  15 15 19](https://user-images.githubusercontent.com/3626094/143984891-b854397a-0d6d-4ce7-8705-91dc709f2b17.png)
<img width="1123" alt="Skærmbillede 2021-11-30 kl  15 15 30" src="https://user-images.githubusercontent.com/3626094/143984734-e240776d-da9e-480d-8b01-ff9244d3bf8b.png">

For now, we can just solve this with a `// swiftlint:disable:this` but the rule should be fixed to ignore such cases, and prevent build failures.

### Environment

* SwiftLint version: 0.45.1
* Installation method used: Homebrew
* Paste your configuration file: 

```yml
...

opt_in_rules:
  - prefer_self_in_static_references
...
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No.
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 13.2 Beta 2

**Comment by jpsim** [comment]
Thanks for the report!

**Comment by jpsim** [comment]
@SimplyDanny do you think you'd have time to teach your new rule how to handle this case? It might also be useful to comb through the cases reported by OSSCheck in the original PR (https://github.com/realm/SwiftLint/pull/3732#issuecomment-934640769) to see if there are any other false positives.

**Comment by SimplyDanny** [comment]
Sure. I'll have a look.
