### ISSUE TITLE
implicit_return wrong readme

### ISSUE THREAD

**Issue by NikKovIos** [realm/SwiftLint#3784]
https://realm.github.io/SwiftLint/implicit_return.html

Maybe I wrong, but it seems that some examples not correct:

Non Triggering Examples
foo.map { $0 + 1 }
func foo() -> Int {
    0
}
...

Triggering Examples
foo.map {
    return $0 + 1
}
...

I didn't write all of them.

**Comment by jpsim** [comment]
It's correct, the rule encourages the use of implicit returns.
