### ISSUE TITLE
Localisation: Is there a way to check if all added languages have strings ?

### ISSUE THREAD

**Issue by parvez-keeptruckin** [realm/SwiftLint#3788]
How can we make sure using SwiftLint (if possible) to determine / have some kind of check that will tell us if .strings file in other language besides the main one has some strings missing ? 
For ex: if english language .strings file has 3 keys with english language specific words / sentences, we want to be sure that other languages too must have same number of keys.  This will be especially helpful where lot of people are working on a project which has localisation support so chances are that some strings translations may be missing in one or more languages.

Is there a way to handle this situation ? It is kind of strict compile time checking to avoid issues due to missing strings. We do not want to display default language string in case corresponding key is missing in other languages.

**Comment by jpsim** [comment]
SwiftLint is not ideally suited for this type of task, considering that localization files are often not stored as Swift source code, and SwiftLint only operates on Swift source. I'd recommend using a localizable string codegen tool such as [SwiftGen](https://github.com/SwiftGen/SwiftGen) to solve your problem.
