### ISSUE TITLE
About glob recursive

### ISSUE THREAD

**Issue by funzin** [realm/SwiftLint#3789]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Now, swiftlint uses `glob` library in `libc`.
https://github.com/realm/SwiftLint/blob/86b6392aa22bb4b91a8f033d4dd11c8e4ab87b8f/Source/SwiftLintFramework/Helpers/Glob.swift#L8

But the library doesn’t support about recursive unlike python glob module.
(ref: https://docs.python.org/3/library/glob.html)
Here is an example of a recursive search
```
e.g.
Tmp/Tmp1.swift
Tmp/Tmp2/Tmp1.swift

pattern: Tmp/**/Tmp1.swift

Desirable Result✌️
Tmp/Tmp1.swift
Tmp/Tmp2/Tmp1.swift

Actual Result🥲
Tmp/Tmp2/Tmp1.swift
```

I would like to introduce recursive search in excluded & included options.
I think that glob logic can be replaced in [Globs.swift](https://github.com/nicklockwood/SwiftFormat/blob/5001bf9111a6f7b4030224342c266ad2aa661d78/Sources/Globs.swift) in SwiftFormat

What do you think about replacing glob logic?
 If possible, I would like to hear your opinion & discuss.

**Comment by jpsim** [comment]
I'm up for it. [Pathos](https://github.com/dduan/Pathos) appears to have support for recursive globs, so perhaps we could use that as well.

**Comment by funzin** [comment]
> I'm up for it. [Pathos](https://github.com/dduan/Pathos) appears to have support for recursive globs, so perhaps we could use that as well.

Thank you for  your reply.
I will check Pathos later and then if I have time, I will create PR which replace glob recursive from the original to Pathos :+1:
