### ISSUE TITLE
Swiftlint doesn't do anything in Atom (but works in Xcode).

### ISSUE THREAD

**Issue by amichail** [realm/SwiftLint#381]
I just get "no issues" all the time in Atom.

**Comment by jpsim** [comment]
How did you integrate SwiftLint into Atom If you're using [linter-swiftlint](https://github.com/AtomLinter/linter-swiftlint), you may want to file an issue there.

**Comment by amichail** [comment]
Yes, I used linter and linter-swiftlint.

**Comment by jpsim** [comment]
I see you filed an issue at AtomLinter/linter-swiftlint#7, so I'll close this as the problem is happening in that project.

**Comment by norio-nomura** [comment]
I have created Atom package for SwiftLint. But I have not released it yet because Atom package does not allow duplication of package names.
Now, I just pushed it as fork of https://github.com/AtomLinter/linter-swiftlint, and filed that as a PR https://github.com/AtomLinter/linter-swiftlint/pull/8.

**Comment by norio-nomura** [comment]
FYI, the PR merged and linter-swiftlint 1.0.0 has been released https://atom.io/packages/linter-swiftlint
