### ISSUE TITLE
Function body length should not include nested functions.

### ISSUE THREAD

**Issue by amichail** [realm/SwiftLint#385]
I don't think people should be encouraged to unnest functions to reduce the function body length.

**Comment by fotiDim** [comment]
Any updates on this?

**Comment by poos** [comment]
Any updates on this?

**Comment by Chrylo** [comment]
Sorry for reopening this but I really think this should be implemented. Tools like Detekt for Kotlin also have this feature to ignore nested methods. Now I am forced to extract these Methods to class level which just makes it more visible to other class methods. This is not show the correct intention of the developer "that this code should only be accessed from this method and I just grouped the logic via a nested method".
