### ISSUE TITLE
Make TypeNameRule conform to ConfigurableRule

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#388]
All its options are currently hardcoded: https://github.com/realm/SwiftLint/blob/9d138ad691f55fd016f883eb4044649b150582b7/Source/SwiftLintFramework/Rules/TypeNameRule.swift

**Comment by scottrhoyt** [comment]
I can tackle this if you tell me what you'd like to make configurable. A cursory glance makes the min and max length stand out.  There's a part of me that almost feels this should be broken into a length rule and a case rule.

**Comment by jpsim** [comment]
> Actually 2 length rules if we want to follow the pattern from variable name length rules.

This was done before your dictionary-based configuration efforts. It would make much more sense IMO to have a `type_name_length` rule be configurable on both `min_length` and `max_length`.

**Comment by scottrhoyt** [comment]
That makes sense, and would be more performant.

**Comment by scottrhoyt** [comment]
I can see a good way to accomplish this (as well as do a conversion for the variable rules). It would involve continuing the work of providing standardization on top of `ConfigurableRule`. I foresee the creation of standard configuration structs in this process.
