### ISSUE TITLE
Building for Linux Arm64

### ISSUE THREAD

**Issue by sam-mfb** [realm/SwiftLint#3895]
I'm trying to build this for linux on my M1 Macbook (using Docker).  Here's the Dockerfile I'm using--which is based on the Dockerfile at the root of the repo (which I assume is what is used to build the official Docker images--which are only for amd64)

```
FROM swiftlang/swift:nightly-5.6-focal AS swiftlint-build
RUN apt-get update
RUN apt-get install -y clang libblocksruntime0 libcurl4-openssl-dev libxml2-dev git
RUN git clone https://github.com/realm/SwiftLint.git
WORKDIR SwiftLint
RUN ln -s /usr/lib/swift/_InternalSwiftSyntaxParser .
ARG SWIFT_FLAGS="-c release -Xswiftc -static-stdlib -Xlinker -lCFURLSessionInterface -Xlinker -lCFXMLInterface -Xlinker -lcurl -Xlinker -lxml2 -Xswiftc -I. -Xlinker -fuse-ld=lld -Xlinker -L/usr/lib/swift/linux"
RUN swift build $SWIFT_FLAGS
RUN mkdir -p /executables
RUN for executable in $(swift package completion-tool list-executables); do \
        install -v `swift build $SWIFT_FLAGS --show-bin-path`/$executable /executables; \
    done
```

It starts to compile, but then fails with this as the output at the end

```
#10 9.946 [11/17] Compiling api.c
#10 9.957 remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[12/18] Compiling ArgumentParserToolInfo ToolInfo.swift
#10 10.14 remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[14/20] Compiling SWXMLHash SWXMLHash.swift
#10 19.97 [16/21] Compiling Yams Constructor.swift
#10 20.00 remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[18/23] Compiling ArgumentParser BashCompletionsGenerator.swift
#10 23.46 [20/24] Compiling CryptoSwift AEAD.swift
#10 27.28 [22/25] Compiling SourceKittenFramework ByteCount.swift
#10 111.0 error: compile command failed due to signal 6 (use -v to see invocation)swift-frontend: /home/build-user/llvm-project/llvm/include/llvm/ADT/APInt.h:1646: int64_t llvm::APInt::getSExtValue() const: Assertion `getMinSignedBits() <= 64 && "Too many bits for int64_t"' failed.
#10 111.0 Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
#10 111.0 Stack dump:
#10 111.0 0.	Running pass 'Function Pass Manager' on module '/SwiftLint/.build/aarch64-unknown-linux-gnu/release/SwiftSyntax.build/AbsolutePosition.swift.o'.
#10 111.0 1.	Running pass 'Loop Pass Manager' on function '@"$s11SwiftSyntax0B6ParserO8parseRaw33_FF480AC1827F0899EF1492D28392D5EALLyAA0eB0CSS_AA26IncrementalParseTransitionCSgSSAA16DiagnosticEngineCSgtFZSvSPySo24swiftparse_syntax_node_taGSgcfU_"'
#10 111.0 2.	Running pass 'Loop Strength Reduction' on basic block '%90'
#10 111.0 Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
#10 111.0 /usr/bin/swift-frontend[0x5523b40]
```

Any one able to get an arm64/aarch64 version building?  Or any ideas on how to debug/fix this?

**Comment by jpsim** [comment]
I haven't tried building on arm64 Linux (arm64 on macOS works fine), but have you tried submitting a bug report as the crash says?

> Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace

**Comment by jpsim** [comment]
This Dockerfile works for me with the latest stable release (0.46.5)

```
# Explicitly specify `focal` because `swift:latest` does not use `ubuntu:latest`.
ARG BUILDER_IMAGE=swiftlang/swift:nightly-5.6-focal
ARG RUNTIME_IMAGE=ubuntu:focal

# builder image
FROM ${BUILDER_IMAGE} AS builder
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libxml2-dev \
 && rm -r /var/lib/apt/lists/*
WORKDIR /workdir/
COPY Source Source/
COPY Tests Tests/
COPY Package.* ./

ARG SWIFT_FLAGS="-c release"
RUN swift build $SWIFT_FLAGS
RUN mkdir -p /executables
RUN mv $(swift build $SWIFT_FLAGS --show-bin-path)/swiftlint /executables

# runtime image
FROM ${RUNTIME_IMAGE}
LABEL org.opencontainers.image.source https://github.com/realm/SwiftLint
RUN apt-get update && apt-get install -y \
    libcurl4 \
    libxml2 \
 && rm -r /var/lib/apt/lists/*
COPY --from=builder /usr/lib/libsourcekitdInProc.so /usr/lib
COPY --from=builder /usr/lib/swift/linux/* /usr/lib
COPY --from=builder /executables/* /usr/bin

RUN swiftlint version

CMD ["swiftlint"]
```

**Comment by sam-mfb** [comment]
Hmm.  That Dockerfile leads to the same error on my M1 Macbook, which makes me think it is something about my setup though I can't think what.  I'm building on an M1 Max MacBook Pro (16-inch, 2021) on Monterey 12.2.1.  What are you using?

On a related note, would you be willing to add arm64 docker images to ghcr.io/realm/swiftlint:latest?  If I had that I wouldn't need to bother building on my machine.

**Comment by jpsim** [comment]
I actually tried to set up multi-platform docker images but it didn’t work because Apple didn’t offer a 5.5 image for arm64. I had to revert in 3d1821d3c0bd09a5eec7d6217bb708ec4c773c9a.

I’m guessing that when 5.6 is officially released it will have an arm64 image since the nightlies have it.

**Comment by jpsim** [comment]
The dockerfile I posted above worked with the 0.46.5 release, but not master, because SwiftSyntax crashes the compiler on arm64 Linux. 

Have you filed a bug at bugs.swift.org? If not I can.

**Comment by sam-mfb** [comment]
Ah, sorry; I missed that nuance.  I haven't filed the bug as I wasn't sure if it was just me.  If you don't mind that would be great.  (I'm fairly new to swift, and I suspect you'd file a better report.)

**Comment by sam-mfb** [comment]
Also, just to close the loop, building release 0.46.5 works for me as well.  If anyone wants a Dockerfile that builds it including handling downloading from git:

```
# Swift build SwiftLint

FROM swiftlang/swift:nightly-5.6-focal AS swiftlint-build
RUN apt-get update
RUN apt-get install -y clang libblocksruntime0 libcurl4-openssl-dev libxml2-dev git
RUN git clone https://github.com/realm/SwiftLint.git
WORKDIR SwiftLint
RUN git checkout 0.46.5 
ARG SWIFT_FLAGS="-c release"
RUN swift build $SWIFT_FLAGS
RUN mkdir -p /executables
RUN mv $(swift build $SWIFT_FLAGS --show-bin-path)/swiftlint /executables
```

You can then copy that over to some other target, for example:

```
# Swift linux development

FROM swiftlang/swift:nightly-5.6-focal AS swift-base
COPY --from=swiftlint-build /executables/swiftlint /usr/bin/swiftlint
```

OK with me to close this Issue, @jpsim, unless you wanted to have it open for tracking the compiler bug or multiarch Docker

**Comment by jpsim** [comment]
I was able to push an arm64 docker image of 0.46.5 over at https://github.com/realm/SwiftLint/pkgs/container/swiftlint/16712103?tag=multiarch

```
docker pull ghcr.io/realm/swiftlint:multiarch
```

Unlike what the tag says, it's just a `linux/arm64` image, it doesn't have an image for `linux/amd64`. It was built from af93485bbe2c1366fce825ddd31605ce4f0d10cb.

However, GitHub Actions took nearly 60 minutes to build this image because it had to do so using QEMU emulation: https://github.com/realm/SwiftLint/runs/5528613566?check_suite_focus=true

This tag should be considered experimental and can be removed/changed at any time, so please don't rely on it.

I'll update this ticket when I file Swift bugs for the compiler & linker issues you encountered.

**Comment by jpsim** [comment]
https://bugs.swift.org/browse/SR-15973
