### ISSUE TITLE
Do you use the correct version of SwiftSyntax

### ISSUE THREAD

**Issue by AF-cgi** [realm/SwiftLint#3906]
The upcoming release of SwiftLint v0.47.x use SwiftSyntax. Please make sure, that you use the correct version of it. Apple has released a new compatible version of it. See here: https://github.com/apple/swift-syntax/releases/tag/0.50600.1.

**Comment by jpsim** [comment]
You can see what versions of SwiftSyntax we're using in our [Package.swift](https://github.com/realm/SwiftLint/blob/master/Package.swift). We're using [0.50600.0](https://github.com/apple/swift-syntax/releases/tag/0.50600.0) right now. Thanks for letting me know that a new tag is a available.

**Comment by jpsim** [comment]
Updating here: https://github.com/realm/SwiftLint/pull/3907
