### ISSUE TITLE
max_length & min_length is not working for `identifier_name`

### ISSUE THREAD

**Issue by yo2bh** [realm/SwiftLint#3925]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? - 0.47.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
disabled_rules:
  - force_cast
  - force_try
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - trailing_whitespace
  - vertical_parameter_alignment
  - switch_case_alignment
  - nesting

opt_in_rules:
  - empty_string

excluded:
  - Pods

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
type_name:
    max_length:
    warning: 45
    error: 60
    min_length:
    warning: 1
    
identifier_name:
    max_length:
    warning: 45
    error: 60
    min_length:
    warning: 1

custom_rules:
  smiley_face:
    name: "Smiley Face"
    regex: '( :\))'
    match_kinds:
      - comment
      - string
    message: "A closing parenthesis smiley :) creates a half-hearted smile, and thus is not preferred. Use :]"
severity: warning
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? - No
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 13.2
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.
```swift
// This triggers a violation:
let singleCalendarDayViewIteratorMultiplierCounter = (1 + index) * 7
```

**Comment by SimplyDanny** [comment]
Your configuration does not use the correct indentation. It should be
```
identifier_name:
    max_length:
      warning: 45
      error: 60
    min_length:
      warning: 1
```
to get proper YAML dictionaries which can be parsed as intended.

**Comment by SimplyDanny** [comment]
Feel free to reopen if this does not fix your issue.
