### ISSUE TITLE
line_length still exist after disabled

### ISSUE THREAD

**Issue by AlfinIndrawan** [realm/SwiftLint#3939]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Tried swiftlint, other rules work fine but line_length is buggy and trailing_whitespace. Tried to update ignore_comments: true but it still not updated in swiftlint rules. So i update to disabled rules but line_length still exist in xcode

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
* 0.47.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
* homebrew
* Paste your configuration file:

```yml
disabled_rules:
    - trailing_whitespace
    - identifier_name
    - line_length

opt_in_rules:
    - empty_count
    - empty_string

included:
    - Xcode_Projects

excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
    
function_body_length:
    warning: 300
    error: 500
    
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
* no

* Which Xcode version are you using (check `xcodebuild -version`)?
* 13.3 use intel mac
 
 
<img width="258" alt="Screenshot 2022-04-10 at 1 31 25 PM" src="https://user-images.githubusercontent.com/77723289/162605554-8577db5a-30b6-41d4-9caa-08a812d8cc5c.png">

**Comment by SimplyDanny** [comment]
If you think that the `line_length` and `trailing_whitespace` rules do not work correctly then please file issues for them explaining what exactly does not work well in your opinion.

It's hard to reproduce the issue with the `line_length`, in that it is triggered while actually disabled in the configuration, without further details about your project setup. In a simple Swift package the mechanism works well for me. Can you reproduce it without Xcode? How do you call SwiftLint from within Xcode?

**Comment by X901** [comment]
I have this issue I cannot change or disable `line_length` rules !
