### ISSUE TITLE
Initialize regexes once per Rule

### ISSUE THREAD

**Issue by scottrhoyt** [realm/SwiftLint#394]
I've come across this while implementing #123. There are quite a few rules that compile a regex for every file that they lint. Given that these regexes are constant and the construction cost is non-trivial, I believe we can get a small performance bump from storing the precompiled regex once for each rule that needs one.

**Comment by jpsim** [comment]
How would one "precompile" a regex?

**Comment by scottrhoyt** [comment]
Sorry, old semantics. I just mean initializing them once and holding them for the life of the `Rule`. Instantiating these things can be relatively expensive. Given my cursory testing, it would probably only be ~2% performance increase, but given it's such a small change, it might be worth it, but maybe not. Doubtless there is more to gain in optimizing the patterns and rules themselves, but this just seemed like a quick win.

**Comment by jpsim** [comment]
Ah, I see what you mean. Yes, I'd be in favor of only generating the regexes once per run. Maybe as static variables on the rules that need them? Would be trivial to do.

**Comment by scottrhoyt** [comment]
Yeah, something like that I think. Should speed up testing a bit too.

**Comment by scottrhoyt** [comment]
I'm going to close this because my testing has not indicated a significant speedup via initializing regex's differently. It is quite possible that there are optimizations happening behind the scenes that make this unnecessary. However, there is still the smaller task of cleaning up and standardizing how `NSRegularExpression`s are created.

**Comment by keith** [comment]
I tested this a while back and it seems like the framework caches recently used regexes
