### ISSUE TITLE
[statement position violation] else and catch on the same line might not apply to guard statements

### ISSUE THREAD

**Issue by BluMist** [realm/SwiftLint#395]
I understand the case for 
if {
} else {
}

however if I want to write something like the following for a guard statement, it should be allowed

guard let ...
let ...
let veryveryveryveryverylongline
else {
}

"proper" but weird looking:
guard let ...
let ...
let veryveryveryveryverylongline else {

}

**Comment by scottrhoyt** [comment]
This is a WIP on the linked PR. Feel free to contribute if you'd like.

**Comment by marcelofabri** [comment]
I'm not sure how this is different from #355

**Comment by marcelofabri** [comment]
I'm closing this because it looks like it was implemented at some point. Feel free to reopen if this is not the case.
