### ISSUE TITLE
Jazzy docs: assets folder is missing in gh-pages

### ISSUE THREAD

**Issue by 0bmxa** [realm/SwiftLint#3968]
### New Issue Checklist

- [x] ~Updated SwiftLint to the latest version~ N/A
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The [`assets`](https://github.com/realm/SwiftLint/tree/master/assets) folder, used by the Jazzy docs, is missing in the published `gh-pages`. It seems to be only used by the [`index.html`](https://github.com/realm/SwiftLint/blob/gh-pages/index.html), and is expected to be found diretly at `/assets`, but it's not.

- Expected e.g. here:
https://github.com/realm/SwiftLint/blob/61619db0957ee9171273145e4d65b53dd57a3432/index.html#L329
- 404 here: https://realm.github.io/SwiftLint/assets/screenshot.png
- Screenshot not visible here (should be right below the badges): https://realm.github.io/SwiftLint/index.html

##### Complete output when running SwiftLint, including the stack trace and command used

N/A

### Environment

N/A

**Comment by SimplyDanny** [comment]
Is this still an issue for you, @0bmxa? https://realm.github.io/SwiftLint embeds the screenshots correctly on my end.

**Comment by 0bmxa** [comment]
Oh, amazing! You're right, it looks correct now – I'll close this issue!
