### ISSUE TITLE
I want to set all of my rules to be warning 

### ISSUE THREAD

**Issue by periva101** [realm/SwiftLint#3973]
I am swiftlint running using 
`$ ./Pods/SwiftLint/swiftlint autocorrect`
I just want to see a warning because I am working on leacgy  project with a lot of error

**Comment by kirkbig** [comment]
try running 
```
$ ./Pods/SwifLint/swiftlint --lenient
```

**Comment by SimplyDanny** [comment]
Fine for you, @periva101?
