### ISSUE TITLE
[question] Is there a rule for "force blanks before and after an assignment statement equal (`=`)"?

### ISSUE THREAD

**Issue by tokizuoh** [realm/SwiftLint#3982]
I want to force a blank before and after the equal of an assignment statement as shown below. Is there a rule already?
(If you don't have it yet, we will develop it and submit a PR.)
thx.

```swift
let a=1
```

↓

```swift
let a = 1
```

**Comment by SimplyDanny** [comment]
Please take a look at the [operator_usage_whitespace](https://realm.github.io/SwiftLint/operator_usage_whitespace.html) rule. Does it fulfill your needs?

**Comment by tokizuoh** [comment]
Thank you!
That rule met my needs. This issue will be closed.
