### ISSUE TITLE
swiftlint command doesn't work locally on Mac with M1 via cocoapods install

### ISSUE THREAD

**Issue by DawidBastek** [realm/SwiftLint#3983]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Hi guys,
I tried to run `swiftlint` command locally but it is not visible to my terminal:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/72853287/170081311-db8c8314-811f-4f62-a23d-49251744a05e.png">

I did an installation via cocoapods:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/72853287/170079666-47cf4055-2796-4f4c-b0b8-db5bc657094b.png">

But without any success, I saw the solution for Homebrew with M1 architecture, and I thought that maybe somehow related.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ {swift_project_directory}/swiftlint
```

### Environment

* SwiftLint version: 0.47.1
* Installation method used: CocoaPods (1.11.3)
* Xcode version: 13.4
* OS version: 12.4
* M1 architecture

**Comment by Cyberbeni** [comment]
https://github.com/realm/SwiftLint#using-cocoapods

> invoke it via `${PODS_ROOT}/SwiftLint/swiftlint` in your Script Build Phases.

**Comment by marcelofabri** [comment]
Yeah, looks like you previously had SwiftLint installed globally.
