### ISSUE TITLE
binary size increased by 2x-3x since 0.47.0

### ISSUE THREAD

**Issue by honghaoz** [realm/SwiftLint#3992]
I noticed that from `0.47.0`, the universal binary size had a huge increase. 
- [0.46.5](https://github.com/realm/SwiftLint/releases/tag/0.46.5): the bin is about 28.9M
- [0.47.0-rc.1](https://github.com/realm/SwiftLint/releases/tag/0.47.0-rc.1): the bin is about 93.3M
- [0.47.1](https://github.com/realm/SwiftLint/releases/tag/0.47.1): the bin is about 60.9M

Is this expected?

**Comment by honghaoz** [comment]
oh, I guess because of this change? https://github.com/realm/SwiftLint/pull/3867#issue-1160045607

**Comment by jpsim** [comment]
Yes, we statically link SwiftSyntax and its dependencies as of 0.47.0, which definitely bloats the binary.

We do this so that rules can be written to leverage SwiftSyntax, which can lead them to be more performant and accurate.

**Comment by honghaoz** [comment]
Gotcha, thanks for the insights!
