### ISSUE TITLE
 `Duplicated Key in Dictionary Literal Violation` does not understand `#line` directive.

### ISSUE THREAD

**Issue by ke-kx** [realm/SwiftLint#4012]
### New Issue Checklist

- [ x] Updated SwiftLint to the latest version
- [ x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`Duplicated Key in Dictionary Literal Violation` does not understand `#line` directive.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
➜ swiftlint lint test.swift
Linting Swift files at paths test.swift
Linting 'test.swift' (1/1)
/Users/nils_kunze/work/misc/test.swift:1:14: warning: Colon Spacing Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
/Users/nils_kunze/work/misc/test.swift:3:5: warning: Duplicated Key in Dictionary Literal Violation: Dictionary literals with duplicated keys will crash in runtime. (duplicated_key_in_dictionary_literal)
/Users/nils_kunze/work/misc/test.swift:4:5: warning: Duplicated Key in Dictionary Literal Violation: Dictionary literals with duplicated keys will crash in runtime. (duplicated_key_in_dictionary_literal)
/Users/nils_kunze/work/misc/test.swift:5:5: warning: Duplicated Key in Dictionary Literal Violation: Dictionary literals with duplicated keys will crash in runtime. (duplicated_key_in_dictionary_literal)
Done linting! Found 4 violations, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.47.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? brew
* Paste your configuration file: None / defrault

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
* Which Xcode version are you using (check `xcodebuild -version`)? -
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
var values: [Int : String] = [
    #line: "one",
    #line: "two",
    #line: "three",
    #line: "four"
]
```

**Comment by SimplyDanny** [comment]
Interesting catch, @ke-kx! I wonder where/why you would use such code, however?

**Comment by ke-kx** [comment]
Good question^^ I found this in unit tests of a customer code base. I guess they don't care about the actual keys and just want to make sure that they are unique or something like that?

**Comment by SimplyDanny** [comment]
So reformatting the dictionary, putting all key-value pairs onto a single line, leads to an exception in the worst case, because keys are no longer unique. Doesn't seem like a good idea to me.

Well, never mind ... The bug is valid and should be quite easy to fix.

**Comment by OrEliyahu** [comment]
Seems like the same issue is reproduced in version 0.48.0 when using `UUID` initializer, for example:

```swift
let foo: [UUID: CGRect] = [
  UUID(): .zero,
  UUID(): .zero
]
```

So I'm assuming that the issue is more general, and not specific just for `#line` directive, but for all keys which are generated in run time with the same code. Also verified  with:

```swift
let foo: [UUID: CGRect] = [
  generateKey(): .zero,
  generateKey(): .zero
]

func generateKey() -> UUID {
  .init()
}
```
