### ISSUE TITLE
SwiftUI?

### ISSUE THREAD

**Issue by DaniSpringer** [realm/SwiftLint#4013]
Any plans/point in pursuing a Linter for SwiftUI?

**Comment by SimplyDanny** [comment]
There already is [one rule](https://realm.github.io/SwiftLint/accessibility_label_for_image.html) available and [another one](https://github.com/realm/SwiftLint/pull/3989) in the works referring to SwiftUI.

Do you have ideas for specific rules? Please file rule requests for them.
