### ISSUE TITLE
Cyclomatic complexity rule

### ISSUE THREAD

**Issue by garnett** [realm/SwiftLint#402]
Surprisingly haven't found this rule https://en.wikipedia.org/wiki/Cyclomatic_complexity
There is "nested ifs" rule, but cyclomatic complexity is different. Looks like it should be pretty easy to implement (just count if, guard, switch, etc.)

It probably should be opt in (or with high triggering values), because from my experience it is considered to be pretty "hardcore" to obey.

@jpsim if you think it might be useful I would be interested in implementing that

**Comment by scottrhoyt** [comment]
This is functionality that I would find very useful while developing, but I think this is more the domain of a static analyzer than a linter.

**Comment by garnett** [comment]
@scottrhoyt I agree with you, but the thing is that `SwiftLint` is only project in the wild right now which allows "analysing"  and IMHO `lint` word in it's name confuses people (me). For example, https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/EmptyCountRule.swift looks to me like static analysis too, but there is not other project/repo where you can put it right now.

**Comment by daniel-beard** [comment]
I think it would be nice for swiftlint to have a cyclomatic complexity rule, so that for iOS dev it's covered for both Objective-C and swift (OCLint has a rule for this: https://github.com/oclint/oclint/blob/master/oclint-rules/rules/size/CyclomaticComplexityRule.cpp)

**Comment by jpsim** [comment]
>  if you think it might be useful I would be interested in implementing that

Would be tremendously useful. Go for it!

**Comment by garnett** [comment]
Implemented!
