### ISSUE TITLE
Is there any way to specify an output file for SwiftLint reports instead of using '>' ?

### ISSUE THREAD

**Issue by tychop** [realm/SwiftLint#4048]
I want to save a json report of my SwiftLint BuildToolPlugin so I can use it elsewhere.

I am currently trying the following:

```
import PackagePlugin

@main
struct SwiftLintPlugin: BuildToolPlugin {
	func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
		return [
			.buildCommand(
				displayName: "Running SwiftLint for \(target.name)",
				executable: try context.tool(named: "swiftlint").path,
				arguments: [
					"lint",
					"--in-process-sourcekit",
					"--path", "\(target.directory.string)",
					"--config", "\(context.package.directory.string)/.swiftlint.yml",
					"--reporter", "json",
					">", "swiftlint.result.json"
				],
				environment: [:]
			)
		]
	}
}
```

But that basically boils down to the following command in which the quotes around the '>' character prevents creating an output file.

```
swiftlint lint \
	--in-process-sourcekit \
	--path BusinessModel \
	--config .swiftlint.yml \
	--reporter json ">" swiftlint.result.json
```

Is there any way to specify an output file for SwiftLint reports instead of using '>' ?

**Comment by SimplyDanny** [comment]
As far as I see, there is currently no other way to write the report to a file.

One option is to support that in SwiftLint. Another one is to convince the maintainers of [swift-tools-support-core](https://github.com/apple/swift-tools-support-core) to avoid escaping of single arguments like `>`, `|`, `2>`, ... [This](https://github.com/apple/swift-tools-support-core/blob/0b77e67c484e532444ceeab60119b8536f8cd648/Sources/TSCBasic/StringConversions.swift#L66) should be the responsible line in their code.

**Comment by jpsim** [comment]
@tychop can you please check out #4148 and let me know if it's what you're looking for?

**Comment by tychop** [comment]
This works excellent !!! Thank you very much.
