### ISSUE TITLE
Clarify documentation for multiline_arguments_brackets and multiline_literal_brackets

### ISSUE THREAD

**Issue by chrisjf** [realm/SwiftLint#4060]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Hello SwiftLint Team! 

I have a documentation improvement request. Today, my coworkers and I were reviewing the documentation for two rules `multiline_arguments_brackets` and `multiline_literal_brackets` and we thought it could be improved by including the following triggering examples. 

The reason I am requesting these triggering examples be included in the documentation is because they are a common style, and it's not immediately obvious from the rule definitions whether these examples would trigger or not. We ended up wasting time making a sample project and integrating SwiftLint, just to figure out if these two examples would trigger or not. So to avoid future lost person-hours, I propose this documentation improvement! 😄 

Thanks,
Chris

#### multiline_arguments_brackets
Existing documentation: https://realm.github.io/SwiftLint/multiline_arguments_brackets.html

```swift
// Triggering Example
foo(↓param1: "Param1",
    param2: "Param2",
    param3: "Param3"↓)
```

#### multiline_literal_brackets
Existing documentation: https://realm.github.io/SwiftLint/multiline_literal_brackets.html

```swift
// Triggering Example
let houseCup = [↓"gryffinder": 460,
		"hufflepuff": 370,
		"ravenclaw": 410,
		"slytherin": 450↓]
```

---

I have attached a screenshot and a sample project showing that the above two examples are indeed triggering. 
<img width="1512" alt="Screen Shot 2022-08-01" src="https://user-images.githubusercontent.com/105042/182261732-7c63a76e-309b-43fa-9393-2da560863a11.png">
Sample Project: [SwiftLintTest.zip](https://github.com/realm/SwiftLint/files/9237933/SwiftLintTest.zip)

--- 

P.s. If you'd like me to make a pull request to update the documentation, would you kindly confirm how I could do so? I don't see a central location for the documentation in the repository. I wonder if the documentation is generated from those `RuleDescription` objects in the code? For example: https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/Style/MultilineLiteralBracketsRule.swift

**Comment by SimplyDanny** [comment]
You are exactly right. The examples are listed in the `RuleDescription` of every rule. They will be listed in the documentation of the rule. Furthermore, they are automatically tested. Feel free to create a PR!

**Comment by chrisjf** [comment]
Thanks for the info @SimplyDanny. I have made a new PR: https://github.com/realm/SwiftLint/pull/4098 🙂
