### ISSUE TITLE
Limit number of method/closure parameters rule

### ISSUE THREAD

**Issue by garnett** [realm/SwiftLint#415]
Time to time I raise this issue with colleagues: there is no proven number to stick, but IMHO anything with 5 or more parameters should be considered as suspicious (might be a good place to use "Introduce Parameter object" refactoring).

I see it as an AST rule that raises warning for methods/functions/closures with 5 or more arguments (configurable). 

Edit: probably it should ignore `init` methods though (value objects usually have tons of parameters)

**Comment by scottrhoyt** [comment]
Interesting idea. Do you think this should or shouldn't count parameters with default values?

**Comment by garnett** [comment]
@scottrhoyt that's a good question indeed :+1: 
Just thinking out loud: declaration of method with 4+ parameters is not often a problem, developer has hard times when he reads place where such method is called or invokes such method. Assuming that I would say that we can:
* make requirement less strict for method containing optional arguments (math to be discussed)
* completely ignore parameters with default values because they can be totally ignored when calling method

**Comment by scottrhoyt** [comment]
Without thinking about it too much, I think I would vote for option number 2 since it is simpler and clearer. Ultimately I think it is more important for this rule to protect potential callers as opposed to the function writer.
