### ISSUE TITLE
Xcode 14, errors or warnings disappeared?

### ISSUE THREAD

**Issue by HolmesZhao** [realm/SwiftLint#4194]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

swiflint installed in cocoapods with Xcode 14 build, without  errors and warnings in Xcode sometimes.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ ./Pods/SwiftLint/swiftlint version
0.49.1
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 
  * 0.49.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
  * Cocoapods
* Paste your configuration file:
  * none
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  * none
* Which Xcode version are you using (check `xcodebuild -version`)?
  * Xcode 14 beta 2
* Do you have a sample that shows the issue? 
like this image, warning in build, but source code without any warning tips.
![image](https://user-images.githubusercontent.com/19728934/189264578-42162e5e-d4de-432d-9a6f-ade58afb57d2.png)

**Comment by dknewman** [comment]
Follwing...Having the same issue. The linting will show for a second then disappear. Very annoying.

Same results regardless if its a warning or error.

**Comment by henryglendening-hh** [comment]
I'm seeing the same thing. But when the build is made via CLI (or CI tools), the lint warnings/errors are thrown and visible in the logs, so I get unexpected build failures.

**Comment by ndtoan75** [comment]
It seems like bug Xcode 14: https://developer.apple.com/forums/thread/715103

**Comment by Jason8Zhang** [comment]
anyone has solutions?

**Comment by dknewman** [comment]
> anyone has solutions?

Update to the latest version of swiftlint, and xcode 14.2, thats what fixed it for me.

**Comment by SimplyDanny** [comment]
> Update to the latest version of swiftlint, and xcode 14.2, thats what fixed it for me.

Can @HolmesZhao, @dknewman and @henryglendening-hh confirm that?

**Comment by HolmesZhao** [comment]
> > Update to the latest version of swiftlint, and xcode 14.2, thats what fixed it for me.
> 
> Can @HolmesZhao, @dknewman and @henryglendening-hh confirm that?

I will try it.

**Comment by merlinpaypal** [comment]
I'm currently getting this issue with XCode 14.2. Has a fix been found?

**Comment by ludimila** [comment]
I have the same problem with XCode 14.2

**Comment by merlinpatt** [comment]
Why was this closed?

**Comment by karimlanguedoc** [comment]
> Why was this closed?

Ditto this.  Anyone figured out the solution for this?

**Comment by jensenharris** [comment]
I am also having this issue with Xcode 14.2.

**Comment by bebugger** [comment]
Anyone found solution for this ?

**Comment by saifulafiqzakaria3** [comment]
Just in case anyone who still having this problem. I managed to solved mine by following whatever written by readme file there on https://github.com/realm/SwiftLint. I'm using 14.3 now and the warning was not appearing. Since I installed swiftlint using cocoapods,  what I did was:
1. Select the project in the file navigator, then select the primary app target, and go to Build Phases. Click the + and select "New Run Script Phase". Insert the following as the script: Note: script will depend base on how you install the swiftlint 
`"${PODS_ROOT}/SwiftLint/swiftlint"`
2. Then you can try to run the build again see if the error comes out or not.

Thats what I did, correct me if I'm wrong. Thanks!
