### ISSUE TITLE
missing_docs warns when using inline doc comments

### ISSUE THREAD

**Issue by bobbradley** [realm/SwiftLint#4232]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

If you use inline doc comments for enum cases, warnings are generated for missing docs. For example:
```
/// Docs for enum.
public enum MyEnum: Int {
    case myCase1 = 1 /// Docs for case 1. <-- Warning generated here
    case myCase2 = 2 /// Docs for case 2.
    case myCase3 = 2 /// Docs for case 3.
}
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
MyEnum.swift:8:10: warning: Missing Docs Violation: public declarations should be documented. (missing_docs)
...
```

### Environment

* SwiftLint version 0.49.1
* Installation method used: pre-built download from GitHub.
* Paste your configuration file:

```yml
opt_in_rules:
  - missing_docs
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using (check `xcodebuild -version`)? Running directly on source code.
* Do you have a sample that shows the issue? Yes, pasted into description.

**Comment by marcelofabri** [comment]
This is expected, as the docs wouldn't be picked up by Xcode:

<img width="721" alt="Screen Shot 2022-09-21 at 12 04 00" src="https://user-images.githubusercontent.com/833072/191589107-429da172-65a6-4d5f-ba06-ce5d85d7679c.png">
