### ISSUE TITLE
No available formula with the name "swiftlint"

### ISSUE THREAD

**Issue by minhtien1403** [realm/SwiftLint#4254]
Im try to install SwiftLint via homebrew but got this error. 
I make some searching on google but can't find anything.
Can anyone tell me how to fix this problem ?

![Screen Shot 2022-09-28 at 17 17 14](https://user-images.githubusercontent.com/54258059/192754336-7b9ee2b9-9b64-43c4-9c4c-9142da4a6196.png)

**Comment by SimplyDanny** [comment]
This is unexpected. SwiftLint is definitely available [via Homebrew](https://formulae.brew.sh/formula/swiftlint). You might want to run `brew doctor` to make sure your Homebrew installation is not corrupted.

**Comment by minhtien1403** [comment]
Thanks for @SimplyDanny suggestion, I try follow instruction from `brew doctor ` and the problem is gone
