### ISSUE TITLE
Statistics of count for each file

### ISSUE THREAD

**Issue by steve21124** [realm/SwiftLint#428]
Hi,
Currently, for every files, I got lots of details warning and error. is it possible to run swiftlint and get statistics instead of detail for every file?
For example : 

<pre>
Sample.swift
   - Line Length Violation = 6
Sample2.swift 
   -Force Unwrap = 4
</pre>

# 

Sample.swift:112: warning: Line Length Violation: Line should be 100 characters or less: currently 101 characters (line_length)
Sample.swift:142: warning: Line Length Violation: Line should be 100 characters or less: currently 101 characters (line_length)
Sample.swift:166: error: Line Length Violation: Line should be 100 characters or less: currently 206 characters (line_length)
Sample.swift:167: error: Line Length Violation: Line should be 100 characters or less: currently 206 characters (line_length)
Sample.swift:168: error: Line Length Violation: Line should be 100 characters or less: currently 206 characters (line_length)
Sample.swift:169: error: Line Length Violation: Line should be 100 characters or less: currently 243 characters (line_length)
Sample.swift:170: error: Line Length Violation: Line should be 100 characters or less: currently 205 characters (line_length)
Sample.swift:171: error: Line Length Violation: Line should be 100 characters or less: currently 206 characters (line_length)
Sample.swift:172: error: Line Length Violation: Line should be 100 characters or less: currently 201 characters (line_length)
Sample.swift:173: error: Line Length Violation: Line should be 100 characters or less: currently 201 characters (line_length)
Linting 'Sample.swift' (84/277)

**Comment by scottrhoyt** [comment]
This is the behavior of the `XcodeReporter` and is needed for displaying violations in Xcode. If you were interested in a separate `Reporter` that outputs statistics only, that shouldn't be too hard to add. However, you would have to run that separately than the `XcodeReporter` to preserve both use cases. Would you be interested in contributing a new `Reporter`?

**Comment by steve21124** [comment]
Thank you for the info, I am checking on it and not sure if have time or not

**Comment by marcelofabri** [comment]
Closing this due to lack of inactivity. Feel free to reopen/send a PR if needed.
