### ISSUE TITLE
TrailingNewlineRule.swift doesn't seem to work

### ISSUE THREAD

**Issue by rajohns08** [realm/SwiftLint#43]
I've tried adding multiple ending new lines and having 0 extra new lines at the end of my file, but I never get a warning for this. I know the swiftlint library is active though, because I'm getting other warnings.

**Comment by jpsim** [comment]
You're absolutely right! I'll look into why this is the case.

**Comment by jpsim** [comment]
The problem was that we weren't specifying a line in the warning, so Xcode didn't pick it up. Fixed in #46.

**Comment by rajohns08** [comment]
Has this fix been pushed to brew yet? Running a brew upgrade didn't update the package.

**Comment by jpsim** [comment]
Nope, there's a big pile of fixes as you can see from the [CHANGELOG](https://github.com/realm/SwiftLint/blob/master/CHANGELOG.md) that I'd like to include in a release shortly. I'll cut a release today or tomorrow.
