### ISSUE TITLE
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

### ISSUE THREAD

**Issue by BluMist** [realm/SwiftLint#432]
Originally reported in issue #200, seems like it is happening again in 0.7.1?

**Comment by scottrhoyt** [comment]
@BluMist can you share any logs or even a project where you see this happening? Warnings should exit with a zero still, but errors should exit non-zero.

**Comment by BluMist** [comment]
.../TQEntityCell.swift:226:67: warning: Force Unwrapping Violation: Force unwrapping should be avoided. (force_unwrapping)
.../TQEntityCell.swift:238:64: warLinting 'TQQueryCell.swift' (365/697)
