### ISSUE TITLE
Building 0.50.0-rc.1 (and current main) fails in release mode

### ISSUE THREAD

**Issue by tiwoc** [realm/SwiftLint#4341]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Building SwiftLint in release mode fails, at least when done via `swift build --configuration release`, because SwiftLintTestHelpers are built even for release builds but then the SwiftLintTestHelpers build fails to import the main framework:

```
$ swift build --configuration release
[…]
SwiftLint/Tests/SwiftLintTestHelpers/TestHelpers.swift:3:18: error: module 'SwiftLintFramework' was not compiled for testing
@testable import SwiftLintFramework
~~~~~~~~~~       ^
```

I tried fixing this by making SwiftLintTestHelpers a `testTarget`, which fixes the SPM build, but unfortunately breaks the Xcode build:

> Testing failed:
> 	Unable to resolve build file: XCBCore.BuildFile (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:SwiftLintTestHelpers')
> 	Testing cancelled because the build failed.

### Environment

* SwiftLint version 0.50.0-rc.1, same on current main
* Xcode 14.0.1 (14A400)

**Comment by tiwoc** [comment]
That makes a lot of sense 🙈 Thank you!

Leaving out the target worked for previous versions which is how I got here, but I'll definitely add it to our scripts now.

**Comment by jpsim** [comment]
I’d rather that would’ve kept working too, but ran into the same limitations you just outlined with `testTargets`.

**Comment by tiwoc** [comment]
FYI: To actually build the executable, I had to specify the product. When I only specified the target, SPM skipped linking the `swiftlint` binary.

```
swift build --configuration release --product swiftlint
```

**Comment by jpsim** [comment]
Good call!
