### ISSUE TITLE
`type_name` rule doesn't validate protocol declarations

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#4430]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`type_name` rule doesn't validate protocol declarations. I think this is a historic oversight, but I'm afraid that simply turning it on would trigger too many violations in existing codebases (see https://github.com/realm/SwiftLint/pull/4428).

Maybe we need to provide a configuration to opt-out from this so people can easily handle the migration. Thoughts?

**Comment by jpsim** [comment]
An opt-out works for me.
