### ISSUE TITLE
v0.7.2: valid_docs rule failing with some return types

### ISSUE THREAD

**Issue by jschmid** [realm/SwiftLint#445]
Since v0.7.1 some functions get warnings even though they did not before.

<img width="778" alt="screen shot 2016-01-29 at 08 03 28" src="https://cloud.githubusercontent.com/assets/574168/12669207/03a66908-c65f-11e5-8014-97c013576f6b.png">

<img width="774" alt="screen shot 2016-01-29 at 08 04 06" src="https://cloud.githubusercontent.com/assets/574168/12669208/0642c3a0-c65f-11e5-8c8a-26e064d38bd3.png">

(`InfoCheckButton.State` is an `enum`)

This is surely related to #282 (which is fixed indeed)

**Comment by jpsim** [comment]
Can you try with 0.7.2 please?

**Comment by jschmid** [comment]
Still the same with 0.7.2 :/

**Comment by jschmid** [comment]
Wait, homebrew did not update it to 0.7.2. Give me a minute :grin:

**Comment by jpsim** [comment]
0.7.2 hasn't been approved by Homebrew yet, so you'd need to install using the pkg or build from source to check.

**Comment by jschmid** [comment]
I just built from source. 0.7.2 does indeed fix the problem. Thanks @jpsim, sorry about the fuss.

**Comment by jpsim** [comment]
No problem at all!
