### ISSUE TITLE
Allow enabling globally disabled rules from comments

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#446]
Say there's this single file in all of your project which _must_ be fully documented, but `MissingDocsRule` is an opt-in rule, you have to add `missing_docs` to the list of `enabled_rules` for the configuration applied to that file, and disable the rule on all other files touched by that configuration: add `// swiftlint:disable missing_docs` to the top of every other file. It'd be much better if you could do `// swiftlint:enable missing_docs` in just that file without having to add `missing_docs` to any configuration file's `enabled_rules`.

Unfortunately, it will be tricky to do this without completely rethinking how SwiftLint determines which regions to lint with which rules. Although a similar refactoring will likely be necessary to ever support configuring rules in source code comment commands (e.g. `// swiftlint:type_body_length 100`).

**Comment by scottrhoyt** [comment]
Yeah, that's a tricky one. Especially the general case of allowing enabling/configuration of rules from source code.

This was the sort of use case I had in mind with `use_nested_configs`. So it's far from ideal to have to separate that file in its own directory, I guess at least you'd have an option.

**Comment by jpsim** [comment]
Yes, this is certainly helped by nested configs, but still something that should be done, not that you seem to be disputing that :wink:

**Comment by RamblinWreck77** [comment]
Just stumbled on this doing research before asking this exact question. 

+1, would be super helpful.
