### ISSUE TITLE
Provide full rule description when using swiftlint from terminal

### ISSUE THREAD

**Issue by garnett** [realm/SwiftLint#448]
Use case:
I've installed `swiftlint` and I want to check:

* which rules are turned on by default
* which rules have severity of warning
* which rules have customizable parameters and their default values

so I don't need to go to Documention / source code to learn them.

Proposed implementation:

* ```swiftint rules``` produces more reach output
* `swiftlint rule $0` provides this kind of output

**Comment by marcelofabri** [comment]
Take a look at #435 and #392

**Comment by garnett** [comment]
@marcelofabri thanks!
