### ISSUE TITLE
Xcodebuild error:Validate plug-in “SwiftLintPlugin” in package “swiftlint”

### ISSUE THREAD

**Issue by agruchala** [realm/SwiftLint#4554]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Swiftlint plug-in doesn't work on CI - error: Validate plug-in “SwiftLintPlugin” in package “swiftlint”

### Environment

macOS 12.5
Xcode 14.1
SPM tools version 5.5
Swiftlint added as dependency from branch main.

Plug-in works fine in Xcode locally, because there is pop up for validating and trusting plug-in.

**Comment by agruchala** [comment]
I did not use this option.
Will official release need this option too? Or it is only for
beta/unversioned releases?

W dniu pt., 18.11.2022 o 21:43 engineeric ***@***.***>
napisał(a):

**Comment by engineeric** [comment]
I believe it applies to all versions.

**Comment by jpsim** [comment]
Sounds like it's an issue with how you're configuring your CI or perhaps a limitation of SwiftPM plugins?

I'm closing this issue assuming it's not a SwiftLint-specific problem, but please let me know if I'm missing something.

**Comment by iDevPro** [comment]
> `-skipPackagePluginValidation`

I'm append this options to build but not help for me :(
