### ISSUE TITLE
Baseline of swiftlint warning

### ISSUE THREAD

**Issue by abhimaandunzo** [realm/SwiftLint#4577]
It would be good to have a baseline feature built in. This would help in making sure the swiftlint plugin can we incorporated in existing project faster.  This ensure we can stop any new issue creeping in right from time its integrated . we can borrow idea from https://detekt.dev/docs/gettingstarted/gradle/   or [lint android baseline](https://googlesamples.github.io/android-custom-lint-rules/usage/baselines.md.html)

**Comment by jpsim** [comment]
Feel free to code review this implementation to see if it does what you want/expect: https://github.com/realm/SwiftLint/pull/3421

**Comment by abhimaandunzo** [comment]
@jpsim yes this is exactly what i was looking for
