### ISSUE TITLE
Rule: `unused_closure_parameter` does not respect parameters with backticks

### ISSUE THREAD

**Issue by chosa91** [realm/SwiftLint#4588]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

In the newly released 0.50.0 version, the rule `unused_closure_parameter` detects parameter names between backticks as unused parameters, even if they are in use.
This might be intended behavior but it was not an issue in (at least) 0.49.1.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
… warning: Unused Closure Parameter Violation: Unused parameter "`self`" in a closure should be replaced with _. (unused_closure_parameter)
```

### Environment

* SwiftLint version: 0.50.0
* Installation method used: Homebrew
* Paste your configuration file:

```yml
only_rules:
  - unused_closure_parameter
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  NO
* Which Xcode version are you using (check `xcodebuild -version`)? 
  Xcode 14.1
  Build version: 14B47b

```swift
func weakify<Owner: AnyObject>(_ owner: Owner, closure: @escaping (Owner) -> Void) -> (() -> Void) {
    { [weak owner] in
        if let owner {
            closure(owner)
        }
    }
}

class Foo {
    struct Sut {
        var arg: (() -> Void)?
    }

    var sut = Sut()

    func bar() {
        var sut = Sut()
        sut.arg = weakify(self) { `self` in
            _ = self
        }
    }
}
```

**Comment by jpsim** [comment]
I think the rule might be working correctly here and that you're strongly capturing `self` in your closure.

To only weakly capture `self` you'd need to refer to it with backticks:

```swift
func weakify<Owner: AnyObject>(_ owner: Owner, closure: @escaping (Owner) -> Void) -> (() -> Void) {
    { [weak owner] in
        if let owner {
            closure(owner)
        }
    }
}

class Foo {
    struct Sut {
        var arg: (() -> Void)?
    }

    var sut = Sut()

    func bar() {
        var sut = Sut()
        sut.arg = weakify(self) { `self` in
            _ = `self`
        }
    }
}
```

Or to use a different closure argument name to avoid the confusion:

```swift
func weakify<Owner: AnyObject>(_ owner: Owner, closure: @escaping (Owner) -> Void) -> (() -> Void) {
    { [weak owner] in
        if let owner {
            closure(owner)
        }
    }
}

class Foo {
    struct Sut {
        var arg: (() -> Void)?
    }

    var sut = Sut()

    func bar() {
        var sut = Sut()
        sut.arg = weakify(self) { this in
            _ = this
        }
    }
}
```

**Comment by chosa91** [comment]
Yeah, you're right in the case of \`self\`, but what about a parameter that doesn't exist in the closure/func/class/global scope, like this:

```swift
class Foo {
    struct Sut {
        var arg: (() -> Void)?
    }

    var sut = Sut()

    func bar() {
        var sut = Sut()
        sut.arg = weakify(self) { `baz` in
            _ = baz
        }
    }
}
```

```bash
warning: Unused Closure Parameter Violation: Unused parameter "`baz`" in a closure should be replaced with _. (unused_closure_parameter)
```

**Comment by jpsim** [comment]
Because SwiftLint rules operate before typechecking and semantic analysis, there’s not enough information available to know if `baz` is referring to the backticked closure argument or some other declaration, perhaps even in a far away imported module.

I’ll do some more research to better understand the behavior of Swift’s identifier shadowing with backticks to see if there’s something we can do to improve this rule without requiring a separate, more semantically-aware analyzer rule.

**Comment by jpsim** [comment]
ok, so some lightweight research tells me that we should be able to ignore backticks when checking usage:

```swift
let foo = 0

let closure: (Int) -> Void = { `foo` in
    print(foo)
}

closure(1) // prints '1'
```

**Comment by jpsim** [comment]
Fix in https://github.com/realm/SwiftLint/pull/4590

**Comment by chosa91** [comment]
Thanks for the quick fix, have a nice day!
