### ISSUE TITLE
0.50.1 - make install fails due to bazel missing

### ISSUE THREAD

**Issue by homedotorg** [realm/SwiftLint#4595]
Cloned the most recent 0.50.1 and make install fails due to bazel being missing.

**Comment by jpsim** [comment]
Yes, `make install` now requires bazel as of https://github.com/realm/SwiftLint/pull/4580 for the reasons I mentioned in that PR.

If you don't want to install bazel or can't use another installation method other than `make install` I could switch back to using SwiftPM for `make install`, but there are many other installation methods listed in https://github.com/realm/SwiftLint#installation

**Comment by homedotorg** [comment]
Thank you very much! I missed that installing bazel first is required. Have done so and it works now. Thanks again!
