### ISSUE TITLE
Unable to run unit tests in Xcode on release 0.50.1

### ISSUE THREAD

**Issue by ryanaveo** [realm/SwiftLint#4606]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
On latest release, 0.50.1 I am unable to run unit tests in Xcode.

#### Steps:

1. Clean derived data
2. Open workspace
3. Clean build folder
4. run CMD+U

##### Complete output when running SwiftLint, including the stack trace and command used

```
Unable to resolve build file: XCBCore.BuildFile (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:SwiftLintTestHelpers')

```

<img width="387" alt="image" src="https://user-images.githubusercontent.com/19614928/204652616-fe141f65-319d-4e67-a9b8-aa5fb3aeb382.png">

### Environment

Tag: 0.50.1
Scheme: SwiftLint-Package
Xcode

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?

Xcode 14.1
Build version 14B47b

**Comment by jpsim** [comment]
Can you please file feedback with Apple for this? If `swift test` works, then it's an Xcode bug that cmd-U doesn't when opening the same SwiftPM package.

FYI this is why I had the SwiftLintTestHelpers module as a normal `.target`, but then `swift build -c release` would fail, so I switched it back to a `.testTarget` in https://github.com/realm/SwiftLint/pull/4563.

If you know of a 3rd secret option to make both `swift build -c release` and Xcode unit tests happy, please let me know.

**Comment by jpsim** [comment]
Thanks for the creative fix, @ryanaveo! It would still be good to file feedback with Apple about this though.
