### ISSUE TITLE
SPM unstable-version error in 0.50.1 in Xcode 14.1

### ISSUE THREAD

**Issue by ehyche** [realm/SwiftLint#4608]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I added the latest SwiftLint to my SPM `Package.swift` as follows:

```
        .package(url: "https://github.com/realm/SwiftLint.git", exact: "0.50.1"),
```

and then attempted to reference the SPM plugin on a particular target in my `Package.swift` as follows:

```
    .target(
        ...,
        plugins: [
            .plugin(name: "SwiftLintPlugin", package: "SwiftLint")
        ]
    )
```

but I am getting the following Xcode package resolution error:

> Dependencies could not be resolved because package 'swiftlint' is required using a stable-version but 'swiftlint' depends on an unstable-version package 'swift-syntax' and root depends on 'swiftlint' 0.50.1.

<img width="634" alt="Screen Shot 2022-11-30 at 9 33 54 AM" src="https://user-images.githubusercontent.com/4141428/204823383-b42d38e7-3447-4ab7-b35e-386b4d944fe6.png">

I think this is because `SwiftLint`'s dependence on `swift-syntax` is for a particular hash instead of a tag. Here is the package dependence on 0.50.1:

```
        .package(url: "https://github.com/apple/swift-syntax.git", revision: "a82041008d2c678a97407fbd0ce420d3ab047538"),
```

Is it not possible to depend on a stable version of `swift-syntax` for 0.50.1?

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? `0.50.1`
* Installation method used (Homebrew, CocoaPods, building from source, etc)? `Swift Package Manager`
* Which Xcode version are you using (check `xcodebuild -version`)? `Xcode 14.1`

**Comment by jpsim** [comment]
Fixed in https://github.com/realm/SwiftLint/pull/4603

**Comment by jpsim** [comment]
No plans for an imminent release considering that there are many other installation methods for SwiftLint and you can always point to the latest commit on `main` to get the latest.
