### ISSUE TITLE
SwiftPM plugin doesn't work when integrated in the build phases of an Xcode project that contains nested SwiftPM packages

### ISSUE THREAD

**Issue by nkristek** [realm/SwiftLint#4628]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I have an Xcode project for an iOS app that contains nested SwiftPM packages. Until now SwiftLint was configured to run as a build phase that uses the installed version of the system, now I want to use the new SwiftPM plugin integration instead (to benefit from easier versioning control across multiple developers).

When using the SwiftLint plugin in the nested SwiftPM packages using the following code in the corresponding `Package.swift`:
```swift
dependencies: [
    .package(url: "https://github.com/realm/SwiftLint.git", branch: "main")
]
// ...
plugins: [
    .plugin(name: "SwiftLintPlugin", package: "SwiftLint")
]
```
the plugin works as intended.

However, when I try to integrate the plugin in the project (in order to lint the main app target) using the instructions [here](https://github.com/realm/SwiftLint#xcode-1) (adding the plugin in the `Run Build Tool Plug-ins` build phase), building the project fails with the error:
```
ld: entry point (_main) undefined. for architecture arm64
```

I'm building the project on an Apple Silicon based machine, but running Xcode under Rosetta2 results in the same error, but listing the Intel architecture instead. I've tried this in multiple codebases including a fresh iOS app (using the Xcode template) and I found out it always occurs once the project has a nested SwiftPM package.

#### Steps to reproduce

- Using Xcode 14.1
- Create a new project using the `App` template in the `iOS` category
  - Select `Storyboard` and `Swift` without Core Data or Tests
- Now we'll add the nested SwiftPM package
- Using `Finder` create a new folder called `NestedModule` inside the project folder
- In that folder create a new file called `Package.swift` with these contents:
```swift
// swift-tools-version:5.7

import PackageDescription

let package = Package(
    name: "NestedModule",
    platforms: [
        .iOS(.v14),
    ],
    products: [
        .library(name: "Nested", targets: ["Nested"])
    ],
    targets: [
        .target(name: "Nested")
    ]
)
```
- In the same folder create a new folder called `Sources`
- Inside `Sources` create a folder called `Nested`
- Inside `Nested` create an empty file called `File.swift` (to silence the warning about no source files)
- Drag the folder `NestedModule` into Xcode directly below the project
  - Instead of having a normal folder icon, the icon should be that of a SwiftPM package, if it doesn't, please restart Xcode
- In the project file > target > `Frameworks, Libraries, and Embedded Content`: press + to add the `Nested` module
- Try to build the project -> succeeds
- In the project file > project > SwiftPM dependencies: add SwiftLint (`https://github.com/realm/SwiftLint.git` targeting the `main` branch) without ticking any boxes when being asked if it should be included in the app
- In the project file > target > build phases tab > `Run Build Tool Plug-ins`: press + to add the SwiftLint plug-in
- Try to build the project -> fails with error `ld: entry point (_main) undefined. for architecture arm64`

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 
  * `main` branch (which currently uses a prebuilt binary of `0.50.1` under the hood)
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
  * SwiftPM
* Paste your configuration file:
  * Default

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? 
  * No
* Which Xcode version are you using (check `xcodebuild -version`)? 
  * 14.1
* Do you have a sample that shows the issue?
  * Reproducible with the steps above

**Comment by jpsim** [comment]
@technocidal some more plugin issues if you can take a look at this.

**Comment by technocidal** [comment]
@nkristek

I was able to reproduce your issue. Thanks for the perfect description. 

Looking around for some indication as this is quite a generic error I found [this thread](https://forums.swift.org/t/using-build-tool-plugins-with-xcproj/56064/10) which dealt with problems regarding the `@main` annotation. In that context it was the reason why the plugin didn't work, but for some reason this also works for your problem. 

So I've added 

```swift 

@main
struct Nested {
    static func main() {}
}
```

to the empty package and Xcode stopped complaining and SwiftLint worked as expected. 

I don't have any clue why this is the case. The `@main` syntax was introduced as a replacement for the `main.swift` convention and for some reason if a local package doesn't use it, Xcode falls down.

Could you try this with one of your actual packages and report back if it fixes it there as well?

**Comment by nkristek** [comment]
Thank you for your quick response! Amazingly this works!

Wow, this sounds like it is an issue in Xcode. Since the `NestedModule` package doesn't expose an executable product itself, I wouldn't have guessed that adding a main function there would fix the error.

I very much appreciate that you looked into it and I would consider this issue here solved.

Out of curiosity, do you know whether this `main` function inside the `Nested` struct will actually be called at some point?

**Comment by nkristek** [comment]
Unfortunately I just found out, that even though the iOS app builds now, it doesn't properly run anymore as soon as any nested package has a type annotated with `@main`. The compiler prefers this empty main function over my appdelegate, which is defined in the main app target and also annotated with `@main`.

I will still leave this issue closed (unless you think otherwise), since I believe this issue is not caused by SwiftLint and instead caused by a bug in Xcode.

**Comment by technocidal** [comment]
@mccarron @nkristek 

That sucks. Do we've enough information to open a Radar?

**Comment by mccarron** [comment]
Going to try a few things myself:
* Test on Xcode 14.2 GM that just came out yesterday
* Create a sample project that breaks with minimal inputs vs our current project

**Comment by nkristek** [comment]
@technocidal @mccarron 
I've tried the Xcode 14.2 RC and the result is unfortunately the same.

**Comment by jpsim** [comment]
Once someone's filed a feedback with Apple on this, I can try to get it looked at.

**Comment by technocidal** [comment]
@nkristek 

I'm currently filing the feedback and adding the package inside the project directory consistently fails. I can only get it to show up if the NestedModule directory is outside the actual project directory. I'm pretty sure that's a separate issue, but I'll adapt your steps to reproduce as to not make the feedback even more confusing. The underlying issue is still reproducible.

**Comment by technocidal** [comment]
And just as I try to file the feedback they completely break new project creation with Xcode 14.2. Filing the feedback using Xcode 14.1 and preparing to get an instant comment telling me to reproduce the issue using Xcode 14.2.

https://developer.apple.com/forums/thread/721912

**Comment by technocidal** [comment]
@jpsim @nkristek @mccarron 

Posted feedback https://feedbackassistant.apple.com/feedback/11877146

**Comment by jpsim** [comment]
Thanks for filing the FB. I've sent it to some Apple folks who work on SwiftPM plugins and CC'd you.
