### ISSUE TITLE
Not able to lint with a trailing space in a directory name

### ISSUE THREAD

**Issue by akuzminskyi** [realm/SwiftLint#4669]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

A linting directory name contains a trailing space in the end and SwiftLint is not able to lint it. 
in the example, `ABC ` folder contains `swift` files. 

Of course, trailing space is definitely not good, but I think the linter should lint it doesn't matter what kind of path. 

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
swiftlint "ABC\ /"
Linting Swift files at paths ABC\ /
Error: No lintable files found at paths: 'ABC\ /'
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? - 0.50.3
* Installation method used (Homebrew, CocoaPods, building from source, etc)? - Homebrew
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? - No
* Which Xcode version are you using (check `xcodebuild -version`)? - 14.2

**Comment by SimplyDanny** [comment]
Using `"ABC\ /"` looks for the folder `ABC\ ` literally (backslash is part of the folder name) which doesn't exist.

Trying either `swiftlint ABC\ /` or `swiftlint "ABC /"` (trailing slash is optional in both cases) works fine.

**Comment by akuzminskyi** [comment]
I apologize, found the issue in another part of the code.
