### ISSUE TITLE
 Object does not exist on the server in CircleCI

### ISSUE THREAD

**Issue by rarias84** [realm/SwiftLint#4670]
Using latest version from > 0.50.0 I got this error in CircleCI.

Downloading Pods/SwiftLint/swiftlint (29 MB)MiB | 1.74 MiB/s   
Error downloading object: Pods/SwiftLint/swiftlint (a1eaf42): Smudge error: Error downloading Pods/SwiftLint/swiftlint (a1eaf42bc959a146ba1bb8c378b7eba3ed18b2d62b83acbff01c0c57bd48b8bb): [a1eaf42bc959a146ba1bb8c378b7eba3ed18b2d62b83acbff01c0c57bd48b8bb] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to '/Users/distiller/project/.git/lfs/logs/20230104T131701.16992.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Pods/SwiftLint/swiftlint: smudge filter lfs failed

exit status 128
CircleCI received exit code 128

**Comment by SimplyDanny** [comment]
Is this still an issue, @rarias84?
