### ISSUE TITLE
Run unit tests with SPM

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#468]
The unit tests are only run in the Xcode job at the moment, it'd be good to also run the unit tests with SPM.

**Comment by norio-nomura** [comment]
Watching: [SR-592 Implement SE-0019 Swift Package Manager Testing](https://bugs.swift.org/browse/SR-592)

**Comment by jpsim** [comment]
It should be possible to do before that proposal is implemented. See this for example: https://github.com/PureSwift/SwiftFoundation/tree/develop/Sources/UnitTests

**Comment by jpsim** [comment]
Done in #476.
