### ISSUE TITLE
Feature Request: Own swift custom rules

### ISSUE THREAD

**Issue by JulesMoorhouse** [realm/SwiftLint#4687]
It would be great to be able to write our own rules in swift rather than regex.

I would imagine there would be a lot of suggested rules etc.

I see there is a Rules folder where rules can be written in swift, but obviously SwiftLint then needs to be rebuilt into an executable.

I guess rebuilding locally to support this wouldn't be too bad, but having to fork to do this is a bit much.

**Comment by marcelofabri** [comment]
This is now possible with Bazel which doesn't require you to fork SwiftLint. https://github.com/jpsim/swiftlint-bazel-example is an example of how to set it up.

**Comment by jpsim** [comment]
Marcelo's right, this is the recommended way to write custom SwiftLint rules written in Swift.

**Comment by alexeagle** [comment]
Instead of writing rules, you could also use our general-purpose Bazel linter framework, I could easily add SwiftLint there: https://github.com/aspect-build/rules_lint/issues/55
