### ISSUE TITLE
Failed to resolve dependencies

### ISSUE THREAD

**Issue by phranck** [realm/SwiftLint#4691]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

We are using several own Swift packages in our project. Each of them has SwiftLint as a package dependency, using it as a plugin for all targets as described here.

```
…
dependencies: [
    .package(url: "https://github.com/realm/SwiftLint.git", exact: "0.50.3")
]
…
targets: [
    .target(
        …
        plugins: [
            .plugin(name: "SwiftLintPlugin", package: "SwiftLint")
        ]
    )
]
```

After resetting the Swift package cache (clean build and deleting Derived Data has been done, too) Xcode always gives me the error:

```
Failed to resolve dependencies Dependencies could not be resolved because package 'swiftlint' is required using a stable-version but 'swiftlint' depends on an unstable-version package 'swift-syntax' and 'cadragebackendkit' depends on 'swiftlint' 0.50.3.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? - `0.50.3`
* Installation method used (Homebrew, CocoaPods, building from source, etc)? - `SPM`
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? - `No`
* Which Xcode version are you using (check `xcodebuild -version`)?  
```
Xcode 14.2
Build version 14C18
```

**Comment by SimplyDanny** [comment]
This is hopefully going to be resolved with the next release as SwiftLint now depends on a fixed tag version of SwiftSyntax.

See also https://github.com/realm/SwiftLint/issues/4641 and https://github.com/realm/SwiftLint/pull/4674.
