### ISSUE TITLE
On 0.7.2 "swiftlint rules" does not output all data

### ISSUE THREAD

**Issue by zippy1978** [realm/SwiftLint#470]
When issuing a "swiftlint rules" only rules ids are printed.
Is it a bug, or is there any reason for that ?

**Comment by zippy1978** [comment]
For info : last working version was 0.5.6

**Comment by jpsim** [comment]
There were a few changes to the rules command (#164 & #314) you're probably referring to the change from #314. These changes were made because they improved the readability and usefulness of the rules command, but now we're working on adding some of that information back in (see #435 & #456).

**Comment by zippy1978** [comment]
Ok,
Thank You !
