### ISSUE TITLE
Can the todo rule put the content of the todo statement in the warning?

### ISSUE THREAD

**Issue by lyptt** [realm/SwiftLint#478]
It'd be incredibly helpful to have the text immediately after a todo statement be placed in the warning, so you don't have to go into each warning to find out what the todo is about.

**Comment by jpsim** [comment]
great idea!

**Comment by scottrhoyt** [comment]
This is a nice idea. Shouldn't be hard to do. Thanks!

**Comment by masters3d** [comment]
this can be closed now
https://github.com/realm/SwiftLint/pull/765
