### ISSUE TITLE
Trim public API for 1.0.0

### ISSUE THREAD

**Issue by scottrhoyt** [realm/SwiftLint#479]
As we get closed to 1.0.0, we should decide what should be available in the public API for `SwiftLintFramework`. It would be fairly straightforward to to simply trim it to what is necessary for `swiftlint` and `SwiftLintFrameworkTests`, but we should discuss and perhaps consider `@testable` imports for `SwiftLintFrameworkTests` to reduce the surface area of the public API.

**Comment by jpsim** [comment]
:+1:

**Comment by norio-nomura** [comment]
I can't imagine which APIs are actually needed to be public without another client of SwiftLintFramework.
