### ISSUE TITLE
Can I create custom rule for finding bad file names?

### ISSUE THREAD

**Issue by IgorNikiforovV** [realm/SwiftLint#4796]
### New Issue Checklist

Hello, I have a question:
I have images in my project assets. I'd like these images have names like: "cover_favorite_channels" (snake_case + lower_case), but developers can create this like coverFavoriteChannels (camel_case) that wrong. I know that images stories in files like  "cover_favorite_channels.imageset".

Can I create some custom rule in swiftlint to find files with bad names like "FavoriteChannels.imageset" and show worrnings? 

I have regexp mask for these files names: "^.*[A-Z]+.*.imageset$".

**Comment by SimplyDanny** [comment]
Generally, SwiftLint only cares for `.swift` files and I guess that's never going to change. It's a linter for Swift code not for general files.

That said, even though not intended it's conceivable to lint names of Swift files with a custom rule. But that'd be more of a hack that won't work for general files either.

**Comment by IgorNikiforovV** [comment]
thanks @SimplyDanny for the explanation.
