### ISSUE TITLE
Finalize YAML configuration for 1.0.0

### ISSUE THREAD

**Issue by scottrhoyt** [realm/SwiftLint#480]
We have come to a structure for YAML configuration that I believe gives us a bit of room to grow. However we should consider additional use cases we will want to consider in 1.x.x releases to make sure we can avoid breaking changes for end users. Specifically it would be helpful to decide whether or not we want to eliminate any of the current shortcuts for configuring rules, decide on standard names, and what modifications can be made to rule configs to continue to support easy console output of rule configuration options.

**Comment by jpsim** [comment]
I'm pretty happy with the current configuration approach and would even keep the array/single value convenience configurations for `SeverityLevelsConfig`. Unless you have specific ideas of how to improve this for future-proofing or concrete issues with the current approach, I vote we consider this topic settled for 1.0.

**Comment by scottrhoyt** [comment]
I agree.

Any additional thoughts, @norio-nomura?

**Comment by norio-nomura** [comment]
I agree.

**Comment by jpsim** [comment]
Easy!
