### ISSUE TITLE
Question about Swiftformat and config file 

### ISSUE THREAD

**Issue by ilikerb0407** [realm/SwiftLint#4825]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

 
### Describe the bug

When I saw the version 0.51.0, it said that 

> SwiftFormat now **ignores** .swiftformat files when explicit --config file is provided 

but when I saw README.md, 

> If you have created a [config file], you can specify its path using --config "/path/to/your/config-file/". Alternatively, if you name the file .swiftformat and place it inside the project you are formatting, it will be picked up automatically

I just wonder if these two points contrast or not ?

Thanks for your time ~

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.51.2
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew

**Comment by CallThemAndSayHello** [comment]
Some of your message refers a tool called 
Swift F O R M A T.
Where you olaced the GitHub issue however is at the repository of
Swift L I N T.

The two separate programs had their own config file and format.

I am wondering if confusing the two might have been the issue?

**Comment by SimplyDanny** [comment]
This is the **SwiftLint** project. Please refer to https://github.com/nicklockwood/SwiftFormat to get you question answered.
