### ISSUE TITLE
local release builds bus errors parsing certain files in apple/swift, whereas shipping builds do not

### ISSUE THREAD

**Issue by mildm8nnered** [realm/SwiftLint#4831]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Shipping builds (e.g. 0.50.3) works fine, as do Debug builds.

```
brew install swiftlint
swiftlint version
git clone https://github.com/apple/swift
cd swift
swiftlint ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
```

```
Linting Swift files at paths ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting '26018-swift-parser-skipsingle.swift' (1/1)
...
Done linting! Found 6 violations, 0 serious in 1 file.
```

But if I try and build a Release build locally:

```
~/bin/swiftlint.release ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting Swift files at paths ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting '26018-swift-parser-skipsingle.swift' (1/1)
zsh: bus error  ~/bin/swiftlint.release 
```

`validation-test/compiler_crashers_fixed/26205-swift-lexer-leximpl.swift`

and other files are also affected.

I did produce my Release configuration build in a slightly hacky way - I changed the Run action of the swiftlint scheme to use Release configuration, and turned off the building of the unit tests for the run action.

##### Complete output when running SwiftLint, including the stack trace and command used

See above

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? `0.50.3`, and main  (commit `6983c813c8bee388519733b9d9f9729633b9df86`).
  
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew, and built from source
* Paste your configuration file:

none

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no

* Which Xcode version are you using (check `xcodebuild -version`)?

```
Xcode 14.2
Build version 14C18
```

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
for
{({{{class
case,
{[{{{{{{{{{{{{{{{{{{{{{{({{({{{{{{{[{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{({{(
{
{
{{{({{{
{{{{{{{
{{{{{{{({{{{{{{({{{{{{{{{{{{{{{{{{{{[{[{{{{{{{{{{{{{{{{{{{({{({{{{{{{[{{{{{{{{{{{{{{{{{{{{{{{{({{(
{({
{{{{
{{{{{{{{{[{({{{{{{{({{{{{{{{{{{{
```

**Comment by SimplyDanny** [comment]
This file definitely contains invalid Swift code. SwiftLint doesn't guarantee anything in this case.

**Comment by mildm8nnered** [comment]
So the problem with the specific files named above is that if I produce a release build locally and run it against them, I get a bus error.

If I run my homebrew installed `0.50.3` against them, or a Debug build, it runs fine.

```
% swiftlint ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting Swift files at paths ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting '26018-swift-parser-skipsingle.swift' (1/1)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:14:1: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration. (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:16:1: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration. (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:21:38: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration. (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:22:1: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration. (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:24:11: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration. (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:14:11: warning: Type Name Violation: Type name should be between 3 and 40 characters long: '' (type_name)
Done linting! Found 6 violations, 0 serious in 1 file.
%
%
% swiftlint.debug ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting Swift files at paths ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting '26018-swift-parser-skipsingle.swift' (1/1)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:14:1: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:16:1: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:21:38: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:22:1: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:24:11: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration (opening_brace)
/Users/martin.redington/Documents/Hudl/Source/swift/validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift:14:11: warning: Type Name Violation: Type name '' should be between 3 and 40 characters long (type_name)
Done linting! Found 6 violations, 0 serious in 1 file.
%
%
% swiftlint.release ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting Swift files at paths ./validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
Linting '26018-swift-parser-skipsingle.swift' (1/1)
zsh: bus error  swiftlint.release 
```

There must be something I'm doing or not doing to cause this and it would be great to understand what.

I opened other issues for other files in `swift` that SwiftLint `0.50.3` chokes on - I'm not sure I entirely buy that if the swift code is invalid, there are no guarantees about what will happen. I would generally expect us not to crash regardless of the input.

If I run `swiftc` against these files, it does not crash.

When I dug into some of the other problem cases, setting them up in test fixtures, they didn't crash there, and there aren't that many problem cases.

It seems a shame that SwiftLint can't lint swift, and I just think maybe it's worth digging a little bit more into these to see if there's some way to fix them, or at least to be able to provide a better story about why we can't lint swift itself.

**Comment by SimplyDanny** [comment]
The point is that these test cases aren't real Swift. I think it's totally acceptable if we cannot lint them or even crash. SwiftLint's rules have to rely on certain prerequisites. Otherwise they may become overly complex. There is a reason why the OSS check skips them.

I don't want to stop you from investigating why the different builds behave differently. However, your time is surely better invested in other parts of this project. 😉
