### ISSUE TITLE
disabling `blanket_disable_command` triggers `blanket_disable_command`

### ISSUE THREAD

**Issue by izik1** [realm/SwiftLint#4869]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

As the title says, using `// swiftlint:disable blanket_disable_command` (without re-enabling it) triggers itself.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
swiftlint lint --path blanket_disable_command.swift --no-cache 
warning: The --path option is deprecated. Pass the path(s) to lint last to the swiftlint command.
Linting Swift files at paths blanket_disable_command.swift
Linting 'blanket_disable_command.swift' (1/1)
[redacted]/blanket_disable_command.swift:1:22: warning: Blanket Disable Command Violation: The disabled 'blanket_disable_command' rule should be re-enabled before the end of the file (blanket_disable_command)
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
```
0.51.0
```
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
* Paste your configuration file:

(none/default)

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?
```
Xcode 14.3
Build version 14E222b
```
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// swiftlint:disable blanket_disable_command
// swiftlint:disable trailing_comma

let foo: [Int] = [
    0,
]
```

Note: if the disable commands are on the same line, then `blanket_disable_command` also triggers for `trailing_comma`

Note: This is a reduced example, I originally had this trigger on generated code that for some reason I decided to disable lints in rather than exclude from being linted all together.

**Comment by mildm8nnered** [comment]
In the original implementation (during development) you could do

`// swiftlint:disable blanket_disable_command comma`

which was nice, but then we changed the parsing for some reason, which broke that.

As a workaround, I would just do

```
// swiftlint:disable:next blanket_disable_command
// swiftlint:disable trailing_comma
```

You can also configure `blanket_disable_command` to allow some rules to be blanket disabled, via `allowed_rules` (by default this includes `file_header`, `file_length`, `file_name`, `file_name_no_space`, and `single_test_class`).

**Comment by SimplyDanny** [comment]
I agree with @mildm8nnered. The behavior described as a bug is the new (and consistent) way of how the `blanket_disable_command` rule works.

As explained in the previous comment, there are some options to deactivate this guard rule protecting from unintentionally disabled rules.
