### ISSUE TITLE
"Command PhaseScriptExecution failed with a nonzero exit code "happens when archieve

### ISSUE THREAD

**Issue by liubtNeu** [realm/SwiftLint#4880]
### Describe the bug

Linting 'ConsiderationView.swift' (300/700)
2023-04-12 18:18:22.929 swiftlint[9751:74957] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff81b6c31ba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff81b1e942b objc_exception_throw + 48
	2   Foundation                          0x00007ff81c4d10d3 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 2302
	3   Foundation                          0x00007ff81c524af3 -[NSRegularExpression(NSMatching) firstMatchInString:options:range:] + 146
	4   swiftlint                           0x0000000101f21c48 $s18SwiftLintFramework25ClosureEndIndentationRuleV24isFirstArgumentOnNewline33_AA5F6345B34AB3E1BF41C0044359A3D3LL_4fileSbAA22SourceKittenDictionaryV_AA0aB4FileCtFTf4nnd_nTf4xn_n + 376
	5   swiftlint                           0x0000000101f226eb $s18SwiftLintFramework25ClosureEndIndentationRuleV17validateArguments33_AA5F6345B34AB3E1BF41C0044359A3D3LL2in10dictionarySayAC9ViolationAELLVGAA0aB4FileC_AA22SourceKittenDictionaryVtFTf4nnd_nTf4nx_n + 43
	6   swiftlint                           0x0000000101f23475 $s18SwiftLintFramework25ClosureEndIndentationRuleV10violations33_AA5F6345B34AB3E1BF41C0044359A3D3LL2in2of10dictionarySayAC9ViolationAELLVGAA0aB4FileC_AA0A14ExpressionKindOAA22SourceKittenDictionaryVtFTf4nnnd_nTf4nnx_n + 229
	7   swiftlint                           0x0000000101d114c9 $s18SwiftLintFramework22SourceKittenDictionaryV18traverseDepthFirst33_0EBA09E17623EAE379194D9431F0C722LL20collectingValuesInto0G5BlockySayxGz_AHSgACXEtlFAA25ClosureEndIndentationRuleV9Violation33_AA5F6345B34AB3E1BF41C0044359A3D3LLV_Tg504$s18ab11Framework25tuvw16V10violations33_yz35B34AB3E1BF41C0044359A3D3LL2inSayAC9x28AELLVGAA0aB4FileC_tFAISgAA22deF6VXEfU_AkA0aB4FileCTf1ncn_nTf4nxng_n + 249
	8   swiftlint                           0x0000000101d1149c $s18SwiftLintFramework22SourceKittenDictionaryV18traverseDepthFirst33_0EBA09E17623EAE379194D9431F0C722LL20collectingValuesInto0G5BlockySayxGz_AHSgACXEtlFAA25ClosureEndIndentationRuleV9Violation33_AA5F6345B34AB3E1BF41C0044359A3D3LLV_Tg504$s18ab11Framework25tuvw16V10violations33_yz35B34AB3E1BF41C0044359A3D3LL2inSayAC9x28AELLVGAA0aB4FileC_tFAISgAA22deF6VXEfU_AkA0aB4FileCTf1ncn_nTf4nxng_n + 204
	9   swiftlint                           0x0000000101d1149c $s18SwiftLintFramework22SourceKittenDictionaryV18traverseDepthFirst33_0EBA09E17623EAE379194D9431F0C722LL20collectingValuesInto0G5BlockySayxGz_AHSgACXEtlFAA25ClosureEndIndentationRuleV9Violation33_AA5F6345B34AB3E1BF41C0044359A3D3LLV_Tg504$s18ab11Framework25tuvw16V10violations33_yz35B34AB3E1BF41C0044359A3D3LL2inSayAC9x28AELLVGAA0aB4FileC_tFAISgAA22deF6VXEfU_AkA0aB4FileCTf1ncn_nTf4nxng_n + 204
	10  swiftlint                           0x0000000101f1f7a3 $s18SwiftLintFramework25ClosureEndIndentationRuleV8validate4fileSayAA14StyleViolationVGAA0aB4FileC_tF + 99
	11  swiftlint                           0x0000000101d3daeb $s18SwiftLintFramework4RulePAAE4lint33_5A5F37FCDEE0B4D78BAE05A90BA8A062LL4file7regions9benchmark7storage13configuration025superfluousDisableCommandD017compilerArgumentsAA0B6ResultAELLVSgAA0aB4FileC_SayAA6RegionVGSbAA0D7StorageCAA13ConfigurationVAA011SuperfluousuvD0VSgSaySSGtFTf4nnnndnnn_n + 507
	12  swiftlint                           0x0000000101d3d771 $s18SwiftLintFramework15CollectedLinterV18getStyleViolations33_5A5F37FCDEE0B4D78BAE05A90BA8A062LL5using9benchmarkSayAA0G9ViolationVG_SaySS2id_Sd4timetGtAA11RuleStorageC_SbtFAA0B6ResultAELLVSgAA0W0_pXEfU0_TA + 113
	13  swiftlint                           0x0000000101d3d7c1 $s18SwiftLintFramework4Rule_pAA0B6Result33_5A5F37FCDEE0B4D78BAE05A90BA8A062LLVSgIgno_AaB_pAFIegnr_TRTA + 33
	14  swiftlint                           0x0000000101d1374d $sSa18SwiftLintFrameworkE11parallelMap9transformSayqd__Gqd__xXE_tlFADSryqd__SgGzXEfU_ySiXEfU_AA4Rule_p_AA0B6Result33_5A5F37FCDEE0B4D78BAE05A90BA8A062LLVSgTg5 + 77
	15  libswiftDispatch.dylib              0x00007ff8303b40f1 $sSiIgy_SiIegy_TRTA + 17
	16  libswiftDispatch.dylib              0x00007ff8303b4114 $sSiIegy_SiIyBy_TR + 20
	17  libdispatch.dylib                   0x00007ff81b3cf066 _dispatch_client_callout2 + 8
	18  libdispatch.dylib                   0x00007ff81b3e1ddd _dispatch_apply_serial + 161
	19  libdispatch.dylib                   0x00007ff81b3cf033 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x00007ff81b3d341f _dispatch_sync_function_invoke + 54
	21  libdispatch.dylib                   0x00007ff81b3e1747 _dispatch_apply_with_attr_f + 1388
	22  libdispatch.dylib                   0x00007ff81b3e1847 dispatch_apply + 45
	23  libswiftDispatch.dylib              0x00007ff8303b41b2 _swift_dispatch_apply_current + 100
	24  libswiftDispatch.dylib              0x00007ff8303b406c $sSo17OS_dispatch_queueC8DispatchE17concurrentPerform10iterations7executeySi_ySiXEtFZ + 156
	25  swiftlint                           0x0000000101d1357e $sSa18SwiftLintFrameworkE11parallelMap9transformSayqd__Gqd__xXE_tlFADSryqd__SgGzXEfU_AA4Rule_p_AA0B6Result33_5A5F37FCDEE0B4D78BAE05A90BA8A062LLVSgTg5 + 78
	26  swiftlint                           0x0000000101d12f36 $sSa18SwiftLintFrameworkE11parallelMap9transformSayqd__Gqd__xXE_tlFAA4Rule_p_AA0B6Result33_5A5F37FCDEE0B4D78BAE05A90BA8A062LLVSgTg5 + 150
	27  swiftlint                           0x0000000101d130d6 $sSa18SwiftLintFrameworkE18parallelCompactMap9transformSayqd__Gqd__SgxXE_tlFAA4Rule_p_AA0B6Result33_5A5F37FCDEE0B4D78BAE05A90BA8A062LLVTg5 + 22
	28  swiftlint                           0x0000000101d38b36 $s18SwiftLintFramework15CollectedLinterV18getStyleViolations33_5A5F37FCDEE0B4D78BAE05A90BA8A062LL5using9benchmarkSayAA0G9ViolationVG_SaySS2id_Sd4timetGtAA11RuleStorageC_SbtF + 854
	29  swiftlint                           0x0000000101d387bd $s18SwiftLintFramework15CollectedLinterV15styleViolations5usingSayAA14StyleViolationVGAA11RuleStorageC_tF + 13
	30  swiftlint                           0x0000000101be781a $s9swiftlint20LintOrAnalyzeCommandV3runys6ResultOyyt10Commandant0H5ErrorOyytGGAA0bcD7OptionsVFZy05SwiftB9Framework15CollectedLinterVcfU_ + 122
	31  swiftlint                           0x0000000101be9b02 $s9swiftlint20LintOrAnalyzeCommandV3runys6ResultOyyt10Commandant0H5ErrorOyytGGAA0bcD7OptionsVFZy05SwiftB9Framework15CollectedLinterVcfU_TA + 66
	32  swiftlint                           0x0000000101bdf8a6 $s18SwiftLintFramework13ConfigurationV9swiftlintE5visit33_30E847BB8C9F32DCEAC767137A79F9B7LL7linters7visitor7storage18duplicateFileNamesSayAA0abS0CGSayAA15CollectedLinterVG_AD20LintableFilesVisitorVAA11RuleStorageCShySSGtFAlOcfU_yyXEfU0_TA + 22
	33  swiftlint                           0x0000000101bdf8c1 $ss5Error_pIgzo_ytsAA_pIegrzo_TRTA + 17
	34  swiftlint                           0x0000000101be06a9 $ss5Error_pIgzo_ytsAA_pIegrzo_TRTA.5 + 9
	35  libswiftObjectiveC.dylib            0x00007ff8329088bc $s10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 44
	36  swiftlint                           0x0000000101bdb64b $s18SwiftLintFramework13ConfigurationV9swiftlintE5visit33_30E847BB8C9F32DCEAC767137A79F9B7LL7linters7visitor7storage18duplicateFileNamesSayAA0abS0CGSayAA15CollectedLinterVG_AD20LintableFilesVisitorVAA11RuleStorageCShySSGtFAlOcfU_ + 667
	37  swiftlint                           0x0000000101bdfa09 $s18SwiftLintFramework15CollectedLinterVAA0aB4FileCIggo_AcEIegnr_TRTA + 57
	38  swiftlint                           0x0000000101bd79d1 $sSa9swiftlintE11parallelMap9transformSayqd__Gqd__xXE_tlFADSryqd__SgGzXEfU_ySiXEfU_18SwiftLintFramework15CollectedLinterV_AG0eF4FileCTg5 + 689
	39  libswiftDispatch.dylib              0x00007ff8303b40f1 $sSiIgy_SiIegy_TRTA + 17
	40  libswiftDispatch.dylib              0x00007ff8303b4114 $sSiIegy_SiIyBy_TR + 20
	41  libdispatch.dylib                   0x00007ff81b3cf066 _dispatch_client_callout2 + 8
	42  libdispatch.dylib                   0x00007ff81b3e0e09 _dispatch_apply_invoke + 213
	43  libdispatch.dylib                   0x00007ff81b3cf033 _dispatch_client_callout + 8
	44  libdispatch.dylib                   0x00007ff81b3df0f6 _dispatch_root_queue_drain + 683
	45  libdispatch.dylib                   0x00007ff81b3df768 _dispatch_worker_thread2 + 170
	46  libsystem_pthread.dylib             0x00007ff81b56cc0f _pthread_wqthread + 257
	47  libsystem_pthread.dylib             0x00007ff81b56bbbf start_wqthread + 15
)
libc++abi: terminating due to uncaught exception of type NSException
/Users/yangchen_neu/Library/Developer/Xcode/DerivedData/Radio105-fjbyizmwyvoercedcypeyjhuzsia/Build/Intermediates.noindex/ArchiveIntermediates/radio105Dev-OneSpan/IntermediateBuildFilesPath/Radio105.build/Develop-iphoneos/radio105-OneSpan.build/Script-08B215AC248D19A6006AA5A6.sh: line 5:  9751 Abort trap: 6           "${PODS_ROOT}/SwiftLint/swiftlint"
Command PhaseScriptExecution failed with a nonzero exit code

### Environment

  - SwiftLint (0.42.0)
  - Xcode 14.2
  - mac os 13.3
  -

**Comment by mildm8nnered** [comment]
Are you able to provide a small sample of code that causes this to happen?

Would also be worth checking if it happens on the latest release (`0.51.0`) ...
