### ISSUE TITLE
Can't install with Homebrew

### ISSUE THREAD

**Issue by jkinder361** [realm/SwiftLint#4902]
### Describe the bug

Error: swiftlint: Failed to download resource "swiftlint_bottle_manifest"
The downloaded GitHub Packages manifest was corrupted or modified (it is not valid JSON): 
/Users/home/Library/Caches/Homebrew/downloads/ab7d962fa1557fb9ad772e918b2e9d230fa2588da64f0b2f6ab3e88b0cd8d881--swiftlint-0.51.0.bottle_manifest.json

**Comment by jpsim** [comment]
Looks like an issue with Homebrew rather than SwiftLint. Have you reported the issue to them?

**Comment by jkinder361** [comment]
I have now.  Thanks for getting back to me.
