### ISSUE TITLE
Performance issue on linting KeychainAccess with 0.8.0

### ISSUE THREAD

**Issue by norio-nomura** [realm/SwiftLint#491]
On linting https://github.com/kishikawakatsumi/KeychainAccess,
0.7.2:
```
swiftlint lint --config ~/.swiftlint-test.yml  3.44s user 0.15s system 91% cpu 3.931 total
```
0.8.0:
```
swiftlint lint --config ~/.swiftlint-test.yml  29.61s user 0.18s system 98% cpu 30.175 total
```

**Comment by scottrhoyt** [comment]
This is a direct result of the work in #365. Carthage did not show any significant change in performance. Will try to track down.

**Comment by jpsim** [comment]
Wow, that's a pretty big regression :grimacing:. Let's be sure to prioritize #376 before cutting the next release.
