### ISSUE TITLE
Build fail with Swift package

### ISSUE THREAD

**Issue by miku1958** [realm/SwiftLint#4973]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I add swift lint to a package, then run `swift build --configuration release`

When It running the SwiftLint plugin, it give me this error
Error: You don’t have permission to save the file “f24c644e2331ac8f4d3710e4d00158eb91751531e3b5ded134ae34577395934b.plist” in the folder “A4FD347F-F59D-3FB2-835A-CAC16AC563DB”.

### Environment

* SwiftLint version: 0.52.2
* Installation method used: SwiftLint plugin

**Comment by SimplyDanny** [comment]
Can you provide an example project that triggers this error when built?

Without a reproducer this issue is hard to tackle.

**Comment by miku1958** [comment]
[Package.zip](https://github.com/realm/SwiftLint/files/11474341/Package.zip)
Here is a example project, it did nothing, just a empty package and use SwiftLint as plugin

When I run 
```
swift build --product MockKit --configuration release
```

It will give me these errors:
```
error: failed: PrebuildCommand(configuration: SPMBuildCore.BuildToolPluginInvocationResult.CommandConfiguration(displayName: Optional("SwiftLint"), executable: <AbsolutePath:"/Volumes/Temp/Package/.build/artifacts/swiftlint/SwiftLintBinary.artifactbundle/swiftlint-0.51.0-macos/bin/swiftlint">, arguments: ["lint", "--quiet", "--force-exclude", "--cache-path", "/Volumes/Temp/Package/.build/plugins/outputs/package/MockKit/SwiftLintPlugin", "/Volumes/Temp/Package/Sources/MockKit/Mock.swift"], environment: [:], workingDirectory: nil), outputFilesDirectory: <AbsolutePath:"/Volumes/Temp/Package/.build/plugins/outputs/package/MockKit/SwiftLintPlugin/Output">)

Error: You don’t have permission to save the file “82a9a46b7a099b414347120e2933802c137b51d564463a3538c3edc35fa64eaf.plist” in the folder “A4FD347F-F59D-3FB2-835A-CAC16AC563DB”.
```

**Comment by SimplyDanny** [comment]
`/Volumes/Temp` is a protected location. Can you try to build the package somewhere in your user folder?

**Comment by miku1958** [comment]
/Volumes/Temp is a volume I created and I found out why, I need to add --disable-sandbox to swift build so that I can build for release but people around me can build the project without disabling it.

Might be adding it to wiki to help others
