### ISSUE TITLE
`redundant_self_in_closure` rule can behave unexpectedly with `withAnimation(_:_:)`

### ISSUE THREAD

**Issue by ski-u** [realm/SwiftLint#4988]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

1. Run SwiftLint v0.52.0 to the following code, for example
```swift
import SwiftUI

struct SampleView: View {
    @State private var number = 0

    var body: some View {
        Text("Sample")
    }

    private func add(_ number: Int) {
        withAnimation {
            self.number = number
        }
    }
}
```

2. SwiftLint removed `self` and we have an error like ↓
<img width="622" alt="スクリーンショット 2023-05-11 13 57 25" src="https://github.com/realm/SwiftLint/assets/37182704/b4264f78-3d5e-4883-ba5d-f59329673b0e">

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --enable-all-rules --fix
Correcting Swift files in current working directory
Correcting 'Contents.swift' (1/1)
/Users/sakai.yunosuke/test/Contents.swift:12:13 Corrected Redundant Self in Closure
Done correcting 1 file!
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?: 0.52.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?: Homebrew
* Paste your configuration file: No configuration file
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?: No
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?: Xcode 14.3
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.
  * I have an example in "Describe the bug" section above.

**Comment by SimplyDanny** [comment]
This is a known shortcoming of this rule that must generally be accepted, unfortunately. The reason is that normal SwiftLint rules only operate on the Swift AST without knowing anything about types.

However, as this case of updating state is quite common it seems reasonable to exclude simple assignments of the form `self.x = x` from being reported. There are still a lot of conceivable other cases that can not be recognized. So we have to expect and accept a certain amount of false positives in this rule.

**Comment by ski-u** [comment]
Thank you for your explanation and working to fix this!
