### ISSUE TITLE
Cannot build (or run) when SwiftLint installed via Swift Package

### ISSUE THREAD

**Issue by anosidium** [realm/SwiftLint#4991]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

We currently use SwiftLint via CocoaPods and it works fine and now we want to use it via Swift Package as we are migrating CocoaPods to Swift Package. The project build failed and can't even run via the iOS simulator. We get these errors.

I also tried by creating a brand new Xcode project and installed SwiftLint via Swift Package and it failed there too with the same error messages. SwiftLint does produce the warnings with Apple default template code for ViewController.swift.

I selected SwiftLint executable during installation and ensured that SwiftLintPlugin (SwiftLint) is added under Run Build Tool Plug-ins on Build Phases tab for the default target.

<img width="1792" alt="image" src="https://github.com/realm/SwiftLint/assets/39738481/0beb74d5-2e01-4051-8b0b-07bd2855833a">

There is an unofficial version from [here](https://github.com/lukepistrol/SwiftLintPlugin) and it works well in this [project](https://github.com/CodeEditApp/CodeEdit).

### Environment

* SwiftLint version: 0.47.1
* Installation method used: Swift Package

**Comment by anosidium** [comment]
Thank you very much! It works perfectly on a brand new Xcode project. It also works in the other Xcode project but it significantly increases the build time which is a major downgrade.

**Comment by SimplyDanny** [comment]
Is this issue resolved and can be closed, @anosidium?

**Comment by anosidium** [comment]
Yep. Thank you.

**Comment by anosidium** [comment]
@aaron-nunley I'm afraid I have not found a solution but at least I can get SwiftLint to run as intended even though it is very slow. I would suggest you open a new issue specifically about this.

**Comment by sstigler** [comment]
I'm seeing the same issue, w except with using the build tool plugin in a separate package: Build times are up by a large amount, seemingly because it has to build all of its dependencies every time. I can't figure out a way to cache them. It would be really nice to be able to use just a binary as the plugin, without dependencies.
