### ISSUE TITLE
Cannot set severity of `missing_docs` rule to `error`

### ISSUE THREAD

**Issue by JoshuaSullivan** [realm/SwiftLint#4993]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Configuring the `missing_docs` rule with a severity level of `error` is accepted by SwiftLint, but does not change the output. All violations continue to be warnings.

```lml
# This does nothing:
missing_docs:
  severity: error
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint
Linting Swift files in current working directory
Linting 'Example.swift' (1/1)
/Users/joshuasullivan/Documents/ios/experiment/SwiftLintTest/Example.swift:9:78: error: Force Unwrapping Violation: Force unwrapping should be avoided (force_unwrapping)
/Users/joshuasullivan/Documents/ios/experiment/SwiftLintTest/Example.swift:4:8: warning: Missing Docs Violation: public declarations should be documented (missing_docs)
Done linting! Found 2 violations, 1 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? `0.52.0`
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Both homebrew and Cocoapods
* Paste your configuration file:

```yml
opt_in_rules:
- missing_docs
- force_unwrapping

missing_docs:
  severity: error

force_unwrapping:
  severity: error
```

* No nested configurations.
* Xcode 14.3 & Command-line
* Example: https://github.com/JoshuaSullivan/SwiftLintMissingDocsExample

**Comment by SimplyDanny** [comment]
The severity configuration for this rule is a bit different than normal. For every visibility level, you can configure the severity that the violation should have when there isn't an attached documentation. For example, if you configure

```yaml
missing_docs:
  error: open, public
  warning: internal
```

you get errors for missing docs on `open` and `public` declarations and warnings for `internal` declarations.

**Comment by JoshuaSullivan** [comment]
Thank you for getting back to me so quickly. Unfortunately, when I place that code snippet into the .swiftlint.yaml file in my example, I'm getting this output:

```bash
$ swiftlint
warning: Invalid configuration for 'missing_docs'. Falling back to default.
Linting Swift files in current working directory
Linting 'Example.swift' (1/1)
/Users/joshuasullivan/Documents/ios/experiment/SwiftLintTest/Example.swift:9:78: error: Force Unwrapping Violation: Force unwrapping should be avoided (force_unwrapping)
/Users/joshuasullivan/Documents/ios/experiment/SwiftLintTest/Example.swift:4:8: warning: Missing Docs Violation: public declarations should be documented (missing_docs)
Done linting! Found 2 violations, 1 serious in 1 file.
```

The configuration is being rejected as invalid.

**Comment by JoshuaSullivan** [comment]
Confirming that this fixed the issue for me. Thank you!
