### ISSUE TITLE
Add the ability to auto-correct

### ISSUE THREAD

**Issue by segiddins** [realm/SwiftLint#5]

**Comment by krzyzanowskim** [comment]
👍

**Comment by skywinder** [comment]
Will be awesome. +1
I think this issue should be divided for a several sub-issues such as

1. detect possible fixups and show them in warnings messages
2. add special option to fix them (As example `-a, --auto-correct               Auto-correct offenses.` in rubocop (ruby linter)
3. add ability to enable/disable this corrections from .swiftlint.yml (depends of #3 )
4. and finally, if it's possible:  integrate it with Xcode to provide this autocorrections directly from Xcode

**Comment by martinlindhe** [comment]
+1

**Comment by lfaoro** [comment]
:+1:

**Comment by mgrebenets** [comment]
+1

We giving SwiftLint a try and one thing people find annoying is number of trailing whitespaces warnings. Why those show up in the code is another question, let's not go into details :)

But if SwiftLint could have an auto formatting option like Uncrustify for Objective-C, we would definitely turn it on. In that case though, it most likely has to be a plugin with "Format on Save" option.

**Comment by Craimasjien** [comment]
Since my current project is the first I'm really working with Swift seriously I'd love this feature. My and my team members already generated 999+ warnings and 318 errors based on SwiftLint, which means we are not really working via the coding standard.

**Comment by jpsim** [comment]
There's a first draft of autocorrect functionality at #241. I'd appreciate your feedback on how I'm planning for this to work. Thanks for your patience!

**Comment by jpsim** [comment]
Done in #241.

**Comment by skywinder** [comment]
:tada:

**Comment by Gerst20051** [comment]
👍
