### ISSUE TITLE
SPM can't find swiftlint in build products dir

### ISSUE THREAD

**Issue by marchinram** [realm/SwiftLint#5032]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

After adding SwiftLint to my project following [these](https://github.com/realm/SwiftLint#xcode-1) directions (I didn't link against the executable & framework products) the SwiftLint plugin cannot appear to find the executable, it assumes its at `/${BUILD_DIR}/${CONFIGURATION}/swiftlint`, I also have swiftlint installed via homebrew but the plugin isn't looking in `/usr/local/bin/swiftlint`

##### Complete output when running SwiftLint, including the stack trace and command used

Xcode build output when plugin is run on build (with directory names changed)

```bash
/usr/bin/sandbox-exec -p "(version 1)
(deny default)
(import \"system.sb\")
(allow file-read*)
(allow process*)
(allow file-write*
    (subpath \"/private/tmp\")
    (subpath \"/private/var/folders/zm/t882rxjn0m1b_vt35vzl3kym0000gn/T\")
)
(deny file-write*
    (subpath \"/src/to/app\")
)
(allow file-write*
    (subpath \"/derived/data/path/SourcePackages/plugins/playground.output/Playground/SwiftLintPlugin\")
)
" "/${BUILD_DIR}/${CONFIGURATION}/swiftlint" lint --quiet --force-exclude --cache-path /derived/data/path/SourcePackages/plugins/playground.output/Playground/SwiftLintPlugin /src/to/app/MyApp.swift

The file “swiftlint” doesn’t exist.
```

### Environment

* 0.52.2
* SPM
* Xcode 14.2
* Build version 14C18

**Comment by mason-livefront** [comment]
I am seeing the same issue.

**Comment by revolter** [comment]
I tried a workaround by adding a `Run Script` build phase with the content
```sh
ln -fs "${BUILD_DIR}/../../SourcePackages/artifacts/swiftlint/SwiftLintBinary.artifactbundle/swiftlint-0.52.2-macos/bin/swiftlint" "/${BUILD_DIR}/${CONFIGURATION}/swiftlint"
```
and even though I couldn't move it before the `Run Build Tool Plug-ins` build phase, I hoped that a second run would work, but it didn't.

I checked that the symbolic link gets created, and at the correct path (`/${BUILD_DIR}/${CONFIGURATION}/swiftlint`), and even successfully executed it from the terminal, but it most probably doesn't work because of the `/usr/bin/sandbox-exec` part.

**Comment by wtpalexander** [comment]
Works on Xcode 14.3 but not Xcode 14.2 for me.

**Comment by jpsim** [comment]
Thanks for filing an issue here. SwiftLint's SwiftPM plugin integration is outside my area of expertise, maybe @technocidal or @tonyarnold could shed some light on what may be happening here?

**Comment by tonyarnold** [comment]
Apologies for the delay in replying, folks. 

Honestly, this appears to be an issue internal to Xcode. I'm not sure there's much that we can do from outside of Apple beyond some of the beautiful, terrifying build phase hacks (or scheme build pre-actions) for releases of Xcode prior to version 14.3. 

I would suggest opening Feedback with Apple as a first step, but I'd imagine they're going to ask you to try to update to Xcode 14.3 or newer.

**Comment by marchinram** [comment]
I'll try with Xcode 14.3 today and close if it works ok

**Comment by marchinram** [comment]
Works for me now in 14.3, thx!
