### ISSUE TITLE
Severity-based `validates_start_with_lowercase` doesn't support disabling the check

### ISSUE THREAD

**Issue by auramagi** [realm/SwiftLint#5036]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

- Since 0.52.1 (#4970) the boolean setting for `validates_start_with_lowercase` is deprecated in favor of a severity-based setting
- The default setting is `error`, so in spite of release notes saying that `Not setting it disables the check`, not setting it will in fact enable the check and result in errors on triggering lines
- The effect of `validates_start_with_lowercase: false` is now impossible to be achieved in a non-deprecated way

**Comment by SimplyDanny** [comment]
Hm ... what would be a good semantic here to support disabling the check without the deprecation warning? I see two:

* Accept `warning`, `error` and `no`/`off` where `no`/`off` disables the check
* Accept `false` without a deprecation warning

And honestly, I don't like any of these much.

**Comment by Zim999** [comment]
`off` makes most sense to me
