### ISSUE TITLE
minor bugs with empty_count 

### ISSUE THREAD

**Issue by BluMist** [realm/SwiftLint#505]
example 1: if I just have a variable named count not associated with an array/object, the rule will trigger. maybe restrict the rule to only check for .count?
var count = 0
return count == 0 (trigger error warning)

as an extension, if I do if num + count > 0, the rule will trigger as well

example 2: (probably undetectable) - classes (ex. NSArray) can have .count but not .isEmpty

**Comment by jpsim** [comment]
These issues are known, which is why the rule isn't on by default. See #206 for a discussion around that.

**Comment by BluMist** [comment]
ah, got it, didn't surface in the search.

**Comment by marcelofabri** [comment]
I don't get why the rule shouldn't check for `.count`. It wouldn't catch a violation if `self` is a collection object (and `count` is used without `self.`), but I think that's a valid tradeoff.

**Comment by jpsim** [comment]
Anecdotally I can say that enabling this rule helped find some inefficient zero comparisons in some `Array` extensions. More false positives but also more true positives.
