### ISSUE TITLE
What do we do after writing custom rules?

### ISSUE THREAD

**Issue by amaurydavid** [realm/SwiftLint#5074]
Hello,
I've been following the examples from the readme to setup bazel and be able to write a custom rule using SwiftSyntax and it's working great.
However, now that I have a custom rule that is supposed to work (at least tests are saying so), how am I supposed to use it in my iOS app project? 
Do I understand correctly that I have to stop using the original swiftlint binary I installed with homebrew, and start using my custom version of swiftlint built with bazel instead ?

**Comment by SimplyDanny** [comment]
> Do I understand correctly that I have to stop using the original swiftlint binary I installed with homebrew, and start using my custom version of swiftlint built with bazel instead?

Yes, that's right. You have a new binary that includes your own written rules. You get the most of that if you're anyway building your project with Bazel. So you don't have to share the binary with your teammates but create/consume and run it in the normal build process.
