### ISSUE TITLE
Rule `direct_return` comments the whole line.

### ISSUE THREAD

**Issue by amaurydavid** [realm/SwiftLint#5081]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When using `swiftlint --fix` with the `direct_return`rule enabled, the following code lines are mishandled:
```swift
let view = nib.instantiate(withOwner: self, options: nil).first as! UIView // swiftlint:disable:this force_cast
return view
``` 

The rule currently updates the code to
```swift
 // swiftlint:disable:this force_cast        return nib.instantiate(withOwner: self, options: nil).first as! UIView // swiftlint:disable:this force_cast
```
adding the comment both before and after the statement.
An expected update would be 
```swift
return nib.instantiate(withOwner: self, options: nil).first as! UIView // swiftlint:disable:this force_cast
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.52.3
* Installation method used (Homebrew, CocoaPods, building from source, etc)? brew
* Paste your configuration file:

```yml
only_rules:
  - direct_return
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
* Which Xcode version are you using (check `xcodebuild -version`)? Version 14.3.1 (14E300c)

**Comment by mildm8nnered** [comment]
I have a possible fix for this ...
