### ISSUE TITLE
SPM dependency support

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#510]
Anyone wanting to use SwiftLintFramework as an SPM dependency currently needs to jump through the same hoops we do (https://github.com/realm/SwiftLint/blob/0.8.0/Makefile#L97-L102).

It'd be nice to figure out how to make plain old `swift build` work, and allow others depending on SwiftLintFramework to do the same.

I filed [SR-688](https://bugs.swift.org/browse/SR-688) to track part of this on the SPM side.

**Comment by norio-nomura** [comment]
Thanks for filing to bugs.swift.org. :pray:

**Comment by brentleyjones** [comment]
@jpsim Seems that it's now fixed, based on SR-688?

**Comment by jpsim** [comment]
Actually we managed to fix this prior to SR-688, so this should already work.

The catch is that the SourceKitten and libClang dependencies have to be installed. See https://github.com/realm/SwiftLint/blob/master/Makefile#L85

**Comment by jpsim** [comment]
This is essentially fixed.
