### ISSUE TITLE
Xcode does not show SwiftLint errors inline or in warning menu, only in terminal and build log.

### ISSUE THREAD

**Issue by DanielGrec** [realm/SwiftLint#5116]
### New Issue Checklist

- [ x ] Updated SwiftLint to the latest version
- [ x ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I have tried everything on the internet, there are very few issues reported on this topic. I have a MacBook Pro with M1, I have updated the path in Xcode based on your latest README, swiftlint works from terminal and can see the errors from the build log but do not appear inline in the editor. 

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
  - 0.52.4
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
  - Homebrew
* Paste your configuration file:
  - none
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  - none
* Which Xcode version are you using (check `xcodebuild -version`)?
  - 14.3.1

edited formatting

**Comment by sidster-io** [comment]
Same issue on Xcode 4.3.1

**Comment by DanielGrec** [comment]
I wonder when we'll get a fix for this. It's kinda the most useful feature of this, and it's not working for me for like 5 months now.

**Comment by SimplyDanny** [comment]
Please post your configuration and the script that calls SwiftLint in Xcode.

**Comment by DanielGrec** [comment]
`if test -d "/opt/homebrew/bin/"; then
  PATH="/opt/homebrew/bin/:${PATH}"
fi

export PATH

if which ./Pods/SwiftLint/swiftlint >/dev/null; then
    ./Pods/SwiftLint/swiftlint lint
else
    echo "error: SwiftLint does not exist, download it from https://github.com/realm/SwiftLint"
    exit 1
fi`

This is the script, but I've used everything, including the script in the README of the documentation, nothing works. What do you mean by configuration @SimplyDanny ?

**Comment by SimplyDanny** [comment]
I mean the `.swiftlint.yml` file.

**Comment by mildm8nnered** [comment]
This works fine for me in a large project, with lots of custom rules, with Xcode 14.3.1 on Ventura, home-brew install, so I suspect it's something specific to your setup or the way you're calling SwiftLint

**Comment by DanielGrec** [comment]
#Last change with swiftlint version 0.27.0
only_rules:
    - class_delegate_protocol
    - closing_brace
    - colon
    - comma
    - compiler_protocol_init
    - control_statement
    - custom_rules
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - cyclomatic_complexity
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_init
    - file_length
    - force_try
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - force_cast
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - force_unwrapping
    - function_body_length
    - function_parameter_count
    - implicit_getter
    - large_tuple
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_nsgeometry_functions
    - legacy_constant
    - legacy_constructor
    - line_length
#    - nesting
    - object_literal
    - opening_brace
    - operator_whitespace
    - overridden_super_call
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_optional_initialization
    - redundant_string_enum_value
    - redundant_void_return
    - return_arrow_whitespace
    - statement_position
    - switch_case_on_newline
    - syntactic_sugar
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    - type_name
    - unused_closure_parameter
    - unused_optional_binding
    - valid_ibinspectable
    - vertical_whitespace
    - weak_delegate

included:
    - projectName
    - projectName Tests
    - projectName UITests
    - Watch Extension
    - Shared
excluded:
    - Pods
    - projectName/common-utils/backend/bluetooth/LWM2M_protocol/Wakamaa_protocol
    - projectName/common-utils/backend/communication/coap/protobuf
    - projectName/common-utils/frontend/SlideMenuController/SlideMenuController.swift
    - projectName/common-utils/crypto/ChaCha20Poly1305.swift
    - projectName Tests/common-utils/crypto/CryptoTest.swift
function_parameter_count:
    warning: 8
    error: 8
function_body_length:
    warning: 90
    error: 100
large_tuple:
    warning: 5
    error: 5

# rules that have both warning and error levels, can set just the warning level
line_length: 170
type_body_length:
  warning: 6000
  error: 7000
file_length:
  warning: 18000
  error: 20000
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
reporter: "checkstyle" # reporter type (xcode, json, csv, checkstyle, junit)


I don't know what's wrong but it used to work, and without changing anything, just randomly stopped working, and it doesn't work for any of my colleagues, so I suppose something got merged and wrecked SwiftLint for us.

**Comment by SimplyDanny** [comment]
The line `reporter: "checkstyle"` is the culprit. It must have the value `xcode` to make SwiftLint report issues in the Xcode UI.

**Comment by DanielGrec** [comment]
That was the problem. Thank you! So simple yet overlooked.
