### ISSUE TITLE
Add example .swiftlint.yml files

### ISSUE THREAD

**Issue by scottrhoyt** [realm/SwiftLint#517]
I've toyed around with the idea of having an `ExampleConfigurations` directory to facilitate configuration file documentation and potentially circulating common configurations. It might even be an imperfect, but lightweight, way of collecting feedback on what default values should be and which custom rules should be considered for including as standard `Rule`s. The more I think about it, it probably makes more sense as a separate repo. I wonder though, is there yet enough variation in community configurations and interest to support this?

**Comment by jpsim** [comment]
We could ask a few popular & actively maintained projects that use SwiftLint to share their workflow. Realm, Lyft & Breather come to mind, I'm sure there are many more.

**Comment by norio-nomura** [comment]
I want `.swiftlint.yml` for benchmarking that runs all rule.

**Comment by scottrhoyt** [comment]
I can probably make that happen, @norio-nomura. I have been playing around with adding serialization to YamlSwift. I have all the cases covered for our needs, however YAML allows some features that make serializing it in the general case a bit hard than I expected at first, but will most likely have it done soon. With that, we can pretty easily do a `swiftlint init --all_rules` that code generate a `.swiftlint.yml` file whitelisting all the `Rule`s.

**Comment by norio-nomura** [comment]
> With that, we can pretty easily do a swiftlint init --all_rules that will generate a .swiftlint.yml file whitelisting all the Rules.

Nice! :+1:
