### ISSUE TITLE
NSNumber.init(value:) is throwing warning, please disable it. It's a wrong rule. Using this method should be fine.

### ISSUE THREAD

**Issue by amadkhilji** [realm/SwiftLint#5172]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [ ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Please describe the rule idea, format
this issue's title as `Rule Removal Request: [ns_number_init_as_function_reference]`:

1. This rule shouldn't be forced and taken out.
2. This syntax is perfectly fine and should be allowed: `let idxNumber = NSNumber.init(value: idx)`

**Comment by SimplyDanny** [comment]
Please provide an example in which the rule triggers falsely. It might be possible to fix this false positive. If you don't like the rule in general, just disable it in your configuration.

**Comment by amadkhilji** [comment]
![Screenshot 2023-08-14 at 12 44 03 PM](https://github.com/realm/SwiftLint/assets/1125063/c04dd337-fbac-43ca-bf6b-8c006ed148ad)

**Comment by marcelofabri** [comment]
Sorry, should've added this as an example when I implemented the rule. The fix is in https://github.com/realm/SwiftLint/pull/5176.

In the meantime, you can use `NSNumber(value: 0.0)` to workaround the bug - this is the more common Swift idiom, so that's why we didn't catch this earlier.
