### ISSUE TITLE
Consider adding a swiftlint init?

### ISSUE THREAD

**Issue by scottrhoyt** [realm/SwiftLint#518]
Inspired by #517, maybe we should have a `swiftlint init` that creates a mostly empty, but commented, `.swiftlint.yml` file in the current directory a la `pod init`, `fastlane init`, `travis init`, etc?

In the future, such a command could even be used to fetch a specific config from a repo, like an `Examples` repo or an internal organization repo. Just a thought.

**Comment by jpsim** [comment]
:+1:. Bonus points for keeping the README sample in sync with this template.

**Comment by AliSoftware** [comment]
@scottrhoyt I just opened #532 as I think this idea is great but we could bring it even further with an even more generic `swiftlint config` command :wink

**Comment by scottrhoyt** [comment]
@AliSoftware I think we are on the same page with the capabilities, but it seems to me that the community standard is `toolname init` like the examples given above. Do you have any examples of the `toolname command init` style?

**Comment by AliSoftware** [comment]
Yeah I see your point.
But given how many commands related to configuration might be added, I found grouping them might be nice.

As an example, in CocoaPods we have indeed `pod init` but also `pod spec create` and `pod lib create` too.

Anyway, I see two options:
1. We ad

**Comment by AliSoftware** [comment]
Sorry, I hit the submit button too early by mistake. Comment edited.

**Comment by scottrhoyt** [comment]
Those are good options. Any thoughts, @jpsim ?

**Comment by jpsim** [comment]
Option 2 is most sensible to me: `swiftlint config create` and `swiftlint config help` are two commands that could come to mind. In the distant future, we could have a `swiftlint config explain` which would give an overview of which files are included/excluded, which nested configurations apply...

I'm letting my imagination get the best of me here, but the point being that I prefer bundling that functionality under the `config` umbrella.

**Comment by jpsim** [comment]
I think we can close this and move the (fairly inactive now) conversation to #532.
