### ISSUE TITLE
no_magic_numbers - Ignore "100" when part of percent conversions

### ISSUE THREAD

**Issue by LowAmmo** [realm/SwiftLint#5185]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

This one probably requires making too broad of an assumption, but would be awesome if the no_magic_numbers logic was smart enough to ignore "100" when it's part of a percent conversion.

For example:

     let batteryPercent = Int(batteryLevel * 100)

     public var mediaVolume: Int {
        return Int(self.outputVolume * 100)
     }

My idea would be that if  the "magic number" is 100 (or 100.0), and used for multiplication or division:

     a * 100
     100 * b
     c / 100

Then ignore the "100"?

Might be able to get away with ignoring any conversion numbers "100, 1000, 1000000", etc. (any instance of 1 followed by any number of 0's)

Totally okay if all this did was make you laugh at my laziness of not wanting to put in a disable comment. But, figured it couldn't hurt to ask!

-Thanks!

**Comment by SimplyDanny** [comment]
Ignoring any power of 10 sounds reasonable, perhaps even independent of the context this number appears in.
