### ISSUE TITLE
add custom_rule under only_rule

### ISSUE THREAD

**Issue by edias** [realm/SwiftLint#5187]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

On the website it states. 

_If using custom rules in combination with only_rules, make sure to add custom_rules as an item under only_rules._

However, I could not find any example of how to do that and all attempts lead to multiple errors due to misconfiguration. 

Can anybody please show an example of how this can be done? It would be great if the website docs could also be updated to include this information.

**Comment by edias** [comment]
Just figured out

**Comment by daniel-moh** [comment]
@edias if you could share an example of how you got this to work, that'd be amazing! I have tried to set something like this up for our projects but the latest version (0.55.1) doesn't seem to support this anymore... #5689.
