### ISSUE TITLE
Rule Request: [`unused_directive`] triggered for unused disable/enable rule directives in source code

### ISSUE THREAD

**Issue by laralove143** [realm/SwiftLint#5213]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

We can use something like
`// swiftlint:disable <rule>`
to disable/enable a rule temporarily

But sometimes these are unnecessary and just polluting the codebase, when:
1. We edited the `.swiftlint.yml` file to already disable/enable the rule
2. It was a false-positive fixed in a later SwiftLint release
3. The code was edited and no longer triggers the lint
4. We added a duplicate directive, essentially disabling/enabling a lint that's already disabled/enabled
5. We falsely foresee that the lint would be raised, so add an disable/enable directive for it in advance

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this: None, hopefully we can discuss this here
2. Provide several examples of what _would_ and _wouldn't_ trigger violations:
    - Triggering: `let abc: Void // swiftlint:disable:this colon`
    - Not triggering: `let abc:Void // swiftlint:disable:this colon` _(would still trigger if the rule is already disabled, in another directive or config file)_
3. Should the rule be configurable: I don't think so
4. Should the rule be opt-in or enabled by default: Default IMO

Many linters have this feature, and many more are adding it, like [Rust](https://rust-lang.github.io/rfcs/2383-lint-reasons.html#expect-lint-attribute), I think it'd be a good addition

**Comment by SimplyDanny** [comment]
What about [`superfluous_disable_command`](https://realm.github.io/SwiftLint/superfluous_disable_command.html)? Isn't it what you're asking for?

**Comment by laralove143** [comment]
ah yes apparently, the docs for that could use examples though

**Comment by mildm8nnered** [comment]
> ah yes apparently, the docs for that could use examples though

Adding more examples to the docs is pretty easy, or, if you have some, I can add them for you
