### ISSUE TITLE
Latest release notes use wrong identifier for new rule (should be `private_swiftui_state` not `private_swiftui_state_property`)

### ISSUE THREAD

**Issue by sebj** [realm/SwiftLint#5244]
The [release notes for 0.53.0](https://github.com/realm/SwiftLint/releases/tag/0.53.0) use the wrong identifier for a newly added opt-in rule (which briefly had me puzzled after copy-pasting and getting an Xcode warning!).

They mention `private_swiftui_state_property` [when the identifier is in fact `private_swiftui_state`](https://github.com/realm/SwiftLint/pull/4769/files#diff-e1542eddd9cb2599db6b6ed58d025cbde989f7e920292122c1581301bd8171b6R10) (despite the name of the merged PR)

**Comment by mildm8nnered** [comment]
I can put up a patch for this later today - there's another typo I'd like to fix as well
