### ISSUE TITLE
unneeded_override doesn't check init

### ISSUE THREAD

**Issue by inotetw** [realm/SwiftLint#5265]
### New Issue Checklist

- [ ] Updated SwiftLint to the latest version
- [ ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

unneeded_override rule does not check  init

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version 0.52.3
* Installation method used CocoaPods

In the following code, `override init()` will not trigger:
```swift

    override init() {
        super.init()
    }

    override func printHi() {
        super.printHi()
    }
```

**Comment by leonardosrodrigues0** [comment]
I opened #5270 with a new option for the rule to affect initializers. I set the option to false by default but I don't know if it is the best decision. It is also my first PR here, so if anyone has suggestions please feel free.
