### ISSUE TITLE
No updating requirements in GitHub Release

### ISSUE THREAD

**Issue by 417-72KI** [realm/SwiftLint#5267]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

In past versions, when Swift requirements were updated, they were listed as `Breaking` in the release (e.g. [`0.50.0`](https://github.com/realm/SwiftLint/releases/tag/0.50.0), [`0.47.0`](https://github.com/realm/SwiftLint/releases/tag/0.47.0), [`0.46.5`](https://github.com/realm/SwiftLint/releases/tag/0.46.5)).
In #5235 Swift 5.9 is now required, but there was no mention of this in [the latest release](https://github.com/realm/SwiftLint/releases/tag/0.53.0), so I had to check the logs when a build failed in a Swift 5.8 environment.

It would be great if the latest release clearly states that Swift 5.9 is now required.

<img width="769" alt="image" src="https://github.com/realm/SwiftLint/assets/4150060/0b01b090-690d-4b2e-8239-f43c4d592906">

**Comment by jpsim** [comment]
0.53.0 still builds with Swift 5.8.
The next release will require building with Swift 5.9.

**Comment by 417-72KI** [comment]
@jpsim 
I'm sorry that I thought I was looking at Package.swift with the `0.53.0` tag, but I was looking at the `main` one.
