### ISSUE TITLE
Validate the number of functions in a type

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#53]
Types should contain 10 functions or less.

**Comment by keith** [comment]
Would the functions being `public/internal/private` affect this number? Also would this also ideally include or exclude extensions? In just type definitions ignoring extensions this should be pretty easy to implement.

**Comment by jpsim** [comment]
I don't think ACL would affect this rule, actually, because that only affects usage complexity rather than implementation complexity.

**Comment by jpsim** [comment]
I no longer think we should actually do this. It could easily lead to encouraging poor design patterns.
