### ISSUE TITLE
SourceKitten

### ISSUE THREAD

**Issue by BorisBakhlykov** [realm/SwiftLint#5325]
Hello! I received this error "SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed", when wrote fix command "swiftlint --fix".

Update and reinstall aren't help me.

**Comment by SimplyDanny** [comment]
On macOS, make sure Xcode is installed. See https://github.com/realm/SwiftLint/issues/1466#issuecomment-297265863 for help.

**Comment by taher-mosbah** [comment]
This also occurs when using a nightly/snapshot toolchain. (tested with latest Swift 5.10 Development Toolchain).

**Comment by ObjectiveCesar** [comment]
> This also occurs when using a nightly/snapshot toolchain. (tested with latest Swift 5.10 Development Toolchain).

This fixed it for me. I had to remove the Swift 6.0 snapshot toolchain.

**Comment by nysander** [comment]
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed

macOS Sequoia and Xcode 16.0

**Comment by raiffeisenhumobil** [comment]
> SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
> 
> macOS Sequoia and Xcode 16.0

any solution on this? I have the same

**Comment by dabrahams** [comment]
This should be reopened.

**Comment by ByeongGwan-Seo** [comment]
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed

same here. guess this should be reopened.
i've checked swiftlint --version on terminal. it worked.
but this error appears

**Comment by ih-codes** [comment]
```
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
```
Also seeing this after downloading the Xcode 12.6 RC. Tried removing and reinstalling with no luck.

I'm on MacOS Sequoia 15.1.1 (24B91).

**Comment by ognerub** [comment]
I had this problem when used xcodes in terminal. My version of Xcode 16.1 was marked as "installed". Then I opened AppStore and downloaded Xcode app from there. And after this problem solved. And xcodes it terminal now shows "installed, selected". Maybe it is not necessary to download app from AppStore and only type command it terminal (xcodes select) but in mine case only new app download helped.
P.S. after install Xcode from AppStore, xcodes in terminal showed something like this:
xcodes installed
16.1 (16B40) (Selected) /Applications/Xcode.app
16.1 (16B40) /Applications/Xcode-16.1.0.app

So it seems was an issue in Xcodes duplicates. And command in terminal "xcodes uninstall 16.1.0" erased unnecessary one.
After this i`ve got this list
xcodes installed
16.1 (16B40) (Selected) /Applications/Xcode.app

And now everything works fine

**Comment by ognerub** [comment]
In truth after update to Sequoia I`ve deleted XCode 15.3 from xcodes, and now use only version 16.1.
But you can try)

**Comment by TimOliver** [comment]
Hey folks! I also just encountered this error message and found this issue while looking for an answer.

Doing this solved it for me: https://github.com/realm/SwiftLint/issues/1466#issuecomment-297265863

**Comment by marcoroth** [comment]
Thanks @TimOliver, that did it for me too! 🙏🏼

**Comment by olcayertas** [comment]
I have the same issue. I have tried both using SwiftLint as Build Tool Plug-in and using it from command line (installed with brew) and got the same error:

**Error from terminal:**

```
swiftlint --fix
Correcting Swift files in current working directory
warning: 'unused_declaration' should be listed in the 'analyzer_rules' configuration section for more clarity as it is only run by 'swiftlint analyze'.
warning: 'unused_import' should be listed in the 'analyzer_rules' configuration section for more clarity as it is only run by 'swiftlint analyze'.
Correcting 'Tests.swift' (3/3)
Correcting 'AppDelegate.swift' (1/3)
Correcting 'ViewController.swift' (2/3)
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
zsh: trace trap  swiftlint --fix
```

Error from Xcode:

```
Plug-in ended with uncaught signal: 5)
SourceKittenFramework/library_wrapper.swift:58: Fatal error:
Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
```

**Comment by riderx** [comment]
> https://github.com/realm/SwiftLint/issues/5325#issuecomment-1905730385

Can we get it work to nightly as well ? it's super annoying when we test new OS release that lint fail

**Comment by talesp** [comment]
I'm getting this error with Xcode 26.1 installed with https://github.com/XcodesOrg/XcodesApp (and symlinked as Xcode.app inside applications)

```
ls -ltra /Applications/Xcode*
lrwxr-xr-x  1 talesp  admin  30 Nov  4 11:18 /Applications/Xcode.app@ -> /Applications/Xcode-26.1.0.app

/Applications/Xcodes.app:
total 0
drwxrwxrwx   10 talesp  staff   320 Sep 20 06:24 Contents/
drwxrwxrwx@   3 talesp  staff    96 Oct 14 10:55 ./
drwxrwxr-x  122 root    admin  3904 Nov  4 11:21 ../

/Applications/Xcode-26.1.0.app:
total 0
drwxr-xr-x@   3 talesp  staff    96 Nov  4 11:16 ./
drwxr-xr-x   16 talesp  staff   512 Nov  4 11:17 Contents/
drwxrwxr-x  122 root    admin  3904 Nov  4 11:21 ../
```

SwiftLint installed with brew. 

swiftlint version
0.62.2

**Comment by acevif** [comment]
I've encountered a similar error with:
* Xcode 26.1.1
* macOS 26.1（25B78）
* SwiftLint SPM Build Tool Plugin

This error was resolved for me after the following steps:

**1. Run `xcode-select`**

```
$ sudo xcode-select -s /Applications/Xcode_26.1.1.app/Contents/Developer
```  

See:
* https://github.com/realm/SwiftLint/issues/5325#issuecomment-2566886224
* https://github.com/realm/SwiftLint/issues/1466#issuecomment-297265863

**2. Restart Xcode**

```
$ xed .
```

Hope this helps.



Thanks to @TimOliver and @jpsim.

**Comment by legoesbenr** [comment]
Reinstalling Xcode fixed it for me...  Save version etc... 
Thanks Apple...

**Comment by talesp** [comment]
I get this error when installing Xcode via https://github.com/XcodesOrg/XcodesApp. `sudo xcode-select -s` does not solve, I had to install from App Store

**Comment by samuelowino** [comment]
**SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed**

I'm getting this error in 2026, after installing with home-brew. 
Considering how long this issue has been open, Its safe to assume this won't be fixed.

**Comment by TimOliver** [comment]
> Considering how long this issue has been open, Its safe to assume this won't be fixed.

But this issue is closed... 😅

**Comment by samuelowino** [comment]
> > Considering how long this issue has been open, Its safe to assume this won't be fixed.
> 
> But this issue is closed... 😅

😅 closed != fixed

**Comment by SimplyDanny** [comment]
This issue has reportedly always been solved by reinstalling/reselecting Xcode, hence I don't see what SwiftLint could do better.

One thing to know is that you can `--disable-sourcekit` in case you're not relying on SourceKit-based rules (which there are only a few of them left). That avoids the issue entirely as there's no runtime dependency required anymore.

**Comment by samuelowino** [comment]
> This issue has reportedly always been solved by reinstalling/reselecting Xcode, hence I don't see what SwiftLint could do better.
> 
> One thing to know is that you can `--disable-sourcekit` in case you're not relying on SourceKit-based rules (which there are only a few of them left). That avoids the issue entirely as there's no runtime dependency required anymore.

Thanks @SimplyDanny , I was able to get it to work by reselecting Xcode. 
Cheers!

**Comment by yannbonafons** [comment]
Just in case, I got this error because, after installingand deleting different Xcode version, I had no more command line tools selected (in Settings>Locations>Command line tools). Selecting one solve the problem.
