### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by nokiaowner** [realm/SwiftLint#5369]
Hello, 

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest.
Does SwiftLint need to include this manifest?
Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

Here’s some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

**Comment by SimplyDanny** [comment]
Considering that SwiftLint is a tool that only comes into play at build time, I don't think this topic is relevant for it. It's not an SDK that gets included in a product.

One can image a product like a Swift editor with integrated linting, though. In this unlikely case, folks need to create an explicit issue requesting such a manifest.

That said, whether any declaration is necessary, depends on your usage. As long as SwiftLint is used as a build tool, this doesn't become applicable.

This is only my naive view on the topic. I don't have any experience with it myself.

@jpsim: Please confirm or object.

**Comment by aiKrice** [comment]
@SimplyDanny I can confirm. The list of involved lib has been published (more over it's just a tool)
