### ISSUE TITLE
swiftlint and SwiftLintFramework being build when only using SwiftLintPlugin on MacOS

### ISSUE THREAD

**Issue by geertbleyen** [realm/SwiftLint#5372]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
I've noticed that while we are only using and referring SwiftLintPlugin form the SwiftLint SPM products, Xcode is building the SwiftLint and SwiftLintFramework targets regardless. These targets take quite some time to build, and don't add anything to the result as they are not used anywhere, and the plugin uses the binaryTarget dependency on MacOS.
Tbh, I suspect this to be an Xcode/Apple related issue, but wanted to report it nonetheless to verify the finding.
Are we doing something wrong, or this is just how it currently works in Xcode 

### Environment

* SwiftLint version: 0.54.0
* Xcode version: 15.0.1
* Installation method: SPM integration
<img width="860" alt="image" src="https://github.com/realm/SwiftLint/assets/71486361/1c4a6d23-33be-49d8-b6d0-7803414b53ca">
<img width="432" alt="image" src="https://github.com/realm/SwiftLint/assets/71486361/caa8b73f-f388-4925-8266-a75f865728f8">
<img width="812" alt="image" src="https://github.com/realm/SwiftLint/assets/71486361/70b0ad45-fa3e-4a89-af43-3462a0af025c">
Don't mind the 0.51.0 version specced here, as our package.resolved has 0.54.0 locked in.
<img width="601" alt="image" src="https://github.com/realm/SwiftLint/assets/71486361/8bd4cadc-6b67-452f-ba2d-6e6af97261b5">

* Paste your configuration file: NA

**Comment by julien-baillon** [comment]
Hi @SimplyDanny, I'm facing the same issue. I have created this [PR](https://github.com/realm/SwiftLint/pull/5404) to fix this issue. Could you test it by using `.package(url: "https://github.com/julien-baillon/SwiftLint", branch: "jb-plugin-dependencies"),` in you `Package.swift`.
