### ISSUE TITLE
`swiftlint:disable` instructions do not work in block comments.

### ISSUE THREAD

**Issue by lhunath** [realm/SwiftLint#5374]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

SwiftLint allows the user to selectively modify the configuration for specific cases using statements such as:
```
        // swiftlint:disable:next unused_setter_value - https://github.com/realm/SwiftLint/issues/3863
        set { fatalError() }
```

This is very useful for scenarios where there needs to be a deviation or we need to work around a limitation.

Unfortunately, SwiftLint does not appear to recognize block-style comments:

```
        /* swiftlint:disable:next unused_setter_value - https://github.com/realm/SwiftLint/issues/3863 */
        set { fatalError() }
```

This is especially notable for situations where we would prefer to apply the rule to the current line but are syntactically prevented from using `//`-style comments, eg:

```
        set { fatalError() /* swiftlint:disable:this unused_setter_value - https://github.com/realm/SwiftLint/issues/3863 */ }
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.53.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? homebrew
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 15.0.1 Build version 15A507

**Comment by SimplyDanny** [comment]
Support for commands in multiline comments has been removed since 0.53.0. You can find detailed reasons for this step in #4798 and the associated PR. In short: Parsing commands in multiline comments has never worked reliably.

**Comment by mildm8nnered** [comment]
See also #4803 for further details
