### ISSUE TITLE
Xcode plugin with "Format on Save" feature

### ISSUE THREAD

**Issue by mgrebenets** [realm/SwiftLint#538]
We've adopted SwiftLint and had a good go for a while. However, the duration of SwiftLint build phase in Xcode has linear dependency on lines of Swift code. Naturally, when our code base size grows, the time for SwiftLint step increases. After enabling autocorrection this time doubles and totals to around 15 seconds. For developers who hit `Cmd + B` regularly (which applies for 90% of devs) the 15 seconds delay becomes quite annoying.

This is obviously due to the fact that by default SwiftLint processes _all_ Swift files it can find. Even configuring `excluded` rule doesn't help much for large code bases.

Surely we can (and will) offload SwiftLint task to CI, however, we also want the early correction and detection of style violations integrated with Xcode.

I believe it would make sense to create an Xcode plugin just like [BBUncrustify Plugin](https://github.com/benoitsan/BBUncrustifyPlugin-Xcode) for `uncrustify` tool.

The plugin would let developers run SwiftLint on demand or automatically in `autocorrect` mode, just like "Format on Save" feature of uncrusity plugin.

I think it's also possible to run SwiftLint in `lint` mode and display linter warnings without the need to have  a build phase. Some other plugins seem to be able to do that.

**Comment by ypresto** [comment]
I created it! https://github.com/ypresto/SwiftLintAutoCorrect
PR to include to alcatraz: https://github.com/alcatraz/alcatraz-packages/pull/538

**Comment by jpsim** [comment]
Looks great @ypresto! Could you make a PR to document this and link to it from the README? I'll close this issue because someone's created it! :tada:

**Comment by ypresto** [comment]
Thanks, I'll send PR!
(I just fixed bug that NON-swift file is formatted.)
