### ISSUE TITLE
Run SwiftLint for changed files only

### ISSUE THREAD

**Issue by mgrebenets** [realm/SwiftLint#539]
This is somewhat related to https://github.com/realm/SwiftLint/issues/538.

For large code bases SwiftLint takes a long time and results to an annoying delay for `Cmd + B` action.

The solution would be to have an option for `swiftlint` executable, to scan git repo for modified files and run `SwiftLint` for those files only.

Sure there are VCSs other than git, but git is most popular, so would make sense to start with it.

There's a number of ways to get list of modified files, for example:

```shell
if git rev-parse --verify HEAD >/dev/null 2>&1 ; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff-index --cached --diff-filter=ACMR --name-only $against -- | \
sed -e 's/^"\(.*\)"$/\1/' | \
while read file
do
    # TODO: add this file to list of files to feed to SwiftLint...
done
```

**Comment by norio-nomura** [comment]
#413 would help you.

**Comment by mgrebenets** [comment]
Thanks, I think it answers the question, I should move this extra logic in my custom script, rather than expect this feature from swiftlint.

**Comment by jpsim** [comment]
FYI I'm considering adding a "stable git revision" CLI option to SwiftLint and I'd be curious to hear your thoughts: realm/SwiftLint#3536
