### ISSUE TITLE
`control_statement` triggers when `,` is used instead of `&&`

### ISSUE THREAD

**Issue by kohtenko** [realm/SwiftLint#5394]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`control_statement` triggers on the example below while it shouldn't. This is problematic, because it changes order of the logical operations. This rule is enabled by default **and** has autocorrect, which means some code could have been changed without developers noticing it 🚨.

```
if (a || b), (c || d) {
    print(a)
}
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint 
Linting Swift files in current working directory
Linting 'test.swift' (1/1)
/Test/test.swift:1:1: warning: Control Statement Violation: `if`, `for`, `guard`, `switch`, `while`, and `catch` statements shouldn't unnecessarily wrap their conditionals or arguments in parentheses (control_statement)
Done linting! Found 1 violation, 0 serious in 1 file.

```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? `0.54.0`
* Installation method used (Homebrew, CocoaPods, building from source, etc)? `Release binary artifact` 
* Paste your configuration file: `No custom config required`

```yml
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
`No`
* Which Xcode version are you using (check `xcodebuild -version`)? `Xcode 15.0`
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
if (a || b), (c || d) {
    print(a)
}
```

**Comment by SimplyDanny** [comment]
It's valid that this code triggers the rule in this example. Removing the parentheses doesn't imply a semantical change. 

A condition list is not the same as joining all conditions with `&&` operations as in `(a || b) && (c || d)`. Removing the parentheses here, would be an issue indeed. A condition list is, as its name implies, just a list of conditions that are evaluated in order and which must all result into `true` to make the whole condition become `true`. There is no overlap between the conditions in the list.

**Comment by kohtenko** [comment]
Thanks for pointing to the right direction. The condition list indeed behaves differently 👍

For reference, here's some playground code to validate @SimplyDanny is right. Only `&&` case changes its behaviour when parenthesis are removed.
```
let a = true
let b = true
let c = false
let d = false

if (a || b) && (c || d)  {
    print("passed &&")
}

if (a || b) , (c || d)  {
    print("passed ,")
}

if a || b && c || d  {
    print("passed && no parenthesis")
}

if a || b , c || d  {
    print("passed , no parenthesis")
}
```
