### ISSUE TITLE
Swift 5.8 support

### ISSUE THREAD

**Issue by kapitoshka438** [realm/SwiftLint#5399]
Was there any real reason why you bumped the swift-tools version to 5.9 in your latest release 0.54.0?
Xcode 15.1 still contains major bugs which prevent us from using it in our projects. That's why we are unable to use SwiftLint 0.54.0 through Swift Package Manager. 
Is it possible to downgrade swift-tools at least to 5.8?

**Comment by SimplyDanny** [comment]
Unfortunately, it's not possible to downgrade. SwiftLint meanwhile heavily relies on macros which require Swift 5.9.
