### ISSUE TITLE
redundant_discardable_let does not play well with swiftui

### ISSUE THREAD

**Issue by sisoje** [realm/SwiftLint#5406]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Can you disable this rule by default?

**Comment by SimplyDanny** [comment]
Which rules are enabled by default and which ones are disabled is highly opinionated. Changing the default later would annoy people.

That said, I recommend you just disable the rule on your end.

**Comment by sisoje** [comment]
you may be right, too late for that change that now

swiftlint annoys people by definition, they don't need another rule to annoy them :)
