### ISSUE TITLE
function_parameter_count should ignore initializers

### ISSUE THREAD

**Issue by ivanbruel** [realm/SwiftLint#544]
How would you work around models with a good amount of properties to be set on an initializer?
I agree with the number of parameters being limited, but not initializers themselves.

<img width="1316" alt="screen shot 2016-02-16 at 18 54 25" src="https://cloud.githubusercontent.com/assets/4968178/13087230/bed07cf4-d4de-11e5-8ea0-ddad6fdd35fb.png">

**Comment by jpsim** [comment]
Just `// swiftlint:disable:next function_parameter_count` on the line above the initializer?

**Comment by ivanbruel** [comment]
It's not about working around but rather trying to understand why it's a best practice when it comes to initializers.

**Comment by jpsim** [comment]
Ok, thinking about this more I would agree. This was even suggested in the initial issue tracking this rule (https://github.com/realm/SwiftLint/issues/415#issue-128552879). This should be just a matter of removing `FunctionConstructor` from the `functionKinds` used to apply the rule: https://github.com/realm/SwiftLint/blob/0.9.0/Source/SwiftLintFramework/Rules/FunctionParameterCountRule.swift#L101

**Comment by kaybutter** [comment]
I tried applying your fix to the `FunctionParameterCountRule` but I'm still seeing the warning with my project. The issue seems to be that my constructor is being recognized as `FunctionMethodInstance` instead of `FunctionConstructor`. :(

**Comment by marcelofabri** [comment]
This was fixed in https://github.com/realm/SwiftLint/pull/942
