### ISSUE TITLE
0.54 not available via brew

### ISSUE THREAD

**Issue by aiKrice** [realm/SwiftLint#5443]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

0.54 not available via brew

**Comment by SimplyDanny** [comment]
This needs to wait for version 5.10 of the Swift compiler. Currently, SwiftLint [doesn't build](https://github.com/Homebrew/homebrew-core/pull/153931) in a Homwbrew context due to sandboxing issues.

**Comment by SimplyDanny** [comment]
Duplicate of #5353.
