### ISSUE TITLE
Unable to use the `final_test_case` rule

### ISSUE THREAD

**Issue by tomassliz** [realm/SwiftLint#5455]
### New Issue Checklist
- [x] Updated SwiftLint to the latest version (updated via brew, brew currently still uses 0.53.0)
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The `final_test_case` rule should be available to use from version 0.53.0 but it isn't. I always get the warning:
> warning: 'final_test_case' is not a valid rule identifier

### Environment

* SwiftLint version: 0.53.0
* Installation method used:  Homebrew

**Comment by SimplyDanny** [comment]
`final_test_case` is only available in versions > 0.54.0. There is no release yet containing the rule.

**Comment by tomassliz** [comment]
I'm so sorry about that! You are absolutely right. Thanks for pointing it out!

**Comment by SimplyDanny** [comment]
> I'm so sorry about that! You are absolutely right. Thanks for pointing it out!

No problem at all. Keep linting! 😉
