### ISSUE TITLE
False positives for force_unwrapping in 0.9.1

### ISSUE THREAD

**Issue by brandenr** [realm/SwiftLint#547]
These three lines are getting caught as force_unwrapping, though they're not force unwrapping:

setEditing(!editing, animated: true)

navigationController.setNavigationBarHidden(!navigationController.navigationBarHidden, animated: true)

if addedToPlaylist && (!self.selectedFilters.isEmpty || self.searchBar?.text?.isEmpty == false) {

**Comment by stephanheilner** [comment]
:+1:

**Comment by norio-nomura** [comment]
I opened PR #552 for fixing the issue #546, #547.
Feedback is welcome.

**Comment by jpsim** [comment]
Fixed by @norio-nomura! :tada:

**Comment by brandenr** [comment]
Any ETA for a release of this fix?

**Comment by jpsim** [comment]
I'll cut a release shortly since we haven't done one in about a month and there have been a handful of bug fixes made since.

**Comment by brandenr** [comment]
Could you also push it to brew, please?

**Comment by jpsim** [comment]
https://github.com/Homebrew/homebrew/pull/50145

**Comment by brandenr** [comment]
Thanks!
