### ISSUE TITLE
`unused_enumerated` rule should also check closure parameters

### ISSUE THREAD

**Issue by SimplyDanny** [realm/SwiftLint#5470]
The `unused_enumerated` rule triggers when either of the two values returned by `.enumerated()` isn't used (replaced by an underscore `_`). The rule currently checks only `for` loops. It could be extended to support closure parameters as well.

The rule would only check the immediate closure after the `.enumerated()` call. Otherwise, the number of parameters and their types could have changed. 

Triggering:

```swift
list.enumerated().map { idx, _ in idx }

list.enumerated().map { _, elem in elem }

list.enumerated().forEach { print($0) }

list.enumerated().map { $1 }
```

Non-triggering:

```swift
list.enumerated().map { idx, elem in "\(idx): \(elem)" }

list.enumerated().map { $0 + $1 }

list.enumerated().something().map { _, elem in elem }
```

PS: This enhancement was motivated by [this comment](https://github.com/nicklockwood/SwiftFormat/issues/1607#issuecomment-1928863362).

**Comment by mildm8nnered** [comment]
I am playing around with some fixes for this ...
