### ISSUE TITLE
CONTRIBUTING.md Out of date and has incorrect instructions

### ISSUE THREAD

**Issue by mredig** [realm/SwiftLint#5473]
### New Issue Checklist

- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I'm not super up to date on the project, but when I updated my PR to use the latest from `main`, I got the error that `ConfigurationProviderRule`, which I had conformed my object to, wasn't found. I searched to project to see if it was a build error and the only other spot it was found was in `CONTRIBUTING.md`.

I spent a few minutes looking through the git history and saw that, apparently, all Rules are now configurable? I haven't had much time to look into it and I don't know what the expected course of action is now, but I can at least take away that `CONTRIBUTING.md` is out of date and need to be updated by someone who knows what the current expectations are. 

P.S. I've gotten my PR to build and pass tests, but I cannot say whether I'm following best practices without a little documentation.

**Comment by SimplyDanny** [comment]
All rules are now configurable. That's why `ConfigurationProviderRule` doesn't exist anymore.

Thank you for the hint. I'll check and update the guidelines.
