### ISSUE TITLE
Request for Rule Update for "opening_brace" (when used with regular expression literals)

### ISSUE THREAD

**Issue by Loradim** [realm/SwiftLint#5481]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version => "swiftlint 0.53.0 is already installed and up-to-date"
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The current version of the "opening_brace" rule does apply to regular expression literals in Swift.

Example:
`let regex2 = /:\s{0,5}px/`

will be modified to
`let regex2 = /:\s {0,5}px/`

(a Whitespace is added before the `{` brace. Does happen with other regular expressions as well)
I would expect SwiftLint to not touch regular expressions, but I assume they are not correctly detected and therefore are being updated.

### Workaround used
`// swiftlint: disable:this all`
(but it took me longer than I would like to admit to find the issue)

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
=> 0.53.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
=> `brew install swiftlint`
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers turned on by default to exclude from running
- type_body_length
- file_length
- function_parameter_count
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
=> No
* Which Xcode version are you using (check `xcodebuild -version`)?
=> Version 15.2 (15C500b)
* Do you have a sample that shows the issue?
=>
```bash
echo "let regex=/:\s{1,2}/" | swiftlint lint --no-cache --use-stdin --enable-all-rules
warning: The `inert_defer` rule is now deprecated and will be completely removed in a future release.
warning: The `anyobject_protocol` rule is now deprecated and will be completely removed in a future release.
warning: The `unused_capture_list` rule is now deprecated and will be completely removed in a future release.
<nopath>:1:12: warning: Colon Spacing Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals (colon)
<nopath>:1:17: warning: Comma Spacing Violation: There should be no space before and one after any comma (comma)
<nopath>:1:1: warning: Explicit ACL Violation: All declarations should specify Access Control Level keywords explicitly (explicit_acl)
<nopath>:1:1: warning: Explicit Top Level ACL Violation: Top-level declarations should specify Access Control Level keywords explicitly (explicit_top_level_acl)
<nopath>:1:5: warning: Explicit Type Interface Violation: Properties should have a type interface (explicit_type_interface)
<nopath>:1:15: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration (opening_brace)
<nopath>:1:5: warning: Prefixed Top-Level Constant Violation: Top-level constants should be prefixed by `k` (prefixed_toplevel_constant)
Done linting! Found 7 violations, 0 serious in 1 file.
```

Is there anything I can help to better understand or fix this issue?

Kind regards,
Loradim

**Comment by SimplyDanny** [comment]
That has already been fixed in #5164. However, there is no release yet containing the fix.
