### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by mvn-toantruong-dn** [realm/SwiftLint#5484]
Hello,
I am an employee of Monstarlab company. I have a question about the Privacy Manifest.

At WWDC23 Apple is requiring all api calls that fall under this ruleset https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394
be added to a privacy manifest file.
Does SwiftLint need to include this manifest?
Please let me know about your upcoming plans to apply the privacy manifest.

Thank you!!!

**Comment by mildm8nnered** [comment]
I don't believe this is needed, as SwiftLint is not distributed via the App Store.

**Comment by SimplyDanny** [comment]
> I don't believe this is needed, as SwiftLint is not distributed via the App Store.

I agree. Only if SwiftLint was used as part of an app (think of an editor with built-in linting), this would become a topic. But for a command line tool that only runs over the code that comprises an app, privacy manifests are not a topic.

For that reason, it's not planned to provide such a manifest. Apps bundling SwiftLint as part of themselves should request it specifically.
