### ISSUE TITLE
Failure PhaseScriptExecution Swiftlint

### ISSUE THREAD

**Issue by daljeet16** [realm/SwiftLint#5486]
I am using swiftlint version 0.54.0 and updated Xcode to 15.2 version
Facing issue while building on Jenkins machine: Here is the error:

The following build commands failed:
PhaseScriptExecution Swiftlint
/Users/administrator/.jenkins/workspace/derivedData/Build/Intermediates.noindex/ArchiveIntermediates//Script-8571282F2B96E3BA00CF1389.sh
(1 failure)

 We tried on the downgrade versions as well like 0.53.0, 0.52.4. But issue remain the same

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 
  0.54.0
* Installation method used ()?
   CocoaPods
* Paste your configuration file:
 The path in the run script 
"${PODS_ROOT}/SwiftLint/swiftlint"

* Which Xcode version are you using (check `xcodebuild -version`)?
   15.2

**Comment by SimplyDanny** [comment]
Please provide your build script.

**Comment by daljeet16** [comment]
Here is Build Script file:
[Script-8571282F2B96E3BA00CF1389.txt](https://github.com/realm/SwiftLint/files/14504649/Script-8571282F2B96E3BA00CF1389.txt)

**Comment by SimplyDanny** [comment]
You need to check what the actual error is. A generic "script failed" is not helpful.

Make sure that `PODS_ROOT` is set correctly.

**Comment by daljeet16** [comment]
PODS_ROOT is set correctly, I double checked. Same was working fine in Xcode version 14.++
Let me know If can share to anything else to fix this

**Comment by SimplyDanny** [comment]
One cannot help without a real error reported by the script.
