### ISSUE TITLE
Brew repo is not hosting the last version of swiftlint

### ISSUE THREAD

**Issue by aiKrice** [realm/SwiftLint#5495]
Hello Team, it's not really a bug but there are no template for this. Currently on Brew, the latest version is 0.53 not the .54.

**Comment by mildm8nnered** [comment]
Dupe of #5476

**Comment by SimplyDanny** [comment]
This needs to wait for version 5.10 of the Swift compiler. Currently, SwiftLint [doesn't build](https://github.com/Homebrew/homebrew-core/pull/153931) in a Homebrew context due to sandboxing issues.

There's nothing here that can be done. So I'll close this ticket.

**Comment by SimplyDanny** [comment]
Duplicate of #5353.
