### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by sakshibala-halodoc** [realm/SwiftLint#5503]
Subject: We need to incorporate the xcprivacy manifest into our app . Starting March 13, Apple will send notifications when uploading builds to the App Store, and this will become mandatory from May 1. All the SDKs used in our app needs to incorporate the xcprivacy manifest.
Reference: https://developer.apple.com/news/?id=3d8a9yyh

Actions needed: We need the compatible xcprivacy manifest version IOS SDK with xcprivacy manifest. We are expecting a seamless upgrade by upgrading to the latest version.

**Comment by SimplyDanny** [comment]
> We are expecting a seamless upgrade by upgrading to the latest version.

And we expect people to search for "Privacy Manifest" in all existing issues before they open a new one.
