### ISSUE TITLE
Rule Request: Line break in between case statements

### ISSUE THREAD

**Issue by JulesMoorhouse** [realm/SwiftLint#5512]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

To make switch statements more readable.

triggering:

```
switch dayOfWeek {
  case 1:
    print("Sunday")
  case 2:
    print("Monday")
  case 3:
    print("Tuesday")
  case 4:
    print("Wednesday")
  case 5:
    print("Thursday")
  case 6:
    print("Friday")
  case 7:
    print("Saturday")
  default:
    print("Invalid day")
}
```

not triggering:
```
switch dayOfWeek {
  case 1:
    print("Sunday")
	    
  case 2:
    print("Monday")
	    
  case 3:
    print("Tuesday")
	    
  case 4:
    print("Wednesday")
	    
  case 5:
    print("Thursday")
	    
  case 6:
    print("Friday")
	    
  case 7:
    print("Saturday")
	    
  default:
    print("Invalid day")
}
```
I've tried to write a regex to do this, but you cannot use quantifiers like *, +, or {n,m} inside a lookbehind assertion

Thanks,

Jules.

**Comment by mildm8nnered** [comment]
I think that rule already exists: https://realm.github.io/SwiftLint/vertical_whitespace_between_cases.html

**Comment by JulesMoorhouse** [comment]
Thanks

**Comment by SimplyDanny** [comment]
> I think that rule already exists: https://realm.github.io/SwiftLint/vertical_whitespace_between_cases.html

Oh, I didn't have that on my radar. 😅

**Comment by mildm8nnered** [comment]
I was just setting up SwiftLint on a new project yesterday, and had to disable that rule. :-)
