### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by kohtenko** [realm/SwiftLint#5530]
The latest release (0.54.0) was released 5 months ago. There seems to be many improvements and rules implemented since then. I'm not sure if there's a rough release schedule already, but we used to have a new version every ~3 months.

**Comment by jpsim** [comment]
The fact that Homebrew / Swift 5.9 were incompatible definitely slowed down the release process. This had to do with Swift macros not being compatible with the macOS Sandbox. This is fixed in Swift 5.10.

@SimplyDanny and I are planning next steps for a release soon.

**Comment by SimplyDanny** [comment]
0.55.0 is now available.
