### ISSUE TITLE
Carthage component seems to use .swiftlint.yml of parent project and not its own

### ISSUE THREAD

**Issue by schwa** [realm/SwiftLint#554]
I have a framework project "Framework" that is compatible with carthage and has a .swiftlint.yml file and is set up to run swiftlint as a Build Phase script. The project is "clean" according to whatever set of swiftlint options it specifies in .swiftlint.yml

I have an app "App" that uses carthage to link to "Framework". This app also has a .swiftlint.yml.

It seems when building "App"'s dependencies with Carthage the "Framework" build uses the "App"'s .swiftlint.yml and _not_ it's own.

The "App"'s configuration can be far stricter than "Framework"'s - leader to inability to compile and build the framework.

Is the right way to fix this to use the --config option? If so then the example Xcode build phase provided in the Swiftlin README should be updated.

**Comment by schwa** [comment]
I've tried using the following as my build phase script, but no luck (related to https://github.com/realm/SwiftLint/issues/550):

```
env >> ~/Desktop/ENV.txt
if which swiftlint >/dev/null; then
  swiftlint lint --config "$SOURCE_ROOT/.swiftlint.yml"
else
  echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint"
fi
```

**Comment by norio-nomura** [comment]
Which version are you using? 0.9.1 includes relating fix #536.
But we have another issue #550 about config.

**Comment by schwa** [comment]
0.9.1

**Comment by onmyway133** [comment]
@schwa Hi, is this still a problem with you?

**Comment by schwa** [comment]
@onmyway133 Don't know. No longer work on the projects where this was an issue.

**Comment by jpsim** [comment]
Thanks for the update. Considering this is almost a year old and we haven't heard other reports of this behavior, I'll be closing this.
