### ISSUE TITLE
Feature request: Add an (opt in) update check to SwiftLint

### ISSUE THREAD

**Issue by mildm8nnered** [realm/SwiftLint#5551]
Periphery has an (opt-out) update check: `--disable-update-check`

I'm not sure how happy I'd be with an opt out network access, but I think a lot of people aren't updating SwiftLint that often (which is a shame because there are a lot of great new rules, bug fixes, and general improvements in every release), and at least offering the option of an opt-in update check would help those users who enabled it to be alerted to new versions.

I've not looked into what we could check - GitHub would be easiest maybe. Probably on a fast timeout, so as not to interfere with people's builds.

**Comment by SimplyDanny** [comment]
I agree that having this check on by default might not be everybody's favorite. Yet, if one needs to explicitly opt-in with an argument when running `swiftlint` to perform the check feels the same like having no check at all. An option in the configuration might be a good middle course, though.

**Comment by mildm8nnered** [comment]
So config file option - I think these should kind of be standard for most command line options anyway - that would help with awareness.

While this would be useless at first when no-one's using it, at least it would be there, and we can build up awareness over time.
