### ISSUE TITLE
ShorthandOptionalBinding Rule not working?

### ISSUE THREAD

**Issue by tomhuettmann** [realm/SwiftLint#5557]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Currently, the `shorthand_optional_binding` seems not to work for me as expected.
None of the triggering examples are showing up for me after enabling the rule.
Rule definition: https://realm.github.io/SwiftLint/shorthand_optional_binding.html
What am I doing wrong?

I am using `0.53.0`, installed via Homebrew.

### Code
I would expect that the following triggers the rule for example:
```swift
if let i = i {}
```
forcing me to refactor it to:
```swift
if let i {}
```

**Comment by SimplyDanny** [comment]
I suspect this is an issue with the slightly broken version comparison algorithm assuming you are on Swift 5.10. Are you?

The issue has been fixed in #5526. I hope a new release can be provided in the upcoming days.

**Comment by tomhuettmann** [comment]
Yeah, I am using Swift 5.10.
Thank you very much, looking forward for the next release 🚀

**Comment by tomhuettmann** [comment]
Small Followup: Works perfectly now with the newest SwiftLint version. Thanks ❤️
