### ISSUE TITLE
Warn about unused swift features.

### ISSUE THREAD

**Issue by amichail** [realm/SwiftLint#556]
This would be a good way to learn as much as possible about Swift and its standard library.

**Comment by jpsim** [comment]
Can you please give an example?

**Comment by amichail** [comment]
For example, if you don't use "defer" anywhere in your project, you would get a warning about that.

**Comment by jpsim** [comment]
hhhmmm, why would that trigger a warning? Maybe I don't have a use for `defer` in my project...

**Comment by amichail** [comment]
The idea is to encourage you to learn more about Swift and its standard library.

If you don't want to use "defer" after looking it up, you can disable the particular warning for "defer".

**Comment by scottrhoyt** [comment]
I highly disagree with this use case for SwiftLint as I don't believe it would be a good experience for our core users.

It might be a good reason for you to fork SwiftLint or use SwiftLintFramework to create a new "learning" project though.

**Comment by jpsim** [comment]
I strongly agree with Scott on this one. Thanks for the suggestion, but ultimately this seems opposed to the way SwiftLint is used in projects today.
