### ISSUE TITLE
Latest releases (0.54.0 and 0.55.0) are not available via Homebrew

### ISSUE THREAD

**Issue by jessesquires** [realm/SwiftLint#5576]
Installing swiftlint via homebrew installs `0.53.0`. 

Both `0.54.0` and `0.55.0` are not available via homebrew.

- https://formulae.brew.sh/formula/swiftlint#default
- https://github.com/realm/SwiftLint/releases/tag/0.54.0
- https://github.com/realm/SwiftLint/releases/tag/0.55.0

**Comment by jessesquires** [comment]
Ah, it looks like this is a known issue.

Thread on Homebrew:
https://github.com/Homebrew/homebrew-core/pull/153931#issuecomment-2106369230

Perhaps we can leave this issue open here until the Swiftlint updates land in Homebrew. (In case anyone else comes here wondering what's going on.)

**Comment by SimplyDanny** [comment]
0.54.0 is blocked by some build issues, but 0.55.0 should actually be good to go. However, as this version comes with a lot of changes and people cannot go back in case of any issues with Homebrew easily, we decided to have some artificial delay between the official release and the Homebrew update.

The issues that came in already have almost all been fixed. So we can hopefully come up with a 0.55.1 release in the next days which will also be published to Homebrew. Cross your fingers that this time it builds successfully there. 😉

**Comment by jessesquires** [comment]
Thanks so much for the update @SimplyDanny! 🙌🏼  I appreciate it!

**Comment by jessesquires** [comment]
@SimplyDanny 

> Cross your fingers that this time it builds successfully there.

Would it make sense to preemptively open a PR for homebrew with 0.55.0 (with no intentions of merging) just to catch potential problems early?

**Comment by jessesquires** [comment]
For those following along, the homebrew PR is now open for 0.55.1

https://github.com/Homebrew/homebrew-core/pull/171923

**Comment by jessesquires** [comment]
ok looks like 0.55.1 is now in homebrew! 🎉
