### ISSUE TITLE
Disable Rules in XCode Run script

### ISSUE THREAD

**Issue by ankitthakur** [realm/SwiftLint#558]
I have installed SwiftLint from Homebrew and now I am trying to disable some rules and want to modify the rules in RunScript
e.g. 1:
```
if which swiftlint >/dev/null; then
  swiftlint :disable trailing_whitespace line_length: 200 
file_length:
  warning: 600
  error: 2000
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

e.g. 2
```
if which swiftlint >/dev/null; then
  swiftlint :disable trailing_whitespace
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

**Comment by scottrhoyt** [comment]
Hey @ankitthakur. Can you achieve the desired effect by having two separate `.swiftlint.yml` files and specifying them in the run script?

e.g.

```
if which swiftlint >/dev/null; then
  swiftlint lint --path path/to/project --config trailing_whitespace.swiftlint.yml
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

If this doesn't work for you, can you explain how your solution accomplishes something different?

Thanks

**Comment by jpsim** [comment]
I hope @scottrhoyt's comment answered your question. If not, please reopen this issue with more information. Thanks!
