### ISSUE TITLE
Validate implicitly unwrapped optionals

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#56]
Implicitly unwrapped optionals should not be used.

**Comment by aarondaub** [comment]
Just a heads up that I'm going to open a PR up for this on Sunday. Just in case anyone wanted to hop on it :)

**Comment by throughnothing** [comment]
+1 for this

**Comment by frederic-adda** [comment]
I don't agree, they are quite useful

**Comment by BrianDoig** [comment]
If crashing is ok in your product, then yes they are useful.  If management yells at you if you have crashes then they aren't ok...

**Comment by throughnothing** [comment]
@frederic-adda It would just be an option to turn on.  You'd be free to keep it off, of course.

**Comment by etayluz** [comment]
Seems like they are OK for certain things:
http://stackoverflow.com/questions/39664622/what-is-the-swifty-way-to-cast-a-uitableviewcell-into-its-subclass

**Comment by jpsim** [comment]
To clarify, implicitly unwrapped optionals certainly have their place, but using them superfluously is certainly a code smell that might indicate that the code should be refactored to avoid them.

If a SwiftLint rule would apply 100% of the time, it should go in the Swift compiler. A linter exists to help identify code smells, not things that are incorrect 100% of the time. That's the language's job.

**Comment by marcelofabri** [comment]
Fixed on #1362 💥
