### ISSUE TITLE
Exclude files using regular expression.

### ISSUE THREAD

**Issue by guidomb** [realm/SwiftLint#560]
It would be nice to ignore files using a regular expression. I could try to add this feature and submit a PR if someone points me in right direction.

**Comment by jpsim** [comment]
I like the idea, feel free to implement!

**Comment by masters3d** [comment]
@guidomb https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Models/Configuration.swift

**Comment by marcelofabri** [comment]
Closing this in favor of #1220.

**Comment by keith** [comment]
This has been merged in https://github.com/realm/SwiftLint/pull/2316 and is part of 0.27.0
