### ISSUE TITLE
SwiftLintCommandPlugin Unknown option '--target'

### ISSUE THREAD

**Issue by kostasniks** [realm/SwiftLint#5603]
### Describe the bug

Greetings 👋 ,
I used the new CommandPlugin but for some reason when I am running it in one of my packages it results to the following error:

![CleanShot 2024-05-24 at 14 34 59](https://github.com/realm/SwiftLint/assets/170009855/5263c137-33b6-4ebd-852d-65afddfe034e)
![CleanShot 2024-05-24 at 14 35 19](https://github.com/realm/SwiftLint/assets/170009855/0db20c08-a73c-4b54-806c-c338b973221f)
![CleanShot 2024-05-24 at 14 32 41](https://github.com/realm/SwiftLint/assets/170009855/abb4522b-dba9-4f5a-ad78-5aea9f5499b8)

My package.swift looks like this:
```swift
// MARK: Networking
        .target(
            name: "Networking",
            dependencies: [],
            plugins: [.plugin(name: "SwiftLintCommandPlugin", package: "SwiftLint")]
        ),
```

### Environment

* SwiftLint version:  0.55.1
* Installation method used: Homebrew
* Paste your configuration file: The default one.

**Comment by SimplyDanny** [comment]
The plugin itself doesn't add the `--target` option, so it must come from Xcode constructing the call. Can you provide the complete commend that Xcode runs?

**Comment by valougep** [comment]
Hello, Apple's documentation about Plugins says `This is commonly used in order to narrow down the application of a command to one or more targets, through the convention of one or more occurrences of a --target option with the name of the target(s)` [Apple's official documentation](https://github.com/swiftlang/swift-package-manager/blob/main/Documentation/Plugins.md). 
In your implementation you do not iterate over the targets like Apple does in its code example. Probably when launching the command from Xcode with a specific target this leads to an error since the --target filled by Xcode is not treated by the plugin. Can you add the `target based` behavior ?

**Comment by zkline101** [comment]
I'm using `SwiftLintPlugins` version `0.56.1` (I also tried `0.57.0`) and I am still seeing this problem when using the command plugin:
![Screenshot 2024-11-19 at 10 56 07 AM](https://github.com/user-attachments/assets/c7c9138a-53a1-49fe-bf89-9072d70e7d2c)

**Comment by zkline101** [comment]
Thanks! That helps get rid of the error. I ran the command plugin from within Xcode and didn't see any linter warnings when there should have been. But based on this doc:

> The command plugin enables running SwiftLint from the command line

It sounds like the command plugin is only supported from the command line and not from within Xcode. Is that correct?

**Comment by SimplyDanny** [comment]
> Thanks! That helps get rid of the error. I ran the command plugin from within Xcode and didn't see any linter warnings when there should have been. But based on this doc:
> 
> > The command plugin enables running SwiftLint from the command line
> 
> It sounds like the command plugin is only supported from the command line and not from within Xcode. Is that correct?

That's correct at present. You can, however, [run it in a build phase](https://github.com/realm/SwiftLint#xcode-run-script-build-phase).

**Comment by SimplyDanny** [comment]
@zkline101: In case you are interested, with #5867 SwiftLint would be available as an Xcode command plugin as well.

**Comment by zkline101** [comment]
Thank you for working on that. I tested it out and I can see the linter warnings in the plug-in command log. Is it possible to get those warnings to show up as they would if you were using the build command? Where the warnings should up as normal warnings would in Xcode.

**Comment by SimplyDanny** [comment]
> Thank you for working on that. I tested it out and I can see the linter warnings in the plug-in command log. Is it possible to get those warnings to show up as they would if you were using the build command? Where the warnings should up as normal warnings would in Xcode.

The output of both plugin variants should be exactly the same. Might be a problem with Xcode not respecting printed warnings from Xcode Commands Plugins. I don't know if that's intended. In terms of SwiftLint, it doesn't seem like we can do anything about it.
