### ISSUE TITLE
Upload Privacy Policy

### ISSUE THREAD

**Issue by sumit-vts** [realm/SwiftLint#5616]
Apple says "Starting May 1, 2024: You'll need to include approved reasons for the listed APIs used by your app's code to upload a new or updated app to App Store Connect."

Please add privacy policy otherwise we couldn't use this library.

**Comment by SimplyDanny** [comment]
If you only use SwiftLint as a command-line tool or plugin, there's no need to add a policy to an app as it doesn't **depend** on any SwiftLint components at runtime.
