### ISSUE TITLE
skipping cache due to an error: https://github.com/realm/SwiftLint: The repository could not be found. Make sure a valid repository exists at the specified location and try again.

### ISSUE THREAD

**Issue by bukira** [realm/SwiftLint#5632]
I am installing swift lint as a plugin for Xcode and I get the following error when checking out packages

skipping cache due to an error: https://github.com/realm/SwiftLint: The repository could not be found. Make sure a valid repository exists at the specified location and try again.

![Screenshot 2024-06-17 at 16 35 34](https://github.com/realm/SwiftLint/assets/226171/176e4eb6-0445-41d3-99cc-8e964086f59e)

**Comment by SimplyDanny** [comment]
Seems like the Swift cache is somehow corrupted. Try if it works again after running `swift package purge-clean` and `swift package reset`.
