### ISSUE TITLE
SwiftLint fails using Xcode 16 beta command line tools

### ISSUE THREAD

**Issue by emawby** [realm/SwiftLint#5635]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
Fatal error when running SwiftLint using Xcode 16 beta CLI tools

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
[1]    72585 trace trap  swiftlint
```

### Environment

* SwiftLint version 0.55.1
* Installation method used Homebrew

Switching to Xcode 15 tools fixed the issue

**Comment by SimplyDanny** [comment]
The Command-line Tools are not sufficient. Your need to install Xcode.
