### ISSUE TITLE
Rule comments ignore next, this and previous

### ISSUE THREAD

**Issue by eaigner** [realm/SwiftLint#564]
SwiftLint seems to ignore the `:next`, `:this` and `:previous` qualifiers of control comments like

    let s = "a,b"  //swiftlint:disable:this comma

won't work, while using a separate `swiftlint:disable comma` line before and `swiftlint:enable comma` after works.

**Comment by jpsim** [comment]
Based on this and the several other bug reports you've filed, you need to update your version of SwiftLint version to the latest (0.9.1), which has all these features.

You can tell which version of SwiftLint you're using by running `swiftlint version`.
