### ISSUE TITLE
Conflict between Swift Testing and Swift Lint

### ISSUE THREAD

**Issue by mikeshappell** [realm/SwiftLint#5642]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When attempting to add Swift Lint to a Swift package, which uses [Swift Testing (0.10.0](https://github.com/apple/swift-testing)), I encountered a conflict between the two packages. The complete message was:

`Failed to resolve dependencies Dependencies could not be resolved because root depends on 'swift-testing' 0.10.0..<1.0.0 and root depends on 'swiftlint' 0.55.1..<1.0.0.
'swiftlint' is incompatible with 'swift-testing' because 'swift-testing' 0.10.0 depends on 'swift-syntax' 600.0.0-latest..<601.0.0 and no versions of 'swift-testing' match the requirement 0.10.1..<1.0.0.
'swiftlint' >= 0.55.1 practically depends on 'swift-syntax' 510.0.2..<511.0.0 because no versions of 'swiftlint' match the requirement 0.55.2..<1.0.0 and 'swiftlint' 0.55.1 depends on 'swift-syntax' 510.0.2..<511.0.0.
`

Therefore, until there is a Swift Lint that works with Swift 6.0, it does not appear that we're able to use Swift Lint as a package plugin.

**Comment by SimplyDanny** [comment]
Please consume the plugin from [this dedicated repository](https://github.com/SimplyDanny/SwiftLintPlugins). It comes without any dependency and so doesn't cause any such issues.

**Comment by mikeshappell** [comment]
Wow! That works perfectly. Thanks for the quick response and pointer!
