### ISSUE TITLE
Feature request - `--only-rule` argument for lint and analyze, to enable just one rule (possibly allowed multiple times)

### ISSUE THREAD

**Issue by mildm8nnered** [realm/SwiftLint#5659]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the feature

Sometime it would be handy to enable just one rule.

Consider trying to autocorrect just the `implicit_return` rule. It would be nice to be able to say

`swiftlint --fix --only-rule implicit_return`

The alternative would be to temporarily hack the configuration file.

Possibly could be added multiple times to enable a few rules, or as a comma separated list.

This is kind of in the spirit of `--enable-all-rules` - the configuration file rule enablement would be ignored, and SwiftLint would behave as though the rules were specified in `only_rules` in the config file.

**Comment by mildm8nnered** [comment]
> The idea is good, but maybe there is a more general solution than the extra argument.
> 
> In case we go with the argument, would it also be allowed on the `lint` command? Why not, right?

Oh absolutely - `lint` and `analyze` - `--fix` is just the most obvious case, and the one I came across and thought - "editing .swiftlint.yml for this is really annoying".

I think the biggest question in my mind is should we allow multiple invocations of `--only-rule`, or make it a comma separated list, or just allow one invocation (probably easiest, and would satisfy a lot of use cases - you can always run it again specifying another rule, and if you want to run it regularly against a number of rules, maybe you should have a dedicated config file for that).

**Comment by mildm8nnered** [comment]
But if you have another angle I'd love to hear it

**Comment by SimplyDanny** [comment]
> But if you have another angle I'd love to hear it

No other angle. Reflecting on it, I always hacked the configuration. That's awkward. I'd like to have the argument as well. 😉 

> I think the biggest question in my mind is should we allow multiple invocations of `--only-rule`, or make it a comma separated list, or just allow one invocation (probably easiest, and would satisfy a lot of use cases - you can always run it again specifying another rule, and if you want to run it regularly against a number of rules, maybe you should have a dedicated config file for that).

Agree, one should be enough.
