### ISSUE TITLE
Accept variable names starting with more than one capital letter in Variable Name Rule

### ISSUE THREAD

**Issue by eaigner** [realm/SwiftLint#566]
Consider the following variable names

    - ID
    - URL
    - XMLString
    - APIHost
    - HTTPVersion
    - MIMEType
    - JSONBody
    - URLField
    - URLStackView

Those would be considered a violation because they start with an uppercase letter, but in those examples they are abbreviations which would be valid.

I know those can be excluded manually, but I don't think it is necessary. Those cases could be detected if the 2nd character is also upper case and contains only alphanumeric characters (thus eliminating cases such as `MY_CONST`)

I'm using swiftlint version `0.9.1`

**Comment by jpsim** [comment]
We were tracking this enhancement in a pull request that was never finished and subsequently closed, so I just renamed this issue to be a more accurate description of what should be done, and now we're tracking this enhancement here.

Anyone should feel free to implement this. It should be an easy task to get started if you've been considering contributing to SwiftLint.

**Comment by eaigner** [comment]
Implemented it and CI seems to pass.
