### ISSUE TITLE
A vertical alignment rule for tables of static data.

### ISSUE THREAD

**Issue by amichail** [realm/SwiftLint#568]
This means sometimes requiring more than one space after a comma so that data in a table is vertically aligned in each column.

**Comment by jpsim** [comment]
What?

**Comment by amichail** [comment]
Say you use a list of lists each level's data in a game and you want to format this as a table in the source code.

Not all cells in the table have the same number of characters so you add extra spaces to align things up in the table.

This means that the number of spaces after each comma may need to be something other than one.

A rule could figure out what these should be and warn you when the spacing is incorrect.

**Comment by jpsim** [comment]
This is outside the scope of SwiftLint.
