### ISSUE TITLE
A warning for missing "commit comments".

### ISSUE THREAD

**Issue by amichail** [realm/SwiftLint#569]
For more info: https://github.com/thebearjew/commit-comments

**Comment by jpsim** [comment]
Isn't that what git and git blame is for?

**Comment by amichail** [comment]
The "commit comments" tool allows you to put commit comments in your source code. Upon git commit, these comments would be removed from the source code and combined into a single commit comment.

A rule could be used to see changes that you made in the source that do not have an accompanying commit comment.

**Comment by jpsim** [comment]
This is outside the scope of SwiftLint.
