### ISSUE TITLE
Xcode 16b4 errors when compiling SwiftLint main due to internal imports

### ISSUE THREAD

**Issue by Brett-Best** [realm/SwiftLint#5700]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Hello, when I use Xcode 16b4 and try to compile SwiftLint (main) in Xcode or using Mint I get compile failures because of: https://github.com/realm/SwiftLint/blob/7904d9a4389ccfeee8df5b0093613a1f6cfeefad/Package.swift#L10
Would it be possible to either resolve these errors or remove the upcoming  feature flag?
I was a little surprised that this was causing errors because the source code is compiled using Swift 5.10 compatibility mode.
I would've thought it would only cause errors when using Swift 6 mode.

##### Complete output when running SwiftLint, including the stack trace and command used
https://gist.github.com/Brett-Best/57c8e2deac550a3186d011d08e2b4252

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? main branch
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Building from source + mint
* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 16.0
Build version 16A5211f

**Comment by SimplyDanny** [comment]
It would be possible to resolve the issues, but I'm not quite sure if these features are ready and reliably working in the Swift 6 compiler yet. So we rather keep the status quo since this will also not be enforced in Swift 6.
