### ISSUE TITLE
Better error reporting for syntax errors in .swiftlint.yml files

### ISSUE THREAD

**Issue by roddi** [realm/SwiftLint#571]
Hi,

I was editing my .swiftlint.yml file and obviously did something wrong. Unfortunately the error message is less than helpful. No line number.

`fatal error: Could not read configuration file at path '/Users/roddi/GitDev/ios-client/.swiftlint.yml': file /tmp/swiftlint20160216-9620-6vz1wh/Source/SwiftLintFramework/Models/Configuration.swift, line 153`

Note: This issue is not about what I did wrong but about the unhelpful error message. To reproduce use an excluded subdirectory but start the line with a tab instead of two spaces.

**Comment by jpsim** [comment]
Could you please file this issue on the YamlSwift repo? Thanks!

**Comment by jpsim** [comment]
Closing since there's not much we can do about this unless it's improved upstream. @roddi feel free to open an issue on https://github.com/behrang/YamlSwift.
