### ISSUE TITLE
exclude / include paths containing Spaces

### ISSUE THREAD

**Issue by roddi** [realm/SwiftLint#572]
Maybe this is just an oversight in the documentation but I did not find a way to exclude a path containing a space character.

**Comment by roddi** [comment]
You actually can use spaces in paths. Documentation should be updated accordingly

**Comment by jpsim** [comment]
I don't know what you think SwiftLint should do differently or be documented. Escaping paths for use as command line arguments or a YAML value follows those standards. Unless I'm missing something.

**Comment by jpsim** [comment]
Closing since this is just standard YAML.
