### ISSUE TITLE
Add rule prefer `() -> ` over `Void -> `

### ISSUE THREAD

**Issue by norio-nomura** [realm/SwiftLint#573]
Related to #570, we talked about another this.
In apple/swift, we can't find `Void ->`.
#570 can also be avoided by this.

**Comment by masters3d** [comment]
@eyeballz
related https://github.com/realm/SwiftLint/issues/717

**Comment by eyeballz** [comment]
how did i not see this :/
http://ericasadun.com/2015/05/11/swift-vs-void/ should be enough as "source of truth" to make a rule out of it. Don't have too much time at the moment but I will try to code this very soon.

**Comment by jpsim** [comment]
@eyeballz I see you were once interested in writing this rule. Are you still interested in contributing to SwiftLint? Do you have any questions on how to proceed? I'm happy to help 😄

**Comment by eyeballz** [comment]
Yes! I am actually waiting for the swift 3 migration https://github.com/realm/SwiftLint/pull/832 to finish.
