### ISSUE TITLE
swiftlint_linux.zip asset missing for 0.56.0 Release

### ISSUE THREAD

**Issue by dgilbert-foreflight** [realm/SwiftLint#5732]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

Previous release have all included a `swiftLint_linux.zip` asset which has SwiftLint compiled for linux machines. This is useful for running SwiftLint actions on GitHub linux runners (cheaper)

### Environment

Linux

**Comment by SimplyDanny** [comment]
Just uploaded it. There's an issue with the Homebrew release build that caused the delay.
