### ISSUE TITLE
Opening brace auto-fix removes code comments

### ISSUE THREAD

**Issue by rivera-ernesto** [realm/SwiftLint#5751]
### New Issue Checklist

- [X ] I've Updated SwiftLint to the latest version.
- [X ] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

Applying auto-fix "kills" code comments when moving the opening brace to the same line, which may not be desirable as comments could provide relevant code information and should be preserved.

Before auto-fix:

```swift
if error.localizedDescription.hasPrefix("CLFC-01449") // Another item with the same name exists
{
    // ...
 }
```

After auto-fix:

```swift
if error.localizedDescription.hasPrefix("CLFC-01449") {
    // ...
 }
```

**Comment by mildm8nnered** [comment]
Resolved by #5780
