### ISSUE TITLE
swiftlint set trailing_whitespace warning for comments

### ISSUE THREAD

**Issue by Sega-Zero** [realm/SwiftLint#576]
This rule is fine for a code, but why does it lint a comments too?
![screenshot](https://cloud.githubusercontent.com/assets/2203199/13490101/a5fe6010-e13b-11e5-89a7-0f250d4009fa.jpg)

**Comment by jpsim** [comment]
Given that documentation comments should use markdown, and that trailing whitespace has meaning, I'm inclined to agree with you that this rule should be disabled for comments.

**Comment by masters3d** [comment]
Should this be configurable? Or just make it the default to ignore comments?

**Comment by jpsim** [comment]
IMHO this should be both configurable, _AND_ default to ignore comments.
