### ISSUE TITLE
Rule customisation. 

### ISSUE THREAD

**Issue by PiotrOlszewski** [realm/SwiftLint#577]
What about adding a possibility to add new rules (can be from .swiftly.yml file) but with extended functionality? Can you add a way to input all configurations for autocorrection, nonTriggeringExamples  and  triggeringExamples ? It could  bed inserted as strings like "regex".

**Comment by scottrhoyt** [comment]
What do you envision the extended functionality over the current custom_rules being? Would it just be autocorrection?

**Comment by PiotrOlszewski** [comment]
It could be done on many ways. Regex support is great but adding fields like in RuleDescription(
        identifier: "comma",
        nonTriggeringExamples, (....) etc). could give more control to the framework users.
Another way would be to add Swift Rule files. It is just the clue to extend this great framework :)

**Comment by scottrhoyt** [comment]
The `identifier` for the rule is already determined by how you identify the custom rule in your YAML file. There is an ability to set the `name`. `triggeringExamples`, `nonTriggeringExamples`, and `corrections` are for documentation and testing purposes for built-in rules. `description` is purely for documentation. They provide less value for a custom rule, and you can achieve the same documentation effect with comments in your YAML file. Is there something I'm missing as to why you would see it useful to have explicit fields for these?

The only area of extension that makes sense to me right now is to perhaps enable autocorrect for `custom_rules`.

**Comment by yonat** [comment]
+1 for autocorrection for custom_rules.
