### ISSUE TITLE
Untranslated Content in README_CN.md

### ISSUE THREAD

**Issue by huixuhx** [realm/SwiftLint#5776]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Feature or Enhancement Proposal

Hi everyone,

I am a native Chinese speaker and recently tried to use SwiftLint by following the instructions in README_CN.md. However, I found that some important content is untranslated, which caused some difficulties for me in installation. Here are the untranslated sections I found:

- Installation using Swift Package Manager
- Installation using Xcode Package Dependency

- These untranslated contents were found on August 30, 2024.

I am willing to fix this issue and make the instructions more friendly to Chinese users.
Feel free to collaborate!

**Comment by SimplyDanny** [comment]
@huixuhx: Is this resolved with your PR being merged?
