### ISSUE TITLE
Mutable capture of 'inout' parameter 'buffer' is not allowed in concurrently-executing code

### ISSUE THREAD

**Issue by wangzhizhou** [realm/SwiftLint#5783]
![image](https://github.com/user-attachments/assets/c51e303c-e68a-41e0-ab75-aa5740a02cfc)

![image](https://github.com/user-attachments/assets/67e83ed0-4b20-4380-8dfa-b39a0bf1a8c5)

![image](https://github.com/user-attachments/assets/02eb956a-5cb7-4b1e-9367-1d8ec3fdb0b3)

**Comment by SimplyDanny** [comment]
Thanks for reporting!

At the moment, it's not planned to fix anything here. See #5754 and #5738.
