### ISSUE TITLE
Swift 6 `sending` attribute makes SwiftLint fail to parse code when using `--fix` (Fixed in main)

### ISSUE THREAD

**Issue by JaviSoto** [realm/SwiftLint#5800]
### New Issue Checklist

- [X] I've Updated SwiftLint to the latest version.
- [X] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

The following code:
```swift
// The culprit is `sending`. It parses without.
public func a(_ b: sending Int) {}
```

Produces this error:
```bash
warning: Skipping correcting file because it produced Swift parser errors: /tmp/foo.swift
{
  "diagnostics" : [
    "unexpected code 'Int' in parameter clause"
  ]
}
```

This one-liner repro's the issue:
```bash
echo 'public func a(_ b: sending Int) {}' > /tmp/foo.swift && swiftlint lint --fix /tmp/foo.swift
```

### Environment

* SwiftLint version: `0.57.0`
* Xcode version: `Xcode 16.0 Build version 16A242`
* Installation method used: `Homebrew`
* Configuration file: None

### Details

This issue doesn't repro if I build SwiftLint from `main`, I suspect thanks to https://github.com/realm/SwiftLint/pull/5795. But I wanted to file this for 2 reasons:
- So others running into this issue can find this (see work-around below).
- To ask if we can get a new release made. Thank you!

### Workaround

If you're running into this, you can surround the function that uses `sending` with `// swiftlint:disable all` until this is fixed. Example:

```swift
// swiftlint:disable all
public func a(_ b: sending Int) {}
// swiftlint:enable all
```

**Comment by SimplyDanny** [comment]
Fixed in main by the update to the SwiftSyntax 600.0.0 release.
