### ISSUE TITLE
Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed

### ISSUE THREAD

**Issue by jvanderwee** [realm/SwiftLint#5808]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

We're getting the following when updating to Xcode 16 on GitHub Actions:

```
The following build commands failed:
	Apply build tool plug-in “SwiftLintBuildToolPlugin” to target “x Dev” in project “y”
```
```
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
```

### Environment

* SwiftLint version: 0.57.0
* Xcode version: 16.0
* Xcode Command Line Tools version: 16.0.0.0.1.1724870825
* Installation method: https://github.com/SimplyDanny/SwiftLintPlugins

**Comment by eonist** [comment]
Same here

**Comment by dabrahams** [comment]
Having the same issue with Jazzy.

**Comment by eonist** [comment]
Resolved when upgrading to latest macOS

**Comment by ognerub** [comment]
I had this problem when used xcodes in terminal. My version of Xcode 16.1 was marked as "installed". Then I opened AppStore and downloaded Xcode app from there. And after this problem solved. And xcodes it terminal now shows "installed, selected". Maybe it is not necessary to download app from AppStore and only type command it terminal (xcodes select) but in mine case only new app download helped.
P.S. after install Xcode from AppStore, xcodes in terminal showed something like this:
xcodes installed
16.1 (16B40) (Selected) /Applications/Xcode.app
16.1 (16B40)            /Applications/Xcode-16.1.0.app

So it seems was an issue in Xcodes duplicates. And command in terminal "xcodes uninstall 16.1.0" erased unnecessary one.
After this i`ve got this list
xcodes installed
16.1 (16B40) (Selected) /Applications/Xcode.app

And now everything works fine
