### ISSUE TITLE
How to lint only changed files?

### ISSUE THREAD

**Issue by xlc** [realm/SwiftLint#5834]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Feature or Enhancement Proposal

How to lint only changed files? I am currently using swiftlint in my git precommit hook but it is taking too long and become unbearable.

I am currently doing `swiftlint lint --fix --quiet`

`swiftlint lint --fix --quiet  13.52s user 16.09s system 188% cpu 15.676 total`

Is it possible to make it only lint changed files? There is no point to lint unchanged packages.

Otherwise is there something I can do to make it faster?

Also the CPU usage is only 188% so there must be rooms for improvement. Especially I am working on a mono repo that contains multiple packages and there is no reason why swiftlint can't lint them concurrently.

**Comment by SimplyDanny** [comment]
You can build your own Git hook containing something like

```bash
swiftlint lint $(git diff --cached --name-only --diff-filter=ACM -z)
```

or you use tooling like `pre-commit` as suggested in [the README](https://github.com/realm/SwiftLint?tab=readme-ov-file#git-pre-commit-hook).

**Comment by xlc** [comment]
Actually, my real issue is lint a single file took 5s

`5.31s user 15.77s system 226% cpu 9.302 total`

I don't think it was that slow before? Any idea what may cause that?

**Comment by SimplyDanny** [comment]
Can you share the file?

How did you get the SwiftLint binary? Homebrew, download from SwiftLint's release page, built it yourself, ...?

**Comment by xlc** [comment]
Homebrew. Will try to reproduce this on a new repo tomorrow and share result

**Comment by xlc** [comment]
After some experiments, I think it could have something to do with my vendor git submodules (e.g. openssl), which are big and I didn't put them on excluded filter because they are not Swift project
When I am linting a single file, it shouldn't try to traverse the directory?
Another question, does swiftlint respect to .gitignore file? if yes, do I need to do anything to enable it? otherwise it will be a useful feature

**Comment by SimplyDanny** [comment]
It doesn't respect `.gitignore` files, but as I mentioned before:

> Make sure to use `included` and `excluded` filters in your `.swiftlint.yml` configuration.

However, sometimes these filters make file processing slow. Would be interesting to know if you use them.

**Comment by xlc** [comment]
```
excluded:
    - "**/.build"
```

is my current filter. this is a mono repo that I have multiple packages so it will be a repetitive to list all of them in the yml config file.

**Comment by SimplyDanny** [comment]
The wildcard `**` makes the path matching pathologically slow, especially in a huge repository. This could be the reason. But actually, single paths passed via command line shouldn't be checked against the exclude patterns.

**Comment by xlc** [comment]
Yeah did some test to lint a single file

- `**/.build`: 7.953s
- `**/.build`: 2.249s
- no excluded: 0.259s

not exactly sure why that can be a troublemaker because I never had such issue with other tools. surely some optimization could be done.

but just ignore it when paths are explicitly passed will address my main use case

Do you want me to rewrite this issue or make a new one given my original question is answered

**Comment by SimplyDanny** [comment]
> Do you want me to rewrite this issue or make a new one given my original question is answered

If the issue is only performance, there's https://github.com/realm/SwiftLint/pull/5157 trying to address that.

Anything else you see as a problem?
