### ISSUE TITLE
SwiftLint above 0.56.0 isn't compilable with Xcode 16

### ISSUE THREAD

**Issue by AF-cgi** [realm/SwiftLint#5853]
### Bug Description

I use [mint](https://github.com/yonaskolb/Mint) to install SwiftLint. The version 0.55.1 works fine and it's possible to install this version with Xcode 16 command line tool. But version 0.56.0 and above it's not possible to install SwiftLint anymore. I get the following error: **Failed to resolve SwiftLint 0.57.0 with SPM**.

**Comment by SimplyDanny** [comment]
Please provide a more detailed error. "Failed to resolve SwiftLint 0.57.0 with SPM" could mean a lot.

**Comment by AF-cgi** [comment]
I get the following issue:
```
Computing version for https://github.com/krzyzanowskim/CryptoSwift.git
error: Couldn’t get the list of tags:
    fatal: cannot use bare repository '/private/var/folders/x4/pm13mqns0kl1wr_1z5m5zcw40000gn/T/mint/github.com_realm_SwiftLint/.build/repositories/CryptoSwift-02302490' (safe.bareRepository is 'explicit')
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
```
I'm not sure, if CryptoSwift is the main issue. When I execute the open PR #5852 I get the following issue:
```
Computing version for https://github.com/apple/swift-crypto.git
error: Couldn’t get the list of tags:
    fatal: cannot use bare repository '/private/var/folders/x4/pm13mqns0kl1wr_1z5m5zcw40000gn/T/mint/github.com_kabiroberai_SwiftLint/.build/repositories/swift-crypto-7e0614ea' (safe.bareRepository is 'explicit')
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
```

**Comment by SimplyDanny** [comment]
This rather looks like a Mint issue. Did you try cleaning the temporary directory and start over with the installation?

**Comment by irangareddy** [comment]
Hi. I also face same issue.

swiftlint
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
[1]    3908 trace trap  swiftlint

**Comment by SimplyDanny** [comment]
> Hi. I also face same issue.
> 
> swiftlint SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed [1] 3908 trace trap swiftlint

There are a few issues addressing this problem. Please search for `sourcekitdInProc` in all issues. I bet you will find a solution.

**Comment by AF-cgi** [comment]
Hi, I figured out the related issue. This issue is based on an issue with the settings of the gloabel `.gitconfig` (see [here](https://forums.swift.org/t/fatal-cannot-use-bare-repository/75588)).
