### ISSUE TITLE
Override configuration or reporter from the command line

### ISSUE THREAD

**Issue by vittoriom** [realm/SwiftLint#586]
Hi, I'm just integrating `swiftlint` in our project and I created a custom `.swiftlint.yml` configuration file. I used `reporter: "xcode"` so that it nicely integrates into Xcode during the development phase.

I would now be interested in overriding the reporter to "checkstyle" to integrate violations information into Jenkins for example. It doesn't look like this is possible at the moment, or am I missing some parameter I can pass from the command line?

Thanks!

**Comment by jpsim** [comment]
This was done in #495.
