### ISSUE TITLE
Question: How to build SwiftLint in Xcode, which Xcode version is needed?

### ISSUE THREAD

**Issue by pan-macpractice** [realm/SwiftLint#587]
Kind of a stupid question.

I downloaded the SwiftLint source code and tried to build it in Xcode 7-2. The build failed.
import SourceKittenFramework   ERROR: no such module "SourceKittenFramework"

Seems build through Xcode, it will not load the Package.swift file, to find the current project's dependency "SourceKittenFramework"

Shall I download the SourceKittenFramework.pkg and install it first?

**Comment by jpsim** [comment]
Please read the README: https://github.com/realm/SwiftLint#installation

> You can also build from source by cloning this project and running `git submodule update --init --recursive; make install` (Xcode 7.1).

**Comment by pan-macpractice** [comment]
Yes. I can build the source code with command: make. or build and install together with: make install. And all these are done in terminal with command and they work.

My question is, can I open the project source code in Xcode tool with user interface, and build it there (just click the build icon)?

Thanks

**Comment by pan-macpractice** [comment]
Hi JP Simard,

Thank you for your response.

Yes. I can build the source code with command: make. Or build and install SwiftLint together with: make install. And all these are done in terminal with commands and they work.

My question is, can I open the project source code in Xcode tool with user interface, and build it there (just click the build icon)?

Thanks

**Comment by jpsim** [comment]
Yes, after you initialize and update the git submodules (`git submodule update --init --recursive`), you can use the Xcode workspace to build, run, test, archive, profile, etc. SwiftLint and SwiftLintFramework.

**Comment by pan-macpractice** [comment]
Got it! It works now. Thank you!

**Comment by JohnBing** [comment]
I had the same problem, but I couldn't solve it
I git clone the current master，then I initialize and update the git submodules (git submodule update --init --recursive)，I tried to build it in Xcode 11.5. The build failed again.
import SourceKittenFramework ERROR: no such module "SourceKittenFramework"
Looking forward to your help
