### ISSUE TITLE
always_keep_imports does not keep Foundation

### ISSUE THREAD

**Issue by apps4everyone** [realm/SwiftLint#5880]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

The following rule does not keep `Foundation` imports.

```bash
opt_in_rules:
  - unused_import:
    require_explicit_imports: true
    always_keep_imports: 
      - Foundation
```

Command:

```bash
$ swiftlint lint analyze --autocorrect
```

### Environment

* SwiftLint version 0.57.0
* Xcode version Xcode 16.1

**Comment by apps4everyone** [comment]
thx, will try

**Comment by apps4everyone** [comment]
is it possible to exclude specific canImport's like
```swift
#if canImport(SwiftUI)
import SwiftUI
#end
```

**Comment by apps4everyone** [comment]
so the whole block will be kept

**Comment by apps4everyone** [comment]
like this approach:
```
always_keep_ can_import _imports:
    - SwiftUI
```

**Comment by SimplyDanny** [comment]
Why is `always_keep_imports: [SwiftUI]` not enough in this case?

**Comment by apps4everyone** [comment]
want to keep it only strict in canImport's because there the lint check does not know runtime, so I want to avoid only changed there

**Comment by SimplyDanny** [comment]
That's currently not possible and would be a new feature.

**Comment by apps4everyone** [comment]
thx, would be nice but only if others also see the benefit in this

**Comment by SimplyDanny** [comment]
This sounds like a reasonable feature to me. It should be extended to all imports surrounded by compiler directives. E.g., in

```swift
#if os(Linux)
import Musl
#else
import Darwin
#endif
```

we most likely don't want to remove any of the imports only by running on a specific platform.
