### ISSUE TITLE
Bazel swiftLint error on execute from new version of swift_rules

### ISSUE THREAD

**Issue by lucasromanomr** [realm/SwiftLint#5892]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

I have a project that is running the latest version of rules_swift, but when I add Swiftlint rules I get an error, because the swift_c_module rule no longer exists.

```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_c_module")
Error: file '@build_bazel_rules_swift//swift:swift.bzl' does not contain symbol 'swift_c_module'
```
### Environment

* SwiftLint version (run `swiftlint version` to be sure)
* Xcode version (run `xcodebuild -version` to be sure)
* Installation method used (Homebrew, CocoaPods, building from source, etc)
* Configuration file:

```yml
# insert yaml contents here
```

Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? If so, paste their
relative paths and respective contents.

**Comment by SimplyDanny** [comment]
This has already been addressed. Please try with version 0.57.1. If the issue still remains, please report it in the projects consumed as dependencies. SwiftLint is not using that symbol directly.
