### ISSUE TITLE
Make Line Length rule configurable

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#598]
To allow ignoring comment-only lines. As requested in #597.

**Comment by gsabran** [comment]
Any update on this? That'd be very helpful, especially since default files have long comments that break the rule

**Comment by jpsim** [comment]
@gsabran to my knowledge, no one's started on this. This is a great starter task, would you be interested in giving it a shot?

**Comment by mlwelles** [comment]
I took a pass fixing this and #975, and just submitted a pull request: https://github.com/realm/SwiftLint/pull/1264

**Comment by marcelofabri** [comment]
Fixed by @mlwelles in #1264! 🎉
