### ISSUE TITLE
Add 'for (_, foo) in bar.enumerate()' rule

### ISSUE THREAD

**Issue by ceeK** [realm/SwiftLint#619]
This would be useful as I see this in code reviews every now and again. 

People no longer need to use the index returned from enumerate, and xcode tells them to ignore "_" the variable. 

Instead, enumerate should be removed. 

Not sure if I should file a radar for this to be added directly to xcode, so opening it here first for discussion.

**Comment by jpsim** [comment]
I could see a rule like this added. Although it's not quite as general as this ticket implies, since that's only relevant for certain `SequenceType`s, but certainly the most common ones like `Array` and `Set`.
