### ISSUE TITLE
Custom rule with regex back reference

### ISSUE THREAD

**Issue by koenpunt** [realm/SwiftLint#629]
It would be nice to have support for backreferencing captures, to detect things like repetition.

For example, masking variables by unwrapping:

```
regex: "let (\w+) = $1
```

But backreferences currently do not work. Or is the syntax different than `$1`? I also tried `\\1` without any luck.

**Comment by norio-nomura** [comment]
Could you please try using `\1`?
```yaml
    regex: "let (\w+) = \1"
```

**Comment by koenpunt** [comment]
That was fast, works like a charm, thanks!
