### ISSUE TITLE
Ability to specify supported declaration type for Rule

### ISSUE THREAD

**Issue by dimazen** [realm/SwiftLint#632]
Hello! 
I'm looking for a way to disable and/or adapt rule for specific declaration kind. For example to remove line limit for comments or to specify another line limit for comments only. Another useful example (the one i'm very interested in) is to allow to declare global constants from the uppercase letter.Currently the only way to do so is to exclude concrete name from the rule completely, which looks like a workaround. 
Idea is to exclude global constants from the `variable_name` rule or to configure it for specific decl type:

To do so i found, that `NameConfiguration` can be extended a bit: 

```
public mutating func applyConfiguration(configuration: AnyObject) throws {
    guard let configurationDict = configuration as? [String: AnyObject] else {
        throw ConfigurationError.UnknownConfiguration
    }

    // .... existing configuration

    if let excludedKinds = [String].arrayOf(configurationDict["excluded_kinds"]) {
        self.excludedKinds = Set(excludedKinds)
    }
}
```

And later add proper handling to the `VariableNameRule`. 

However, this also leads to the need for new rule `ConstantNameRule` which will do exactly the same, as `VariableNameRule` but with uppercase, which looks odd. 
Solution is to enable ability to use the same rule with different configurations which distinguished by different "scopes" (declaration kinds). 

Please, let me know your opinion about this. Thanks in advance!

**Comment by marcelofabri** [comment]
I think in practice would be really hard to make it work with every rule, so IMO this should be done in specific rules via custom configurations.

**Comment by marcelofabri** [comment]
I'm closing this for now. @dimazen, if you come up with use cases that would benefit from this, feel free to open new issues about those. Thanks!
