### ISSUE TITLE
Make line length rule opt in

### ISSUE THREAD

**Issue by crmitchelmore** [realm/SwiftLint#634]
Encouraging hard wraps is additional work for, at best, marginal gains and might be a habit worth evaluating.

A more thorough insight can be read here http://www.cocoawithlove.com/blog/2016/04/01/neither-tabs-nor-spaces.html#non-indent-formatting

**Comment by masters3d** [comment]
I also turned this off on my project and there is a very high percentage of projects that turn off line length.

https://github.com/search?q=disabled_rules%3A+%23+rule+identifiers+to+exclude+from+running&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by marcelofabri** [comment]
Closing this for now since we've increased the default value.
