### ISSUE TITLE
wrong operator_whitespace rule

### ISSUE THREAD

**Issue by mcplectrum** [realm/SwiftLint#641]
Hi,

the operator_whitespace rule cannot cope with overriding "=="-operator yet and shows the warning: Operator Function Whitespace Violation: Operators should be surrounded by a single whitespace when defining them. (operator_whitespace)

example:

public func ==(lhs: Item, rhs: Item) -> Bool {
...
}

**Comment by keith** [comment]
The error here is telling you that you need a space before the (

**Comment by mcplectrum** [comment]
You are right 👍 First thought it should be written like normal functions i.e. func foo(){..}. Overriding these operators is an exception and Apple uses the same convention: "func == (left: Vector2D, right: Vector2D) -> Bool {" source: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AdvancedOperators.html
