### ISSUE TITLE
bug: legacy_cggeometry_functions autocorrect generates extraneous argument label

### ISSUE THREAD

**Issue by BluMist** [realm/SwiftLint#643]
`CGRectContainsRect(area, point)` 
gets autocorrected to:
`area.contains(point: point)
`
the `point:` is extraneous

**Comment by AviSergey** [comment]
Hello. Is there any progress here?
I has the same issue. Swiftlint version is 0.10.0. For example:
`CGRectContainsPoint(frame, point)`
gets autocorrected to:
`frame.contains(point: point)`
where Extraneous argument label 'point:' in call
