### ISSUE TITLE
Support linting cuddled else

### ISSUE THREAD

**Issue by ateliercw** [realm/SwiftLint#651]
As an alternative to the standard StatementPosition Rule, I'd like to see support for uncuddled else statements, either as a configuration option for statement position, or as a separate mutually exclusive rule.

**Comment by jpsim** [comment]
yup, I'd envision this working as a configuration option on the statement position rule.

**Comment by ateliercw** [comment]
@jpsim I folded the listing for uncuddled else into statement position on my branch, but I closed the PR until I get autocorrect implemented for the alternate style, if you have any comments on the parameter name or implementation let me know

https://github.com/ateliercw/SwiftLint/blob/ms-cuddled-else-rule/Source/SwiftLintFramework/Rules/StatementPositionRule.swift

**Comment by jpsim** [comment]
That looks good to me! Not 100% sure about the wording, but can't think of anything better either.

I could imagine autocorrect for the uncuddled case being difficult to get right with indentation, so I'd accept if autocorrect just skipped that rule if the uncuddled mode was specified.

**Comment by ateliercw** [comment]
@jpsim I changed the options to use snake case to match the rest of the options, and have an autocorrect option that's passing tests
