### ISSUE TITLE
Add support for lowerCamelCase enum cases

### ISSUE THREAD

**Issue by bmunge** [realm/SwiftLint#654]
The accepted Swift evolution guideline for Swift 3.0 standardizes lowerCamelCase enum values.
[Source](https://github.com/apple/swift-evolution/blob/master/proposals/0006-apply-api-guidelines-to-the-standard-library.md)

Unless I'm missing something, the current type_name rule does not allow a way to ignore the uppercase requirement for enum cases. I think support needs to be added to the type_name rule to exclude enum cases from the capitalization requirement, or from the rule entirely.

**Comment by jpsim** [comment]
as of #660, we allow lowercase names for enum cases.
