### ISSUE TITLE
Exclude enum cases from type_name rule

### ISSUE THREAD

**Issue by phelgo** [realm/SwiftLint#655]
The `type_name` rule is currently being applied to enum cases. While the capital and alphanumerical requirements apply perfectly to enum cases, the minimum length may not. Examples like `Direction.Up`, `Sixe.XL`, `Cardinal.SW` should be allowed, and it feels cumbersome to add all these exceptions to the `.swiflint.yml`

**Comment by chadmoone** [comment]
I'm not sure about this.  Potentially some default exceptions should be added for common two-letter words (`up`, `in`, `id` etc).  But your other examples are acronyms/abbreviations, which most styleguides discourage to begin with.   Personally, I don't see why enum cases should be treated differently than anything else in this regard.  If your application really needs to have several two-letter enum types, you can always customize the rule to change the minimum allowed to 2.

**Comment by jpsim** [comment]
as of #660, we allow lowercase names for enum cases.
