### ISSUE TITLE
Ignore XCTestCase subclasses in missing_doc rule

### ISSUE THREAD

**Issue by chadmoone** [realm/SwiftLint#659]
We would like to include our tests in our linted files to enforce the same standards that we enforce elsewhere, but I'm not sure that it's valid to require documentation for all tests and test helpers.  It seems like subclasses of `XCTestCase` or possibly classes within a folder name with the `Tests` suffix should be ignored.

If you disagree with the above as a default, would it be possible to make this option configurable?

**Comment by scottrhoyt** [comment]
One option you have here is to use a nested configuration. If your test classes reside in a different directory, you can put a separate swiftlint.yml in the root of that directory to override your main configuration's settings. Let us know if that works for you!

**Comment by chadmoone** [comment]
Thanks @scottrhoyt!  I somehow missed that feature altogether.  I think that's probably a better solution for the case outlined above and works perfectly.

**Comment by scottrhoyt** [comment]
No problem! It was exactly this use case that inspired that feature, so I’m glad it works for you.
