### ISSUE TITLE
Validate comment length

### ISSUE THREAD

**Issue by segiddins** [realm/SwiftLint#67]

**Comment by jpsim** [comment]
What do you mean by this? The line length rule applies to all lines, including comments.

**Comment by segiddins** [comment]
But comments can span multiple lines, and probably shouldn't be too long

**Comment by aarondaub** [comment]
Comments on the public interface can conceivably be quite long

**Comment by jpsim** [comment]
I'm afraid I don't think it would be appropriate to enforce such a rule. If we ever end up supporting rules that are disabled by default, then I'd consider a PR implementing this, but otherwise no.
