### ISSUE TITLE
Discourage calling `init()` directly

### ISSUE THREAD

**Issue by joshfriend** [realm/SwiftLint#672]
The apple language docs always use `Foo()` style over `Foo.init()`. While both do the same thing, using `.init()` seems superfluous. 

A check for this rule could find instances of the text `.init` and verify that it is not preceded by either `self`, or `super`.

**Comment by mbrandonw** [comment]
You would also want to allow things like `optionalString.flatMap(NSURL.init(string:))`.

**Comment by joshfriend** [comment]
Hmm, yes that would make this more tricky...

**Comment by norio-nomura** [comment]
implemented on #715 and #826
