### ISSUE TITLE
Don't warn on force casts in situations like cellForRowAtIndexPath

### ISSUE THREAD

**Issue by rajohns08** [realm/SwiftLint#69]
See the style guide's response:

https://github.com/github/swift-style-guide/issues/38

**Comment by jpsim** [comment]
Indeed, there are times when force-casting is appropriate. You could say the same about all the other rules in SwiftLint and the appropriate solution there I think is to allow disabling a rule for a given region (#4). So I'll be closing this issue as I believe it to be already covered by #4.
