### ISSUE TITLE
Add config profiles/samples

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#699]
Much like clang-format has profiles for LLVM, WebKit and others, we could package `.swiftlint.yml` files used by organizations with common configurations spanning different styles.

**Comment by scottrhoyt** [comment]
Love this idea. We could start a separate repo (e.g. SwiftLint-Configs) to manage this. We could even integrate this into a command line verb for easy initialization of an example config (e.g. 'swiftlint config realm'). In addition to being a nice feature, it could help incentivize organizations to keep their standard config up to date.

**Comment by jpsim** [comment]
agreed on all points other than this being in a separate repo. Keeping it in here would be preferable I think.

**Comment by jpsim** [comment]
Closing as a duplicate of #517
