### ISSUE TITLE
Question Name Format Violation (High Severity)

### ISSUE THREAD

**Issue by crossle** [realm/SwiftLint#71]
let URL = "https://xx.xx.com"

Name Format Violation (High Severity): Variable name should only contain alphanumeric characters: 

why

**Comment by jpsim** [comment]
Because to help disambiguate between types and variables, it's recommended that variables start with a lowercase letter, and types start with an uppercase letter. There will be times when it's appropriate to go against this convention, which is why we're working on #4.
