### ISSUE TITLE
rule: empty_count miss diagnosed 

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#719]
When using count as variable, empty_count thinks I am checking a collection.
![image](https://cloud.githubusercontent.com/assets/6539412/16716068/664593c8-46a6-11e6-84e0-c141f3b3da3a.png)

**Comment by masters3d** [comment]
this seems to be related: https://github.com/realm/SwiftLint/pull/635

**Comment by masters3d** [comment]
known issue I guess, closing::
https://github.com/realm/SwiftLint/issues/505
https://github.com/realm/SwiftLint/blob/master/.swiftlint.yml

**Comment by masture** [comment]
I am seeing same issue.. I have a function which accepts count as Int? input and when I check its presence and count not being zero, it recommends to use isEmpty
My code is:
```
If let count = count, count != 0 {
    print("Do something with \(count)"
}

```
