### ISSUE TITLE
force_unwrapping: False positive inside of strings when used as opt_in_rules

### ISSUE THREAD

**Issue by cmittendorf** [realm/SwiftLint#721]
When using `for_unwrapping` as `opt_in_rules` in `.swiftlint.yml`

    opt_in_rules:
      - force_unwrapping

 the following line

    print("\(xVar)!")

results in a false positive violation:

    Loading configuration from '.swiftlint.yml'
    Linting Swift files in current working directory
    Linting 'test.swift' (1/1)
    …/test.swift:3:15: warning: Force Unwrapping Violation: Force unwrapping should be avoided. (force_unwrapping)
    Done linting! Found 1 violation, 0 serious in 1 file.

swiftlint version is 0.11.1

**Comment by jpsim** [comment]
Yes, that would happen! This is a bug and should be relatively easy to fix.
