### ISSUE TITLE
Building SwiftLint CLI as a standalone/portable file ? 

### ISSUE THREAD

**Issue by freak4pc** [realm/SwiftLint#731]
Hey guys,
I'm trying to build an integration for CodeClimate that uses SwiftLint. 

Their developer platform only allows using Docker and Docker can't run Xcode or OSX so I can't build SwiftLint on the machine. 

Would it be possible somehow to "pack" SwiftLint CLI in a standalone format that could be part of a DockerImage ? 

Thanks :)
Shai.

**Comment by freak4pc** [comment]
Just noticed the `Makefile` has a portable_zip target. Gonna try that first. 

_doh_

**Comment by jpsim** [comment]
As you mentioned, Docker doesn't support OS X guests, so this would require supporting Linux first. I just created an issue for that (#732). I'll close this one since it's quite a ways away.

**Comment by freak4pc** [comment]
Would the portable_zip approach be helpful or it won't run properly on a non-OS X environment?

**Comment by jpsim** [comment]
SwiftLint relies on SourceKit, which at the moment isn't included in Linux releases of Swift, so that first needs to be done. So just building the source for SwiftLint isn't enough to make it run on Linux.

**Comment by freak4pc** [comment]
Yeah that was my initial instinct but wanted to make sure. 
Thanks a lot !

**Comment by vovimayhem** [comment]
There's actually an [official Swift image](https://hub.docker.com/_/swift/) Wouldn't that help?

**Comment by jpsim** [comment]
@vovimayhem the official Swift releases for Linux don't include SourceKit, but https://github.com/apple/swift/pull/8189 will address that.

**Comment by caiofbpa** [comment]
@freak4pc SwiftLint seems to fully support Linux now, any news on the Codeclimate Plugin/Engine?

**Comment by freak4pc** [comment]
@caiofbpa I have actually dropped this since and just have a Danger phase. Don't think I'll be pursuant his anytime soon :)
