### ISSUE TITLE
Version 0.1.0 not upgrading to 0.1.1 in brew

### ISSUE THREAD

**Issue by rajohns08** [realm/SwiftLint#74]
When I run
`brew upgrade swiftlint`

I get the following output:
`swiftlint 0.1.0 already installed`

but hasn't 0.1.1 been release for a few days now?

**Comment by jpsim** [comment]
What if you run brew update before that?

**Comment by rajohns08** [comment]
Yep, I'm an idiot. Sorry, new to brew.

**Comment by rajohns08** [comment]
On a side note, swiftlint is now failing my build. Was this intentional?

**Comment by jpsim** [comment]
SwiftLint will emit errors for violations of medium severity or higher. If you have some in your code, then yes that's intentional. You could make a separate target just for SwiftLint if you don't want it to prevent another target from building.
