### ISSUE TITLE
Ignore #colorLiteral for line length

### ISSUE THREAD

**Issue by Juice805** [realm/SwiftLint#742]
In Xcode 8 there is the ability to directly input a color from a swatch picker in the editor. In Xcode it simply shows a colored square, however the actual code is: 
`#colorLiteral(red: 0.2431372549, green: 0.6431372549, blue: 0.6823529412, alpha: 1)` 

this often trips the line_length rule. Is there a way to configure SwiftLint to ignore specifically this bit without individually marking each occurrence? I would also like to suggest this rule to be a default.

**Comment by freak4pc** [comment]
One thought would be to "remove" `#colorLiteral(.*?)` from every `Line` in `LineLengthRule.validateFile(_:)`. 

https://github.com/realm/SwiftLint/blob/ecbba04f270a5b57690df34c10017c633363cc36/Source/SwiftLintFramework/Rules/LineLengthRule.swift#L28

**Comment by marcelofabri** [comment]
Now that #830 was merged, I think this can be closed

**Comment by norio-nomura** [comment]
Thanks.
