### ISSUE TITLE
Adapt the rules command to include custom rules

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#745]
"We should also adapt the rules command to include custom rules in the table and allow swiftlint rules my_custom_rule to work." #515

**Comment by jpsim** [comment]
Great idea! Are you interested in working on this @masters3d?

**Comment by jhildensperger** [comment]
Has there been any development here?

**Comment by marcelofabri** [comment]
@jhildensperger no, but PRs are welcome!

**Comment by jhildensperger** [comment]
Great I might take a swing at it.

Also, it seems that there is another related bug for custom rules in general. When running the `rules` command custom rules always appears as "enabled in your config" even if there are no custom rules in the yaml. If I do find some time to contribute I think I'll go for fixing this first and I'll start with a proper bug report.
