### ISSUE TITLE
Support for Continuous Integration

### ISSUE THREAD

**Issue by merktassel** [realm/SwiftLint#750]
Are there any plans to support continuous integration systems such as Travis CI? Coming from a Javascript background I'm used running linters as command line utilities that you can simply push to a CI server as part of your testing process. However, I'm not sure how something like this would work out given the dependency on Xcode.

**Comment by freak4pc** [comment]
There is an ongoing ticket to allow SwiftLint to compile under Linux. When that's done these sort of integrations will probably be feasible probably.

https://github.com/jpsim/SourceKitten/pull/223

**Comment by merktassel** [comment]
Gotcha, thanks for the clarification!

**Comment by jpsim** [comment]
SwiftLint is already a command line tool and used on CI systems. In fact, Travis _ships_ SwiftLint with its OS X images! See https://twitter.com/travisci/status/752709056691785728
