### ISSUE TITLE
Rule for invalid @IBInspectable

### ISSUE THREAD

**Issue by ikonst** [realm/SwiftLint#756]
I've been thinking of adding a rule flagging invalid uses of `@IBInspectable` such as:
- variables with unsupported types (only a [handful of types](http://stackoverflow.com/q/28749598/130066) are supported by IB)
- variables with inferred types (unsupported by IB)

Do we want to add add rules that detect likely bugs rather than just stylistic issues? The contributing guide does not answer this question.

**Comment by jpsim** [comment]
> Do we want to add add rules that detect likely bugs rather than just stylistic issues?

Sure! We already do this for one or two rules. Feel free to clarify that in the contributing guide.
