### ISSUE TITLE
Best practice for ordering build phases?

### ISSUE THREAD

**Issue by AndrewSB** [realm/SwiftLint#763]
What is the *right* order for my build phases? Where should swiftlint be?

<img width="701" alt="screen shot 2016-08-18 at 3 31 16 pm" src="https://cloud.githubusercontent.com/assets/3814772/17833367/07bd207e-66d0-11e6-82fe-1aea292307f9.png">

I have it right after `Compile Sources` currently, but that choice was arbitrary

**Comment by jpsim** [comment]
SwiftLint doesn't affect your built artifact or your source code (unless you run `swiftlint autocorrect`), so you can put that build phase wherever you'd like.
