### ISSUE TITLE
Support Swift 2

### ISSUE THREAD

**Issue by aarondaub** [realm/SwiftLint#77]
We should have a branch (I suggest it not be master) that builds with the prerelease software. Not sure how feasible this is because of dependencies.

**Comment by jpsim** [comment]
:+1:

**Comment by jpsim** [comment]
PRs welcome!

**Comment by remzr7** [comment]
+1

**Comment by Shirk** [comment]
:+1:

**Comment by bishalg** [comment]
:+1:

**Comment by lfaoro** [comment]
still now Swift-2.0 branch?

**Comment by jpsim** [comment]
I got around to doing this. PR in #98.
