### ISSUE TITLE
Add section on performance testing responsibility in contributing.md

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#774]
We accidentally shipped a major performance regression in 0.11.2 (see #772). This would've been caught by perf tests (#376), but until we have those, we could at least add a paragraph to contributing.md requiring that PRs post a before/after metric of `IntegrationTests.testSwiftLintLints()`. Maybe a PR template that has placeholders for this would help too.

**Comment by marcelofabri** [comment]
Is this still valid now that we have performance tests?

**Comment by jpsim** [comment]
No, let's close until/if we notice that the perf tests on Circle aren't sufficient.
