### ISSUE TITLE
ConditionalReturnsOnNewline severity cannot be configured

### ISSUE THREAD

**Issue by BluMist** [realm/SwiftLint#783]
adding "conditional_returns_on_newline: error" to .yml is a no-op at the moment 
configuration.severity is not passed onto the StyleViolation constructor (line 39-40 of ConditionalReturnsOnNewline.swift)

**Comment by BluMist** [comment]
ping @HaloZero for visibility

**Comment by HaloZero** [comment]
Oops, thanks. I'll submit a PR soon

**Comment by HaloZero** [comment]
https://github.com/realm/SwiftLint/pull/806

**Comment by norio-nomura** [comment]
fixed by #806
