### ISSUE TITLE
Ability to ignore certain files (e.g. dependencies for iOS 7?)

### ISSUE THREAD

**Issue by msanders** [realm/SwiftLint#81]
Hi, is it possible to configure SwiftLint to ignore certain files in the "Run Script" phase? I had to drag in a few dependencies for iOS 7 and it's spamming my project with errors.

**Comment by jpsim** [comment]
For now, you could run SwiftLint individually on each file you want linted, but I agree it'd be nice to allow excluding files.

**Comment by bahlo** [comment]
:+1:, I just added a framework via Carthage and now my project won't build. Maybe just ignore all files in `.gitignore` and other vcs.

Or make a `.swiftlint` config file.

Until then I have to disable the build step :cry:

**Comment by msanders** [comment]
Ended up working around this by running `swiftlint --path [srcdir]`, which suits my needs just fine.

**Comment by jpsim** [comment]
You can now specify `excluded` in your `.swiftlint.yml` file. See https://github.com/realm/SwiftLint#configuration for more details.
