### ISSUE TITLE
Support list of files as argument

### ISSUE THREAD

**Issue by gzfrancisco** [realm/SwiftLint#810]
I think the tool can be improved if the command can take a list of files so we can check only those files.

We can do something like:

```
$ swiftlint MyClass.swift AnotherClass.swift script.swift
```

**Comment by jpsim** [comment]
That would indeed be nice. This could be done with Commandant by using an `Argument` option, which would look like this:

```shell
$ swiftlint lint -- MyClass.swift AnotherClass.swift script.swift
```

**Comment by benasher44** [comment]
I've started working on this in an effort to make SwiftLint work with pre-commit as part of pre-commit/pre-commit#451. I'm making decent progress, but I have a question/issue. What does `rootPath` mean in the context of multiple paths? Would the current working directory suffice if more than one path is specified, or would it be more appropriate to calculate nearest common ancestor of all of the paths? It seems like the latter would be better. Thoughts?

**Comment by PH9** [comment]
Is this should be close issue. It is already merged

**Comment by benasher44** [comment]
Ah yep this is merged
