### ISSUE TITLE
Autocorrect all classes/structs

### ISSUE THREAD

**Issue by floskel** [realm/SwiftLint#812]
When using autocorrect only the classes named exactly like the file are auto corrected. Any other classes/structs are not changed.

**Comment by jpsim** [comment]
Sorry for the delay in getting back to you.

Can you please elaborate @floskel? What you're saying is impossible.

It might be possible that in your project, you were expecting something to be corrected, and it wasn't, and you incorrectly made a connection between the name of your types and the violations that were or weren't corrected.

I look forward to getting more information from you so we can help you!

**Comment by jpsim** [comment]
Never heard back...

**Comment by floskel** [comment]
Ah, sorry. Got caught up in Swift 2 -> 3 migration and had to pause implementing the linter. I will make a new issue if i experience the problem again.
