### ISSUE TITLE
Check dependencies failed when installing on Mac OS Sierra

### ISSUE THREAD

**Issue by shaps80** [realm/SwiftLint#814]
I ran the command:

`brew install swiftlint` -- which I've successfully run on previous versions of OSX

but I get an error during the installation.

```
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
bitrise                                                                         dynamodb-local                                                                  pango

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Using the sandbox
==> Cloning https://github.com/realm/SwiftLint.git
Updating /Users/Shaps/Library/Caches/Homebrew/swiftlint--git
==> Checking out tag 0.12.0
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Commandant'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/SWXMLHash'
Synchronizing submodule url for 'Carthage/Checkouts/YamlSwift'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
==> make prefix_install PREFIX=/usr/local/Cellar/swiftlint/0.12.0 TEMPORARY_FOLDER=/private/tmp/swiftlint-20160913-93597-16xpw7r/SwiftLint.dst
Last 15 lines from /Users/Shaps/Library/Logs/Homebrew/swiftlint/01.make:

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies
(6 failures)
make: *** [clean] Error 65
make: *** Waiting for unfinished jobs....
*** Bootstrapping Carthage/Checkouts/SourceKitten...

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

I realise this is still not a formal release and even the warnings above mention this is not necessarily a tested/supported configuration, but no one else seems to be mentioning any issues around this.

Additional Notes:
* `xcode-select` is set to use Xcode 8, running with Xcode 7 presents an error stating my version of Xcode is out of date. This appears to be more a `brew` issue however, than a SwiftLint issue.

* This is also a FRESH OSX install, not an upgrade. 

* The resulting `make` file is attached [01.make.zip](https://github.com/realm/SwiftLint/files/470288/01.make.zip)

**Comment by shaps80** [comment]
For those having similar issues around this here's the fix:

https://github.com/realm/SwiftLint/releases/

The wonderful dev's at Realm provide a fantastic PKG installer that works like a charm. I should've checked this first -- my bad :)

---

Regarding the problem above, this is related to `brew` more than it is SwiftLint.

If you have `xcode-select` setup to use Xcode 8, you'll see the error above since SwiftLint requires Swift 2.2

However if you then switch back to using Xcode 7, `brew` will complain about an outdated version of Xcode. So, use the package installer and smile ;)

**Comment by zmwangx** [comment]
@shaps80 Hi, I'm a maintainer of Homebrew.

> Regarding the problem above, this is related to brew more than it is SwiftLint.

> If you have xcode-select setup to use Xcode 8, you'll see the error above since SwiftLint requires Swift 2.2

> However if you then switch back to using Xcode 7, brew will complain about an outdated version of Xcode. So, use the package installer and smile ;)

May I interpret this comment as SwiftLint is not supposed to work with Xcode 8 (Swift 3), and consequently macOS Sierra? I certainly don't think there's a Sierra + Xcode 7 setup and won't call it a "problem" of brew.

**Comment by zmwangx** [comment]
Oh sorry, you're not a member of the SwiftLint team.

**Comment by shaps80** [comment]
Hey,

Apologies if I offended you. I certainly didn't mean it in a bad way. I love brew and you guys have done a fantastic job! Don't know what I'd do without it ;-)

You're right, it's not a problem, however it doesn't appear to be a supported configuration and since many of us will require swift 2.2 for some time to come, it means I can't use brew to install libs that depend on it while running Sierra. 

Unless you can tell me how? ;-)

Shaps

**Comment by zmwangx** [comment]
I'm not offended, I'm trying to figure out this packaging problem myself. See https://github.com/realm/SwiftLint/issues/815 and https://github.com/Homebrew/homebrew-core/issues/4841.

**Comment by shaps80** [comment]
Ah I see. Glad to hear! 

Let me know if I can help at all. 

Thanks,

Shaps
