### ISSUE TITLE
SwiftLint LineLengthViolation should not account for swift embedded resource snippets

### ISSUE THREAD

**Issue by luisgrimaldo** [realm/SwiftLint#821]
The following `#imageLiteral(resourceName: "pause_tapped")` should be count as the length of `pause_tapped` + 1 (for the thumbnail) instead of the length of the whole expression "#imageLiteral(resourceName: "pause_tapped")" as in Xcode this contains a special display

**Comment by marcelofabri** [comment]
This should be fixed now that https://github.com/realm/SwiftLint/pull/830 was merged 🎉

**Comment by norio-nomura** [comment]
Thanks!
