### ISSUE TITLE
Using .swiftlint.yml file with Xcode auto-correct plugin

### ISSUE THREAD

**Issue by sumit-nathany** [realm/SwiftLint#828]
How can I use autocorrect plugin but use .swiftlint.yml file for enabling/disabling certain rules.

**Comment by marcelofabri** [comment]
Are you talking about [this](https://github.com/ypresto/SwiftLintXcode) plugin? I think you should open an issue on that repository instead, as it's not related to SwiftLint itself.

Also, the problem seems to be fixed according to this issue: https://github.com/ypresto/SwiftLintXcode/issues/9

**Comment by jpsim** [comment]
Closing as we never heard back from @sumit-nathany and it appears to be resolved elsewhere.
