### ISSUE TITLE
File header rule

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#844]
We could have an opt-in rule that warned when the file have the default comment header included in Xcode template. For example:

```
//
//  LegacyConstructorRule.swift
//  SwiftLint
//
//  Created by Marcelo Fabri on 29/11/15.
//  Copyright © 2015 Realm. All rights reserved.
//
```

This wouldn't be enabled for SwiftLint 😅

**Comment by keith** [comment]
I think I have a closed PR for this somewhere from before opt in rules were supported. Otherwise we have it on our fork. I'd be happy to submit it again.

**Comment by marcelofabri** [comment]
Hah, just found it: https://github.com/realm/SwiftLint/pull/126
