### ISSUE TITLE
What is the purpose of opt_in_rules?

### ISSUE THREAD

**Issue by castus** [realm/SwiftLint#850]
I know that this question might by stupid, but I don't get the idea behind opt_in_rules. Can someone explain me what is the purpose of opt_in_rules?
Thanks

**Comment by marcelofabri** [comment]
`opt_in_rules` are disabled by default (you have to explicitly add them on your configuration file). 

From what I've seen there're a few reasons on why a rule should be opt-in:

* A rule that can have many false positives (`empty_count`)
* A rule that is too slow
* A rule that is not general consensus or only useful in some cases (`force_unwrapping`, `missing_docs`)

**Comment by jpsim** [comment]
That's exactly right.

**Comment by castus** [comment]
Thank you for such a good answer!
