### ISSUE TITLE
New release for Xcode 8 and Swift 2.3

### ISSUE THREAD

**Issue by koke** [realm/SwiftLint#857]
The latest release (0.12.0) fails to build with `make`, and prompts to convert to current swift syntax when you open the Xcode project.

This is already fixed in master, but there hasn't been a new release since August.

**Comment by sharat** [comment]
You're right, the only solution is to install `brew install --HEAD swiftlint`. This is actually eating up lot of build minutes on the CI Server. The installation is very slow. Waiting for the new release.

**Comment by brennantaylor** [comment]
Is this a problem on Sierra? The 0.12.0 bottle pours for our team on elcap from brew just fine.

**Comment by sharat** [comment]
@brennantaylor Are you on Xcode 8.x?

**Comment by norio-nomura** [comment]
0.13.0 has been released on both of [github release](https://github.com/realm/SwiftLint/releases/tag/0.13.0) and [homebrew](https://github.com/Homebrew/homebrew-core/pull/6584).
