### ISSUE TITLE
Disable multiple rules with one comment

### ISSUE THREAD

**Issue by AndrewSB** [realm/SwiftLint#861]
I think it would be cool to be able to put

`//swiftlint:disable:next variable_name trailing_whitespace`

and have it disable both of those rules for the next line. Currently, to achieve something similar Im doing:

```
//swiftlint:disable variable_name
<offending line of swift code> //swiftlint:disable:this trailing_whitespace
```

**Comment by kwosu87** [comment]
+1 agree with that

**Comment by jpsim** [comment]
Done in #897
