### ISSUE TITLE
Cocopods architecture with SwiftLint 

### ISSUE THREAD

**Issue by Goule** [realm/SwiftLint#867]
Hello,

I'm trying to make run SwiftLint with cocoa pod library, but it don't want compile (command exit).
Where I'm suppose to execute the script with this architecture :

<img width="328" alt="capture d ecran 2016-11-07 a 12 35 17" src="https://cloud.githubusercontent.com/assets/21126201/20056508/d5d939da-a4e6-11e6-9f54-687401479872.png">

In Pod project ? 
And where set .swiftlint.yml ?

Thank you

**Comment by jpsim** [comment]
I'd encourage you to put the `.swiftlint.yml` file at the root of your project (next to `.travis.yml` in this case).

You mention "but it don't want compile (command exit)". I'm not sure what you mean by that. CocoaPods doesn't do anything with SwiftLint or with the `.swiftlint.yml` configuration file...

**Comment by jpsim** [comment]
Hopefully my response was helpful to you @Goule! I'm closing this since we haven't heard back from you in a while.
