### ISSUE TITLE
Comma violation is not being triggered for all cases if there are consecutive violations in the expression

### ISSUE THREAD

**Issue by sadefigu** [realm/SwiftLint#872]
PROBLEM

Some comma violations are being ignored by the comma rule. For example: var a = [1,2,3,4]
Instead of presenting violations for 1,2 2,3 3,4, it just presents the violations for 1,2 and 3,4

INVESTIGATION

The reg exp pattern being used for comma rule violations search for 
                 NotSpace-Space-Comma-(Space Or NotSpace).

So, if we have an expression like 
                  var a = [1,2,3,4] 
it will be able to find the violations for 1,2 and 3,4, but it will not find the violation 2,3

This happens because the reg exp pattern will consume 1,2 and then, the remaining sequence to be consumed is ,3,4 which begins with a comma. The pattern does not comprise the case where the content being with the query, so, it will ignore the first comma violation and will consume 3,4

**Comment by jpsim** [comment]
Fixed in #876.
