### ISSUE TITLE
Inline ignore macros

### ISSUE THREAD

**Issue by mfclarke** [realm/SwiftLint#88]
Say you have a UICollectionViewController, with the following method:

```
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCellWithReuseIdentifier("someidentifier", forIndexPath: indexPath) as! UICollectionViewCell
    return cell
}
```

SwiftLint complains about the force casting from AnyObject returned by ```collectionView.dequeueReusableCellWithReuseIdentifier``` to UICollectionViewCell, but there's really no other way. The SDK requires you to use this method to fetch a cell to return, and you have to return a UICollectionViewCell.

Is there something I can wrap these sorts of exceptions in, similar to Clang's ```#pragma```'s maybe, so SwiftLint ignores them?

**Comment by jpsim** [comment]
We'd love to add that functionality! We're currently tracking this as #4, so I'll be closing this issue as a duplicate, but please feel free to continue the conversation there!
