### ISSUE TITLE
Included *.swift 

### ISSUE THREAD

**Issue by terflogag** [realm/SwiftLint#887]
Hello,

I'm trying to included some file to the SwiftLint file. 
But I can't add every swift file of a folder : 

```
included: 
  - ../MyFolder/Classes/Controller/MyFile.swift   # work fine 
  - ../MyFolder/Classes/Controller/*.swift  #didn't work , none of the .swift file in the Controller folder are checked are compilation.
```

Any idea ? Probably the syntax ?

**Comment by jpsim** [comment]
`included` doesn't use shell-like file globbing syntax, it uses regular expression syntax. Try this:

```
../MyFolder/Classes/Controller/.*.swift
```

**Comment by terflogag** [comment]
Hello, thank you for your response :) 
But with : 
`../MyFolder/Classes/Controller/.*.swift`
File are not include :/

**Comment by jpsim** [comment]
Oops, I was totally wrong. `included`/`excluded` don't use regular expression syntax at all, it doesn't do any wildcard expansion of any kind. See https://github.com/realm/SwiftLint/blob/0.13.0/Source/SwiftLintFramework/Models/Configuration.swift#L189-L199

So instead of `../MyFolder/Classes/Controller/*.swift` you should specify the root directory: `../MyFolder/Classes/Controller`.

**Comment by terflogag** [comment]
Work fine ! Thank you !!!

**Comment by fabb** [comment]
@jpsim does that mean the example in the readme is wrong?
```
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
```
https://github.com/realm/SwiftLint/blame/master/README.md#L318

**Comment by marcelofabri** [comment]
@fabb This feature has been recently added, so the README is correct.

**Comment by fabb** [comment]
Is it included in 0.27.0? I couldn‘t get it to work 😕

**Comment by jpsim** [comment]
Note that globs are only supported when _excluding_ files, not _including_ them.

**Comment by fabb** [comment]
Yeah I tried globs in excluding, didn‘t work. Will try again, maybe it was a special combination that caused issues. Also I tried starting with a glob (`*/filename.swift`), that even made seiftlint throw an error.
