### ISSUE TITLE
Line length restrictions

### ISSUE THREAD

**Issue by alimoeeny** [realm/SwiftLint#95]
Guys, for lines that contain a literal string, like when you create an `NSLocalizedString` or things like that, the line length limitation becomes inconvenient. 
Is there a way to make it possible for people to opt out of it? Like pass an argument to disable line limit check?

**Comment by jpsim** [comment]
Hi @alimoeeny, there are lots of valid reasons to disable/modify SwiftLint rules for specific scenarios, which we intend to support by #4. Closing as a duplicate.
