### ISSUE TITLE
Idea: `swiftlint init` could create a new .swiftlint in the current directory

### ISSUE THREAD

**Issue by bensarz** [realm/SwiftLint#959]
I find myself having to create a new .swiftlint.yml file every now and then. This would help.
Additionally, the current .swiftlint.yml file gets often out of date as new rules are created/added. This function could add the missing rules to the config file.

**Comment by marcelofabri** [comment]
Can you check #518 and #532 to see if they cover your idea? Thanks!

**Comment by bensarz** [comment]
Totally covers it!
Sorry for not searching for this before opening an issue, closing.
