### ISSUE TITLE
Fix failing tests on Linux

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#966]
As of #963, there are a handful of failing Linux tests. We should investigate why they're failing and fix them:

- [x] `ConfigurationTests.testExcludedPaths`
- [x] `ReporterTests.testJSONReporter`
- [ ] `RulesTests.testForceUnwrapping`
- [x] `RulesTests.testLeadingWhitespace`
- [x] `RulesTests.testPrivateUnitTest`
- [x] `RulesTests.testTypeName`
- [x] `RulesTests.testVariableName`

**Comment by norio-nomura** [comment]
SwiftLint is affected by https://bugs.swift.org/browse/SR-3366

**Comment by norio-nomura** [comment]
> SwiftLint is affected by https://bugs.swift.org/browse/SR-3366

I have not yet investigated each failing tests, but I know that might be a critical issue for SwiftLint on Linux.

**Comment by norio-nomura** [comment]
Sorry, that was not correct. 
SwiftLint does not call the function. 🙇

**Comment by jpsim** [comment]
Re-enabled `testJSONReporter` in c82cc6d9f654fafe2f75b770c2bff716994d1e4f and `testPrivateUnitTest` in ae4b01d5c46eceb4942ef9fd7ca36ddeddc67675.

**Comment by marcelofabri** [comment]
I've filled [SR-3485](https://bugs.swift.org/browse/SR-3485) which seems the reason of `RulesTests.testTypeName`, `RulesTests.testVariableName` and https://github.com/realm/SwiftLint/pull/1068 failures.

**Comment by marcelofabri** [comment]
[SR-2123](https://bugs.swift.org/browse/SR-2123) seems to be the reason of `RulesTests.testLeadingWhitespace` failure.

**Comment by marcelofabri** [comment]
I think the only remaining commented test is failing for the same reasons of https://github.com/realm/SwiftLint/issues/1001.
