### ISSUE TITLE
HTML Reporter - Invalid CSS Styling

### ISSUE THREAD

**Issue by aamctustwo** [realm/SwiftLint#981]
At the moment, the HTML report has an invalid CSS style within it. It is attempting to defining a background color in the table header to have an alpha value. This is the [currently offending line](https://github.com/realm/SwiftLint/blob/b36ca2f071d55df7af8152b0ab0717696801de81/Source/SwiftLintFramework/Reporters/HTMLReporter.swift#L63).

Currently, CSS color properties do not support defining an RGBA color from an 8 hexidecimal characters value (only using the `rgba` functions). See [CSS Color Module Level 3 Recommendation](https://www.w3.org/TR/css3-color/#rgba-color).

Defining RGBA colors from hex is tentatively slated for the future. See [CSS Color Module Level 4 Editor's Draft](https://drafts.csswg.org/css-color/#hex-notation).

We should either use a non-transparent color there or we should use the `rgba` function to generate the desired color.

**Comment by marcelofabri** [comment]
@aamctustwo Would you like to open a PR addressing this?

**Comment by aamctustwo** [comment]
@marcelofabri Yes, I'll have the PR ready to go later today! 😄
